### ISSUE TITLE
Bed Tramming on right side not working

### ISSUE THREAD

**Issue by wovka88** [mriscoc/Ender3V2S1#1]
### Description

Have build and flashed the inital Version for Board 4.2.2 with bltouch. Bed Tramming is only working on the left side, if I choose right the Hotend is not moving.

### Steps to Reproduce

1. Select Prepare
2. Select Bed Tramming
3. Select any Right Point

**Expected behavior:** Bl-Touch is triggering the right side

**Actual behavior:** nothing

**Comment by mriscoc** [comment]
Increase your probe offsets.
