### ISSUE TITLE
Swapped from normal firmware to TJC screen version and now have thermal issues

### ISSUE THREAD

**Issue by CodyNorth04** [mriscoc/Ender3V2S1#1001]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I have been using the standard release for the ender 3v2 422 BL touch with no issues other than bed leveling mesh not showing values. I asked reddit and found out the tjc display needs a special version of the firmware and installed it today. Ever since then I have been having thermal issues. I am using the creality speedy spider which has had no issues getting up to 200 in under 40 seconds, but now takes at least 2 minutes and can't keep the temperature constant. Then the readout will jump either down to 180 or all the way up to 270+. In order to make sure it was the firmware and not the thermistor I installed the official creality firmware and haven't had any issues. Also, I'm not sure if I'm using ABL or UBL. It's whatever comes stock with the firmware and CR touch. 

### Bug Timeline

Immediately after swapping to the TJC firmware

### Expected behavior

I expected it to accurately measure temperature. 

### Actual behavior

It was unable to provide accurate readings of the hotends current temperature. 

### Steps to Reproduce

1. Install the most recent Ender 3 V2 422 BLTUBL firmware
2. Have visual issues with bed leveling / mesh
3. Find out you have a TJC screen
4. Install the special configuration firmware
5. See thermal readings all over the place while the hotend is probably significantly hotter
6. Install different version of the firmware or official firmware to double check 
I haven't reproduced the issue; this is just what I did. 

### Version of Professional Firmware

Ender3V2-422-BLTUBL-TJC-MPC-20230525

### Printer model

Ender 3V2

### Electronics

4.2.2

### Add-ons

Creality Speedy Spider Ceramic

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
The only changes in TJC versions is about some screen drawing functions.
