### ISSUE TITLE
[BUG] (bug summary) Firmware Info screen periodically displays, screen non-responsive.

### ISSUE THREAD

**Issue by liz-muehlmann** [mriscoc/Ender3V2S1#1007]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Printer: Ender 3pro v2. 

After I boot (no print running) the Professional Firmware info splash will display over the main menu. The screen is non-responsive during these times. It will appear repeatedly at various intervals and the printer is unusable. 

I have Octoprint running on a Raspberry Pi 3b, but this issue has been happening while Octoprint has been disconnected.

### Bug Timeline

It worked for about a week, now this issue has started.

### Expected behavior

I didn't expect the splash screen after reaching the main menu.

### Actual behavior

The menu repeatedly displays.

### Steps to Reproduce

It's immediate upon turning on my printer. I have started it up and this bug does not occur. I have noticed a pattern of when it does/doesn't happen. 

### Version of Professional Firmware

Ender3V2-422-BLTUBL-MPC-20230522B

### Printer model

Ender 3v2

### Electronics

Creality 4.2.2

### Add-ons

BLTouch, Dual Z, Octoprint

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

### Additional information & file uploads

[Video Here](https://imgur.com/a/DJ0gXIH)

**Comment by mriscoc** [comment]
Not a firmware issue.
The issue report page is only for report failures about firmware. For general help with the printer use the Discussion page or other community networks.

Check your thermistors connections.
