### ISSUE TITLE
Home screen invisible bottom functions

### ISSUE THREAD

**Issue by Juli337-afk** [mriscoc/Ender3V2S1#1012]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Before updating to the latest release, on the homescreen were about 5 options on the bottom (Home, disable stepper, create mesh,etc) Now they are invisible, I can't see them but if I turn the knob all the way to the right and press it, it will disable the stepper motors.

### Bug Timeline

Brand new, happened today with the new update (AUG 5)

### Expected behavior

Homescreen as usual

### Actual behavior

Bottom buttons invisible

### Steps to Reproduce

Just update to the latest version of the firmware (I also updated the DWIN_SET on the screen)

### Version of Professional Firmware

Ender3V2-422-BLTUBL-MPC

### Printer model

Ender 3 V2

### Electronics

4.2.2

### Add-ons

CR Touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by classicrocker883** [comment]
did you compile your own?  
https://github.com/mriscoc/Ender3V2S1/issues/249

it disappears when you change the author, that should be left alone

**Comment by Juli337-afk** [comment]
> did you compile your own? #249
> 
> it disappears when you change the author, that should be left alone

Nope, I just downloaded the new release and installed it. The LA version also wont show those buttons.

**Comment by Crazy-Charles** [comment]
> did you compile your own? #249
> 
> it disappears when you change the author, that should be left alone

Not anymore, authors name is embedded in the proui libraries.

**Comment by Juli337-afk** [comment]
This is how the menu looks like for me 
![IMG_20230806_012634](https://github.com/mriscoc/Ender3V2S1/assets/74382882/7de52538-6a00-4c48-b592-87d24382c086)

**Comment by mriscoc** [comment]
Some people are reporting the same issue, but I if load the file: https://github.com/mriscoc/Ender3V2S1/releases/download/20230805/Ender3V2-422-BLTUBL-MPC-20230805.bin
in my printer all seems correct.
What SoC your printer has? STM32 or GD32?

**Comment by Crazy-Charles** [comment]
Just tried the precompiled Ender3V2-427-BLTUBL-MPC-20230805.bin file and it has the same problem, no toolbar or proUIEx.init display.

Custom builds seem to be ok

**Comment by mriscoc** [comment]
Please post the results of custom g-code **C115**

**Comment by Juli337-afk** [comment]
My SoC is the STM32

**Comment by Juli337-afk** [comment]
> Please post the results of **C115**

What's that

**Comment by Crazy-Charles** [comment]
>>> C115
SENDING:C115
Marlin ProUI Version: 2.1.3 MRiscoC
FFICIAL BUILD: 20230805 - 06:59
Author: Miguel Risco-Castillo (MRiscoC)
ok P15 B15

**Comment by RejZoRSheep** [comment]
I'm using latest BLT 422 version and the toolbar is invisible indeed. It seems to be there as turning Ender 3 v2 knob to select icons seems to go further, you just don't see it.

**Comment by renepetro** [comment]
Seems like to be some inconsistencies in config files , which one is correct ?

#define STRING_CONFIG_H_AUTHOR "Miguel Risco-Castillo (MRiscoC)" // Who made the changes.

#define STRING_CONFIG_H_AUTHOR "Miguel A. Risco-Castillo (MRiscoC)" // Who made the changes.

**Comment by mriscoc** [comment]
**NOTE**: Due to a bug, where some people report that the info box and toolbar are not showing, binary downloads have been removed. The error seems to be board dependent, some printers with the same firmware file work and some don't. Until this can be fixed, the binaries will not be released.

**Comment by mriscoc** [comment]
Please download the more recent binaries, the issue was solved.
