### ISSUE TITLE
[BUG] Incorrect files in configurations folder

### ISSUE THREAD

**Issue by HD16K** [mriscoc/Ender3V2S1#1015]
### Bug Description

In source code, the files located in the configurations folder (at least in "Ender3V2-422-BLT", the rest I have not checked) are not correct. For example there is a word `either ` that causes compilation errors, in the default files isany `any`.

### Bug Timeline

in Pre-release 20230805

### Expected behavior

Update files

### Actual behavior

Files are not correct.

### Version of Professional Firmware

20230805

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Thanks, the files from https://github.com/mriscoc/Special_Configurations were updated.
