### ISSUE TITLE
[BUG] Filament Runout Sensor is enabled in MOTION by default and trigger an Advanced Pause

### ISSUE THREAD

**Issue by hagenman** [mriscoc/Ender3V2S1#1025]
## HOW TO SOLVE:
If you don't have an smart filament sensor (as BTT) set the filament active state to HIGH or LOW: https://github.com/mriscoc/Ender3V2S1/issues/1025#issuecomment-1678273341

-----

### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

After upgrading, prints will run for a bit, then the runout sensor will trigger (i think?) and it will go to the purging screen. I tell it to continue then it will for a little while before the issue occurs again.  Also, the estimate time just keeps climbing until the sensor triggers again.

### Expected behavior

I expected prints to continue like they did on your previous firmware

### Actual behavior

After upgrading, prints will run for a bit, then the runout sensor will trigger (i think?) and it will go to the purging screen. I tell it to continue then it will for a little while before the issue occurs again.  Also, the estimate time just keeps climbing until the sensor triggers again.

### Version of Professional Firmware

20230810-11:42

### Printer model

Ender 3 S1 F4

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by anoblet** [comment]
I'm having a similar issue. My prints will hit the runout screen, although there's still plenty of filament running through the sensor. Afterwards the filament breaks since it stays in the hotend heating.

**Comment by classicrocker883** [comment]
check the runout setting, if set to HIGH/LOW set to opposite

**Comment by hagenman** [comment]
Mine is set to Motion.

**Comment by lam522008** [comment]
I am also having this issue on my Ender 3 v2, not sure what to do unable to print anything without it purging and spitting out the filament for no apparent reason. Any solutions?

**Comment by mriscoc** [comment]
Seems that the configuration files sets by mistake the filament run-out sensor in the MOTION active state, that is wrong if you don't have an smart filament sensor. Check your filament runout sensor settings: https://github.com/mriscoc/Ender3V2S1/wiki/Filament-Settings-Menu#run-out-sensor

**Don't forget to store settings after the changes.**

![filament-settings1](https://github.com/mriscoc/Ender3V2S1/assets/2745567/d3b262a5-d65c-4690-8d42-0fed037c055b)

With the help of the end-stop diagnostic screen, set your `Runout Active` to HIGH or LOW so that if there is filament in the sensor, it will indicate TRIGGERED. If you have the Ender 3 S1 and the stock filament runout sensor, go to Advanced / Filament settings menu and set Runout Active to HIGH, if you have a Ender 3 V2 without runout sensor, disabled it.

![](https://raw.githubusercontent.com/mriscoc/Marlin_Ender3v2/Ender3v2-Released/screenshots/endstops-diagnostic.jpg)

**Comment by lam522008** [comment]
Thank you that did help! I don't have errors but can't seem to print anything more than 20 minutes without it messing up. Any solutions?

**Comment by monkiki** [comment]
I've the same issue in my Ender 3 S1. Going back to v20230522 solved the problem.

**Comment by lam522008** [comment]
> I've the same issue in my Ender 3 S1. Going back to v20230522 solved the problem.

How did you go back to that Version?

**Comment by Ollipop030** [comment]
> How did you go back to that Version?

Here:
https://github.com/mriscoc/Ender3V2S1/releases/tag/20230522

**Comment by Ollipop030** [comment]
> If you have the Ender 3 S1 and the stock filament runout sensor, go to Advanced / Filament settings menu and set Runout Active to HIGH

Doesn´t work for me. I´ve testet high/low, the printer stops every few minutes. Sometimes it doesn´t even finish the first layer. Only option for me is to disable the sensor. With May firmware it works fine.

**Comment by gitfve** [comment]
Is this a problem in the Ender3 S1 PRO too?

I dont know about any BTT sensor on my Ender3 S1 PRO, it is the stock filament sensor. 

I use this one without any problem Ender3S1-F4-UBL-20230312.bin

**Comment by NetCaptive** [comment]
Setting "Enable Runout" to "off" solved this problem for me on my Ender 3v2 with BLTouch.  My "Runout Active" setting was "Motion" and I left that unchanged.

**Comment by andrenalin282** [comment]
Same problem for me Ender 3V2, high, low, runout deactivation, nothing works, plugged off the cable works for me, i wait for the fix.

**Comment by mriscoc** [comment]
> Same problem for me Ender 3V2, high, low, runout deactivation, nothing works, plugged off the cable works for me, i wait for the fix.

The problem was only with the default value of Runout active, deactivating or set it properly and then save settings, should solve the issue.

**Comment by RejZoRSheep** [comment]
Jesus, wasted almost 1 hour trying to figure out the problem, then finally come here and see it's not just me. The buggy update with invisible toolbar didn't cause me any problems, updated to latest fixed version and haven't printed anything then. Tried now and kept pausing even though I just put new 1KG spool on it.

**Comment by plastisizer** [comment]
Had the same issue with the Advaced pause, turned off the runout detector and now was able to move past that point. I was then able to start the print, but the extruder was not pushing any filament. I rebooted and was able to restart the print without issues.

**Comment by Crapoulos** [comment]
If it helps, I also had the same problem on my Ender 3 S1 with the latest version 20230805.
When I re-installed version v20230522 it solved the problem. 
I tested version 20230805 again and the problem returned. Runout sensor comes back every 4mn or so. Not yet tested the suggestion "set your Runout Active to HIGH or LOW".

**Comment by mriscoc** [comment]
> Not yet tested the suggestion "set your Runout Active to HIGH or LOW".

**Step 4** of the Calibration guides, a must-read for anyone trying to install this firmware.

![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/08d19b1e-7ee8-45cf-ab80-1235903c261e)

**Comment by Rippeee** [comment]
Has anyone found a solution for BTT yet? Other than rolling back previous version?

**Comment by Belliqueu** [comment]
Disabling runout in the menus did not work for me, but adding M412 S0 to my start code did

**Comment by mriscoc** [comment]
After disable it in the menu you need to save settings.

**Comment by gitfve** [comment]
@ Belliqueu, As i read the code your M412 wont do anything?
From the code: 
```
#if ENABLED(FILAMENT_RUNOUT_SENSOR)
  #define FIL_RUNOUT_ENABLED_DEFAULT true // **Enable the sensor on startup. Override with M412 followed by M500.**
```
There are so many reports on the RunOutSensor.  I do not understand why this version is not disabled, and a new is released. I can see the developer have solved it in the source code, but no new .bin file is released. I think it will be a help to many users if new bin was released.

**Comment by Rippeee** [comment]
If I Disable it from the menu, then it's disabled, If I enable it, it triggers pause like every 30 seconds. How do I get Smart sensor to work like intended?

**Comment by Rippeee** [comment]
For those who are having issues with BTT sensor triggering every 30sec, I think I found the solution. I'm not using any custom configs or G-godes. I'm using the latest mriscoc firmware with BTT sensor, Mode set as motion. The recommended Distance for BTT is 7 mm, and that doesn't work, unless your sensor is literally Next to the extruder. I would recommend to set it to 14 mm, if that doesn't work, try 20,30,40,50 etc. In my case, I'm running Sprite pro Direct drive upgrade kit, and I'm mounting the sensor at the top, next to the filament spool. For that reason, there is a lot of ''slag'' between the extruder and the sensor, so there will be moments when the filament ain't moving at all. 7 mm would never work in my case and in my case it doesn't really matter even if the distance is 100 mm because once the filament is out of sensor, there is still like 20CM of filament going in the extruder. In a Nutshell the solution is Crank up your distance from 7 to 8,9,10,11,12,13,14,15,16… etc. Until it works.

**Comment by mriscoc** [comment]
Solved in the last version

**Comment by Crapoulos** [comment]
Thank you Miguel for all your hard work and all the improvements you've made with all these firmwares ! Much appreciated.

**Comment by Rippeee** [comment]
Little of the topic but if some of you're running BTT Smart filament sensor with a Sprite extruder and Looking for a mounting system that allows to have that 7 mm Run out distance, and actually WORK

You are welcome…  https://www.thingiverse.com/thing:6209226

**Comment by zfkdnop** [comment]
EDIT: Disregard. The issue was caused by my own configuration edits. My apologies. And thank you Miguel for your hard work. This firmware is EXCELLENT!

> > Solved in the last version
> 
> Now I can't compile:
> 
> ```Compiling .pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_sram.cpp.o
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/HAL_SPI.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> Compiling .pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_wired.cpp.o
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/HAL.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> Compiling .pio/build/STM32F103RC_creality/src/src/HAL/STM32/fast_pwm.cpp.o
> Compiling .pio/build/STM32F103RC_creality/src/src/HAL/STM32/fastio.cpp.o
> Compiling .pio/build/STM32F103RC_creality/src/src/HAL/STM32/msc_sd.cpp.o
> Compiling .pio/build/STM32F103RC_creality/src/src/HAL/STM32/sdio.cpp.o
> Compiling .pio/build/STM32F103RC_creality/src/src/HAL/STM32/timers.cpp.o
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/MarlinSerial.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/HAL_SPI.cpp.o] Error 1
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/fastio.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/Servo.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/eeprom_bl24cxx.cpp:32:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/eeprom_sdcard.cpp:31:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/eeprom_if_iic.cpp:32:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/eeprom_flash.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/eeprom_sram.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/eeprom_wired.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/fast_pwm.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/HAL.cpp.o] Error 1
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/sdio.cpp:27:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/MarlinSerial.cpp.o] Error 1
> In file included from Marlin/src/HAL/STM32/../../inc/MarlinConfig.h:52,
>                  from Marlin/src/HAL/STM32/timers.cpp:26:
> Marlin/src/HAL/STM32/../../inc/SanityCheck.h:2753:6: error: #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>  2753 |     #error "RUNOUT_TUNE_ITEM requires HAS_FILAMENT_SENSOR."
>       |      ^~~~~
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/fastio.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_sdcard.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_if_iic.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_wired.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_sram.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/Servo.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_flash.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/eeprom_bl24cxx.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/fast_pwm.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/sdio.cpp.o] Error 1
> *** [.pio/build/STM32F103RC_creality/src/src/HAL/STM32/timers.cpp.o] Error 1
> ```
> 
> And if I remove RUNOUT_TUNE_ITEM, there are further errors which are to complex for me to resolve by simply removing configuration lines:
> 
> ```Compiling .pio/build/STM32F103RC_creality/src/src/libs/nozzle.cpp.o
> Marlin/src/lcd/marlinui.cpp: In static member function 'static void MarlinUI::media_changed(uint8_t, uint8_t)':
> Marlin/src/lcd/marlinui.cpp:1813:11: error: 'clear_menu_history' was not declared in this scope
>  1813 |           clear_menu_history();
>       |           ^~~~~~~~~~~~~~~~~~
> In file included from Marlin/src/lcd/../inc/MarlinConfigPre.h:37,
>                  from Marlin/src/lcd/../inc/MarlinConfig.h:28,
>                  from Marlin/src/lcd/marlinui.cpp:23:
> Marlin/src/lcd/marlinui.h:255:91: error: 'menu_media' was not declared in this scope
>   255 |     #define MEDIA_MENU_GATEWAY TERN(PASSWORD_ON_SD_PRINT_MENU, password.media_gatekeeper, menu_media)
>       |                                                                                           ^~~~~~~~~~
> Marlin/src/lcd/../inc/../core/macros.h:609:26: note: in definition of macro 'THIRD'
>   609 | #define THIRD(a,b,c,...) c
>       |                          ^
> Marlin/src/lcd/../inc/../core/macros.h:206:29: note: in expansion of macro '___TERN'
>   206 | #define __TERN(T,V...)      ___TERN(_CAT(_NO,T),V)  // Prepend '_NO' to get '_NOT_0' or '_NOT_1'
>       |                             ^~~~~~~
> Marlin/src/lcd/../inc/../core/macros.h:205:29: note: in expansion of macro '__TERN'
>   205 | #define _TERN(E,V...)       __TERN(_CAT(T_,E),V)    // Prepend 'T_' to get 'T_0' or 'T_1'
>       |                             ^~~~~~
> Marlin/src/lcd/../inc/../core/macros.h:201:29: note: in expansion of macro '_TERN'
>   201 | #define TERN(O,A,B)         _TERN(_ENA_1(O),B,A)    // OPTION ? 'A' : 'B'
>       |                             ^~~~~
> Marlin/src/lcd/marlinui.h:255:32: note: in expansion of macro 'TERN'
>   255 |     #define MEDIA_MENU_GATEWAY TERN(PASSWORD_ON_SD_PRINT_MENU, password.media_gatekeeper, menu_media)
>       |                                ^~~~
> Marlin/src/lcd/marlinui.cpp:1815:23: note: in expansion of macro 'MEDIA_MENU_GATEWAY'
>  1815 |           goto_screen(MEDIA_MENU_GATEWAY);
>       |                       ^~~~~~~~~~~~~~~~~~
> Marlin/src/lcd/marlinui.cpp:1815:11: error: 'goto_screen' was not declared in this scope
>  1815 |           goto_screen(MEDIA_MENU_GATEWAY);
>       |           ^~~~~~~~~~~
> Compiling .pio/build/STM32F103RC_creality/src/src/libs/numtostr.cpp.o
> *** [.pio/build/STM32F103RC_creality/src/src/lcd/marlinui.cpp.o] Error 1
> ```
