### ISSUE TITLE
[Setting] MINTEMP error immediately after print start

### ISSUE THREAD

**Issue by csihama** [mriscoc/Ender3V2S1#1042]
### Did you test with a precompiled firmware?

No, but I will test it now!

### Bug Description

On Ender 3 V2 with 4.2.2 board, can't heat up hotend and bed at the same time on lots of FW (sometimes works, sometimes not). Need to change the start G-code script: 
`M190 S{material_bed_temperature} ; heat to bed setting in Cura and WAIT`
`M109 S{material_print_temperature} ; heat hotend to setting in Cura and WAIT`

### Expected behavior

Heat both hotend and bed

### Actual behavior

MINTEMP error

### Version of Professional Firmware

Custom built from your repo

### Printer model

Creality Ender 3 V2

### Electronics

Board 4.2.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by csihama** [comment]
Further investigating: 

Recv:``  T:28.91 /0.00 B:60.25 /60.00 @:0 B@:7 W:0
Recv: ok N11 P15 B15
Send: N12 M113 S49&#42;109
Recv: ok N12 P15 B15
Send: N13 M109 S190&#42;82
Recv:  T:28.93 /190.00 B:60.23 /60.00 @:0 B@:12 W:?
Recv: Error:MINTEMP triggered, system stopped! Heater_ID: 690
Recv: echo:Home XYZ `First

**Comment by csihama** [comment]
Solved,

Need changes in Configuration_adv.h
`#define MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED 1`
`#define PREHEAT_TIME_HOTEND_MS 30000`

**Comment by mriscoc** [comment]
```cpp
#define PREHEAT_TIME_HOTEND_MS 30000
```
Maybe it is not a good idea, check the recommendation in the configuration file.

**Comment by classicrocker883** [comment]
> Solved,
> 
> Need changes in Configuration_adv.h `#define MAX_CONSECUTIVE_LOW_TEMPERATURE_ERROR_ALLOWED 1` `#define PREHEAT_TIME_HOTEND_MS 30000`

I leave these disabled.

**Comment by csihama** [comment]
I played with the values. The lowest value was: 19000. If i go with lower values, the FW kills the machine with MINTEMP error, even while the temperature reading rising. 

Solved the issue for myself, the printer works with that timeout offset. Perhaps because my Ender 3 V2, board 4.2.2 with STM32F103RE was the first implementation. I don’t know, but thanks for the reply.
