### ISSUE TITLE
Move to z home with 3d touch[BUG] (bug summary)

### ISSUE THREAD

**Issue by xingjl86** [mriscoc/Ender3V2S1#1043]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

When trying to Move to Z home, the 3d touch pin deployed in the first time and stow after touch the bed. It should deploy and touch the bed again for calculating, but it just shining without deploying and consider this position to be the second touch calculate height. So it would move to home about 5mm above the actual height. I think the time might be too short about the second time pin deploy. The pin could be deploy by the function "Deploy Z-Probe".
It might be the 3D touch was not working so good. But i think there shoube some delay here to be logical.

### Bug Timeline

It might be the 3D touch was not

### Expected behavior

Move to z home

### Actual behavior

Move to the height just 5mm above the actual.

### Steps to Reproduce

Move to z home

### Version of Professional Firmware

2.1.3MRiscoC 20230809 official build & 20230522B

### Printer model

Ender 3v2

### Electronics

4.2.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

None

### Host Software

None

**Comment by xingjl86** [comment]
I have tried to disable HS Mode, it's working now.

**Comment by mriscoc** [comment]
With a compatible 3DTouch (3.1 version), in HS mode the pin is not stowed until finish the second probe. With HS mode disabled, the pin is stowed in each probing.

**Comment by xingjl86** [comment]
So the problem might be the pin deployed but can not drop freely in the first probe.

**Comment by xingjl86** [comment]
And Yes, it would be better to show False alarm and stop all the next steps.
