### ISSUE TITLE
Movement on Z axis is inverted

### ISSUE THREAD

**Issue by alexandruvoicu** [mriscoc/Ender3V2S1#1045]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

When I make Auto Home the gantry is moving up not down and keep moving until reach the end of z axis.  

### Expected behavior

The movement on z when Auto Home is invoked must be in down.

### Actual behavior

The movement on z when Auto Home is selected is in up.

### Steps to Reproduce

1. Auto Home is selected
2. The z axis is moving up

### Version of Professional Firmware

Ender3V2-427-BLTUBL-MPC-20230809

### Printer model

Creality Ender 3V2

### Electronics

Creality 4.2.7 with TMC2225 drivers

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

None

### Additional information & file uploads

The problem is in configuration.h where the #define INVERT_Z_DIR is true instead of false. Please, change it to false before compile. This will solve the inverted movement on z axis.

**Comment by mriscoc** [comment]
From Creality configuration files (works in Ender3V2 with 4.2.2 and 4.2.7 boards):
```cpp
// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false
#define INVERT_Y_DIR false
#define INVERT_Z_DIR true
```

https://github.com/MarlinFirmware/Configurations/blob/bb3c2eaf05df1f23f292645f3fe3ae3582d56592/config/examples/Creality/Ender-3%20V2/CrealityV422/CrealityUI/Configuration.h#L1721-L1723
