### ISSUE TITLE
No trigger signal in Trianglelab 3DTouch

### ISSUE THREAD

**Issue by SergioFrank** [mriscoc/Ender3V2S1#1055]
AUGUST 2023
=========
Hi, I was using Miguel Risco Ender3V2-427-MM-MPC-20230812 firmware on my Ender 3 V2 and I was having problems with the leveling of the bed, probably coming from the Z axis end of course sensor, it often misaligned and my first layer did not attach to the bed. I bought a Trianglelab 3D Touch bed leveler, installed the firmware Ender3V2-427-BLTUBL-MPC-20230809 and things got even worse. The auto home never goes to the Z 0.00 position, it is always 5mm above, every time I request auto home or Z home, the Z axis goes up another 5mm, there is no way to go down via command, with that, of course, the auto leveling is done in air (10mm above). Could someone help me? Detail: I'm using the V 4.2.7 motherboard because I changed the previous V 4.2.2 that had the same problem with Creality's 3D Touch and CR Touch, even using the Jyers firmware. Thanks.

**Comment by classicrocker883** [comment]
this is a safety guard to raise the Z a few mm after homing. do you have the previous Z axis switch still installed? that should be unplugged. 
auto bed leveling isnt actually done in the air. it might start 10mm above, but takes the probe measurements as needed. if you want Z axis to be 0.00 after homing you would need to change that in the firmware source code. otherwise in Z offset wizard menu you can set the nozzle down to the center of the bed and that should do what you are looking to do.

**Comment by SergioFrank** [comment]
Andrew thanks for your attention. There is nothing I do that brings the hotend closer to the bed. Each time I request Z homing, the hotend goes up 5mm, if I request manual leveling, the hotend positions itself in the air. Could you explain better how to change the firmware source code? Where should I change? I am a beginner and still have little knowledge in this area. Thanks if you can help me.


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Andrew ***@***.***>
Enviado: segunda-feira, 28 de agosto de 2023 19:39
Para: mriscoc/Ender3V2S1 ***@***.***>
Cc: SergioFrank ***@***.***>; Author ***@***.***>
Assunto: Re: [mriscoc/Ender3V2S1] AUGUST 2023 (Issue #1055)


this is a safety guard to raise the Z a few mm after homing. do you have the previous Z axis switch still installed? that should be unplugged.
auto bed leveling isnt actually done in the air. it might start 10mm above, but takes the probe measurements as needed. if you want Z axis to be 0.00 after homing you would need to change that in the firmware source code. otherwise in Z offset wizard menu you can set the nozzle down to the center of the bed and that should do what you are looking to do.

**Comment by plastisizer** [comment]
might it be that your table just needs to be brought up a bit as maybe the z axis can't go any lower due to physical restraints? ie use the thumbwheels to raise the table a bit so there is pleany of room for the z axis to make contact.

**Comment by SergioFrank** [comment]
I don't think I'm able to explain my problem. Regardless of how the bed springs are adjusted, any command given to the Z axis makes it move 5mm upwards, so it always moves away, and no command makes it go down again. After going up every 5mm there is no way to go down the hotend except turning off the printer and turning the Z axes (I use two) manually. Does anyone have an idea what might be going on? Thanks.

**Comment by plastisizer** [comment]
ok so you have a BL touch or similar device correct? (touch bed leveler I believe). so that comes down and touches the bed corrrect but you're seeing the nozzle 5mm above the bed correct?...So it sounds like you just need to dial in your z offset no? Mine requires a -1.65 z offset with the swiss micro hotend on the direct extruder...yours may be different...but It's most likely going to be a negative value

**Comment by SergioFrank** [comment]
Yes, it's a Trianglelab 3D Touch. I can put any value for the Z offset when commanding auto leveling the bed will go up 5mm and start leveling in the air, and when I finish doing that, if I command Homing all axes, it will go up another 5mm, if I request new leveling it will go up 5mm more and leveling will be 15mm high. Any idea?


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: plastisizer ***@***.***>
Enviado: terça-feira, 29 de agosto de 2023 14:04
Para: mriscoc/Ender3V2S1 ***@***.***>
Cc: SergioFrank ***@***.***>; Author ***@***.***>
Assunto: Re: [mriscoc/Ender3V2S1] AUGUST 2023 (Issue #1055)


ok so you have a BL touch or similar device correct? (touch bed leveler I believe). so that comes down and touches the bed corrrect but you're seeing the nozzle 5mm above the bed correct?...So it sounds like you just need to dial in your z offset no?

**Comment by mriscoc** [comment]
Hello, check the probe connections (3D touch), the printer raises the Z axis to make room for deploy the probe's tip, then begins to lower the axis until a probe's trigger signal is received.

I think that the trigger signal is always there, so the printer doesn't lower the axis and only raises it.

Note: It is not necessary to remove the Z-end stop switch with this firmware (OFFICIAL BUILDS), I have mine connected to be able to interchange the MM / BLT version for make tests.

**Comment by SergioFrank** [comment]
I believe this is the problem, after your instructions, I tested it with a pin-by-pin multimeter from the motherboard to the 3D Touch connector and the white Z-Stop wire (OUT) is not conducting. I believe that because it is a very thin wire, it broke or came with a manufacturer's defect. I will provide another one and I will post the result here again and my thanks for the commitment and dedication of Miguel Risco and Github collaborators. Thank you very much this was already driving me crazy.


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Miguel Risco-Castillo ***@***.***>
Enviado: quarta-feira, 30 de agosto de 2023 14:23
Para: mriscoc/Ender3V2S1 ***@***.***>
Cc: SergioFrank ***@***.***>; Author ***@***.***>
Assunto: Re: [mriscoc/Ender3V2S1] AUGUST 2023 (Issue #1055)


Hello, check the probe connections (3D touch), the printer raises the Z axis to make room for deploy the probe's tip, then begins to lower the axis until a probe's trigger signal is received.

I think that the trigger signal is always there, so the printer doesn't lower the axis and only raises it.

**Comment by SergioFrank** [comment]
Muito obrigado. Agora funciona bem. Não conseguia entender como um produto novo poderia vir com defeito em seus cabos, Grato a todos colaboradores em especial Miguel Risco pela excelente versão do firmware.


Enviado do Outlook<http://aka.ms/weboutlook>

________________________________
De: Miguel Risco-Castillo ***@***.***>
Enviado: quarta-feira, 30 de agosto de 2023 14:23
Para: mriscoc/Ender3V2S1 ***@***.***>
Cc: SergioFrank ***@***.***>; Author ***@***.***>
Assunto: Re: [mriscoc/Ender3V2S1] AUGUST 2023 (Issue #1055)


Hello, check the probe connections (3D touch), the printer raises the Z axis to make room for deploy the probe's tip, then begins to lower the axis until a probe's trigger signal is received.

I think that the trigger signal is always there, so the printer doesn't lower the axis and only raises it.
