### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by plastisizer** [mriscoc/Ender3V2S1#1057]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

y axis motor seems to overdrive when maxed out

### Bug Timeline

just downloaded the latest build

### Expected behavior

I expected the y axis to stop without overdriving it

### Actual behavior

the Y axis motor continues after the table has reached its maxium limit

### Steps to Reproduce

1. homes all axis
2, I added -10 to the y axis for the swiss micro offset (maybe part of the issue)
3. I added -5 to the x axis as well ( I have not tested to see if the x axis overdrives yet)
4. use the move command to move the y axis to the limit, the motor continues to drive it for what seems to be the 10mm that I added to it( hard to tell...just guessing by the time it continues to drive it)
5. on a separate note, I can't seem to get the updated display firmware to work using the dwin board..copied the file on a formatted drive as directed, seems to install correctly, but no change in the display afterwards. 

### Version of Professional Firmware

Ender-3 V2/S1 Professional Firmware 20230805

### Printer model

ender 3 v2 with bl touch

### Electronics

4.2.2

### Add-ons

swiss micro direct drive, dual z driver motors

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
Check: https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides and reduce XY MAX according to your changes.
