### ISSUE TITLE
need more firmware tweaking 

### ISSUE THREAD

**Issue by HERO5507** [mriscoc/Ender3V2S1#107]
HI I just testing the firmware on my mod ender 3v2 . It is amassing firmware ,it can quickly modify the setting to match the spec .don't have to edit compile the firmware , the firmware is new and need more tweaking to make it perfect for everyone
**Describe the bug
bl touch z baby step don't work
it keep crash when  build mesh ,I have to multiples run 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
Firmware version and release date

**Additional context**

**Comment by mriscoc** [comment]
Hi. There are at least 5 firmware flavors please fill in the issue template.

**Comment by mriscoc** [comment]
Maybe related to the z-offset bug fixed in the latest version.
