### ISSUE TITLE
[BUG] Cant install Profesional firmware on Ender 3 V2 neo

### ISSUE THREAD

**Issue by matte-oss** [mriscoc/Ender3V2S1#1070]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I tried to install the Professional Firmware because the creality stock firmware does not provide enough settings for me, after downloading it, putting it on the SD and inserting it in the printer **the printer remains stuck on the Creality logo**, although on the same SD the stock firmware installs without problems
I know the Ender 3 v2 neo is not officially supported but I have seen other people install it without problems

Thanks in Advance for the replies

### Expected behavior

Insert SD card, loading bar and firmware installed

### Actual behavior

Stuck on creality logo

### Steps to Reproduce

Download Professional Firmware [Ender3V2-422-BLTUBL-MPC-20230809.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20230805/Ender3V2-422-BLTUBL-MPC-20230809.bin)
Format SD card to FAT32 with 4096 bytes of cluster
Put SD card in 3d printer

### Version of Professional Firmware

20230805

### Printer model

Ender 3 V2 neo

### Electronics

Board 4.2.2

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

**WHAT I HAVE TRIED:**
Change SD
Downgrade to an older version of the stock firmware and then install the professional firmware
Wait 30 minutes
Try other versions of Professional firmware

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/issues/966
https://github.com/mriscoc/Ender3V2S1/issues/721
https://github.com/mriscoc/Ender3V2S1/discussions/413
