### ISSUE TITLE
BTT SFS 2.0 filament sensor connection

### ISSUE THREAD

**Issue by madspeed** [mriscoc/Ender3V2S1#1077]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Connection problem

### Expected behavior

Both motion and switch sensors working.

### Version of Professional Firmware

2.1.3

### Printer model

3v2 neo

### Electronics

4.2.2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

### Additional information & file uploads

Has anyone managed to connect BTT SFS 2.0 filament sensor to ender with 4.2.2 board? Please provide firmware setup and wiring diagram.

**Comment by mriscoc** [comment]
It is not a firmware issue, use the Q&A in the discussion page.
