### ISSUE TITLE
Using old configuration files causes compile errors

### ISSUE THREAD

**Issue by gsuresh2u** [mriscoc/Ender3V2S1#1081]
### Did you test with a precompiled firmware?

No, but I will test it now!

### Bug Description

Hi, when i try to compile my own firemware with your source for SKR Mini E3 V3, its giving error `"\marlin\src\lcd\e3v2\proui\proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope"`

[Configs.zip](https://github.com/mriscoc/Ender3V2S1/files/12533686/Configs.zip)

### Bug Timeline

form release Ender3V2S1-20230904

### Expected behavior

Need to compile

### Actual behavior

Not compiling

### Version of Professional Firmware

20230904

### Printer model

Ender 3V2

### Electronics

SKR Mini

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

**Comment by mriscoc** [comment]
Update your configuration files with https://github.com/mriscoc/Special_Configurations

**Comment by gsuresh2u** [comment]
Sir, i am using source files from https://github.com/mriscoc/Special_Configurations/tree/main/Ender3V2-SKRME3V3-BLTUBL-MPC

**Comment by mriscoc** [comment]
DEF_PROBEZFIX is defined there: https://github.com/mriscoc/Special_Configurations/tree/main/Ender3V2-SKRME3V3-BLTUBL-MPC/Configuration.h#L3390

**Comment by Travois123** [comment]
I had this same issue. Ender 3 v2 with an ezabl, 4.2.2 board. Came here looking for a solution after beating my head against the wall for 3 days. Added in the line of code that mriscoc posted in the previous comment and it compiled and am now happily printing again. TYSVM!

**Comment by Viperuss2009** [comment]
> Sir, i am using source files from https://github.com/mriscoc/Special_Configurations/tree/main/Ender3V2-SKRME3V3-BLTUBL-MPC


compiled successfully, need to download special configuration from page itself, not form releases if that makes sense 
![image](https://github.com/mriscoc/Ender3V2S1/assets/140408389/835631a5-73e2-4d68-83af-7d1c65ab0ec2)

**Comment by mriscoc** [comment]
Pre-made configurations files have been deleted; as of now, the proper way to have correct configuration files is by using the Configurator.  
  
![](https://github.com/mriscoc/Special_Configurations/raw/main/images/Configurator.png)

**Comment by gsuresh2u** [comment]
Sir, sorry for late reply, still getting same error, from where can i download source files?
i downloaded from https://github.com/mriscoc/Ender3V2S1

**Comment by mriscoc** [comment]
> from where can i download source files?

You must use the Configurator to generate the configuration files and firmware sources from the main repository.

**Comment by gsuresh2u** [comment]
Yes, I used configurator, still same error

**Comment by mriscoc** [comment]
> Yes, I used configurator, still same error

Look for DEF_PROBEZFIX in your configuration files, if you don't find it, you have old configuration files and you should try downloading the files again until you get DEF_PROBEZFIX.

**Comment by gsuresh2u** [comment]
I found the files, when i try to use configurator, now its giving error

![Configurator](https://github.com/mriscoc/Ender3V2S1/assets/39871361/f8b3c643-25a2-4a63-842f-401512d441fb)

**Comment by mriscoc** [comment]
You need to download **all** files from the [special configurations repository](https://github.com/mriscoc/Special_Configurations).

![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/76ce7c16-08a3-431c-87f0-52396b3152d7)

**Comment by gsuresh2u** [comment]
Ok, Thanks
