### ISSUE TITLE
[BUG] Firmware stuck on "Please wait until reboot" with Link Time Optimization (LTO) enabled

### ISSUE THREAD

**Issue by Luro02** [mriscoc/Ender3V2S1#1083]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

There is a compiler option called [link time optimization (LTO)](https://llvm.org/docs/LinkTimeOptimization.html), which enables further optimizations across compilation units. For example when you link an external library to your project and both have the same function, one of them will be removed.

I added this option to the `ini/stm32f4.ini`:
```diff,ini
[env:STM32F401RC_creality]
extends                     = stm32_variant
board                       = genericSTM32F401RC
board_build.variant         = MARLIN_CREALITY_STM32F401
board_build.offset          = 0x10000
board_upload.offset_address = 0x08010000
board_build.rename          = firmware-{date}-{time}.bin
build_flags                 = ${stm32_variant.build_flags}
                              -DMCU_STM32F401RC -DSTM32F4 -DSTM32F401xC
                              -DSS_TIMER=4 -DTIMER_SERVO=TIM5
                              -DENABLE_HWSERIAL3 -DTRANSFER_CLOCK_DIV=8
+                             -flto
```

With my custom configuration I was able to reduce the space from 191kb to 177kb (~7.3%).
Especially on mainboards like the STM32F4RC, this can be a game change (I think with this one could add MPC and UBL to the standard firmware).

The only problem is that the firmware does not flash, on my printer it is stuck on the "Please wait until reboot" screen.

### Version of Professional Firmware

20230904

### Printer model

Ender 3 S1 F4

### Electronics

STM32F401RC

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

**Comment by mriscoc** [comment]
Connect the printer to a terminal (Pronterface, Octoprint, Termite, etc.) and look for any error message. Try with the current Marlin bugfix, seems to be a problem with that optimization and HAL/EEPROM library.
