### ISSUE TITLE
[BUG] (bug summary)

### ISSUE THREAD

**Issue by bombardeo38** [mriscoc/Ender3V2S1#1086]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

en el manual traming elijas la esquina tato delantera como trasera solo mide las de la izquierda no se desplaza a los puntos derechos de la cama a parte el primer movimiento es extremadamente lento en el traming automatico si se desplaza y a buena velocidad

### Bug Timeline

a sido despues de actualizar a la ultima version

### Expected behavior

que se desplaca a las esquinas manualmente cuando las elijo 

### Actual behavior

cuando seleccion la esquina derecha no se desplaza sube y baja en la esquina izquierda

### Steps to Reproduce

ir a manual tramming y cambiar de izquierda a derecha da igual sies posterior o delantera

### Version of Professional Firmware

2.1.3 20230904

### Printer model

ender 3 v2

### Electronics

4.2.2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
Did you set the correct mesh inset?  https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides

**Comment by bombardeo38** [comment]
si lo hice y calibre los pasos de motores fue un fallo puntual solo me a ocurrido 2 veces es como si la impresora no reconociera la posicion que tu le indicas para moverse seguro que por saturacion de memoria de todas maneras si me puedes ayudar quiero configurar el gcode se salida para que nivele la cama ante de imprimir puse el g29 pero no hace caso en prusa ni cura ultima version gracias por todo

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/Slicer-G-code-Scripts

Not a firmware issue
