### ISSUE TITLE
[BUG] Firmware Configurator Doesn't Launch on Windows

### ISSUE THREAD

**Issue by aerladis** [mriscoc/Ender3V2S1#1089]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

The Configurator for special releases pops up and disappears. When I open it from the command line I get the error;
FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: '_printers'

FYI Turkish part says; The system cannot find the path specified.

### Bug Timeline

Current bug

### Expected behavior

 Program opens

### Actual behavior

A python window flashes and crashes.

When I use command line I get the error; FileNotFoundError: [WinError 3] Sistem belirtilen yolu bulamıyor: '_printers'

### Steps to Reproduce

Download Python.
Installl everyting
Try to run Configurator
Get error

### Version of Professional Firmware

NA

### Printer model

NA

### Electronics

NA

### Add-ons

NA

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
Not a firmware issue
