### ISSUE TITLE
Skr mini board wont turn on heater block cooling fan. [BUG] (bug summary)

### ISSUE THREAD

**Issue by Comicrocket** [mriscoc/Ender3V2S1#1091]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

The fan for cooling the main filament heater will not turn on at all. 

### Bug Timeline

this started as soon as i hooked the board up to the printer

### Expected behavior

The fan should turn on to cool the heater stopping potential fires

### Actual behavior

it wont even turn on

### Version of Professional Firmware

the most recent as of this post

### Printer model

ender 3 v2

### Electronics

skr mini

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
From SKRME3V3 configuration files:

```h
/**
 * Extruder cooling fans
 *
 * Extruder auto fans automatically turn on when their extruders'
 * temperatures go above EXTRUDER_AUTO_FAN_TEMPERATURE.
 *
 * Your board's pins file specifies the recommended pins. Override those here
 * or set to -1 to disable completely.
 *
 * Multiple extruders can be assigned to the same pin in which case
 * the fan will turn on when any selected extruder is above the threshold.
 */
#define E0_AUTO_FAN_PIN PC7
...
#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
```
