### ISSUE TITLE
[BUG] Latest Source code won't compile with configuration from configurator)

### ISSUE THREAD

**Issue by carpe-zz** [mriscoc/Ender3V2S1#1095]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

When downloading the source code and using the output from your configurator tool, I get the below error when trying to compile.

### Bug Timeline

September release - 20230904

### Expected behavior

I've used the configurator for the past three releases with no issues compiling.
Selecting:

Ender3V2, 422, BLT (UBL Checked,) DACAI, T13, LA and MPC

### Actual behavior

platformio run --silent -e STM32F103RE_creality
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\MinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\MinSerial.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\msc_sd.cpp:20:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\msc_sd.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\usb_serial.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\usb_serial.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\HAL.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\MarlinSerial.h:24,
                 from Marlin\src\HAL\STM32\HAL.h:34,
                 from Marlin\src\HAL\STM32\MarlinSPI.h:24,
                 from Marlin\src\HAL\STM32\MarlinSPI.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\Servo.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_bl24cxx.cpp:32:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\HAL_SPI.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\MarlinSPI.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\HAL.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_if_iic.cpp:32:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_sdcard.cpp:31:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_sram.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\eeprom_wired.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\fastio.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\fast_pwm.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\sdio.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\timers.cpp:26:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\MarlinSerial.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\Servo.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\STM32\usb_host.cpp:27:
Marlin\src\HAL\STM32\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\shared\Delay.h:24,
                 from Marlin\src\HAL\shared\Delay.cpp:23:
Marlin\src\HAL\shared\../../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\eeprom_bl24cxx.cpp.o] Error 1
In file included from Marlin\src\HAL\shared\backtrace\../../../core/../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\shared\backtrace\../../../core/../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\shared\backtrace\../../../core/../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\shared\backtrace\../../../core/serial.h:24,
                 from Marlin\src\HAL\shared\backtrace\../MinSerial.h:24,
                 from Marlin\src\HAL\shared\backtrace\backtrace.cpp:28:
Marlin\src\HAL\shared\backtrace\../../../core/../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\shared\../../core/../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\shared\../../core/../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\shared\../../core/../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\shared\../../core/serial.h:24,
                 from Marlin\src\HAL\shared\MinSerial.h:24,
                 from Marlin\src\HAL\shared\MinSerial.cpp:22:
Marlin\src\HAL\shared\../../core/../inc/../lcd/e3v2/proui/proui.h:97:21: error: 'DEF_PROBEZFIX' was not declared in this scope
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
In file included from Marlin\src\HAL\shared\../../inc/../lcd/e3v2/proui/dwin_defines.h:107,
                 from Marlin\src\HAL\shared\../../inc/MarlinConfigPre.h:66,
                 from Marlin\src\HAL\shared\../../inc/MarlinConfig.h:28,
                 from Marlin\src\HAL\shared\HAL.cpp:27:
   97 |   float probezfix = DEF_PROBEZFIX;
      |                     ^~~~~~~~~~~~~
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\eeprom_if_iic.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\eeprom_flash.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\fastio.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\eeprom_sdcard.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\eeprom_sram.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\fast_pwm.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\eeprom_wired.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\sdio.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\timers.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\shared\backtrace\backtrace.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\shared\Delay.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\shared\MinSerial.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\STM32\usb_host.cpp.o] Error 1
*** [.pio\build\STM32F103RE_creality\src\src\HAL\shared\HAL.cpp.o] Error 1

### Steps to Reproduce

Re-download source files, extracting to clean folder.  
Adding configuration files from your configurator tool.

### Version of Professional Firmware

Source files downloaded 9/17/23

### Printer model

Ender 3 V2 

### Electronics

4.2.2

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by classicrocker883** [comment]
it doesnt appear DEF_PROBEZFIX is used. simply comment out any instances 

especially **lcd/e3v2/proui/proui.h** line : 97

**Comment by mriscoc** [comment]
You need to update the [special configurations repository](https://github.com/mriscoc/Special_Configurations/archive/refs/heads/main.zip) (all files)

**Comment by carpe-zz** [comment]
> You need to update the [special configurations repository](https://github.com/mriscoc/Special_Configurations/archive/refs/heads/main.zip) (all files)

Ahhh, this was it.  Somehow I had grabbed the special configurations sponsored zip instead.  My apologies, it's compiling without issue now!  Thanks
