### ISSUE TITLE
[BUG] (Unable to compile custom firmware)

### ISSUE THREAD

**Issue by cooldude290403** [mriscoc/Ender3V2S1#1100]
### Did you test with a precompiled firmware?

Pre compiled firmware is not available with my configuration

### Bug Description

I am currently trying to compile firmware with UBL, IS and LA for my Ender 3 s1 with the STM32F404RCT6 board, however when I try to compile I am met with an error stating that `section .rodata' will not fit in region FLASH'` and `region FLASH' overflowed by 17104 bytes`

If I select the 512k environment, I am able to successfully compile the .bin file.
The .bin file is only 213.7kb when compiled in the 512k environment, so I don't't understand why it won't work in 256k
I did attempt to flash the 512k firmware, but the printer got stuck on the creality logo. I was able to revert to a precompiled version.

Apologies if there is something I'm just missing or if this config simply isn't possible due to size constraints.

### Bug Timeline

Started to day on fresh downloads of all requited files

### Expected behavior

Compile firmware and create .bin file

### Actual behavior

The compiler fails and throws this error
```
linux@pop-os:~/Documents/Marlin/Ender3V2S1-Ender3V2S1-Released$ platformio run --silent -e STM32F401RC_creality ; echo "done" >|"/tmp/ipc"
/home/linux/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: .pio/build/STM32F401RC_creality/firmware.elf section `.rodata' will not fit in region `FLASH'
/home/linux/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 17104 bytes
collect2: error: ld returned 1 exit status
*** [.pio/build/STM32F401RC_creality/firmware.elf] Error 1
=================================== [FAILED] Took 15.63 seconds ===================================

Environment           Status    Duration
--------------------  --------  ------------
STM32F401RC_creality  FAILED    00:00:15.627
============================== 1 failed, 0 succeeded in 00:00:15.627 ==============================
```

### Steps to Reproduce

1. Create custom firmware for the Ender 3 s1 with UBL, IS and LA
2. Attempt to compile firmware using 256k environment
3. Error is generated

### Version of Professional Firmware

2.1.3

### Printer model

Ender 3 S1 F4

### Electronics

STM32F401RCT6

### Add-ons

CL touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
Hello, it is not a firmware error, your SoC does not have enough program memory. Sorry, but I can no longer provide free support for custom builds, but if you search this github you will find the solution.
