### ISSUE TITLE
The download for the zip is broken.  Looking at the HTML, it looks like the zip is just text.  The href is just =""

### ISSUE THREAD

**Issue by thepip3r** [mriscoc/Ender3V2S1#1122]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Can't download the firmware.

### Bug Timeline

Don't know.

### Expected behavior

I should be able to download the firmware.

### Actual behavior

The hyperlink for the zip does nothing.

### Steps to Reproduce

1.  Click on the link (nothing happens)

### Version of Professional Firmware

Ender-3 S1_Pro_HWv24S1_301_SWV2.0.8.26F4_FDM_LASER

### Printer model

3V2S1 Pro

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Not a firmware issue
