### ISSUE TITLE
[BUG] Ender 3 S1 with TJC display doesn't show numbers in bed tramming wizard and mesh viewer.

### ISSUE THREAD

**Issue by roadburp** [mriscoc/Ender3V2S1#1128]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

firmware doesnt work, i cant abl, or tramm.

### Expected behavior

i expected it to tramm

### Actual behavior

its showing colors

### Steps to Reproduce

have a f4 board i guess

### Version of Professional Firmware

the f4 ubl version

### Printer model

f4 s1

### Electronics

?

### Add-ons

none

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Additional information & file uploads

![IMG_0948-min](https://github.com/mriscoc/Ender3V2S1/assets/73664449/7c35f9fd-fabd-4645-9858-00523e5dbe20)

**Comment by mriscoc** [comment]
Not a printer firmware issue.
Already answered, please use the search function in the Github. Look for TJC

**Comment by roadburp** [comment]
i did install it, it changes nothing. it still shows squares.
    On Monday, November 6, 2023 at 05:50:18 AM MST, Miguel Risco-Castillo ***@***.***> wrote:  
 
 


Already answered, please use the search function in the Github. Look for TJC
