### ISSUE TITLE
[BUG] 3D Touch Sensor Probe Does Not Deploy When Homing

### ISSUE THREAD

**Issue by Lillythefox** [mriscoc/Ender3V2S1#1147]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

The 3D touch probe deploys on boot as expected, but when homing the probe dose not deploy and the nozzle crashes into the bed. The probe dose not deploy nor retract when running the tests in the advanced menu. The probe is correctly wired according to this diagram: 
![image](https://github.com/mriscoc/Ender3V2S1/assets/30854494/544e6ff9-4ab6-42d9-846d-c8866607d3bc)

Update: Manually deploying the probe head then telling it to home makes the nozzle crash even though the 3D Touch is triggered. 

### Bug Timeline

New, after installing the probe and flashing the firmware

### Expected behavior

I expected it to extend the probe to home and for the probe to respond to the test commands, 

### Actual behavior

The probe extends and retracts on boot but it dose not extend when I try home or though the test commands.

### Version of Professional Firmware

Precomplied, Ender3V2-422-BLTUBL-MPC-20230904

### Printer model

Ender 3 V2

### Electronics

4.2.2

### Add-ons

3D Touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
Hi, this is not a general printer support forum.

This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:

Enhanced support in Patreon: https://www.patreon.com/mriscoc

Free community support:
- Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
- Facebook: https://www.facebook.com/groups/professionalfirmware
- Telegram: https://t.me/ender3v2s1firmware
- Reddit: https://www.reddit.com/r/Ender3v2Firmware
- Discord: https://discord.gg/3dprinters
