### ISSUE TITLE
Strange Scrolling on Ender 3 V2 with SYNWIT (VIEWE) screen unit

### ISSUE THREAD

**Issue by andrewandneil** [mriscoc/Ender3V2S1#117]
### Description

Artefacts while scrolling through menu on Ender 3 V2’s stock LCD

### Steps to Reproduce

Opening any menu and scrolling causes scroll select bar highlight to ‘follow’ the current selection and instead of removing previous highlight, remains until scrolled on top of. It’s difficult to explain please see video below.

**Expected behavior:** Bars to no longer be highlighted when they are no longer selected

**Actual behavior:** Bars remain highlighted when scrolling through the screen until scrolled back over at which point it is cleared

#### Additional Information

Printer was flashed with the 422 BLTouch pre compiled firmware

![image](https://user-images.githubusercontent.com/20885631/163231012-67c0d8ee-c7c5-415b-be41-082a61148f07.jpg)

![video](https://user-images.githubusercontent.com/20885631/163230404-88596bd8-cbec-43e7-a2a4-94f0e62dac3a.MOV)

**Comment by mriscoc** [comment]
Please post a capture of your info page. From your screenshot, something is bad with your version because the icons are not with transparent background. Maybe the screen is loaded with an incompatible icon set.

**Comment by andrewandneil** [comment]
![image](https://user-images.githubusercontent.com/20885631/163232215-4b17db67-6c68-41b0-af54-5135a9c74c75.jpg)
Is this what you were asking for?

**Comment by mriscoc** [comment]
Did you flash your screen before? If yes, you need to re-flash with a compatible icon set from here: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display

If not, and you have a stock screen unit and your printer is a new purchase, then maybe we have here a new screen unit not checked before, if you can, please post a capture of the board inside of your screen.

**Comment by andrewandneil** [comment]
You know, I think you’re right. Doesn’t fit either the DACAI nor the DWIN screen type. Just got it a few days ago. Everything is stock apart from fans and a CRTouch install.
![image](https://user-images.githubusercontent.com/20885631/163233168-8434050a-f96e-4f7b-be8e-8e852e90c545.jpg)

**Comment by mriscoc** [comment]
Please take a closeup picture from the main chip of the board of the screen unit, as clear as possible, and also from the labels, I will do research. It is similar to the DACAI screen.

**Comment by andrewandneil** [comment]
![IMG_0341](https://user-images.githubusercontent.com/20885631/163235759-4883661d-2738-4ebb-a420-f5f1ffc781cf.jpeg)
![IMG_0342](https://user-images.githubusercontent.com/20885631/163235783-9f2e6309-d7d6-40a2-af45-6594aa6ca5d0.jpeg)
![IMG_0343](https://user-images.githubusercontent.com/20885631/163235791-2ebb40f5-ecee-44d9-8e40-00ac785804e2.jpeg)

Hope these help. Took them zoomed in as much as I could. Please notify if you require more. Thank you for all this.

**Comment by mriscoc** [comment]
I'm preparing a version for your test, could you try it?  
[Experimental-Ender3V2-BLTouch-20220413.zip](https://github.com/mriscoc/Ender3V2S1/files/8483911/Experimental-Ender3V2-BLTouch-20220413.zip)

**Comment by andrewandneil** [comment]
So I just got a chance to try it out. This has fixed the strange scrolling issue, however, scrolling seems ‘laggy’. But much more useable than before. However, I don’t know if you tried to, but it has not fixed the black boxes around the icons. Please see video attached. Thank you again
https://user-images.githubusercontent.com/20885631/163368531-d5d8d2a4-555c-42c3-b9ac-0db2c043a54b.MOV

**Comment by mriscoc** [comment]
The icons are not fixable for your screen firmware version. You can select a darker background color in the Advanced Settings menu.

**Comment by mriscoc** [comment]
Hi, do you have the problem reported here? https://github.com/mriscoc/Ender3V2S1/issues/323
