### ISSUE TITLE
[BUG] Flashing on an Ender 7

### ISSUE THREAD

**Issue by AerosolSP** [mriscoc/Ender3V2S1#1171]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I fully respect that touchscreens are not supported, but I'm kind of at my wits end. 

My Ender 7 with CR Touch won't get past the boot screen, and flashing the firmware I have doesn't get it to work. I'd love to try this, but obviously even though it uses the same motherboard as an Ender 3 S1...it has a touchscreen.

Am I plum outta options here?

### Version of Professional Firmware

Haven't isntalled

### Printer model

Ender 7

### Electronics

2.4.S1_301

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
Hi, this is not a general printer support forum.

This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:

Enhanced support in Patreon: https://www.patreon.com/mriscoc

Free community support:
- Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
- Facebook: https://www.facebook.com/groups/professionalfirmware
- Telegram: https://t.me/ender3v2s1firmware
- Reddit: https://www.reddit.com/r/Ender3v2Firmware
- Discord: https://discord.gg/3dprinters
