### ISSUE TITLE
[BUG] Disable one of more toolbar options causes screen corruption and reboot if scrolled on the main menu

### ISSUE THREAD

**Issue by Crazy-Charles** [mriscoc/Ender3V2S1#1175]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Screen corruption and reboot if one or more toolbar items are disable

### Bug Timeline

New 

### Expected behavior

Too continue operating

### Actual behavior

Crashed and rebooted

### Version of Professional Firmware

Ender3V2-427-BLTUBL-MPC-20231208.bin

### Printer model

3V2

### Electronics

4.2.7

### LCD/Controller

Dwin

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

### Additional information & file uploads

![20231216_103823](https://github.com/mriscoc/Ender3V2S1/assets/119892416/572148a3-de1f-4e37-a0bb-8d299d584df8)
![20231216_103835](https://github.com/mriscoc/Ender3V2S1/assets/119892416/e8dad338-6e85-4546-8b73-eae36579843f)
![20231216_103857](https://github.com/mriscoc/Ender3V2S1/assets/119892416/0fa22643-091d-4526-912a-adfbeba97850)

**Comment by mriscoc** [comment]
Thank you. Fixed in the source code repository and for binaries released after 2023/12/17

**Comment by mriscoc** [comment]
Fixed in current sources
