### ISSUE TITLE
[BUG] unable to print because my printer cant do homing, my z axis won't go down, only up

### ISSUE THREAD

**Issue by ghost** [mriscoc/Ender3V2S1#1178]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Ok, today is my second day using this firmaware, yesterday I had no problems, but I noticed that I would need to calibrate my E-Steps, so today I went to calibrate my E-Steps I did exactly the following, I turned on the printer, I put the hotend at 185c, I waited for the hotend to reach temperature, and use the "comand" extrude 100mm, I stayed for about 10 minutes doing the calibration, I made several changes to the value of my E-Steps, in some of these changes I saved the settings, after finishing the calibration of my E-Steps, I saved the correct value, I put it to preheat, pla with the hotend setting 195C, bed 60C , I went to the hotend settings and went up from 195C to 200C, then I gave the wizard treaming "command", the table was already at the target temperature when I gave the command, when I gave the command the printer started homing, both X and Y axes were measured successfully, but when it started to do the Z axis, it went up, lowered the bltouch test rod, and it didn't go down, instead of going down it stayed still for a while, then the bltouch rod kept going up and down, up and down, until an error message appears on the display, after that, I tried to auto homing, and again, X Y axes are checked, but Z goes up, lowers the test rod, stays still, and then the test rod goes up and go down.
I tried:
restart the printer and start homing (the problem persists)
I restored the default settings and started homing (the problem persists)
I tried turning off hs mode (the problem persists)
I tried printing to check if homing would work there, (the problem persists) 

today is my second day dealing with this problem, looks like, that if i pre heat pla first, and after try to use, wizard treaming, bed mash or auto homing, my z axes wont go dowm. 

Sorry for the bad English and if this is not a bug

### Bug Timeline

today 12/16/2023

### Expected behavior

be able to measure the Z axis to finish homing, in other words, after checking the x y axis, the Z axis goes up a little, bltouch test rod lowers, Z axis goes down until it touches the table, bl touch detects the contact, Z axis goes up a little, Z axis goes down a little, BL touch detects the touch again, and ends homing

### Actual behavior

X Y axes are measured during homing, after that the measurement of the Z axis begins, it goes up, the bl touch rod goes down, it stays for a while, then the bl touch rod goes up and down, up and down, until an error appears on the display, At no point does my Z axis go down after going up
​

### Steps to Reproduce

i think, this is the most acurret 
1. turn on the printer 
2. pre heat pla 
3. wait for it to reach temperature 
4. use the homing "comand"  or wizard treaming, or bad mash

or it could be 

1. set hotend to 180 
2. use the comand extrude 100mm 
5. change your esteps 
6. save some of them, while calibrating
7. do the steps 2 at 4 for more or less 10 minutes 
8. save the corect value of esteps 
9. pre heat pla 
10. change the hot end value 
11. wait the bad to heat
12. use the wizard tream, after the X Y axes are measured, the z axes should bug

### Version of Professional Firmware

2.1.3

### Printer model

ender 3v2

### Electronics

4.22

### LCD/Controller

standart ender 3v2 

### Other add-ons

Creality BLtouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
Hi, this is not a general printer support forum.

This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:

Enhanced support in Patreon: https://www.patreon.com/mriscoc

Free community support:
- Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
- Facebook: https://www.facebook.com/groups/professionalfirmware
- Telegram: https://t.me/ender3v2s1firmware
- Reddit: https://www.reddit.com/r/Ender3v2Firmware
- Discord: https://discord.gg/3dprinters
