### ISSUE TITLE
AML 2.0 sets limits to tramming locations

### ISSUE THREAD

**Issue by smeyernyc** [mriscoc/Ender3V2S1#1179]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

AML 2.0 is amazing. That said, bed tramming wizard (again, love) now only does the last locations tested by the previous print's AML. It will not do all 4 bed corners, just the print's corners. A restart of the printer however sets the tramming locations back to normal.

### Bug Timeline

New

### Expected behavior

Bed tramming wizard will do all four corners regardless of previous print without a restart of the printer.

### Actual behavior

Bed tramming wizard only does tramming of the previous prints locations until printer is restarted.

### Steps to Reproduce

Print a 1CM cube using AML 2.0
Cancel/complete job
Use tramming wizard

### Version of Professional Firmware

Ender3V2-422-BLTUBL-MPC-20231217.bin

### Printer model

Ender 3v2

### Electronics

4.2.2

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
You can reload the previous mesh settings in the end g-code script with G29 L0 for example or maximize and center mesh with C29 M C, the bed tramming wizard uses as corners the mesh limits.

If you have a custom mesh limits use C29 F## L## B## R## (## = position in mm)

When your reboot the printer, the selected mesh slot is reloaded and the limits are restored.

**Comment by smeyernyc** [comment]
@mriscoc Makes sense. Thanks for explaining. Really appreciate your work.
