### ISSUE TITLE
Hot motors latest firmware

### ISSUE THREAD

**Issue by lawhitecross** [mriscoc/Ender3V2S1#1183]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

My motors are getting extremely hot to even the touch after latest firmware, actually since previous one already. Im using the standard settings and using your precompiled version of the firmware for the Ender 3 V2 with the BTT SKR mini v3.

### Bug Timeline

1 month

### Steps to Reproduce

On prints the motors aree getting extremely hot

### Version of Professional Firmware

IRMWARE_NAME:Marlin 2.1.3 MRiscoC Ender3V2-SKRME3V3-BLTUBL-MPC, based on bugfix-2.1.x (Dec 18 2023 00:00:05)

### Printer model

3V2

### Electronics

Skr Mini v3

### LCD/Controller

stock LCD

### Other add-ons

microswiss direct drive

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
Check the values of the TMC drivers current in advanced settings.
