### ISSUE TITLE
Thermal runaway stock ender 3v2 with Ender3V2-422-MM-MPC-20231208

### ISSUE THREAD

**Issue by notwired** [mriscoc/Ender3V2S1#1197]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Was printing a gcode from octoprint installed on RPi and after 30 minutes, tasmota plugin that was monitoring thermal limits reported a thermal runaway and turned off the printer. Octoprint reported that the temperature blinked at 1000 degrees C. 

### Bug Timeline

printed fine with this firmware for many days

### Version of Professional Firmware

Ender3V2-422-MM-MPC-20231208

### Printer model

Creality Ender 3V2 stock

### Electronics

Board 4.2.2

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
Did you removed the +VUSB from the USB cable? https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint

**Comment by notwired** [comment]
Yes its taped day one. Since yesterday i printed the same part twice and no error. Maybe its the hotend thermistor going bad.

**Comment by mriscoc** [comment]
Could be related to https://github.com/mriscoc/Ender3V2S1/issues/889

**Comment by Fortex365** [comment]
<img width="590" alt="image" src="https://github.com/mriscoc/Ender3V2S1/assets/60440858/7eeb4277-b404-4019-aa0b-cad29b92469c">

4.2.2 + stock e3v2 thermistor and heater, custom build your firmware from latest in december:
<img width="451" alt="image" src="https://github.com/mriscoc/Ender3V2S1/assets/60440858/d93a92db-b984-47b2-96fc-4d41e376ce27">

rpi power pin disabled

**Comment by mriscoc** [comment]
Your temperature plot is very inconsistent, check your thermistor.
