### ISSUE TITLE
JPEG Thumbnail not visible

### ISSUE THREAD

**Issue by Transcedental** [mriscoc/Ender3V2S1#120]
Printer Ender 3  V2, Firmware 20220330, firmware of display updated (DACAI), Cura v. 4.13.1 - plugin "Create JPEG Thumbnail" installed and activated. 
When Cura plugin is deactivated and new STL file sliced, then printer show QR code with link - OK from my side.
When Cura plugin is active then Thumbnail is generated in G-code but in printer is not visible.

![20220415_091926](https://user-images.githubusercontent.com/103732161/163687080-cdb9ce5e-0f59-4952-a010-dfee42fb0300.jpg)
![20220415_092003](https://user-images.githubusercontent.com/103732161/163687084-84bb5de5-38b6-4e2a-a258-c0d92340007f.jpg)
![20220415_092120](https://user-images.githubusercontent.com/103732161/163687085-c4d57b37-e0ea-4e76-925f-c3887b93d15b.jpg)
![20220415_092258](https://user-images.githubusercontent.com/103732161/163687086-701361e1-0568-4fbd-ae07-eabd8c3e5369.jpg)

**Comment by Nbrooks639** [comment]
![image](https://user-images.githubusercontent.com/100983669/163690722-33119a24-fb83-4804-96f4-901a4034ab6d.png)

**Comment by KriswiffaK** [comment]
Same deal here-

However it used to work

**Comment by mriscoc** [comment]
> Same deal here-
> 
> However it used to work

If the embedded thumbnail is too large the preview is disabled.

**Comment by KriswiffaK** [comment]
> > Same deal here-
> > 
> > However it used to work
> 
> If the embedded thumbnail is too large the preview is disabled.



230x180 set in cura

**Comment by mriscoc** [comment]
> > > Same deal here-
> > > However it used to work
> > 
> > 
> > If the embedded thumbnail is too large the preview is disabled.
> 
> 230x180 set in cura

Not only about the dimensions, but thumbnail size in bytes.
