### ISSUE TITLE
Does this work with the Ender 3 S1 Pro?

### ISSUE THREAD

**Issue by leberschnitzel** [mriscoc/Ender3V2S1#121]
Hi!
does this Firmware work with the Ender 3 S1 Pro with touch screen control?
Happy to try out things to test it, just want to make sure there's no "no go".

**Comment by Cal-LF** [comment]
Refer to #114

**Comment by leberschnitzel** [comment]
Ok, thank you!
Than I'll see what I can find out about the touch screen and if I can use the core firmware with adapted touch screen firmware, since that seems available in the download folder for the pro.
