### ISSUE TITLE
[BUG]  When SPEAKER was enabled, setting `LCD_FEEDBACK_FREQUENCY_DURATION_MS` and `LCD_FEEDBACK_FREQUENCY_HZ` to zero does not turn off LCD encoder tick sound

### ISSUE THREAD

**Issue by Abasz** [mriscoc/Ender3V2S1#1213]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Even though I set `LCD_FEEDBACK_FREQUENCY_DURATION_MS` and `LCD_FEEDBACK_FREQUENCY_HZ` to zero in config, I still get tone on encoder click.

I think the issue is that in the code below the BUZZ frequency is hard coded instead of using the above variables:

```cpp
// TODO: Replace with ui.quick_feedback
void Encoder_tick() {
  #if ENABLED(SPEAKER)
    if (ui.sound_on) BUZZ(50,800);
  #elif HAS_BEEPER
    if (ui.sound_on) buzzer.click(10);
  #endif
}
```

I happy to submit a quick PR where I change the 50 and the 800 to the config values. Let me know what you prefer.

### Bug Timeline

Issue started when `  #if ENABLED(SPEAKER)     if (ui.sound_on) BUZZ(50,800);` line was introduced to the code

### Expected behavior

To be able to disable the LCD UI menu feedback while keeping sound for events like filament runout on.

### Actual behavior

LCD UI menu sound is tied to the sound on and off

### Steps to Reproduce

1. Set the LCD_FEEDBACK_FREQUENCY_DURATION_MS` and `LCD_FEEDBACK_FREQUENCY_HZ` to zero and compile
2. Enable sound
3. listen to the beep on encoder click

### Version of Professional Firmware

20240107

### Printer model

ender 3v2

### Electronics

SKR mini

### LCD/Controller

Dwin

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
Thank you!
