### ISSUE TITLE
Speed Problem prof firmw. Ender 3v2 4.2.2.

### ISSUE THREAD

**Issue by MIB205** [mriscoc/Ender3V2S1#1242]
Hallo together. I installed The professional firmware yesterday on my ender 3v2 4.2.2. 
Leveling and adjusting worked very well. When I wanted to print, the Brim was printed with the right speed. As IT starts to prind the Objekt. IT startet to print very fast on the first Player. I had to pull IT Down to 20 % of the speed and IT Was still to fast.
The Brim in the next layer it continue in a slow speed. Later IT get again very fast.
Hast anyone an idea where i can Chance some settings oder install new files?
I will be thankfull for any Information.
Greats Michael

_Originally posted by @MIB205 in https://github.com/mriscoc/Ender3V2S1/discussions/1241_

**Comment by mriscoc** [comment]
Hi, this is not a general printer support forum.

This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:

Enhanced support in Patreon: https://www.patreon.com/mriscoc

Free community support:
- Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
- Facebook: https://www.facebook.com/groups/professionalfirmware
- Telegram: https://t.me/ender3v2s1firmware
- Reddit: https://www.reddit.com/r/Ender3v2Firmware
- Discord: https://discord.gg/3dprinters
