### ISSUE TITLE
[BUG] (support for runout sensor not working)

### ISSUE THREAD

**Issue by CalDymos** [mriscoc/Ender3V2S1#1243]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I have an Ender 3 S1 with filament run-out sensor.
I have activated the sensor in the "Filament Settings Menu" and checked its function via the "end-stop diagnostic page".
If I now start a print and no filament is loaded, the print process starts anyway, i.e. the print process starts without filament.
I have also tried to set the "Runout Active" parameter to LOW, which also did not help.
Changing the "Runout Dist mm" to 1mm doesn't help either.
The run-out sensor remains without function.
Even if I pull the filament out of the sensor during printing, the print does not stop.

### Expected behavior

Printer stopps if filament runs out and print does not start if no filament is loaded

### Actual behavior

The printer does not stop when the filament runs out and printing starts even if no filament is loaded.

### Version of Professional Firmware

2.1.3 ( Ender3S1-F4-UBL-20240126.bin )

### Printer model

Ender 3 S1

### Electronics

STM32F401

### LCD/Controller

TJC

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

**Comment by ShixinSun** [comment]
Same problem, the printer kept running even though the filament had run out.
I've checked the sensor and tried several settings in the filament menu without success. 
It works with the original firmware.

**Comment by mriscoc** [comment]
The filament runout sensor is only checked when the extruder movement begins, and if the filament is missing, Marlin waits for "Runout Dist" before to launch an alert, of course the firmware only controls that if the print job was started from the SD.

**Comment by CalDymos** [comment]
I have also tried this.
When I start a print process from the SD card and no filament is loaded, the print process starts without a message.
I have already set Runout Dist down to 1mm, without success.

In the original Creality firmware, the print stops when the filament runs out and the print process cannot be started if no filament is loaded.
