### ISSUE TITLE
[BUG] Printer occasionally restarts after selecting gcode with thumbnail

### ISSUE THREAD

**Issue by Spencer-Yoder** [mriscoc/Ender3V2S1#1249]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

After turning the printer on when I select a gcode file with a thumbnail in it, the printer will restart. It will keep happening until randomly after many restarts, it will fix its self and start working. While this is happening, it will not restart when trying to load a gcode file that doesn't have a thumbnail. 

I have tried different scenarios of inserting the sd card and then turning on the printer, as well as turning on the printer and then inserting the card.

https://github.com/mriscoc/Ender3V2S1/assets/25213226/05f6ba5c-a2a6-48c6-91c9-90bdb96de8a4

### Bug Timeline

It wasn't an issue in 20230805, but now happens in 20240127

### Expected behavior

When selecting a gcode file that contains a thumbnail, the gcode file is loaded and is able to be printed

### Actual behavior

The printer restarts.

### Steps to Reproduce

1. Turn the printer on
2. Navigate to a gcode file that has a thumbnail, and select it
3. Observe the printer restart 
4. Repeat and eventually it will work

### Version of Professional Firmware

2.1.3 20240127 - 14:17

### Printer model

S1 F4

### Other add-ons

None

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Additional information & file uploads

[gcode file.zip](https://github.com/mriscoc/Ender3V2S1/files/14173335/gcode.file.zip)

I download the firmware from the Special Configurations repo under the Linear Advance release. ` Ender3S1-F4-LA-20240127.bin`
https://github.com/mriscoc/Special_Configurations/releases/tag/LinearAdvance

**Comment by Witska** [comment]
I have the same problem (not always), firmware Ender3S1-F4-DACAI-T13-LA

115200 baud rate
ɽ���I��F*g��Si��-���cgk�bootloader SD card...

SD����û��update.bin�ļ�
���kC�����)�{�MHYY������N��[)�)i�)++e�N��cy�c�­�μ
�c��
�o)��k�k{�sik)k����������kk!�!�ki�xzo�o�ު����ػ�������{k�g��ʮ�k[�������ocC�k�     ��w�c
���)i���{�H))�ȵa-

250000 baud rate
File opened: XYZCAL~2.GCO Size: 645621
File selected
����x����x�������������������~����f����`��怘start
 Watchdog Reset
Marlin ProUI Version: 2.1.3 MRiscoC
CUSTOM BUILD: 20240201 - 21:38
Author: Miguel Risco-Castillo (MRiscoC)
echo: Free Memory: 53759  PlannerBufferBytes: 1792
echo:A90 stored settings retrieved (827 bytes; crc 52775)
//action:notification Stored settings retrieved
//action:prompt_end
BL24CXX Check succeeded!
echo:SD card ok
echo: Serial 0 baud rate set to 250000
ok P15 B16

**Comment by mriscoc** [comment]
Thanks for the report, how many attempts approx. are necessary to trigger the bug with that g-code?

**Comment by Witska** [comment]
I get the error intermittently. It doesn't matter which g-code, it's the same with all of them. Taking out the sd card and inserting it doesn't help, only turning off the printer for more than 20s.

**Comment by SYoder1** [comment]
> Thanks for the report, how many attempts approx. are necessary to trigger the bug with that g-code?

It normally happens right when turning on the printer, and then will continue for ~15 more times. Then just fix it's self and load.

**Comment by Spencer-Yoder** [comment]
> Thanks for the report, how many attempts approx. are necessary to trigger the bug with that g-code?


It normally happens right when turning on the printer, and then will continue for ~15 more times. Then just fix it's self and load.

**Comment by mriscoc** [comment]
I tried the same G-code with a 4.2.2 board (at least 20 times) without issue, so, it is specific to S1 F4 boards. It could also be a problem with certain SD cards and the board's controller.

**Comment by classicrocker883** [comment]
this isn't specific to anything initially. its more prevalent in chips having 256k because it seems the thumbnail image cache isnt being cleared once exited.
for reference:  
https://github.com/classicrocker883/MRiscoCProUI/issues/64 

I was able to fix over on my end.

**Comment by mriscoc** [comment]
> this isn't specific to anything initially. its more prevalent in chips having 256k because it seems the thumbnail image cache isnt being cleared once exited. for reference: [classicrocker883#64](https://github.com/classicrocker883/MRiscoCProUI/issues/64)
> 
> I was able to fix over on my end.

That's a different issue related only to the SDcard management, in the official ProUI the image is read in little chunks so the memory is never filled.

**Comment by Spencer-Yoder** [comment]
Sorry I am just getting back to this.

I tried with a few different SD cards (the card that came with the printer, SanDisk, PNY) and they all have the same problem. I have noticed that if you change the filament before trying to open a file, it works on the first attempt. I don't know if it has something to do with just waiting, or if a different operation cleans something up.

**Comment by mriscoc** [comment]
> Sorry I am just getting back to this.

Check that you have the latest firmware version: Control / Info / Build date

**Comment by Spencer-Yoder** [comment]
> > Sorry I am just getting back to this.
> 
> Check that you have the latest firmware version: Control / Info / Build date

I am still running `2.1.3 20240127 - 14:17`. I got the firmware from the Linear Advance release https://github.com/mriscoc/Special_Configurations/releases/tag/LinearAdvance

**Comment by Spencer-Yoder** [comment]
I am still running having this issue
