### ISSUE TITLE
[BUG] Cleaning/prime the nozzle off the table

### ISSUE THREAD

**Issue by ms-daniel** [mriscoc/Ender3V2S1#1257]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

the printer is cleaning the nozzle practically off the table. See images.

On Orca Slicer:
the printer is cleaning the nozzle practically off the table
![image](https://github.com/mriscoc/Ender3V2S1/assets/62726040/2171c667-ff1d-4dcf-bf5f-951b26a0b00b)

on the printer:
See "Actual behavior"

### Bug Timeline

i installed this firmware for the first time, so in the first print this happened

### Expected behavior

Before installation, cleaning was done on this blue line:
![image](https://github.com/mriscoc/Ender3V2S1/assets/62726040/703dce08-e094-4905-bfdd-bbcdffd40c82)

### Actual behavior

On the printer (red circle):
![image](https://github.com/mriscoc/Ender3V2S1/assets/62726040/5e65281c-3fa9-497a-8893-d3ffa06cb521)

### Steps to Reproduce

I just did the usual, I generated the gcode and when I started printing it cleaned the nozzle outside the table

### Version of Professional Firmware

2.1.3 (20240127)

### Printer model

Ender 3V2 Neo

### Electronics

Board 4.2.2

### LCD/Controller

TJC (i did the update)

### Bed Leveling

None

### Your Slicer

Other (explain below)

### Host Software

SD Card (headless)

**Comment by ms-daniel** [comment]
more images:
![image](https://github.com/mriscoc/Ender3V2S1/assets/62726040/ecdb1dc4-5ca0-414d-9175-64ef9d095618)
![image](https://github.com/mriscoc/Ender3V2S1/assets/62726040/cbfc9667-6d73-4ea3-bff1-6e03e5db81fc)
![image](https://github.com/mriscoc/Ender3V2S1/assets/62726040/14c4d481-2528-4a6c-9e2a-ec368593d454)

**Comment by mriscoc** [comment]
Hi, this is not a general printer support forum. Many problems can be easily solved by reading the firmware manual [Wiki](https://github.com/mriscoc/Ender3V2S1/wiki#main-topics) please check the calibration guide.

This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:

Enhanced support in Patreon: https://www.patreon.com/mriscoc

Free community support:
- Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
- Facebook: https://www.facebook.com/groups/professionalfirmware
- Telegram: https://t.me/ender3v2s1firmware
- Reddit: https://www.reddit.com/r/Ender3v2Firmware
- Discord: https://discord.gg/3dprinters

**Comment by ms-daniel** [comment]
> Hi, this is not a general printer support forum. Many problems can be easily solved by reading the firmware manual [Wiki](https://github.com/mriscoc/Ender3V2S1/wiki#main-topics) please check the calibration guide.
> 
> This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:
> 
> Enhanced support in Patreon: https://www.patreon.com/mriscoc
> 
> Free community support:
> 
> * Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
> * Facebook: https://www.facebook.com/groups/professionalfirmware
> * Telegram: https://t.me/ender3v2s1firmware
> * Reddit: https://www.reddit.com/r/Ender3v2Firmware
> * Discord: https://discord.gg/3dprinters

Thanks, and sorry me 🥹
