### ISSUE TITLE
Restart Printer menu option results in error (STM32F401)

### ISSUE THREAD

**Issue by theSt33v** [mriscoc/Ender3V2S1#126]
**Describe the bug**
Restarting the printer via the menu option reboots the printer and immediately shows an M112 error.

**To Reproduce**
1. Reboot printer via menu option.
2. Printer reboots.
3. Printer shows message "Printer killed! M112 Shutdown. Turn off printer." Printer is unresponsive until power cycled.

**Expected behavior**
Printer reboots without error.

**Version (please complete the following information):**
Experimental build 2.1.0.1 15Apr2022 (STM32F401)

**Comment by mriscoc** [comment]
M112 could be an error reported by Octoprint, Check this: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint
