### ISSUE TITLE
Support for Ender 3 S1 with the STM32F401RCT6 SoC

### ISSUE THREAD

**Issue by mriscoc** [mriscoc/Ender3V2S1#128]
New Release candidate version with the changes from the APRIL2022 release, only for Ender3S1 with the **STM32F401RCT6** chip:  

[Ender3S1-STM32F4-20220515.zip]()

The issue https://github.com/mriscoc/Ender3V2S1/issues/125 has been fixed.

@houseofbugs has discover that the firmware must be inside the STM32F4_UPDATE folder of the memory card for a correct flash procedure in some S1 F4 printers.

This is a private build for testing the compatibility of the firmware with the **Ender3S1** with the **F4 SoC**, please use it with caution.

### Disclaimer
THIS FIRMWARE AND ALL OTHER FILES IN THE DOWNLOAD ARE PROVIDED FREE OF CHARGE WITH NO WARRANTY OR GUARANTEE. SUPPORT IS NOT INCLUDED JUST BECAUSE YOU DOWNLOADED THE FIRMWARE. WE ARE NOT LIABLE FOR ANY DAMAGE TO YOUR PRINTER, PERSON, OR ANY OTHER PROPERTY DUE TO THE USE OF THIS FIRMWARE. IF YOU DO NOT AGREE TO THESE TERMS THEN DO NOT USE THIS FIRMWARE.

**Comment by mriscoc** [comment]
Zip file updated, some printers need the binary file in the root of the memory card.

**Comment by mriscoc** [comment]
Zip file updated, applied latest Marlin Bugfix.

**Comment by kiby** [comment]
Hi.
Experimental-Ender3S1-STM32F4-20220504 Tested.
Changed settings are not stored to EEPROM when saved (STM32F401)

**Comment by WZ9V** [comment]
I can also confirm that settings are not saved.  I just got a replacement board which has the F4, ran the Hotend PID tune, saved the updated settings, powered down and upon restart the setting were back to the defaults.  Experimental Zip 20220504.  Any chance you can post the config changes needed so I can make a few changes for the Sprite Pro Extruder.

**Comment by Maxtor78** [comment]
hello, 
so me when I install it the screen is frozen on the logo.
i have a pro version

**Comment by WZ9V** [comment]
Did you upgrade the screen firmware first?  If not, you will need to open it up and upgrade it with a micro SD card.  Look at Wiki topic updating the display.

**Comment by nickgarvey** [comment]
I'm not sure this works for the pro version?

**Comment by WZ9V** [comment]
Oh yeah, I forgot that I swapped the non-touch screen display with the knob on my S1 Pro.  The touchscreen won't work.

**Comment by shmink** [comment]
Thanks for this. My printer wasn't even booting until I tried this firmware so you really saved me.

As others have mentioned it does seem like some settings aren't being saved. Should there be a _save config_ in the prepare section?

**Comment by mriscoc** [comment]
> Thanks for this. My printer wasn't even booting until I tried this firmware so you really saved me.
> 
> As others have mentioned it does seem like some settings aren't being saved. Should there be a _save config_ in the prepare section?

The is currently a known issue https://github.com/mriscoc/Ender3V2S1/issues/125 we are working to fix that.

**Comment by mriscoc** [comment]
New Release Candidate for the Ender3S1F4, the file has been updated.

**Comment by shmink** [comment]
Super small detail that I've noticed since updating my firmware to this new version is that 9x9 mesh levelling seems to fail all the time for me. Not sure if it's just me though.

**Comment by WZ9V** [comment]
Mine finished the 9x9 grid but the front left was squished and the back was to high.  I trammed the bed so that it was within 0.01 on the corners.

**Comment by WZ9V** [comment]
> New Release Candidate for the Ender3S1F4, the file has been updated.

Link?

**Comment by mriscoc** [comment]
> Super small detail that I've noticed since updating my firmware to this new version is that 9x9 mesh levelling seems to fail all the time for me. Not sure if it's just me though.

Check that you have the HS mode disabled for meshes larger than 5x5.

**Comment by TopazAaron** [comment]
@mriscoc Appreciate the work on the RC for the F4 chip. I've been playing around with it and I've noticed the filament runout sensor isn't working still. just letting you know.

**Comment by mriscoc** [comment]
> @mriscoc Appreciate the work on the RC for the F4 chip. I've been playing around with it and I've noticed the filament runout sensor isn't working still. just letting you know.

Check your runout distance and the End-stop diagnostic.

**Comment by xXwinsXx** [comment]
End-stop diagnostic works, for me your firmware works quite well, what doesn't work is the bed size setting, it reboots after installation. Everything is saved, even after several hours, all settings are retained.
What bothers me in the print display is the unnecessary remaining display, get rid of it and please do the rest of the time.

**Comment by xXwinsXx** [comment]
Hi, ok the flow is not saved after the printer is switched off, which I don't like, the Z offset I set is retained after the switch is switched off, but the first layer is still not always the same, what I noticed is that the Z motors in the print don't move which means to me that BED leveling isn't carried over, that's a real shame.

**Comment by mriscoc** [comment]
> Hi, ok the flow is not saved after the printer is switched off, which I don't like, the Z offset I set is retained after the switch is switched off, but the first layer is still not always the same, what I noticed is that the Z motors in the print don't move which means to me that BED leveling isn't carried over, that's a real shame.

The flow is never saved, not even in the stock firmware, flow is only a corrective parameter when the calibration of the e-steps is not ok. If you want to have a corrective flow set to a given value, you can use the G-code M221: https://marlinfw.org/docs/gcode/M221.html
To use mesh leveling don't forget to add the M420 S1 after the G28 as is indicated in the wiki.

**Comment by mriscoc** [comment]
I'm closing this issue now, please open a new issue if you found a bug or want to request a feature, remember to do a search first on the closed issues for not to duplicate them.

**Comment by trulow** [comment]
Will the latest release [Ender3S1-STM32F4-20220515.zip]() work with S1 Pro and the 300 degree all metal hot end?

**Comment by Skydsler** [comment]
> Will the latest release [Ender3S1-STM32F4-20220515.zip]() work with S1 Pro and the 300 degree all metal hot end?

nope, only 260°... maybe we get a new 300° version from @mriscoc  :) :)

**Comment by trulow** [comment]
> > Will the latest release [Ender3S1-STM32F4-20220515.zip]() work with S1 Pro and the 300 degree all metal hot end?
> 
> nope, only 260°... maybe we get a new 300° version from @mriscoc :) :)

Thanks, I was able to get this version of the firmware working on my S1 Pro. Had to purchase and install a v2 screen but everything seems to work without issues. Hopefully there's an update soon to which supports the higher temps the S1 Pro provides.

**Comment by acothebraco** [comment]
> > > Will the latest release [Ender3S1-STM32F4-20220515.zip]() work with S1 Pro and the 300 degree all metal hot end?
> > 
> > 
> > nope, only 260°... maybe we get a new 300° version from @mriscoc :) :)
> 
> Thanks, I was able to get this version of the firmware working on my S1 Pro. Had to purchase and install a v2 screen but everything seems to work without issues. Hopefully there's an update soon to which supports the higher temps the S1 Pro provides.


Edit the Configuration.h on HEATER_0_MAXTEMP 275 to 295 and recompile the Firmware again and you have higher Temp on the Extruder Pro. Note:  The difference is ever 15 degree Celsius in the Firmware to real Temp. That means you will have  280 degree Celsius in real when you set it to 295 in the Configuration.h

**Comment by GS1305** [comment]
Hallo alle zusammen. Ich haffe das einer von euch mir weiter helfen kann. Meine Situation ist das ich nach dem Tausch meines Defektem Mainboard das neue nicht über SD karte(4GB-32GB FAT32) nicht flashen kann. Egal welche Release ich benutze. Nun habe ich mir Arduin uno besorg und möchte nun direkt die Firmware und den Bootloader Flashen. Leider finde ich keine Information welche pins ich verbinden muss. 4 pins STM32 GND SWDIO SWCLK und VCC. Frage wo muss ich SWDIO und SWCLK am Arduino anschließen. Oder het das auch über AREF (Arduino) USB STM32?

**Comment by Skydsler** [comment]
> Hallo alle zusammen. Ich haffe das einer von euch mir weiter helfen kann. Meine Situation ist das ich nach dem Tausch meines Defektem Mainboard das neue nicht über SD karte(4GB-32GB FAT32) nicht flashen kann. Egal welche Release ich benutze. Nun habe ich mir Arduin uno besorg und möchte nun direkt die Firmware und den Bootloader Flashen. Leider finde ich keine Information welche pins ich verbinden muss. 4 pins STM32 GND SWDIO SWCLK und VCC. Frage wo muss ich SWDIO und SWCLK am Arduino anschließen. Oder het das auch über AREF (Arduino) USB STM32?

Hallöchen,

Hast du schon geschaut welcher Chip auf dem neuen Board ist?

**Comment by GS1305** [comment]
STM32F103RCT6

**Comment by Skydsler** [comment]
> STM32F103RCT6

Dann sollte die hier ( https://github.com/mriscoc/Ender3V2S1/releases/download/20220419/Ender3S1-20220419.bin)  im root Verzeichnis der SD funktionieren... Ggf auch die MM variante

**Comment by GS1305** [comment]
alles schon probiert wie es scheint worde beim aufspielen der Firmware das annehmen von neuer über SD ausgeschaltet. Dadurch liest das System nicht ob eine neue Version vorhanden ist und installiert sie. Um das zu beheben habe ich herausgefunden muss ich einen neuen bootloader aufspielen und dann sollte es auch mit SD funktionieren. Leider hat das Neue Systemboard nur 4 pin und USB anschluss. Daher meine Frage wie schliesse ich das STM an Arduino an. Für 8 Bit finde ich alle informationen aber nichts zum 32Bit

**Comment by Skydsler** [comment]
Klingt schon komisch. Wo hast du dein board bestellt? Habe jetzt 4 Stück bestellt und immer ein F401 board bekommen... Hätte auch gern ein 103er :)

**Comment by GS1305** [comment]
direkt von Creality

**Comment by GS1305** [comment]
Das alte und das neue sind identisch. Hab gelesen das man den zugriff für Firmenware von der SD karte entsprechend ausschalten kann. Somit muss ich nur einen neuen Bootloader aufspielen und dann anschließend über USB die Firmware laden

**Comment by xXwinsXx** [comment]
Ich habo vom Creality Support einen RAR Datei bekommen. Der Inhalt ist, Booloader samt Firmware für denn F4 Chip inklusive Anleitung.  Kann ich die RAR Datei hier hochladen? wie?

**Comment by GS1305** [comment]
OK kannst du mir die per mail senden

**Comment by xXwinsXx** [comment]
Wenn ich die hier hoch lade haben alle was davon. Ich weiß nicht wie das mit nem Iphone funktioniert. Du?

**Comment by Skydsler** [comment]
Da müsstest du mit @mriscoc reden, ob er die Datei mit veröffentlichen will.
In Englisch wenn möglich :) alternativ auch Spanisch xD

**Comment by GS1305** [comment]
hei xXwinXx kannst du sie mir mach gsvws1305 @ gmail . com senden. Vieleicht ist da auch ne anleitung für die anschlüsse drin.

**Comment by xXwinsXx** [comment]
Ok gut, dann hoffe ich er wird es lesen. Email ist gesendet

**Comment by GS1305** [comment]
ok danke

**Comment by mtigeli** [comment]
Hallo
Haben Sie versucht, die Firmware mit hilfe dieser Video-Tutorials zu flashen?
https://youtu.be/byOzpJXpUTo?t=39

**Comment by Skydsler** [comment]
> Ok gut, dann hoffe ich er wird es lesen. Email ist gesendet

Welche Firmware-Version haben sie dir gesendet?
3.0.3? Oder 3.0.4?

**Comment by GS1305** [comment]
3.0.3

**Comment by GS1305** [comment]
hab leider noch nichts bekommen gsvws1305@gmail.com

**Comment by GS1305** [comment]
mtigeli das ist nur die firmware für display

**Comment by xXwinsXx** [comment]
> mtigeli das ist nur die firmware für display

Nein das ist die Firmware fürs Board. Die fürs Display ist aber auch dabei. In der Beschreibung steht auch drin das man einen Update ordner erstellen muss. Glaub mir die haben mir alles gesendet so wie ich die fertig gemacht habe 😄

**Comment by GS1305** [comment]
ok dann werde ich mal es versuchen

**Comment by GS1305** [comment]
Sorry [xXwinsXx] es war für mtideli. Von dir habe ich noch nichts erhalten hatte dir noch mal die Adresse gesendet gsvws1305@gmail.com

**Comment by xXwinsXx** [comment]
> Sorry [xXwinsXx] es war für mtideli. Von dir habe ich noch nichts erhalten hatte dir noch mal die Adresse gesendet [gsvws1305@gmail.com](mailto:gsvws1305@gmail.com)

Immer noch nicht? Spam Ordner?

**Comment by GS1305** [comment]
angekommen. War im Spam wie lange hat das bei dir gedauert

**Comment by GS1305** [comment]
Hat funktioniert. Aber schön blöd das man ein update Verzeichnis anlegen muss

**Comment by Skydsler** [comment]
Dann war es aber doch kein f103 Board oder?

**Comment by GS1305** [comment]
doch

**Comment by GS1305** [comment]
Nun mal wieder eine frage an alle. Leider scheint es so das es kaum mehr möglich ist eine Marlin Firmware auf das STM32F103RCT6 zu bringen. Habe nun eine neues von Creality aufspielen können aber kein von Marlin. Habe alles mögliche versucht. Der Bootloader hängt sie immer wieder auf und ich muss dann mit dem Bootloader und dem Update von  Creality drüber gehen. Kann es sein das ich nur über usb c - icsp (zb Arduino) flashen kann. Oder hat da jemand ne tipp. Würde gern wieder mit Marlin abeiten.

**Comment by GS1305** [comment]
So neues update von mir nach langen hin und herhabe ich es geschaft mein neues board upzudaten. Zu meiner Schande muss ich gestehen das ich davon ausging ein 103 bekommen zu haben. So wie es aber jetzt aussieht habe ich ein F4 bekommen. Nach dem ich das Verzeichnis auf SD erstellt habe und die Datei dort hinein kopiert hatte ging das update ohne Probleme durch. Jetzt habe ich nur noch die Herausforderung wie ich meinen neuen Extruder(300 grad) richtig aufheizen kann. Da warte ich sehnsüchtig auf ein neues Update.

**Comment by mriscoc** [comment]
To unlock the temperature limit of the hotend you can use this G-code in a terminal as Octoprint with the latest firmware version:
```gcode
C104 U1 T300  ; set absolute limit to 300°C
M500          ; save settings
```
But be careful to not to exceed the manufacturer's limit.

**Comment by Skydsler** [comment]
> So neues update von mir nach langen hin und herhabe ich es geschaft mein neues board upzudaten. Zu meiner Schande muss ich gestehen das ich davon ausging ein 103 bekommen zu haben. So wie es aber jetzt aussieht habe ich ein F4 bekommen. Nach dem ich das Verzeichnis auf SD erstellt habe und die Datei dort hinein kopiert hatte ging das update ohne Probleme durch. Jetzt habe ich nur noch die Herausforderung wie ich meinen neuen Extruder(300 grad) richtig aufheizen kann. Da warte ich sehnsüchtig auf ein neues Update.

Wenn du magst kann ich dir eine Firmware compilen für 300°

**Comment by GS1305** [comment]
Das wäre super.
Werde mich in Zukunft ein wenig mehr mit der Programmierung auseinander setzen finde die Möglichkeiten die wir mit ne 3d Drucker haben echt super.  Was mir immer fehlt im Display ist die angaben zu den Einheiten. z.b ob mm, Stepps usw.
Gerade beim einstellen vom Druckbett arbeite ich mit Messschieber und ner Wasserwaage um das Bett besser auszurichten. Hab feststellen müssen das die Grundplatte nicht wirklich plan ist. Werde mir wahrscheinlich mal eine machen lassen die wirklich 100% eben ist. Ich bekomme es nie hin das alles grün ist. Die ecken Toleranz ca 0,2 zur Mitte +- 8. Habe in der Mitte mit Papier etwas aus geglichen danach -+ 3

**Comment by trulow** [comment]
@mriscoc Thanks, I just updated my S1 Pro with the latest version, sent the custom G-code you provided and everything looks good. I appreciate your help with all of this!

**Comment by neumo** [comment]
> > So neues update von mir nach langen hin und herhabe ich es geschaft mein neues board upzudaten. Zu meiner Schande muss ich gestehen das ich davon ausging ein 103 bekommen zu haben. So wie es aber jetzt aussieht habe ich ein F4 bekommen. Nach dem ich das Verzeichnis auf SD erstellt habe und die Datei dort hinein kopiert hatte ging das update ohne Probleme durch. Jetzt habe ich nur noch die Herausforderung wie ich meinen neuen Extruder(300 grad) richtig aufheizen kann. Da warte ich sehnsüchtig auf ein neues Update.
> 
> Wenn du magst kann ich dir eine Firmware compilen für 300°

Da hab ich auch Interesse. Ich bin leider zu blöd die neue Firmware für den EnderS1F4 zu finden :-(
Nachdem ich den S1 Pro habe, kannst Du da auch die Betttemperatur von bis zu 110 Grad zulassen?

**Comment by GS1305** [comment]
Jep das wäre auch ne gute Sache mit 110 Grad. Hätte da noch ne Kleinlichkeit. Wäre es möglich 2 oder 3 Profile zu lager um sie dann abzurufen. Denke gerade ans leveln und div unterschiedliche druck platten. Habe eine von Crality und eine von Cura. Bedie sind unterschiedlich dick. Wäre schön wenn man beim wechseln einfach das entsprechende Profil auf rufen kann und dann auto levelt.

**Comment by GS1305** [comment]
Hatt einer von euch die gleiche Erfahrung gemacht das die Grundplatte nicht wirklich gerade ist. Ich habe es nie das alles Grün wird in der Mitte habe ich immer ein unter schied von +- 0,4 bis 0,8

**Comment by neumo** [comment]
mmh  so uneben ist das bei Dir? 0.8 mm finde ich schon enorm viel!? Ich hab neulich die Glasplatte vom alten A6 auf den S1 geklemmt - a Traum! Aber selbst Die hat gewisse Unebenheiten, doch die sind im Bereich der 2. Nachkommastelle und eher klein. 

Gibt es eigentlich irgendwo eine Anleitung, wie man die Firmware selbst kompiliert? Hatte gesucht, aber nicht wirklich was dazu gefunden...

**Comment by GS1305** [comment]
Anzeige 0,6 oder -0,6. Leider habe ich keinen Bezug ob das nur die Differenz ist oder mm/ym sind. Was ich jetzt nur noch brauche ist das update auf 300 grad.

**Comment by GS1305** [comment]
Achtung!!! die Version Ender3S!-F4-20220527 hat einen Fehler. Der Flow wird bei mir nach dem ersten Layer unterbrochen und wird auch nicht fortgesetzt Habe die Version Ender3S1-STM32F4-20220515 wieder drauf gemacht und alles wieder ok. Also schön aufpassen

**Comment by neumo** [comment]
> Achtung!!! die Version Ender3S!-F4-20220527 hat einen Fehler. Der Flow wird bei mir nach dem ersten Layer unterbrochen und wird auch nicht fortgesetzt Habe die Version Ender3S1-STM32F4-20220515 wieder drauf gemacht und alles wieder ok. Also schön aufpassen

Danke für den Test, ich wollte das heute Abend auch probieren. Hast Du Screens gemacht? Wenn Du das Issue reportest könnte das der Chef beheben. Falls nicht, kann ich das noch nachholen...sag Bescheid.

**Comment by GS1305** [comment]
nein leider nicht aber hier das Resultat von einen Rechteck mit 0,4 mm 
![20220531_205740](https://user-images.githubusercontent.com/98468464/171264654-f27cd5f4-75e3-4ac8-97c5-5b9ee0af7573.jpg)
t

**Comment by GS1305** [comment]
und das selbe nach dem update zurück. Sorry hatte es schon in den Müll entsorgt das wegen die krummen wände. :)
![20220531_210308](https://user-images.githubusercontent.com/98468464/171265480-d475700d-75d8-4987-a6eb-1f65bcc70e33.jpg)

**Comment by neumo** [comment]
> Achtung!!! die Version Ender3S!-F4-20220527 hat einen Fehler. Der Flow wird bei mir nach dem ersten Layer unterbrochen und wird auch nicht fortgesetzt Habe die Version Ender3S1-STM32F4-20220515 wieder drauf gemacht und alles wieder ok. Also schön aufpassen

Habe eben auf die Version F4 20220527 upgedated, Restore settings gemacht, Grund Setup gemacht, aber ohne PID Tuning. !. Druck läuft, bis jetzt Layer 13 , 2.6mm, keine Probleme mit dem Flow. Ich hab einen S1 Pro....keine Ahnung, warum das bei Dir nicht tut.
Gefühlt nimmt er aber das Mesh nicht her. :-(

**Comment by GS1305** [comment]
Tja wenn ich das wüste warum? Warte jetzt auf die Version mit 300Grad und dann versuche ich es nochmal. Bin gerade dabei einen Flaschenadapter für Soda stream zu drucken damit kann ich auch die Glasflaschen füllen und die PETG entsorgen. Hie die Live Übertragung vom Druck. https://www.youtube.com/watch?v=0m2MRwd9tOU

**Comment by GS1305** [comment]
Noch 150min.

**Comment by GS1305** [comment]
Hei mriskoc wie lange brauchst bis ne Version für 300 Grad fertig ist. Wäre schön wenn ich meinen neuen Kopf mal testen könnte

**Comment by mriscoc** [comment]
> Hei mriskoc wie lange brauchst bis ne Version für 300 Grad fertig ist. Wäre schön wenn ich meinen neuen Kopf mal testen könnte

Download the sources and change in the configuration files the value for TEMP_SENSOR_0 and HEATER_0_MAXTEMP. You can use some sponsored compile from here: https://github.com/mriscoc/Special_Configurations/releases Creality don't give up to date an official answer about the correct thermistor configuration to the Sprite extruder Pro, but some users have had succesful using this configuration: https://github.com/mriscoc/Special_Configurations/releases/tag/AM3950T13 but Marlin doesn't have a calibration table for temperatures above 300°C then the maximum usable temperature is 300-15=285°C

**Comment by GS1305** [comment]
Hmmm??? leider habe ich bis jetzt nie einen code Manuel verändert. Hmmm Hab mir ArduinoUno zugelegt und das entsprechende Program. Bin leider aus Zeitmangel noch nicht dazu gekommen damit etwas zu machen. Bin leider 40 Jahre raus aus der programierei. Werde wohl oder übel darauf warten das einer das update fertigstellt.

**Comment by GS1305** [comment]
Hei Mriskoc, Habe wieder versucht die 527 Version zu nutzen. Nach leveln und einstellen mittels Test druck hatte ich wieder Probleme mit dem Ausdruck. Die wände waren nicht wirklich sauber. Auch führ der Kopf einmal Komplet zum ende der Y Achse und dann wieder zurück zum druck Objekt. Habe versuch es mit Einstellungen zu kompensieren ohne Erfolg. Habe dann wieder auf die 515 gewechselt. Ohne das ich etwas nachgestellt habe war der Ausdruck um längen besser. Als Slicer benutze ich Simplify 3D. Bin mir nicht sicher ob es vielleicht an dem Neuen Board (F4) liegen kann!? Mit dem Alten hatte ich nie Probleme.

**Comment by mriscoc** [comment]
I'm printing without problems with the latest version 20220527 in my V2, and don't see what changes with the previous version could negatively affect your printing quality.

**Comment by GS1305** [comment]
OK Tja ist schon komisch. Vielleicht ist das ein zusammen spiel vom neuen Board und dem neuen Druckkopf? Wer weiß das schon. Ist nicht so schlimm. Ich kann ja drucken und das zählt. Werde mich bald an die Sache mit den 300 Grad machen. Mal sehen ob ich es hinbekomme
