### ISSUE TITLE
Probe stowed during mesh levelling, Z-Axis still goes down

### ISSUE THREAD

**Issue by bengo06** [mriscoc/Ender3V2S1#1306]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

At random points during the mesh levelling procedure, my CR touch probe will stow, but the Z-axis still goes down, causing the nozzle to crash into the bed and a NaN point to appear in the mesh. Happens in both manual mesh levelling and AML process.

### Bug Timeline

At update to 20240125

### Expected behavior

I expected the probe not to stow and properly probe the bed.

### Actual behavior

The probe stowed at random time and the nozzle crashed into the bed.

### Steps to Reproduce

1. Start mesh level
2. Wait

### Version of Professional Firmware

20240125

### Printer model

Ender 3 v2 NEO

### Electronics

Board 4.2.2

### Other add-ons

CR Touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

**Comment by mriscoc** [comment]
Hi, this is not a general printer support forum. Many problems can be easily solved by reading the firmware [Wiki](https://github.com/mriscoc/Ender3V2S1/wiki#main-topics) please check the calibration guide.

This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:

Enhanced support in Patreon: https://www.patreon.com/mriscoc

Free community support:
- Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
- Facebook: https://www.facebook.com/groups/professionalfirmware
- Telegram: https://t.me/ender3v2s1firmware
- Reddit: https://www.reddit.com/r/Ender3v2Firmware
- Discord: https://discord.gg/3dprinters

**Comment by bengo06** [comment]
My apologies, I didn't read that far into the mesh levelling page. I appreciate the prompt response.
