### ISSUE TITLE
[BUG] Unsupported custom configuration: Ender3 Pro, E3 free-runs, CR10DSPLY and Ultipanel PROUI extension

### ISSUE THREAD

**Issue by entityThiex** [mriscoc/Ender3V2S1#1328]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.  <<--- There isn't any precompiled firmware for that configuration (Edit)

### Bug Description

I'm trying to compile a custom configuration and have run into a platformio issue, the file 'libproui_ubl_ultipanel.a' cannot be found. I've followed the directions step by step, so this should not happen, right? The file is also not there, I've manually looked it up to make sure it is not a too long path or similiar.

### Expected behavior

Compile without error

### Actual behavior

failed with FileNotFoundError: [Errno 2]

### Steps to Reproduce

follow the steps of your configurator tool, then try to compile it.

### Version of Professional Firmware

Marlin 2.1.1.0

### Printer model

Ender 3 Pro  <<-- That printer can't be found in the Configurator (Edit)

### Electronics

E3 free-runs TMC2209

### LCD/Controller

12864

### Other add-ons

cr-touch, creality spider hotend

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

**Comment by mriscoc** [comment]
The libraries are here: https://github.com/mriscoc/Ender3V2S1/tree/Ender3V2S1-Released/Marlin/lib/proui/ but only for supported configurations, be sure that you are using the Configurator and the files in the main repository you should not need to search for the library files manually.

**Comment by entityThiex** [comment]
Thanks, I'll use these

**Comment by entityThiex** [comment]
Just a short question, isn't there a difference between the two board types, can I just copy the files from the other one?

**Comment by mriscoc** [comment]
The support for that board is preliminary: https://github.com/MarlinFirmware/Marlin/pull/26562

**Comment by entityThiex** [comment]
But wasn't that branch deleted? shouldn't these changes be in the main branch? If so, are they simply not usable in the configurator or unavailable at the moment?

**Comment by mriscoc** [comment]
I just check and currently there is no support for the combination: E3 free-runs + Ultipanel. I will try to update the support soon. If you are in Patreon, you will have access to a pre-release library or to an official compiled firmware.

**Comment by entityThiex** [comment]
Is there a need to use the ultipanel? I'm using a CR10DSPLY display, is that the problem or am I doing something wrong?

**Comment by mriscoc** [comment]
Ultipanel is a generic Marlin name for many displays including the CR10DSPLY.

**Comment by entityThiex** [comment]
Can you give me some approximate time this will take? You probably have a lot on your plate, so I don't think that it will be fast. Just would be nice to know a roundabout time.

**Comment by mriscoc** [comment]
Usually, a previously unsupported combination is compiled when someone requests it on the Patreon site and then the library is made available, also when there are many requests for that specific combination.

**Comment by entityThiex** [comment]
What display would I need to have a supported version?

**Comment by mriscoc** [comment]
A color display such as DWIN/DACAI/TJC: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display
With those displays you will have additional benefits such as being able to see the leveling grid, a graph of the temperatures, etc.
