### ISSUE TITLE
After octoprint connection, the printer displays the message "Media init fail "

### ISSUE THREAD

**Issue by fabiomaticus** [mriscoc/Ender3V2S1#133]
After octoprint connection, the printer displays the message: "Media init fail"
No sd is connected.
In octoprint in the gcode section I inserted these lines:
After connection to printer is estabilished: M117 Octoprint is connected

**Comment by mriscoc** [comment]
Your Octoprint is configured for list the contents of the SD card and requesting the printer to read it, but there isn't a memory card, then shows a Media Init Fail message.

**Comment by fabiomaticus** [comment]
Ok. I changed the configuration to octoprint.
Thanks
