### ISSUE TITLE
[BUG?] Rotating control became rather unpredictable in latest versions

### ISSUE THREAD

**Issue by acritum** [mriscoc/Ender3V2S1#1338]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I feel that the rotating control (jog dial) became very unpredictable in the latest versions (it wasn't so unpredictable before). When I rotate it really slow, the values are added or decreased as I expect it, but when I rotate it slightly faster,  the values change drastically fast, i.e. fast rotation to 90-180 degrees may increase temperature from 0 to 260 at once. As I understand this is not a bug but a feature to change the values faster than usual, but it really changes values at unreasonably high steps and this becomes unpredictable. This is not a big problem when just setting hotend temperature, because in case of error we can always reset the temperature at once - the hotend won't heat that fast anyway. But this becomes a REAL PROBLEM when settings nozzle movement values. Just a slightly awkward rotation of the control may send the head to some far position we don't intend it to go to. When I configured Z-position offset of the nozzle and just rotated the control a bit, and the nozzle position decreased drastically at once to the level below the physical bed level, the head went down at once and pinned into the bed deep. I couldn't stop it and turned the power off in emergency to prevent the head from going down even more. Luckily, the bed was on the springs and went down under the nozzle pressure and this didn't make any noticeable damage to the machine, but I think it shouldn't be like this. Rotating control should change the values VERY SLOWLY AND PREDICTABLY, especially in cases when the movement of the head happens in real time and quickly increased/decreased values can make some damage to hardware.

My suggested solutions: make it possible to disable this behavior in the settings or make a setting item that allows to set a custom acceleration value, i.e. how fast you should rotate the control to start the fast increment/decrement of values or how fast the values are incremented/decremented when the control is rotated faster than usual.

### Version of Professional Firmware

New Year 2024 (20240122)

### Printer model

Creality Ender 3V2

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by acritum** [comment]
I see "Encoder improvements (#26501)" in the New Year 2024 (20240122) what's new, maybe this behavior has to deal with these improvements? https://github.com/mriscoc/Ender3V2S1/releases

**Comment by mriscoc** [comment]
Duplicated of: https://github.com/mriscoc/Ender3V2S1/issues/1126 and https://github.com/mriscoc/Ender3V2S1/issues/977

**Comment by acritum** [comment]
> Duplicated of: #1126 and #977

So, if many people have this issue with the encoder, is it possible to add a menu item SMOOTH_ENCODER_MENUITEMS in the settings menu? It will be rather boring to recompile a custom version with the fix every time a new version of the firmware releases.

**Comment by acritum** [comment]
The issue is still actual, we need a way to workaround it through settings menus without recompiling the whole software after every release with SMOOTH_ENCODER_MENUITEMS.

**Comment by mriscoc** [comment]
Not a firmware issue
