### ISSUE TITLE
Cura 5.8.0 doesn't have Display Filename and Progress on LCD plugins as indicated in the calibration guides

### ISSUE THREAD

**Issue by smeyernyc** [mriscoc/Ender3V2S1#1344]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Cure depreciated several scripts from: https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides#post-processing-scripts
Should we care?
![Screenshot 2024-08-26 162759](https://github.com/user-attachments/assets/0a1107b4-b298-479d-95b3-9960def731ba)

### Bug Timeline

New

### Expected behavior

Shouldn't give error

### Actual behavior

Gives errors

### Steps to Reproduce

Just open Cura, or remove and add back scripts (and AML)

### Version of Professional Firmware

Ender3V2-422-BLTUBL-MPC-20240122.bin

### Printer model

Ender 3v2

### Electronics

4.2.2

### LCD/Controller

I will check later

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
The latest versions of Cura have integrated two plugins in one, so it is now necessary to configure the new plugin: "Display Info on LCD"
![image](https://github.com/user-attachments/assets/3839fff8-0ffd-48de-9063-cfac33570fcb)
