### ISSUE TITLE
creality cloud plugin  for octoprint

### ISSUE THREAD

**Issue by mikweb2017** [mriscoc/Ender3V2S1#135]
Ender 3 s1
last release
Ender3S1-20220419.bin20220419.bin
after install your firmware  dont work anymore creality cloud plugin  for octoprint

https://github.com/crealitycloud/OctoPrint-CrealityCloud.

can you fix this?

**Comment by mriscoc** [comment]
Set Baud to 115K in Advanced menu

**Comment by mikweb2017** [comment]
don't work  i see printer but dont send any commands.

**Comment by mriscoc** [comment]
Octoprint is working with this firmware https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint
So, it could be an incompatibility between that plugin and the firmware.
