### ISSUE TITLE
DWIN Set Not Reachable (Security Warning)

### ISSUE THREAD

**Issue by Bigguy511** [mriscoc/Ender3V2S1#1354]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Went do download display set, and got a security alert>:(

### Bug Timeline

Started Today

### Expected behavior

I wanted to download it

### Actual behavior

it wouldn't let me download it:(

### Steps to Reproduce

1. Go to DOWNLOAD DWIN_SET HERE 2. Click on it 3. Get security alert

### Version of Professional Firmware

422

### Printer model

Ender3v2

### Electronics

4.2.2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Other (explain below)

### Host Software

None

**Comment by mriscoc** [comment]
Some browsers flag the [DownGit](https://minhaskamal.github.io/DownGit) page like a malware distribution page.
