### ISSUE TITLE
Support for Ender 3 S1 ProX

### ISSUE THREAD

**Issue by Waldehyd** [mriscoc/Ender3V2S1#1366]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

On Amazon is a new 2024 Version of the Ender 3 S1 Pro called ProX. It supposedly prints faster, but only due to Firmware changes. Is there any information on whether it's a good idea to flash it with new Firmware?

### Version of Professional Firmware

-

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
