### ISSUE TITLE
Move or Copy Leveling Mesh size command

### ISSUE THREAD

**Issue by lrahnz** [mriscoc/Ender3V2S1#137]
I have a BLTouch.  I do my initial bed leveling using 2x2 mesh points to get the corners adjusted.  Then I do 9x9 mesh points for production use.  It would be easier if I could set the mesh points in the Prepare group of commands instead of going back and forth between the Prepare and Advanced menus

**Comment by mriscoc** [comment]
In the latest versions there is not a 2x2 mesh any more. In the "Prepare" menu there is a bed tramming that takes measurements of the level of the corners to take average and suggest an adjustment of the leveling knobs.

**Comment by lrahnz** [comment]
I loaded your latest firmware and the Bed Tramming wizard automates exactly what I was doing.  Very nice!  
 
I also like the configurable Toolbar.  This will be very helpful with day to day use.  Right now I have a “Menu Card” that I use to find my most frequently used commands.  Now I can put them on the toolbar and have them on screen.
 
Anyway, consider my issue closed.
 
Regards
Logan
