### ISSUE TITLE
[BUG] Nozzle & bed heats up one after the other instead of heating up at the same time.

### ISSUE THREAD

**Issue by yussufbiyik** [mriscoc/Ender3V2S1#1378]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

While the printer heats up simultaneously when using preheat options, it does not heat up at the same time when printing. Is this a bug or is it just how this is?

### Bug Timeline

have been happening for years

### Expected behavior

Printer should heat up all components at the same time to save time 

### Actual behavior

Printer heats the bed first and then heats the nozzle

### Steps to Reproduce

1. Start a print
2. Observe

### Version of Professional Firmware

20240125

### Printer model

Ender 3 V2

### Electronics

4.2.2

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
Sorry, that is not a firmware issue, check your start G-code script
This is not a general printer support forum. Many problems can be easily solved by reading the firmware [Wiki](https://github.com/mriscoc/Ender3V2S1/wiki#main-topics) please check the calibration guide.

This Issue Queue is for firmware bug reports and development-related issues, and we prefer not to handle user-support questions here. For best results getting help with configuration and troubleshooting, please use the following resources:

Enhanced support in Patreon: https://www.patreon.com/mriscoc

Free community support:
- Github discussions: https://github.com/mriscoc/Ender3V2S1/discussions
- Facebook: https://www.facebook.com/groups/professionalfirmware
- Telegram: https://t.me/ender3v2s1firmware
- Reddit: https://www.reddit.com/r/Ender3v2Firmware
- Discord: https://discord.gg/3dprinters

**Comment by yussufbiyik** [comment]
Thank you so much, then i think we can close this issue then
