### ISSUE TITLE
After Reboot Mesh Leveling->Activate Leveling is not ticked

### ISSUE THREAD

**Issue by zhoupengyu823** [mriscoc/Ender3V2S1#142]
In "Ender3V2-422MM-20220419"
After restarting after manual leveling, the switch of Advanced Settings ->Mesh Leveling->Activate Leveling is not ticked

**Comment by mriscoc** [comment]
The mesh is deactivated by any home axis and the default status after power on or reboot is disabled.

**Comment by mriscoc** [comment]
Normal behavior.
