### ISSUE TITLE
Wish the manual leveling edit function would move in real time based on the adjustment

### ISSUE THREAD

**Issue by zhoupengyu823** [mriscoc/Ender3V2S1#143]
In the Mesh Leveling->Edit Mesh function in the advanced settings, when X/Y is selected, it is hoped that the nozzle can be moved to the specified X/Y coordinates, and can be moved in real time according to the change of Z Value, because the manual leveling point After more than 9, the errors of manual leveling will increase, and one will take a long time.

**Comment by mriscoc** [comment]
noted for a future release, but if the Z value is incorrect, the bed/nozzle could be damaged

**Comment by mriscoc** [comment]
That feature has been implemented in the latest releases.
