### ISSUE TITLE
Preheat Constants Limited to 3... with even further limitations? CONFIGURATION_H_VERSION 02010000

### ISSUE THREAD

**Issue by Chris-Jayden** [mriscoc/Ender3V2S1#145]
**For CONFIGURATION_H_VERSION 02010000**

> //
> // Preheat Constants - Up to 5 are supported without changes
> //
> #define PREHEAT_1_LABEL       "PLA & TPU"
> #define PREHEAT_1_TEMP_HOTEND 228
> #define PREHEAT_1_TEMP_BED     55
> #define PREHEAT_1_FAN_SPEED     0 // Value from 0 to 255
> 
> #define PREHEAT_2_LABEL       "ABS & PETG"
> #define PREHEAT_2_TEMP_HOTEND 262
> #define PREHEAT_2_TEMP_BED     65
> #define PREHEAT_2_FAN_SPEED     0 // Value from 0 to 255
> 
> #define PREHEAT_3_LABEL       "Hot-End Management"
> #define PREHEAT_3_TEMP_HOTEND 212
> #define PREHEAT_3_TEMP_BED      0
> #define PREHEAT_3_FAN_SPEED     0 // Value from 0 to 255

=======================

I have successfully compiled and installed a 4.2.2 TMC2208 Firmware for my Ender 3 v2, but, for some reason, the machine doesn't display more than 3 Preheat Constants. Anything in excess of 3 is simply not shown. Is this a known bug? Personally, on Jyer's 2.0.9.2 or 2.0.9.3 I was fine with even 6:

========================

> #define PREHEAT_1_LABEL       "Hot-End Management"
> #define PREHEAT_1_TEMP_HOTEND 212
> #define PREHEAT_1_TEMP_BED      0
> #define PREHEAT_1_FAN_SPEED     0 // Value from 0 to 255
> 
> #define PREHEAT_2_LABEL       "PLA"
> #define PREHEAT_2_TEMP_HOTEND 222
> #define PREHEAT_2_TEMP_BED     55
> #define PREHEAT_2_FAN_SPEED     0 // Value from 0 to 255
> 
> #define PREHEAT_3_LABEL       "ABS"
> #define PREHEAT_3_TEMP_HOTEND 262
> #define PREHEAT_3_TEMP_BED    65
> #define PREHEAT_3_FAN_SPEED     0 // Value from 0 to 255
> 
> #define PREHEAT_4_LABEL       "PETG"
> #define PREHEAT_4_TEMP_HOTEND 262
> #define PREHEAT_4_TEMP_BED     65
> #define PREHEAT_4_FAN_SPEED     0 // Value from 0 to 255
> 
> #define PREHEAT_5_LABEL       "TPU"
> #define PREHEAT_5_TEMP_HOTEND 242
> #define PREHEAT_5_TEMP_BED     55
> #define PREHEAT_5_FAN_SPEED     0 // Value from 0 to 255
> 
> #define PREHEAT_6_LABEL       "Cold-Pull"
> #define PREHEAT_6_TEMP_HOTEND  92
> #define PREHEAT_6_TEMP_BED      0
> #define PREHEAT_6_FAN_SPEED     0 // Value from 0 to 255

=========================

Furthermore, another limitation seems to be that the number 3 Preheat Constant is forcibly named "Custom" instead of what I've actually named it within the compiled firmware.

Here is my Configuration.h (it's zipped because github doesn't support .h files)
[Configuration.zip](https://github.com/mriscoc/Ender3V2S1/files/8644497/Configuration.zip)

**Comment by mriscoc** [comment]
The current implementation only supports three preheat menus. Because of the lack of flash space in RCT devices we consider that having the two normal menus (PLA, ABS) and a CUSTOM menu is enough, but you can change the dwin.cpp file to enable more preheat menus.
