### ISSUE TITLE
Octoprint support

### ISSUE THREAD

**Issue by toferzim** [mriscoc/Ender3V2S1#147]
**Is your feature request related to a problem? Please describe.**
When I do a printing job from OctoPrint the printer monitor doesn't show the job status same way as if it is shown, when I start printing from the printer.

**Describe the solution you'd like**
I want to see a printing status on the printer monitor when I send a model to print from octoprint.

**Comment by daniel-volz** [comment]
That´s not a firmware problem, use this OctoPrint Plugin to get the status bar working:
https://plugins.octoprint.org/plugins/m73progress/

Have a look in the Wiki:
https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint
