### ISSUE TITLE
Auto/Mesh Bed Leveling: Auto-save, Save, and Continue? CONFIGURATION_H_VERSION 02010000

### ISSUE THREAD

**Issue by Chris-Jayden** [mriscoc/Ender3V2S1#148]
Hi Guys,

I've noticed a few things about ABL, at least from the firmware I've compiled. 
[Configuration.zip](https://github.com/mriscoc/Ender3V2S1/files/8645641/Configuration.zip)

For one, it doesn't automatically save if initiated as a G29 Start G-Code. Yes, the ABL sequence initiates, but it expects me to press Save or Continue -> this is annoying if I were to walk away after starting a print. 

Secondly, it's a bit jarring to me that the default highlighted button (after the ABL sequence is complete) is "Continue". I keep accidentally hitting "Continue" instead of hitting "Save", and this leads to no mesh information being stored to the machine.
Wouldn't it be better to either **not have a "Continue" option** or, instead, **have "Save" as the default highlighted option**?

Please let me know if there's any lines in VSCode/platform.io that I can actually add/modify to change this behaviour, or whether or not I can change this behaviour while operating the machine itself.
Otherwise, I can only hope that these changes will arrive in the future to come.

**Comment by mriscoc** [comment]
C108
M500
