### ISSUE TITLE
Marlin reports error when a G2 without parameters is sent

### ISSUE THREAD

**Issue by psu1989** [mriscoc/Ender3V2S1#149]
**Describe the bug**
Error when issuing G2 commands on Ender 3 S1

**To Reproduce**
1. Install: Ender3S1-UBL-20220419.bin
2. In Octoprint, issue M115 and see: Recv: Cap:ARCS:1
3. In OctoPrint issue G2 and see: Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: G2/G3 bad parameters.  Printer display: Printer Killed M112 Shutdown

**Expected behavior**
Expect Firmware to recognize G2 and G3 commands

**Screenshots**
![2022-05-08 14_04_09-Window](https://user-images.githubusercontent.com/24849943/167309352-51bd3eab-ad16-4aeb-b3ce-d71a9772eaa9.jpg)

**Version (please complete the following information):**
Ender3S1-UBL-20220419.bin

**Additional context**

**Comment by mriscoc** [comment]
https://marlinfw.org/docs/gcode/G002-G003.html
