### ISSUE TITLE
Bed Tramming issue

### ISSUE THREAD

**Issue by PapsDizzy** [mriscoc/Ender3V2S1#15]
in your new blt bin for ender 3 v2 is an issue in the bed tramming menü. front right and back right are not funcniable. i mean nothing happens when you chose it.

**Comment by mriscoc** [comment]
Please increase the Probe Margin in advanced/probe settings.

**Comment by PapsDizzy** [comment]
when i use the checkbox manual trammning the rigth points are usable. without manual tramming the right points have no funktion
ok i incrase the probe margin from 25 to 50 and nox it works
