### ISSUE TITLE
Bed tramming wizard does not work anymore

### ISSUE THREAD

**Issue by RoP09** [mriscoc/Ender3V2S1#151]
**Describe the bug**
Bed tramming wizard does not work anymore. Worked fine with previous fw version.

**To Reproduce**
1. Go to 'Bed tramming'
2. Click on 'Tramming wizard'

**Expected behavior**
Bed tramming wizard moves to all 4 corners and measures distance with CR/BL Touch

**Actual behavior**
Bed tramming wizard only moves to 1st front left corner and stops after measuring 3 times. 
Gives a positive result (after shorting calculation screen)  showing all 4 edges level even if only 1 was measured.
(all edges showing 0.0 values)

If edges are selected manually only front left and center can be selected. Otherwise it says "**outside of probing area**" if any of the other edges are selected.

**Version:**
**Ender3V2-422BLT-20220419.bin**

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides

![image](https://user-images.githubusercontent.com/2745567/167703348-bf40d97d-a342-4115-96ed-a591a601451e.png)

**Comment by RoP09** [comment]
did not help, all physical settings are configured as before still, tried reentering / saving the changes but still the same behaviour:

x bed size: 230
y bed size: 230
x min pos: 0
y min pos: 0
x max pos: 246
y max pos: 231
z max pos: 250

**Comment by badlyshot75** [comment]
Try reseting your Probe X Offset back to -41.5 and Y Offset back to -7.0

**Comment by RoP09** [comment]
If I do that it can go to Center / Front left / Rear left, but for Front right and rear right still the same error message appears and it won't go there (still says successful tramming after reaching rear left position and probing).

(My probe offset is originally -50.5 / -31.5, same values as being used with the previous version of this firmware where it worked flawlessly)

**Comment by badlyshot75** [comment]
Probe Margins can be set up to 60 (20 is default), but I see no control item on the menu to change it.

**Comment by mriscoc** [comment]
Mesh inset https://github.com/mriscoc/Ender3V2S1/issues/151#issuecomment-1122011429

**Comment by badlyshot75** [comment]
OK Thanks. It just was not intuitive for us slow folk.

**Comment by mriscoc** [comment]
> OK Thanks. It just was not intuitive for us slow folk.

Yes, something to correct.

**Comment by eblieb** [comment]
Delete - Never mind I missed the part about hitting maximize and then center. Now it is working.
