### ISSUE TITLE
M300 Support?

### ISSUE THREAD

**Issue by andycarver101** [mriscoc/Ender3V2S1#153]
Ive seen mixed stories that M300 GCode can run on the E3V2 Buzzer. Do you know if it can and if so do you have plans to implement this?

P.S Just updated from Jyers. Looks Great, love the features. Will try it out on the weekend.

**Comment by davbrat** [comment]
I would love support for this also, as I would like to be able to fire off a few M300 commands at the end of a print job... a "I'm done" alarm.   Only have had my E3V2 for about 2 weeks and just updated the firmware. Great Job!!!!

**Comment by mriscoc** [comment]
The Ender3 series only has a simple buzzer connected in the screen unit, we can only control the duration of the beeps. There are some PWM techniques that can allow you to use a digital pin to command a simple speaker, similar to old PCs.
