### ISSUE TITLE
Filament RunOut - Ender 3 S1 

### ISSUE THREAD

**Issue by pacocatech** [mriscoc/Ender3V2S1#156]
Hello, I'm using the latest firmware version you released for Ender3 S1 Ender3S1-20220419.bin, first I would like to thank you for sharing this version, it is much superior to the original FW.
I work with my machine connected to Octoprint, when the filament ends it is not doing the exchange flow, do I need to enable something on my side or is this part not yet foreseen in the FW that connects to Octoprint?

Thanks.

**Comment by mriscoc** [comment]
This firmware implements `Host Action Commands`. When the printer detects a filament run out, first wait to complete the `Runout Distance` for use the filament between the sensor and the extruder, then informs Octoprint to start a pause, the printers enter in the `Advanced Pause` routine allowing you to change the filament.
Verify that you set your Octoprint according to this guide: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint also check your runout sensor connections, you can debug the runout sensor using the `End-stop Diagnostic` tool in `Advanced` menu.

https://github.com/mriscoc/Ender3V2S1/wiki/Filament-Settings-Menu

**Comment by pacocatech** [comment]
the point is that the filament ended and did not make the filament change call. I let the material reach almost the edge of the extruder.

**Comment by pacocatech** [comment]
My octoprint settings are OK see:

![image](https://user-images.githubusercontent.com/70729684/168658775-fc4a51e4-9eda-424d-999b-1dc5a8b07aec.png)


![image](https://user-images.githubusercontent.com/70729684/168658806-12f5a2ff-3e1d-4897-9e91-0bac745615c7.png)

I have a print running now through Octoprint, see the status in it:

![image](https://user-images.githubusercontent.com/70729684/168659021-b3d3de96-4baf-4eec-a671-853d5676266b.png)

and now on the printer:

![image](https://user-images.githubusercontent.com/70729684/168658938-62bc5c72-de71-4da0-b693-2b38a9e8be7f.png)


It seems that it is not recognizing the commands sent by Octoprint.
I prepare the pieces with PrusaSlicer.



I'm waiting for this print to finish to validate the filament sensor settings.

**Comment by pacocatech** [comment]
This my filament sensor config in printer:

![image](https://user-images.githubusercontent.com/70729684/168675073-5bf2f3a0-5c43-4dd2-8b6c-50250f81bd84.png)

![image](https://user-images.githubusercontent.com/70729684/168675114-a270831b-5101-4e30-a7d8-38b08f433b97.png)

**Comment by mriscoc** [comment]
If you remove the filament from the sensor, the End-stop diagnostic will show open and not TRIGGERED.

**Comment by pacocatech** [comment]
Yes, saw:

![image](https://user-images.githubusercontent.com/70729684/168925730-ca22bccb-3367-4c8d-947c-6f556ddf905e.png)

**Comment by pacocatech** [comment]
Hello my friend,
I took a new test today and I don't know if it was because I reset my octoprint, but this time the sensor fired the event correctly.
I managed to make the switch even using octoprint.
Thanks for the firmware created, it is a thousand times better than the original version, I tried to create a custom one but I didn't have time for the details and you nailed it.

I create content about 3D printing in Brazil and I have a channel where I explain about Firmware and if you need help with firmware, you can count on my help.


If you want to follow us on social media:

Youtube: https://www.youtube.com/Pa%C3%A7ocaTech
Instagram: https://www.instagram.com/pacacatech/

**Comment by mriscoc** [comment]
It could be very helpful if you take advantage of your learn curve with this firmware and do some videos about calibrations and fine tuning of your printer with this firmware. There are many beginner that need video help and can't follow the written guide lines of the wiki: https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
