### ISSUE TITLE
Mesh data is flipped

### ISSUE THREAD

**Issue by seth199** [mriscoc/Ender3V2S1#158]
**Describe the bug**
"View mesh" does not match mesh shown when M420 V1 command is issued. The result is flipped about the horizontal axis. I do not know if this flips the mesh when printing though it seems it does.

**To Reproduce**
1. create a mesh and save
2. Advanced > Mesh Leveling > View Mesh
3. Using Pronterface issue M420 V1 command

**Expected behavior**
Ignoring the rounding of numbers the mesh data should be identical between the LCD display and the Pronterface console.

**Screenshots**
![image_67166209](https://user-images.githubusercontent.com/67761230/168725569-654da5db-966b-4965-a18c-1df0582dea68.JPG)

![2022-05-16_22-37](https://user-images.githubusercontent.com/67761230/168725628-a76402b9-7b16-4429-9bc7-616498bf0af2.png)

**Version (please complete the following information):**
2.1.0.1 MRiscoC (non UBL)
Apr 20 2022 00:01:07

**Additional context**

**Comment by mriscoc** [comment]
It is not flipped; the text table shows the 0,0 in the upper left corner, but physically the 0,0 is in the front left corner. The mesh viewer shows the values as if the observer were over the bed.

**Comment by seth199** [comment]
Thanks for the quick reply. Sorry for the dumb question.
