### ISSUE TITLE
Preview on cura 5.0

### ISSUE THREAD

**Issue by jakub118** [mriscoc/Ender3V2S1#159]
Just upgraded to the new cura 5.0 and it seems like the script for the preview does not work

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/issues/136

**Comment by mriscoc** [comment]
> > #136
> 
> Cura 5.0.0 is a full release now; it's no longer in Beta

https://github.com/mriscoc/Ender3V2S1/discussions/139#discussioncomment-2670926
