### ISSUE TITLE
Confusion about FAN1_PIN in official Creality and Professional Firmware

### ISSUE THREAD

**Issue by Avedena** [mriscoc/Ender3V2S1#167]
I'am confused about the difference of the FAN1_PIN in the Official Creality Firmware for the Ender-3 S1 and your Professional Firmware. You select Pin PC0 for the Extruder Fan but Creality use PA0

https://github.com/mriscoc/Ender3V2S1/blob/fd215454c21c3b3afecca522e6141f52576aa4c7/Marlin/src/pins/stm32f1/pins_CREALITY_V24S1_301.h#L73

https://github.com/CrealityOfficial/Ender-3S1/blob/74c1485572219007e435155eed23a616ecb1cdda/Marlin/src/pins/stm32f1/pins_CREALITY_S1.h#L151

I get some conflicts with the SanityCheck for the Laser support, because the PMW Pin is also PC0:

https://github.com/CrealityOfficial/Ender-3S1/blob/74c1485572219007e435155eed23a616ecb1cdda/Marlin/src/pins/stm32f1/pins_CREALITY_S1.h#L235

Can you confirm Pin PC0 is right? On my S1 the Fan is Spinning normal with the Professional firmware.

Thanks.

**Comment by mriscoc** [comment]
https://github.com/CrealityOfficial/Ender-3S1/blob/74c1485572219007e435155eed23a616ecb1cdda/Marlin/Configuration_adv.h#L545
