### ISSUE TITLE
Tune menu when printing from Octoprint

### ISSUE THREAD

**Issue by vaskito85** [mriscoc/Ender3V2S1#168]
**Describe the bug**
When I print from Octoprint I can´t have the tune options, pause or cancel button as when i print from the SD card. This is normal or im doing something wrong?

**Screenshots**

![20220522_123622](https://user-images.githubusercontent.com/105981708/169703793-b1ebc91b-5293-4a08-a5b2-36d57c58ef4c.jpg)
Printing From the SD card

![20220522_120431](https://user-images.githubusercontent.com/105981708/169703811-95d00870-a4f0-4845-854c-7a1fe0fb5beb.jpg)
Printing from octoprint

**Version (please complete the following information):**
Latest version April 20 for Ender 3V2 4.2.2 board

**Comment by mriscoc** [comment]
Please read de Wiki https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint

**Comment by vaskito85** [comment]
Miguel, Acabo de darme cuenta de que los dos somos compatriotas latinoamericanos. 
Habia hecho todos los pasos de la wiki y seguia sin aparecer. 

Re-instale el firmware y re-instale el octoprint y ahora si funciona. Perdon por generar el "Issue".

Abrazo desde Argentina!
