### ISSUE TITLE
Build error when building for STM32F4

### ISSUE THREAD

**Issue by theSt33v** [mriscoc/Ender3V2S1#170]
**Describe the bug**
Marlin build error when building for STM32F401.

**To Reproduce**
1. Attempt to build firmware using current source and current config for STM32F401 from Special_Configurations
2. Build fails with the following error:
`Marlin\src\gcode\calibrate\G28.cpp: In function 'void home_z_safely()':
Marlin\src\gcode\calibrate\G28.cpp:130:45: error: the value of 'safe_homing_xy' is not usable in a constant expression
  130 |       constexpr xy_float_t okay_homing_xy = safe_homing_xy;
      |                                             ^~~~~~~~~~~~~~
Marlin\src\gcode\calibrate\G28.cpp:125:43: note: 'safe_homing_xy' was not declared 'constexpr'
  125 |     TERN(ProUIex, , constexpr) xy_float_t safe_homing_xy = { Z_SAFE_HOMING_X_POINT, Z_SAFE_HOMING_Y_POINT };
      |                                           ^~~~~~~~~~~~~~`

**Expected behavior**
Successful build.

**Screenshots**
![Screenshot 2022-05-25 153411](https://user-images.githubusercontent.com/21251502/170353567-f38f9430-7896-4d47-bca0-9d8e82536ef6.png)

**Version (please complete the following information):**
Current source as of 25May2022

**Additional context**
N/A

**Comment by matthiasp101** [comment]
Same here.

**Comment by Nbrooks639** [comment]
same here

**Comment by mriscoc** [comment]
The current source is for a previous PlatformIO version and also doesn't have the fixes for the F4. The updated source will be available along with the release of the latest firmware version maybe this weekend.

**Comment by theSt33v** [comment]
Downgrading platformio does not fix the issue, so I don't think that's related. I'll wait for the new release though.

**Comment by mriscoc** [comment]
The latest sources are available now for compilation with the new Platform IO version.
