### ISSUE TITLE
Enabling fan_kickstart_time

### ISSUE THREAD

**Issue by dylanparry** [mriscoc/Ender3V2S1#173]
**Is your feature request related to a problem? Please describe.**

My part cooling fan won't start running when set to a low speed. I can manually give it a poke when it looks like it's trying to start, so I know it can actually turn at such low speeds.

Once it's started to turn, changing the speed works fine.

**Describe the solution you'd like**
I'd like to enable `fan_kickstart_time` to set the fan speed to 100% for a brief period when first starting it up. I see that it's commented out in the config files, but would love to be able to use this feature.

I don't know enough about this software to know if that's something I can change myself or not.

**Comment by mriscoc** [comment]
Because that is a very special case, I recommend you to compile a version with that feature enabled, it is easy to do.
Maybe someone can sponsor that particular configuration in the special configuration repository: https://github.com/mriscoc/Special_Configurations
