### ISSUE TITLE
Add support for Prusa Slicer 2.4.2 to the thumbnail generator script

### ISSUE THREAD

**Issue by LiFulian** [mriscoc/Ender3V2S1#174]
when i use 'How to generate a gcode preview' and export the gcode
![屏幕截图 2022-05-29 175144](https://user-images.githubusercontent.com/45170678/170862183-ebff5a86-adbe-42bf-94ea-776748db8049.jpg)

【PrusaSlicer encountered an error】
Post-processing script "C:\Python310\python.exe" "C:\Users\lifulian\AppData\Roaming\PrusaSlicer\scripts\CreateHeaderAndThumbnail.py" on file C:\Users\lifulian\AppData\Local\Temp\.17656.gcode.pp failed.
Error code: 1

**Comment by CaVO32** [comment]
i also have the same identical problem
using prusa slicer 2.4.2

**Comment by mriscoc** [comment]
Current python script has support up to Prusaslicer 2.4.0, the script will be updated soon.

**Comment by mriscoc** [comment]
Updated super/Prusa Slicer thumbnail post processing script, please re-download it.
