### ISSUE TITLE
mesh leveling doesn't work well

### ISSUE THREAD

**Issue by Marvindaut** [mriscoc/Ender3V2S1#176]
The mesh leveling curiously don’t work for me.
I got 4 models of the Ender 3 S1, two with the F103 and two with the F401 board. On every single printer the same problem:
It seems like it’s working (z-axis moves), but not the shape of the bed.
When I turn the ABL off, manually perfect levelt, it works way better.
On the following Picture you can see the results in comparison, the lower sheet is with ABL turned on.
Hopefully someone can help me.
BTW I also got the problem on stock firmware.

**Comment by Marvindaut** [comment]
![IMG_6087](https://user-images.githubusercontent.com/106264547/170870914-cea4a5ef-d6be-48ad-bcc1-928816ff3b2c.JPG)

**Comment by DevlshOne** [comment]
That sounds like a bad sensor to me.  Turn it off and everything works better?

**Comment by Marvindaut** [comment]
> That sounds like a bad sensor to me. Turn it off and everything works better?

Can't believe it's the sensor, it would be veeery unlucky if I got four bad sensors:D
Yes the samples on the picture printed with same settings, except the upper sample was printed without using the mesh.
Deviation is about ~0.003.

**Comment by carnaue** [comment]
I had same but fixed it with the UBL capabilities in the firmware. 

Instructions here: 

https://www.printables.com/model/213992-perfect-1st-layers-ender-3-v2-ender-3s1-ender-3s1-/files

**Comment by RoP09** [comment]
Same here (latest firmware from here, CR Touch w highspeed turned off), getting a weird stripe in my mesh which is also occuring in the prints if mesh is turned on:
![PXL_20220601_153013308](https://user-images.githubusercontent.com/82153569/171442815-046c7eed-fa43-42b4-af36-51b6f8d28bd4.jpg)

Results are actually better if I disable the M420 S1 in my GCODE startup code completely (if the bed would be perfectly leveled that is) - first one is with Mesh leveling, second without (right side is bad on both, but the one with mesh additionally has that gap on the left starting where also the stripe is detected above in the auto mesh setup):
<img width="950" alt="Screenshot 2022-06-01 173423" src="https://user-images.githubusercontent.com/82153569/171443231-7872b695-b9f3-4e4c-937f-70ab958d1c30.png">

**Comment by mriscoc** [comment]
> Same here (latest firmware from here, CR Touch w highspeed turned off), getting a weird stripe in my mesh which is also occuring in the prints if mesh is turned on

Check the eccentric wheels of your X axis.

**Comment by RoP09** [comment]
> > Same here (latest firmware from here, CR Touch w highspeed turned off), getting a weird stripe in my mesh which is also occuring in the prints if mesh is turned on
> 
> Check the eccentric wheels of your X axis.

Indeed I increased the tension of the X-axis today, that made the stripe go from 4th column to 2nd column (as now in the picture above). So you mean it has some inconsitent rotation?

But nevertheless, shouldn't the ABL exactly compensate for this? Or is it too much of a difference alreadY? Or does it over/undercompensate and that is why turning it off in this case is actually better?

Edit: I just tried switchting to a 4x4 mesh (not changing anything else) giving me that:
![PXL_20220601_155534395](https://user-images.githubusercontent.com/82153569/171453631-4cf286e1-e562-4e4f-a425-c0df09453035.jpg)

Now here I am out,, looks like a SW issue now (if I change back 5x5 it looks like above again, the stripe on the 2nd column).

**Comment by RoP09** [comment]
And here is the same 9x9:

![PXL_20220601_171936846](https://user-images.githubusercontent.com/82153569/171487213-e9ee24d0-18e3-4547-8ef6-89310fe6601b.jpg)

Bed tramming shows totally levelled bed

**Comment by mriscoc** [comment]
You have at least two positions in your X axis where the carriage doesn't move smoothly. Check your eccentric wheels and the head screws.

**Comment by RoP09** [comment]
Ok, will check that. One more question, when I read the mesh in Octoprint it looks much better than the one shown in the printer (green = good?):
<img width="487" alt="Screenshot 2022-06-02 075852" src="https://user-images.githubusercontent.com/82153569/171562915-b0c9cb48-9440-42a4-accc-0ed8449c84e6.png">

Why is there such a discrepancy? Only view differences?
`Send: M420 V
Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3      4      5      6      7      8
Recv:  0 +0.009 +0.027 +0.132 +0.035 +0.027 +0.077 +0.025 -0.073 +0.047
Recv:  1 -0.003 +0.020 +0.077 +0.012 +0.005 +0.050 +0.015 -0.070 +0.029
Recv:  2 -0.015 +0.032 +0.115 +0.047 +0.025 +0.065 +0.055 -0.008 +0.040
Recv:  3 -0.020 +0.030 +0.090 +0.020 +0.032 +0.100 +0.037 -0.060 +0.040
Recv:  4 -0.045 +0.022 +0.060 +0.005 +0.005 +0.057 +0.030 -0.075 +0.010
Recv:  5 -0.003 +0.032 +0.115 +0.022 +0.025 +0.080 +0.035 -0.065 +0.052
Recv:  6 +0.017 +0.040 +0.100 +0.042 +0.022 +0.077 +0.029 -0.034 +0.024
Recv:  7 -0.015 +0.022 +0.081 +0.012 +0.020 +0.077 +0.052 -0.075 +0.037
Recv:  8 +0.015 +0.035 +0.097 +0.032 +0.020 +0.070 +0.057 -0.048 +0.032
Recv: 
Recv: echo:Bed Leveling OFF
Recv: echo:Fade Height 10.00
Recv: ok P15 B3`

**Comment by RoP09** [comment]
Did again 2 test  prints - a single 0.2mm layer and laying them out on a light photo plane so it shines through to make the densitiy of the material more visible , first one with mesh leveling (9x9) enabled, 2nd one without. 
Why is the one without actually more uniform, would not expect that at all?
![PXL_20220602_093059484](https://user-images.githubusercontent.com/82153569/171606196-4a1e1109-cb88-4b50-b58c-c94116cf6c55.jpg)

This looks like the leveling is not working at all, and even making things worse than without it.

FYI, I use the Creality magnetic surface which has this rough structure (on an Ender 3 V2, with micro swiss direct drive extruder, dual z-axis motors (linked with a ribbon drive) and the Creality Spider hotend + alot of other modifications...)

**Comment by Marvindaut** [comment]
I suspect the following in the meantime:
Due to the fact that, not the entire bed measured during automatic leveling (40mm missing at the back), a reasonable mesh cannot be created. Creality should have made the profile for the Y-axis 40mm longer, so that not only the entire bed can be printed, but also measured.
With the automatic leveling, it is then somehow converted, since the missing areas can only be estimated. This would also explain why a perfectly, manually leveled bed is "corrected" again during an automatic mesh built. Am I correct with this?

**Comment by Victordiazbis** [comment]
Let me share my experience. The vertical stripes in the mesh are caused by the X axis wheels. The problem is not the up and down movement, because it would be compensated by the autolevel. The real problem is the oscillation. As the there's an offset in X an Y  between the sensor and the nozzle, any oscillation produces big inaccuracies in the mesh. I solved the problem of the phantom waves by replacing the wheels. However I still have a problem. The sensor produce meshes tilted to the right so I suppose the extruder is tilting while it moves along x-axis. (bad tolerances of X axis profile?), so I have to follow the following process to get good results.  I use the tramming wizard, then create the auto mesh, and finally I made a manual tramming. Not happy at all. Any idea to improve the situation is welcome

**Comment by mriscoc** [comment]
> Ok, will check that. One more question, when I read the mesh in Octoprint it looks much better than the one shown in the printer (green = good?)

@RoP09, I don't see the discrepancy, indeed the Octoprint mesh visualizer confirms the printer mesh viewer data, about the numbers, don't forget that, in the matrix from the plugin, the position 0,0 is in the upper left corner.

**Comment by RoP09** [comment]
> > Ok, will check that. One more question, when I read the mesh in Octoprint it looks much better than the one shown in the printer (green = good?)
> 
> @RoP09, I don't see the discrepancy, indeed the Octoprint mesh visualizer confirms the printer mesh viewer data, about the numbers, don't forget that, in the matrix from the plugin, the position 0,0 is in the upper left corner.

No I mean according to Octorpint everything is "good" (green), still the ABL is not able to successfully level the print. How much better leveled has the bed to be to make ABL level the rest successfully? 
Or in other words, what is the reason for having ABL if it cannot deal with this amount of bed level shifts?

**Comment by mriscoc** [comment]
Check this https://www.printables.com/es/model/213992-perfect-1st-layers-ender-3-v2-ender-3s1-ender-3s1-****

**Comment by RoP09** [comment]
> Check this https://www.printables.com/es/model/213992-perfect-1st-layers-ender-3-v2-ender-3s1-ender-3s1-****

I read that before, but this would basically mean i can take the CR Touch and throw it out the window.

**Comment by Victordiazbis** [comment]
Yes and no. The problem comes from the kinematics of the printer, not from the CR touch. As the CR touch is quite far from the nozzle, any imperfection produces very bad results in the mesh. Check every element of your X axis, mainly the wheels.

**Comment by Marvindaut** [comment]
> Yes and no. The problem comes from the kinematics of the printer, not from the CR touch. As the CR touch is quite far from the nozzle, any imperfection produces very bad results in the mesh. Check every element of your X axis, mainly the wheels.

Even everything is perfekt adjusted on the printer, the problem of the "unknown 40mm", stays. I just ordered a 2040 v-slot profile to extend the range of the y axis by 40mm. According to my understanding, that should solve the main problem. I will report my experience, when installed.

By the way another question, why can't I change the bedsize? I tried to change to 230x230, but on x axis the firmware seems to fail and on y axis, its limited to 220. Is there any reason for that, and is it possible to fix/ unlock it?

**Comment by Victordiazbis** [comment]
> > Yes and no. The problem comes from the kinematics of the printer, not from the CR touch. As the CR touch is quite far from the nozzle, any imperfection produces very bad results in the mesh. Check every element of your X axis, mainly the wheels.
> 
> Even everything is perfekt adjusted on the printer, the problem of the "unknown 40mm", stays. I just ordered a 2040 v-slot profile to extend the range of the y axis by 40mm. According to my understanding, that should solve the main problem. I will report my experience, when installed.
> 
> By the way another question, why can't I change the bedsize? I tried to change to 230x230, but on x axis the firmware seems to fail and on y axis, its limited to 220. Is there any reason for that, and is it possible to fix/ unlock it?

I would ask to Miguel for a possible improvement. The chance extend the auto mesh to the unmeasurable area by adding points defined manually.

**Comment by Victordiazbis** [comment]
If I have time I would like to design a bracket to relocate the CR touch closer to the nozzle. I think everything would improve if x & y offsets weren't so big

**Comment by RoP09** [comment]
> If I have time I would like to design a bracket to relocate the CR touch closer to the nozzle. I think everything would improve if x & y offsets weren't so big

Indeed i have a custom mount made for the CR Touch which is pretty far away ( -50/-30)

**Comment by mriscoc** [comment]
> By the way another question, why can't I change the bedsize? I tried to change to 230x230, but on x axis the firmware seems to fail and on y axis, its limited to 220. Is there any reason for that, and is it possible to fix/ unlock it?

Did you change the X/Y max position? The bed can't be bigger than the maximum allowed axis size.

**Comment by mriscoc** [comment]
Check this: https://github.com/mriscoc/Ender3V2S1/issues/154

**Comment by Marvindaut** [comment]
Ok I now upgraded my printer by a profile for the y axis.
 
![image](https://user-images.githubusercontent.com/106264547/172861196-a4fa7847-04e5-4d58-92bf-434f5d557131.png)

I tested some configurations and now the sensor is measuring exactly centered and on the same Points, where the nozzle prints.
On this picture you can see a printed grid with 9x9 squares (220mmx220mm). 

![image](https://user-images.githubusercontent.com/106264547/172861249-4438a259-6090-47da-84f4-2e3ced384bf9.png)

I changed to the following settings:
Physical settings:
        X bed size: 230
        Y bed size: 230
        X min position: -5
        Y min position: -3
        X max position: 252
        Y max position: 270
Mesh inset:
        Mesh X minimum: 10
	Mesh Y minimum: 10
	Mesh X maximum: 220
	Mesh Y maximum: 220
So far so good, but I still got problems on the first Layer.
Here two pictures of the mesh and a first layer print:

![image](https://user-images.githubusercontent.com/106264547/172861324-e74dd371-f8ca-49bb-b6c0-aed4f18064f0.png)
![image](https://user-images.githubusercontent.com/106264547/172861405-211e54ac-bfb7-416e-91e4-f85a1242da26.png)

As you can see, the nozzle was too close to the bed at the front, and further back it was partly too far away. This problem is still on my other S1 – front to close, back to far away.
Do I have to change anything else in the firmware?
Is there any offset that maybe shifts the mesh, so that it is not perfect placed on the bed?
Thank you for your effort!

**Comment by RoP09** [comment]
Same here in the E3V2. Exchanged the eccentric wheels and created a new mount for the CR Touch now sitting at x=0 to the nozzle.

Still the same stripes as shown in the pictures above.

**Comment by Victordiazbis** [comment]
> Same here in the E3V2. Exchanged the eccentric wheels and created a new mount for the CR Touch now sitting at x=0 to the nozzle.
> 
> Still the same stripes as shown in the pictures above.

Yesterday I replaced the wheels and the CR-Touch. Mesh looks good with no stripes, however  nozzle is slightly closer to the bed in the right side of the bed. I have to tilt the bed after mesh creation to get good results. Maybe my x axis profile is slightly twisted. Wheels and auto bed leveling are not good combination. Maybe with linear rails
