### ISSUE TITLE
Using Prusa Slicer Start G-Code Prusa Slicer generates and error.

### ISSUE THREAD

**Issue by macbentosh** [mriscoc/Ender3V2S1#177]
Using Prusa Slicer Start G-Code Prusa Slicer generates and error.

Add STL to slicer with added start g-code 
Slice 
Get error 
G-code export to /var/folders/yd/scsfqp016_140ypsfml9ql1m0000gn/T/.34757.gcode failed due to invalid custom G-code sections:
start_gcode
Parsing error at line 18: Not a variable name
M104 S{first_layer_temperature[initial_extruder]+extruder_temperature_offset[initial_extruder]} ; set final nozzle temp
                                                 ^
Please inspect the file /var/folders/yd/scsfqp016_140ypsfml9ql1m0000gn/T/.34757.gcode.tmp for error messages enclosed between
        !!!!! Failed to process the custom G-code template ...
and
        !!!!! End of an error report for the custom G-code template ...
for all macro processing errors.

**Expected behavior**
Slice 
Save Print

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/issues/174
```gcode
M501; Read values from EEPROM
M201 X500.00 Y500.00 Z100.00 E5000.00 ;Setup machine max acceleration
M203 X500.00 Y500.00 Z20.00 E50.00 ;Setup machine max feedrate
M204 P500.00 R1000.00 T500.00 ;Setup Print/Retract/Travel acceleration
M205 X8.00 Y8.00 Z0.40 E5.00 ;Setup Jerk
M220 S100 ;Reset Feedrate
M221 S100 ;Reset Flowrate

G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S[first_layer_temperature] ; set extruder temp
M140 S[first_layer_bed_temperature] ; set bed temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M109 S[first_layer_temperature] ; wait for extruder temp
; Setup firmware retraction settings
M207 F{ retract_speed[0] * 60} S[retract_length_0] Z[retract_lift_0]
M208 F{ deretract_speed[0] * 60} S[retract_restart_extra_0]
G28 ; home all
M420 S1 Z2 ; Active mesh leveling
G1 Z2 F240
G1 X2 Y10 F3000
G1 Z0.28 F240
G92 E0
G1 Y190 E15 F1500 ; intro line
G1 X2.3 F5000
G92 E0
G1 Y10 E15 F1200 ; intro line
G92 E0
```
