### ISSUE TITLE
No tuning possible during octo print

### ISSUE THREAD

**Issue by robindonne1** [mriscoc/Ender3V2S1#179]
Im new to this firmware but besides al the good points compared to the jyers version, i cant seem to find or have the TuneMenu when a print is activated. Am i missing something, and/or do i need to activate this option? Or is it just not available when printing through octoprint?
![image1](https://user-images.githubusercontent.com/50793201/171306139-dcc6d368-ab53-4159-bee8-addcaff5de66.jpeg)

![image0](https://user-images.githubusercontent.com/50793201/171306158-a546429c-2132-47c1-a5ab-38f7df45615e.jpeg)

the pictures show the message that its performing homing, and after homing it starts printing while my screen just show one of the menu pages open, and not the Tune Menu like i used to see in my previous firmware.

Thanks for reading.

im using 2.1.0.1 on a ender 3 v2 4.2.7 blt

**Comment by mriscoc** [comment]
Please read the Wiki: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint
