### ISSUE TITLE
Support for the new build volume for the Ender 3 S1 Plus

### ISSUE THREAD

**Issue by trulow** [mriscoc/Ender3V2S1#183]
**Is your feature request related to a problem? Please describe.**
I was hoping if it was possible to add support for the new [Ender 3 S1 Plus](https://store.creality.com/products/pre-order-code-for-ender-3-s1-plus-3d-printer) 300x300x300 build volume

**Describe the solution you'd like**
The new S1 Plus should be a simple fix as the only change to the current S1 F1/F4 firmware should be the build volume size modification. Since we can already change the build plate size within the settings menu, an alternative solution would be to allow us to use the current F1/F4 firmware and just add a Z axis size adjustment settings to go along the X and Y adjustment setting.

**Comment by mriscoc** [comment]
You can use Advanced / Physical Settings
![physical-settings-2](https://user-images.githubusercontent.com/2745567/171549589-3cae36fc-4304-4188-bfad-4f853b23a3c9.jpg)
