### ISSUE TITLE
Printer reboot on accessing print menu and creat jpeg thumbnail script not working cura 5

### ISSUE THREAD

**Issue by Moobien** [mriscoc/Ender3V2S1#186]
**Describe the bug**

Since updating to firmware BLT 20220527 my printer will reboot every time I try to access the print menu for 3-5 minutes after inserting my micro sd card.

**To Reproduce**
1. insert micro sd card
2. wait a few seconds
3. try to open print menu

**Expected behavior**

previously i could go to my print menu seconds after inserting my micro sd card.

Create JPEG Thumbnail script issue.

installed the script as per instructions for cura 5, however when you go to extenssions - post processing etc to enable the script it does not show in the list to be selected.

**Comment by mriscoc** [comment]
Format or change your memory card. 
Update the post processing script.

**Comment by Moobien** [comment]
Have reformatted the card numeous times,

EDIT 1: memory card reads in my pc instantly when I plug it in.  and prior to updating to the firmware listed above this issue did not happen. have uploaded a video to youtube showing what it is doing and will edit in url for it once it finally uploads.
EDIT 2: video url. https://youtu.be/fZjp6xP0Sg4

The updating the script worked! thank you for that,

**Comment by mriscoc** [comment]
We don't have SD problems, but it can be very dependent on the class of memory card, number of files, size of the name of the files, number of folders, etc. You could test by formatting the card and putting only some files on it. The reboot could be an error of memory overflow due to a large folder structure.
