### ISSUE TITLE
Bed Tramming Support for Ender 3 S1 Plus

### ISSUE THREAD

**Issue by trulow** [mriscoc/Ender3V2S1#190]
When running the bed tramming wizard on the Ender 3 S1 Plus, the probe does not go to all for corners. Even after changing the physical bed size within the advanced menu settings to 300x300, the tramming wizard acts like the bed is still a 220x220 bed. It starts the tramming wizard at 0x0 but then when moving to the next point, stops halfway to the 0x220 mark before moving onto the back portion of the bed at 220x220, and finally moving to 220x0

**Version (please complete the following information):**
[Ender3S1-F4-20220527.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20220527/Ender3S1-F4-20220527.bin)

EDIT: I also noticed that the auto bed leveling also has the same issue and probes the bed as if it were only a 220x220 sized bed instead of a 300x300 sized bed.

**Comment by trulow** [comment]
I tried my hand at updating the configurations. First time compiling it so use and test on your own risk.

Updated these lines in the following files

### File Configuration_adv.h
`
  // Define positions for probe points.
  #define TRAMMING_POINT_XY { {  20, 20 }, { 290,  20 }, { 290, 290 }, { 20, 290 } }`

`#if EITHER(MESH_BED_LEVELING, AUTO_BED_LEVELING_UBL)
  // Override the mesh area if the automatic (max) area is too large
  #define MESH_MIN_X 10
  #define MESH_MIN_Y 10
  #define MESH_MAX_X 290
  #define MESH_MAX_Y 290`

### File Configuration.h
`// The size of the printable area
#define X_BED_SIZE 300  // MRiscoC Max usable bed size
#define Y_BED_SIZE 300  // MRiscoC Max usable bed size

// Travel limits (linear=mm, rotational=°) after homing, corresponding to endstop positions.
#define X_MIN_POS -10  // MRiscoC Stock physical limit
#define Y_MIN_POS -8  // MRiscoC Stock physical limit
#define Z_MIN_POS 0
#define X_MAX_POS 300  // MRiscoC Stock physical limit
#define Y_MAX_POS 300  // MRiscoC Stock physical limit
#define Z_MAX_POS 300  // Ender Configs`

[firmware-20220609-134242-PLUS.bin](https://we.tl/t-sY2oRH9dRL)

**Comment by mriscoc** [comment]
Please check: https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides

`Advanced` / `Mesh leveling` / `Mesh inset` / Maximize Area, then Center Area
