### ISSUE TITLE
High temp

### ISSUE THREAD

**Issue by pacocatech** [mriscoc/Ender3V2S1#191]
Can I change the hotend temperature? I bought a kit to use above 300º the firmware already supports? What do I need to do to get this support?

**Comment by mriscoc** [comment]
It depends on the thermistor type of your heater block. Stock thermistor type is fixed to 300-15 (overshoot)= 285°C

**Comment by pacocatech** [comment]
i know it depends on it, i bought an extruder kit that can withstand high temperature, i wanted to know if the firmware is already prepared so i can increase the temperature

**Comment by mriscoc** [comment]
But what is your thermistor type, stock is 1, there are special versions for type 5 and 13.
https://github.com/mriscoc/Special_Configurations/releases

**Comment by pacocatech** [comment]
thanks for shared this special configurantions.
