### ISSUE TITLE
Z Axis E-Steps

### ISSUE THREAD

**Issue by I-wish-2** [mriscoc/Ender3V2S1#199]
**Is your feature request related to a problem? Please describe.**
This is not related to any problem, it is just an enhancement to the Z axis e-steps when up grading the leadscrew to a finer 2mm pitch.

**Describe the solution you'd like**
I have a strong desire to change my stock Z axis lead screw for one that is a 2mm Pitch, 1 Start & 2mm Lead in addition to adding a Anti Backlash Spring Loaded Nut to the lead screw. This is in an effort to stop the Z axis drop and allow for a finer print quality.  This lead screw will require the Z axis to have an E-step value of about 1600.  Currently the max E-step value allowed is 999.9.  I'm not sure if the decimal place will be required for this new lead screw.
Please note that your firmware is loaded on to my Ender 5 Pro for for the 4.2.2 motherboard and display.  The original display was replaced with a E3 V2 display v 1.4 and your private firmware.  This E5 Pro is fully functional in all aspects after quite a bit of elbow grease was applied.
Your firmware is loaded on my E3 V2 as well which will also have its lead screw upgraded.

**Describe alternatives you've considered**
I have not looked into any other options regarding the Leadscrew upgrade other than to keep using the original stock one.  Which is an 8 pitch or 8mm of movement for 360 degrees of rotation.  The other is 2mm of movement for 360 degrees of rotation.

**Additional context**
Here is a youtube video on the lead screw up grade if you need it.  https://www.youtube.com/watch?v=lBpXHWJG7aM
Thank you Sir for a fine effort with your firmware and share.  I came here through 3DHub.   Sorry for being wordy.
Doug

**Comment by mriscoc** [comment]
The current experimental version has a limit of 1999.9 by you request, it will be available after some test.

**Comment by I-wish-2** [comment]
Greetings Miguel,
Thank you very much for your reply and great news.  This will be quite an improvement for the step resolution of the Z axis on Ender 3 V2 and Ender 5 Pro that I have running your firmware.
Do you feel that it will require a motherboard and display firmware update?  Thank you once again.
My Best Regards
Doug

**Comment by mriscoc** [comment]
You will need to update only the main firmware.

**Comment by I-wish-2** [comment]
I hope the testing goes well.  Once again thank you sir.
Best Regards
Doug

**Comment by I-wish-2** [comment]
Greetings,  I wanted to add that if you would like a test site using an Ender 3 V2 and a Ender 5 Pro my machines are available.  Both of these printers are running your current firmware and are working well.  If you have an interest please let me know.  I'm currently retired and have the time to devote to such a project.
Best Regards
Doug

**Comment by mriscoc** [comment]
> Greetings, I wanted to add that if you would like a test site using an Ender 3 V2 and a Ender 5 Pro my machines are available. Both of these printers are running your current firmware and are working well. If you have an interest please let me know. I'm currently retired and have the time to devote to such a project. Best Regards Doug

Thank you.

**Comment by mriscoc** [comment]
Maximum limit of E-steps have been increased in the latest release.

**Comment by I-wish-2** [comment]
Greetings Miguel,  Thank you for the E-Steps changes.  I will start the lead screw upgrade on the Ender 5 Pro today and can post the results here in this comment area.  Again thank you for your efforts.
Best Regards
Doc'

**Comment by I-wish-2** [comment]
Re-Hi Miguel,  The new Z axis 400mm T8 Tr8x2 ( Acme Thread, 2mm Pitch, 1 Start, 2mm Lead ) with a T8 Anti-Backlash spring loaded nut is now installed.  The e-steps for the Z axis calibrated for a 0 to 300 mm range is ( 1,595.744 ).  Thank you again Miguel for making this upgrade possible for all Ender 3 V2 and 5 Pro printers.

Best Regards
Doc'
