### ISSUE TITLE
Add a longer time before cooling down during M600 filament change

### ISSUE THREAD

**Issue by ecogice** [mriscoc/Ender3V2S1#200]
**Is your feature request related to a problem? Please describe.**
I set up M600 filament changes in my gcode often and the screen says "Click to heat" and starts cooling down within about a minute after the command

**Describe the solution you'd like**
I'd like the time before cooling down to be changed to 2-3 minutes

**Comment by mriscoc** [comment]
I don't remember the current timeout but it is more than 1 minute, remember that more time is more risk to have crystallization of the residues inside of the nozzle and that could produce clogs.

**Comment by ecogice** [comment]
I used a stopwatch and from the time that it raises off the build plate to the time that it says "Click to heat," it was about a minute and 5 seconds. I do understand that leaving it heated without printing can cause clogs, but adding 60 seconds more to the waiting time would make changing filament faster

**Comment by mriscoc** [comment]
OK, I will check, you could help me by finding the relevant parameter in the configuration files.

**Comment by ecogice** [comment]
Yes, in the configuration_adv.h file in each config folder, and at line 2576, there is PAUSE_PARK_NOZZLE_TIMEOUT, which is at 45, so this could be changed to 90

**Comment by mriscoc** [comment]
Excellent, I will increase PAUSE_PARK_NOZZLE_TIMEOUT to 90 in the next version. Thanks.

**Comment by cristianmur** [comment]
una pregunta de novato, no se podria hacer una retraccion mas larga en el cambio de color, para no tener que estar tan pendiente de la impresora?

yo lo digo por que ya me ha pasado varias veces que por algunproblema como filamento roto, se me a quedado parada la impresion toda la noche y luego sigue genial.

La verdad que estoy enamorado de tu firmware es increible, al principio lo instale pero al tener el chip F4 que era nuevo no guardaba en la eprom, pero ya lo solucionaste. No me acordaba y estaba trabajando con un marlin externo hasta que ayer me dijeron que ya lo habias solucionado lo de la placa nueva.
Muchas gracias , eres un genio pedazo de compilacion.

**Comment by mriscoc** [comment]
> una pregunta de novato, no se podria hacer una retraccion mas larga en el cambio de color, para no tener que estar tan pendiente de la impresora?
 
La longitud de carga y descarga puedes manejarla desde el menu `Advanced / Filament Settings`

**Comment by ZoeESummers** [comment]
> Excellent, I will increase PAUSE_PARK_NOZZLE_TIMEOUT to 90 in the next version. Thanks.

Can it be changed to resume on touching a button on the screen, like you do on the Prusa printers? So no fixed timeout is needed and the screen will show the temps and will resume when back up to temp and continue has been touched.

**Comment by mriscoc** [comment]
> > Excellent, I will increase PAUSE_PARK_NOZZLE_TIMEOUT to 90 in the next version. Thanks.
> 
> Can it be changed to resume on touching a button on the screen, like you do on the Prusa printers? So no fixed timeout is needed and the screen will show the temps and will resume when back up to temp and continue has been touched.

It could be dangerous not to implement an automatic timeout.

**Comment by mriscoc** [comment]
PAUSE_PARK_NOZZLE_TIMEOUT  increased to 90s in the latest version
