### ISSUE TITLE
Cant set bed temperature over 100

### ISSUE THREAD

**Issue by vikeis** [mriscoc/Ender3V2S1#201]
**Describe the bug**
Cant set bed temperature over 100, i have a S1 F4. 

Send: M140 S110
Recv: ok P15 B3
Recv:  T:109.07 /0.00 B:86.21 /100.00 @:0 B@:127

**Version (please complete the following information):**
Firmware version and release date
20220527 version

**Comment by hayden-t** [comment]
what was the problem here ?
