### ISSUE TITLE
CRTouch UBL Mesh generation crashes at 64th data point collection with HS mode active

### ISSUE THREAD

**Issue by thujones** [mriscoc/Ender3V2S1#203]
**Describe the bug**
Appears using any mesh size > 63 points causes crash when attempting to get 64th data point

**To Reproduce**
1) Configure UBL Mesh Generation to 8x8 or 9x9 (64 or 81 points respectively)
2) Perform G28 homing
3) Perform G29 P1 to begin populating mesh
4) Monitor progress x of 64 or x of 81 depending on selection above in terminal output or screen
5) Upon reaching 64th probe point, probe appears to retract, the extruder dives to the print bed and and emergency stop M112 is issued
5a) Retested 3 times and same behavior every time
6) Using anything lower such as 5x5, 6x6, or 7x7 probes and generates just fine and is usable.

**Expected behavior**
Mesh generation beyond 63 datapoints, current compiled firmware seems configured for squares of numbers, so 7x7 (49 probe points) appears the largest that can be used at the moment on this specific build

**Screenshots**

**Version (please complete the following information):**
Ender3V2-422-BLTUBL-20220527.bin

**Additional context**
Octoprint Mesh generation script in use is as follows:

M300 S440 P200
M117 Heating Bed to 70C
M190 S70
M300 S440 P200
M117 Homing XYZ
G28
M300 S440 P200
M117 Probing Bed
M420 S0
M155 S30
G29 P1 ; FAILS AT PROBE POINT 64
G29 P3
G29 P3
@BEDLEVELVISUALIZER
M420 S1 V
G29 S0
G29 F 10.0
G29 A
M500
M155 S3
M140 S0
M117 Bed mesh levels completed
M300 S440 P200

**Comment by mriscoc** [comment]
With a CRTouch for large mesh it is advisable to disable the HS mode: https://github.com/mriscoc/Ender3V2S1/wiki/3D-BLTouch#notes-about-crtouch.

For avoid emergency stops (M112) you must follow this octoprint configuration: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#error-handling

**Comment by thujones** [comment]
Thank you so much. Turns out while i did read the manual, clearly I didn't understand it :-)
![image](https://user-images.githubusercontent.com/921428/175432482-96ab7151-b012-45fd-8267-1bf98a7ee134.jpeg)

Worked like a charm. Thanks so much! Cheers!

**Comment by mriscoc** [comment]
If you are using the G29 P1 in your start G-code script you can remove the mesh viewer using the special G-code C108 just after the G29 P1.

**Comment by thujones** [comment]
My goodness, I am so glad for people like you that can connect the dots for me. That is a small quality of life improvement :-) thanks so much!
