### ISSUE TITLE
After cancel a host printing process the next home results in bed moving to front.

### ISSUE THREAD

**Issue by anilgunduzz** [mriscoc/Ender3V2S1#204]
I'm having an issue with Z offset wizard. I select the "Move Z to Home", the nozzle is going to its location and Y is starting to move. When I do it a second time, it's working without issues.

Here is the video record:

https://imgur.com/a/HAPdNFe

Mainboard: BTT SKR Mini E3 V3
Probe: CR Touch
Hotend: Biqu H2 v2

**Comment by mriscoc** [comment]
Did you cancel a print before of that?

**Comment by anilgunduzz** [comment]
> Did you cancel a print before of that?

Yes I did.

**Comment by mriscoc** [comment]
The printer was not able to execute the end script at print cancel, because the host did not inform the printer. That is a known issue when you start a print process and cancel the print from the host. So, the printer executes the end script at the end of the next axes homing.
