### ISSUE TITLE
Add support for PB0 pin on the Ender 3 S1 for POWER_MONITOR_VOLTAGE

### ISSUE THREAD

**Issue by tiagofreire-pt** [mriscoc/Ender3V2S1#206]
**Is your feature request related to a problem? Please describe.**

The Ender 3 S1 mainboard has a ADC pin ` PB0` that might be useful for monitoring the power supply.

In: https://github.com/CrealityOfficial/Ender-3S1/blob/main/Marlin/src/pins/stm32f4/pins_CREALITY_S1_F401RC.h#L95

**Describe the solution you'd like**

For saving the current position into the SDCard and moving the Z axis up, while printing, as a proper way to elegantly manage a power outage.

**Describe alternatives you've considered**
None

**Additional context**
Might  be also useful for the Marlin `POWER_MONITOR_VOLTAGE` option.

**Comment by mriscoc** [comment]
That feature requires an alternative power source as batteries, UPS, or supercapacitors to energize the board when the main power is down. Currently there is no plans for implement that feature in the firmware.
