### ISSUE TITLE
Ender 3 S1 Pro support

### ISSUE THREAD

**Issue by kentsigurdsen** [mriscoc/Ender3V2S1#211]
Would love to have this compiled for Ender 3 S1 Pro as well. Is this possible, or is the LCD screen preventing custom firmware?

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/discussions/161
https://github.com/mriscoc/Ender3V2S1/discussions/123
https://github.com/mriscoc/Ender3V2S1/issues/144
https://github.com/mriscoc/Ender3V2S1/issues/121
https://github.com/mriscoc/Ender3V2S1/issues/114
