### ISSUE TITLE
Ender 3 S1 Expansion Interface Software Control

### ISSUE THREAD

**Issue by jaredbiehler** [mriscoc/Ender3V2S1#215]
This is a shot in the dark (ha) - I'm wondering if the controller has any ability to interface with or control the Expansion Interface that's included on the Ender 3 S1 models? The most popular accessory I've seen this used for is a light bar and it'd be useful to allow this light be controlled (especially remotely). I thought I'd ask here before setting up a relay with OctoPrint. Thank you for your time and all the wonderful features in this firmware!
![plug-cover-on-ender-3-s1](https://user-images.githubusercontent.com/684719/177415216-709e6e34-2ba2-485e-9564-a9a73932ab25.jpeg)

**Comment by mriscoc** [comment]
The port can be controlled but currently there is not a device that use it.

**Comment by jaredbiehler** [comment]
https://www.creality3dofficial.com/products/ender-3s1-led-kit does. I was hoping to figure out a way to turn this light on / off via this port remotely via OctoPrint through the controller, if possible.

**Comment by mriscoc** [comment]
> https://www.creality3dofficial.com/products/ender-3s1-led-kit does. I was hoping to figure out a way to turn this light on / off via this port remotely via OctoPrint through the controller, if possible.

I think that the lamp is not using the expansion port (PWM) but only the 24V power supply.

**Comment by Lungenpest** [comment]
> > https://www.creality3dofficial.com/products/ender-3s1-led-kit does. I was hoping to figure out a way to turn this light on / off via this port remotely via OctoPrint through the controller, if possible.
> 
> I think that the lamp is not using the expansion port (PWM) but only the 24V power supply.

It is connected to the expansion port.

https://www.youtube.com/watch?v=LifRM4gGVi0

![grafik](https://user-images.githubusercontent.com/64774660/180476614-cd745db9-1781-4ec0-b852-1939c7d192ec.png)

**Comment by mriscoc** [comment]
From your video, only power is used:
![image](https://user-images.githubusercontent.com/2745567/180508250-78805549-5bd8-4442-902d-872912719017.png)

And from your image:
![image](https://user-images.githubusercontent.com/2745567/180509751-a34207c8-21c5-4bb0-a3f2-b99ffd941dbc.png)

**Comment by mriscoc** [comment]
From your video, only power is used:
![image](https://user-images.githubusercontent.com/2745567/180508250-78805549-5bd8-4442-902d-872912719017.png)

**Comment by jaredbiehler** [comment]
Ah I was wondering if that's what you were referencing or if you had meant that you believed that light was connected directly to the internal rails of the 24v power supply. So there's only the ability to control the PWM settings, but nothing that can turn the 24v on / off to this expansion interface via software then?

**Comment by mriscoc** [comment]
Power supply is not under management of the control board.
