### ISSUE TITLE
Ender 3 v2 4.2.2 neopixel support?

### ISSUE THREAD

**Issue by G1t1t** [mriscoc/Ender3V2S1#219]
Your link to Ender 3 v2 4.2.2 neopixel support is missing. I’ve tried compiling your firmware with know settings to enable neopixels and menu nothing is working? 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Special_Configurations/

**Comment by G1t1t** [comment]
Failing to compile?


Marlin/src/gcode/calibrate/G28.cpp: In function 'void home_z_safely()':
Marlin/src/gcode/calibrate/G28.cpp:130:45: error: the value of 'safe_homing_xy' is not usable in a constant expression
  130 |       constexpr xy_float_t okay_homing_xy = safe_homing_xy;
      |                                             ^~~~~~~~~~~~~~
Marlin/src/gcode/calibrate/G28.cpp:125:43: note: 'safe_homing_xy' was not declared 'constexpr'
  125 |     TERN(ProUIex, , constexpr) xy_float_t safe_homing_xy = { Z_SAFE_HOMING_X_POINT, Z_SAFE_HOMING_Y_POINT };
      |                                           ^~~~~~~~~~~~~~
*** [.pio/build/STM32F103RE_creality/src/src/gcode/calibrate/G28.cpp.o] Error 1
========================= [FAILED] Took 40.76 seconds =========================

**Comment by mriscoc** [comment]
Sources updated
