### ISSUE TITLE
Issue with bed tramming

### ISSUE THREAD

**Issue by davkvi** [mriscoc/Ender3V2S1#22]
4.2.2 bl touch

When bed tramming is enabled it will only allow the following
left front
left back
center

On the following it does nothing, only the display changes.
right front
right back

**Comment by jk7gr** [comment]
I assume you had to change the X and Y offsets of your probe. If this is the case you also need to increase the probe margin. This is currently set to 20 mm. This means that if the offset you have set is bigger than then initial one then your nozzle is pushed very far right to an unreachable area. If your margin is set to 30mm then your nozzle will not be push than much to the right. I would suggest that you change the margin to 30 and test again. Let me know how it goes..

**Comment by mrarzt** [comment]
Which settings did you use jk? So probe settings and home offset?

**Comment by PapsDizzy** [comment]
see here guys 
https://github.com/mriscoc/Ender3V2S1/issues/15#issuecomment-1029074533

**Comment by PapsDizzy** [comment]
i have increasd the margin from 25 to 30 and now is it working

**Comment by jk7gr** [comment]
> Which settings did you use jk? So probe settings and home offset?

![20220203_113955.jpg](https://user-images.githubusercontent.com/17036347/152633485-77013c07-7290-40d5-a41b-f9bce3ba1031.jpg)

**Comment by jk7gr** [comment]
I have the Satsana Air Duct which has these settings.

**Comment by jk7gr** [comment]
> > Which settings did you use jk? So probe settings and home offset?
> 
> ![20220203_113955.jpg](https://user-images.githubusercontent.com/17036347/152633485-77013c07-7290-40d5-a41b-f9bce3ba1031.jpg)

I have the Satsana Air Duct which has these settings.

**Comment by davkvi** [comment]
> I assume you had to change the X and Y offsets of your probe. If this is the case you also need to increase the probe margin. This is currently set to 20 mm. This means that if the offset you have set is bigger than then initial one then your nozzle is pushed very far right to an unreachable area. If your margin is set to 30mm then your nozzle will not be push than much to the right. I would suggest that you change the margin to 30 and test again. Let me know how it goes..

This is the correct solution :)
