### ISSUE TITLE
CRTouch/Z-Offset is not working good with a previously working firmware version.

### ISSUE THREAD

**Issue by ghost** [mriscoc/Ender3V2S1#224]
Greetings
I have installed, after making an UPGRADE on my Creality Ender3V2 (Creality Silent Mainboard 4.2.7 / Creality Sprite Pro Extruder Kit / Cr Touch), the Professional Firmware 202205527 Version 4.2.7 BLT.
The problem that now Z offset varies every time I turn the printer off and on.
Before loading this Firmware everything worked fine but now even if I reinstall the previous Firmware, nothing changes regarding Z Offset.
Is this problem known?
Can you help me please?
Regards

**Comment by mriscoc** [comment]
Some CRTouch doesn´t work consistently. But if with your previous firmware it worked, I recommend you to return to that version. Flashing the firmware is an reversible operation and nothing but configuration is left in the printer, So, if you change the firmware and load the default settings you always we return to the previous status.

**Comment by ghost** [comment]
Hello
I tried to go back to the previous version but the Z Offset also varies with the previous version (and before downloading the new firmware it worked fine)

**Comment by mriscoc** [comment]
If your CRTouch is also failing with the old firmware you can have a hardware problem with it, check your wires and conections.

**Comment by Moobien** [comment]
I can attest this has been happening for me over the last few firmware versions. Trammed  bed, set zoffset with 0.1mm feeler.  go to print and after the g29 has run the nozzle is a lot higher than 0.1mm

**Comment by ghost** [comment]
> If your CRTouch is also failing with the old firmware you can have a hardware problem with it, check your wires and conections.

The CR touch works fine.
I think the problem is the firmwareZ offset varies after each print and each time the printer is turned on.
And if you read Moobien Green's latest comment that I'm not the only one who has this problem.

**Comment by Moobien** [comment]
> > If your CRTouch is also failing with the old firmware you can have a hardware problem with it, check your wires and conections.
> 
> The CR touch works fine. I think the problem is the firmwareZ offset varies after each print and each time the printer is turned on. And if you read Moobien Green's latest comment that I'm not the only one who has this problem.

Yeah my cr touch is fine according to the M48 diagnostic, its almost like it is adding layer height to z offset instead of factoring the z offset into it.

**Comment by mriscoc** [comment]
If your hardware is not working with a version where it previously worked with the same configuration then it is a hardware problem.

**Comment by Moobien** [comment]
Only time i never seemed to have this issue was on stock firmware
