### ISSUE TITLE
can't cancel print from printer screen

### ISSUE THREAD

**Issue by wjcarpenter** [mriscoc/Ender3V2S1#226]
**Describe the bug**
Maybe I am misinterpreting, but I assumed "In screen control of host printing" meant that I should be able to pause or cancel a print from the printer's LCD. I have not found any way to do that.

**To Reproduce**
Start a print from Octoprint.
Try to find a way to cancel the print from the printer PCD.

**Expected behavior**
I expected to find a menu item for pause/resume/cancel or similar.

**Version (please complete the following information):**
[Ender3V2-422-BLTUBL-20220716.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20220716/Ender3V2-422-BLTUBL-20220716.bin)

**Additional context**
 I am using an Ender 3v2 with BLTouch and BTT filament sensor.

**Comment by mriscoc** [comment]
Please, read the wiki: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint
