### ISSUE TITLE
Strange X-axis Issue

### ISSUE THREAD

**Issue by anilgunduzz** [mriscoc/Ender3V2S1#228]
Hi,

I upgraded the firmware to the latest version. Configured tramming and UBL and started a print but the x-axis didn't move. Also, the same thing happened on Z probe wizard.

I recompiled the firmware for Linear Advance (and disabled S curve acceleration)

You can find 2 videos in this link:

[https://imgur.com/a/d3rTixX](https://imgur.com/a/d3rTixX)

Am I doing wrong something or is this a bug?

Update: I tried precompiled UBL firmware and it worked without this issue.

Mainboard: SKR Mini E3 V3

**Comment by mriscoc** [comment]
Hi, if it works with the precompiled, then the hardware is ok, maybe there is some error in the configuration files that you are using.

**Comment by mriscoc** [comment]
From your videos, you must configure the offsets correctly.
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
