### ISSUE TITLE
steppers making louder noises on latest firmware

### ISSUE THREAD

**Issue by jxer** [mriscoc/Ender3V2S1#231]
Universal 20220716 422bltUBL

e3v2,

I am now seeing you disabled ADAPTIVE_STEP_SMOOTHING

This needs to be a selectable option (call it silent mode if you want). 

I can now hear this printer running from across my entire house, due to the resonance. Changing acceleration, is a bandaid. My printer was holding amazing accuracy before this change. I don't agree with it being disabled, without being able to turn it back on.

according to marlin this also helps with surface artifacts. i agree i will have more of these artifacts as the printer is noticeably vibrating more from these moves

please make a poll, i will be shocked if anyone agrees with this change.

**Comment by jxer** [comment]
I am reading there is some kind of silent mode for the steppers? is this true?

**Comment by mriscoc** [comment]
Duplicated of https://github.com/mriscoc/Ender3V2S1/issues/229

**Comment by jxer** [comment]
@mriscoc so to be clear, your not even going to discuss making this an option?

**Comment by mriscoc** [comment]
Currently there is no plan to be integrated as menu option, but can be re-enabled in the configuration_adv.h file for devices with 512K of program memory (RET6) we are reaching the program memory limit for the RCT6 devices.

**Comment by jxer** [comment]
That issue is specific to skr boards per the marlin discussion page, why are you implementing it across creality boards?
