### ISSUE TITLE
SD card files sorting on the printer screen

### ISSUE THREAD

**Issue by TioSam13** [mriscoc/Ender3V2S1#232]
First of all, thanks for the wonderfull work on our firmware, it's a game changer with more options than creality stock for sure.

I would like to request a extra option on the configuration menu to choose between alphabetic and last modified files on the printer screen. Currently, we are locked with alphabetic order wich is ok, but lot's of times we have Stl's with similar file names

Add an option on the advanced menu to choose between alphabetical and last modified files.
Prusa already got this option compiled on their firmware as seen in the 2 images bellow

![WhatsApp Image 2022-07-19 at 16 55 17 (1)](https://user-images.githubusercontent.com/81544936/179837224-01f5e7d2-6397-4869-881c-15ad981a6698.jpeg)
![WhatsApp Image 2022-07-19 at 16 55 17](https://user-images.githubusercontent.com/81544936/179837228-98e87c31-05c9-4788-b515-72961c2bc61a.jpeg)

**Comment by GeorgelT** [comment]
I'd just like to add myself also to this request. Wanted to submit an issue exactly with this request but saw this one exists already. Really annoying sometimes, I'm not sure how it sorts files right now, but I don't think it's alphabetical either(on 22 dec fw release on S1). 

I usually have my naming as nozzel size, time, model name, material, so all my files start like this: 0.4_20h_modelname_pla , but sometimes newest ones are first, sometimes last and they are definitely not alphabetical. Started a print already but will add a screenshot once it finishes.

**Comment by mriscoc** [comment]
The filelist is sorted alphabetically if the number of files is less than 40, use SDSORT_LIMIT for increase the number of files sorted.
You can configure the file sorting with the command [M34](https://marlinfw.org/docs/gcode/M034.html), use it in a [configuration file](https://github.com/mriscoc/Ender3V2S1/wiki/Configuration-files).

**Comment by TioSam13** [comment]
> The filelist is sorted alphabetically if the number of files is less than 40, use SDSORT_LIMIT for increase the number of files sorted. You can configure the file sorting with the command [M34](https://marlinfw.org/docs/gcode/M034.html), use it in a [configuration file](https://github.com/mriscoc/Ender3V2S1/wiki/Configuration-files).

After following your instructions on the [configuration file](https://github.com/mriscoc/Ender3V2S1/wiki/Configuration-files) I coded the file like this and saved the file as: auto0.g

; Professional Firmware Configuration File
;=====================================================
C10                    ; Mark as a configuration file
M117 Applying configuration
;-----------------------------------------------------
M34 F1 S<bool>         ; SDCard Sorting
;-----------------------------------------------------
G4 S1                  ; Wait a second
M300 P200              ; Beep
M117 Configuration Applied
;-----------------------------------------------------

Now I have the SD CARD files in alphabetical instead of no order, wich is a progress, but is it possible to put the files in the Last Modified order?

Thank you very much for replying my issue =D

**Comment by Sarah-1331** [comment]
I would still like this to sort in latest modified

**Comment by TioSam13** [comment]
> I would still like this to sort in latest modified

Me too, is the best sorting option!
