### ISSUE TITLE
No printing screen when the printing start from Octoprint

### ISSUE THREAD

**Issue by egonwinter** [mriscoc/Ender3V2S1#245]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by egonwinter** [comment]
When I print with Octopi, there is no solution to stop a print, only in Cura ore Octopi, is it possible to do a Butten in the print Menü to stop the print? Thanks for your answer

**Comment by mriscoc** [comment]
> 

https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint

**Comment by egonwinter** [comment]
Hi Miguel

You send me the Link, I check the Link, but I don´t know what to do, I´m not that specialist in programming I´m just
A user, please advice what to do to have a Break and a Print Stop button on the display, thanks for your help.

Best regards

Egon Winter

Wilhelm – Schweizer – Straße. 10
56564 Neuwied

Mob. +49 170 6868491
Tel. +49 2631 4003157

Mail. ***@***.***

Von: Miguel Risco-Castillo ***@***.***>
Datum: Sonntag, 24. Juli 2022 um 00:47
An: mriscoc/Ender3V2S1 ***@***.***>
Cc: egonwinter ***@***.***>, Author ***@***.***>
Betreff: Re: [mriscoc/Ender3V2S1] Start Stop Print (Issue #245)

https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint

**Comment by mriscoc** [comment]
> Hi Miguel You send me the Link, I check the Link, but I don´t know what to do, I´m not that specialist in programming I´m just A user, please advice what to do to have a Break and a Print Stop button on the display, thanks for your help. Best regards 

You only need to follow the guide for configure your Octoprint:  https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#octoprint-gcode-scripts

Basically you are missing the start print G-code script
```gcode
M75 {{ event.name }}
```
But all the scripts are important.
