### ISSUE TITLE
Ender 3 S1 - Preview STL

### ISSUE THREAD

**Issue by pacocatech** [mriscoc/Ender3V2S1#248]
Hello,
I'm using the latest version of the FW that you released for ender3 s1 and I updated the display as per your post.
I did the entire flow of the python scripts to generate the preview of the file on the printer, however, when I put it to print my display always looks like this.

Is there anything I can do to resolve it?

![image](https://user-images.githubusercontent.com/70729684/180883916-de72fab0-07f7-49b7-bf82-650fd9271a9d.png)

**Comment by mriscoc** [comment]
G-code preview is only compatible with DWIN screens not DACAI, check here: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-generate-a-gcode-preview#dacai-screen-units-dont-support-g-code-preview

Compare your screen unit with these pictures: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display

**Comment by ghost** [comment]
My Ender 3 V2 screen is DACAI and it shows the qrcode below the print information. I will post pictures of her.
![IMG_20220702_152028](https://user-images.githubusercontent.com/62189156/180898039-8ad86205-298f-4d5c-bb85-3cf09a17a16c.jpg)
![IMG_20220719_204316](https://user-images.githubusercontent.com/62189156/180898041-8bbabe44-e0a4-4477-852f-108d9baf3ae1.jpg)

**Comment by pacocatech** [comment]
thanks
