### ISSUE TITLE
Missing library when compile from the sources in the release

### ISSUE THREAD

**Issue by mriscoc** [mriscoc/Ender3V2S1#25]
If you got an error when compiling like this:
![image](https://user-images.githubusercontent.com/2745567/152587285-7dd322f3-f918-45bc-8447-22500ce87083.png)

Please download the missing library from the repository or compile using the latest sources from the repo:

![image](https://user-images.githubusercontent.com/2745567/152587485-3d119c9a-b4e0-4921-acfa-764d8302577c.png)

You will get a successful compile

![image](https://user-images.githubusercontent.com/2745567/152587793-b650b31d-4a3e-4acd-9782-eedea154980f.png)

**Comment by mriscoc** [comment]
Fixed in the last release and repository

**Comment by ImUrX** [comment]
You can pin issues (a maximum of 4) so they appear at the top of the search bar in the issues tab, so you dont need to have these issues open.
![image](https://user-images.githubusercontent.com/3698237/161889461-e71b9491-ae21-4e0a-bfc9-07ebb1085dd0.png)

If you already knew this sorry to bother lol

**Comment by mriscoc** [comment]
Thank you! I don't know that.
