### ISSUE TITLE
M73 Does not display status on screen from Octoprint

### ISSUE THREAD

**Issue by Madmike-1337** [mriscoc/Ender3V2S1#259]
**Is your feature request related to a problem? Please describe.**
This firmware is fantastic, and this is a very minor ask: M73 used to update the status bar with percent complete from Octoprint. It was working in my previous firmware.

**Describe the solution you'd like**
Implement M73 updates to the screen to allow status checks without opening an app or browser.

**Describe alternatives you've considered**
Just look at OctoApp or open a browser window anywhere on the LAN

**Additional context**
This firmware build is way better than my previous. I'm confused about the lack of this functionality or if I'm trying to implement it incorrectly. It's a very minor thing.

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint
