### ISSUE TITLE
Flow Setting is resetting to default value when the printer turned off and on

### ISSUE THREAD

**Issue by anilgunduzz** [mriscoc/Ender3V2S1#260]
Hi,

I recently noticed the Flow setting is turning back to default value when the printer is powered off and on. Is this a bug?

Board: BTT Skr Mini E3 V3
Firmware version: 20220716
Precompiled: Ender3V2-SKRME3V3-BLTUBL-20220716.bin

**Comment by mriscoc** [comment]
That is normal behavior, flow, speed, etc. are only temporal corrective parameters when your slicer or printer settings are not correct.
