### ISSUE TITLE
HS mode for CR touch recomendation may need updating

### ISSUE THREAD

**Issue by hayden-t** [mriscoc/Ender3V2S1#265]
In several wiki pages it is recommended to disable HS mode.

Ive found however that on my ender S1 pro F4 probe test or leveling fails without it.

thanks

**Comment by mriscoc** [comment]
HS mode must be disabled for mesh leveling bigger than 5x5 points.

**Comment by hayden-t** [comment]
why you dismiss me ?? HS mode fails probe usage any size, with hs mode on i can do 9x9 mesh no problem

**Comment by mriscoc** [comment]
> why you dismiss me ?? HS mode fails probe usage any size, with hs mode on i can do 9x9 mesh no problem

That behavior is very particular, I don't have any report about that. If non HS mode is failing for you that could be a indication of hardware failure and not a firmware failure. However, if the HS mode is working for you, that is better, but always check the resulting mesh leveling.

**Comment by hayden-t** [comment]
HS mode works, the mesh matches the contour of my plate as witnessed by printing and using metal ruler

**Comment by hayden-t** [comment]
https://github.com/mriscoc/Ender3V2S1/issues/195#issuecomment-1201521918

"They seem to have HS mode enabled too"
