### ISSUE TITLE
Media Init Fail message

### ISSUE THREAD

**Issue by G1t1t** [mriscoc/Ender3V2S1#266]
I am getting a Media init fail message, if I open the Print icon without sd card inserted or Ifuse a micro sd card extension. Media Init fail message will not clear without powering down the printer? 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
Firmware version and release date

**Additional context**

**Comment by cr08** [comment]
I'm seeing the same thing on my V2 (4.2.2 BLT). Doesn't seem to negatively affect anything, just a cosmetic glitch.

**Comment by mriscoc** [comment]
Without a memory card the printer can't initialize it before of list the files inside it.
