### ISSUE TITLE
Ender3V2S1/Configuration.h Y_MAX_POS  is beyond physical limits of Ender 3 S1 (P4)

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [mriscoc/Ender3V2S1#267]
**Describe the bug**
Y-Max is outside physical capability of Ender 3 S1 (P4).

**To Reproduce**
1. Attempt to go to a Y value greater than approx. 178. 

**Expected behavior**
Endstop code should prevent system from going beyond limit.

**Version (please complete the following information):**
Universal 20220716

**Additional context**
Discovered issue when fiddling with Octoprint, Bed Leveling, and g-code using UBL. Platen attempted to go to Y 220 and made a gawdawful din and loosened the Y belt. Discovered that g-code pulled relevant working envelope from configs.

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
