### ISSUE TITLE
Make Menu Titles Centered

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#270]
In bold is the line to add to change to make the titles centered. I think this is an important change

file
proui --> **menus.cpp**
```cpp
void Draw_Title(TitleClass* title) {
  DWIN_Draw_Rectangle(1, HMI_data.TitleBg_color, 0, 0, DWIN_WIDTH - 1, TITLE_HEIGHT - 1);
  if (title->frameid) 
    DWIN_Frame_AreaCopy(title->frameid, title->frame.left, title->frame.top, title->frame.right, title->frame.bottom, 14, (TITLE_HEIGHT - (title->frame.bottom - title->frame.top)) / 2 - 1);
  else
**DWINUI::Draw_CenteredString(false, DWIN_FONT_HEAD, HMI_data.TitleTxt_color, HMI_data.TitleBg_color, (TITLE_HEIGHT - DWINUI::fontHeight(DWIN_FONT_HEAD)) / 2 - 1, title->caption);** //changed here
}
```

**Comment by mriscoc** [comment]
Thanks, but it's a matter of taste. I prefer uncentered menu titles.

**Comment by classicrocker883** [comment]
> Thanks, but it's a matter of taste. I prefer uncentered menu titles.

no problem

**Comment by classicrocker883** [comment]
@mriscoc 
This is the change I suggest for anyone who would like to choose either or
### _in Config_adv.h   --> Line 1375_

  //Change Title Menu Text to Centered
  #define TITLE_CENTERED  


### _in proui/menus.cpp   --> Line 50 under void Draw_Title(TitleClass* title)_


 #if ENABLED(TITLE_CENTERED) 
  DWINUI::Draw_CenteredString(false, DWIN_FONT_HEAD, HMI_data.TitleTxt_color, HMI_data.TitleBg_color, (TITLE_HEIGHT - DWINUI::fontHeight(DWIN_FONT_HEAD)) / 2 - 1, title->caption);

  #else
  DWIN_Draw_String(false, DWIN_FONT_HEAD, HMI_data.TitleTxt_color, HMI_data.TitleBg_color, 14, (TITLE_HEIGHT - DWINUI::fontHeight(DWIN_FONT_HEAD)) / 2 - 1, title->caption);
#endif

**Comment by mriscoc** [comment]
Thanks.

**Comment by mriscoc** [comment]
> @mriscoc This is the change I suggest for anyone who would like to choose either or
> 
> ### _in Config_adv.h --> Line 1375_
> //Change Title Menu Text to Centered #define TITLE_CENTERED
> 
I will to implement your contribution in a future version.
