### ISSUE TITLE
littl noise problem

### ISSUE THREAD

**Issue by Ice-Cue** [mriscoc/Ender3V2S1#275]
Hello, thank you for your effort.
the Ender3v2 (v4.2.2) runs really well with your firmware.

But I noticed one small thing. The stepper motors have now become audibly louder. What could be the reason?

up to now I have used the firmware provided by creality.

Thank you very much.
Caspar

**Comment by mriscoc** [comment]
Please check: https://github.com/mriscoc/Ender3V2S1/issues/229
