### ISSUE TITLE
Screen not refreshing properly when in z-axis offset mode

### ISSUE THREAD

**Issue by forReason** [mriscoc/Ender3V2S1#276]
**Describe the bug**
I often find myself adjusting the z-offset when adjusting bed level or changing build surface or for fine tuning/optimisation.
To do this I often open the menu to adjust z-ofset while still preheating so that i can pre set a value and fine adjust after homing.

However, when in the z-offset menu and the homing starts, the big homing screen will not go away after homing. the only way to bring back the screen is by going back (confirm with button press) then rotating the knob up and down in order to overwrite the homing screen with new list content. (the list is not big enough to 100% get the homing screen away)

**To Reproduce**
1. start a print
2. Click on 'Tune'
3. Scroll down to 'Z-Offset'
4. Enter Z-Offset adjusting menu before homing starts
5. Let printer heat and home
6. 'Homing...' screen wont go away and block screen

**Expected behavior**
Homing information goes away after homing is finished

**Screenshots**
can attach photos if required but i think it can be reproduced on any machine

**Version (please complete the following information):**
20220527

**Comment by mriscoc** [comment]
That was corrected some versions ago, please update your firmware version.
