### ISSUE TITLE
Have Sound(beep) disabled for button clicks, but leave enabled when printing (with Gcode) 

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#277]
When I disable sound, it disables it entirely.

I'd like it to just be disabled for button clicks - Menu navigation. 

Is there a way to leave it enabled when printing, say for Gcode to produce?

**Comment by mriscoc** [comment]
It is possible to mute menu clicks by editing the enconder.cpp file and commenting out the content of `Encoder_tick`:
```cpp
void Encoder_tick() {
  #if PIN_EXISTS(BEEPER)
    if (ui.sound_on) buzzer.click(10);
  #endif
}
```

**Comment by classicrocker883** [comment]
@mriscoc 
I commented out 
>**Encoder_Tick();** 

on line 88 in encoder.cpp
i didnt actually try commenting out 


> ```c++
> void Encoder_tick() {
>   #if PIN_EXISTS(BEEPER)
>     if (ui.sound_on) buzzer.click(10);
>   #endif
> }
> ```

### i also found a bug

file:  src/inc/Conditionals_Adv.h
line:  1028

it should be

 > **#ifndef LCD_SERIAL_PORT**

originally it is **#ifdef**
because the LCD serial port for ender3v2 and the voxelab aquila is defined as >> **3**

the warning shows up when line 105 is commented out in Configuration.h

>//#define NO_AUTO_ASSIGN_WARNING

**Comment by mriscoc** [comment]
The line:
```cpp
  #ifdef LCD_SERIAL_PORT
```
Is correct, see: https://github.com/MarlinFirmware/Marlin/blob/5b68a3f79b845c4c125c43cfd0d506073da6007e/Marlin/src/inc/Conditionals_adv.h#L1049

The line:
```cpp
#define NO_AUTO_ASSIGN_WARNING
``` 
Is there to avoid the warnings because `LCD_SERIAL_PORT` was defined automatically in Conditionals_Adv.h

**Comment by mriscoc** [comment]
This is not a firmware issue.
