### ISSUE TITLE
High speed extruding

### ISSUE THREAD

**Issue by davkvi** [mriscoc/Ender3V2S1#28]
Might be related to reboot.

sometimes when extruding the stepper has a speed similar to the x or y axis steppers. Happend when extruding 50mm after preheat pla.  grinds the filament down.

**Comment by davkvi** [comment]
Feature request. 

an extrude 100mm option in menu for calibration

**Comment by mriscoc** [comment]
Insert in your test g-code the FXXXX parameter to control de speed of the extruding, if not, you are using the last set feed rate.
https://marlinfw.org/docs/gcode/G000-G001.html
