### ISSUE TITLE
Ender 3 V2 Neo support

### ISSUE THREAD

**Issue by adrianocr** [mriscoc/Ender3V2S1#280]
I'm wondering if the new V2 refresh (Ender 3 V2 Neo) can be added to this project. It comes with auto leveling and some slightly upgraded internal bits too and a new screen but I think the mainboard is the same as the standard V2. It also runs a version of Marlin Firmware.

**Comment by mriscoc** [comment]
Test with the Ender3V2-422-BLTUBL firmware.

**Comment by adrianocr** [comment]
@mriscoc that actually worked great! The only concern so far is that I'm not sure I got the physical settings correct. Do you have any tips on how to find the correct values? Once again it seems that the V2 neo is so recent that a google search came up blank.

The firmware seems to start off at 230x230x250 but the V2 Neo is actually 220x220x250mm so I adjusted that and subsequently tried manually moving the axes around and came up with x min -26, y min -26, x max 218, y max 205, and z max 250. 

Additionally I had to manually set the prove offsets to x -21 and y (+)7 to set the prove right in the very center of the bed like the stock firmware does it. That's the correct approach, right? Or should it be off center like this firmware?

For anyone in the future that sees this: those values may be slightly incorrect.

**Comment by mriscoc** [comment]
Thanks for your report, XY MIN/MAX Position and other physical settings can currently be found only experimenting like you did.

**Comment by ssrshark** [comment]
Ender 3 V2 Neo now has made the thumbnail preview work on DACAI screen, It is very cool if you add this to your project. This is what of us have been waiting for.

**Comment by mriscoc** [comment]
> Ender 3 V2 Neo now has made the thumbnail preview work on DACAI screen, It is very cool if you add this to your project. This is what of us have been waiting for.

Are you sure that they are DACAI? I did receive reports that they are using fully compatible DWIN screens.

**Comment by adrianocr** [comment]
@mriscoc it does seem that my unit also has a DACAI screen but this firmware with the DWIN files (to the best of my understanding) works flawlessly too.

**Comment by ssrshark** [comment]
I owed Ender V2 Neo, the screen they used is DACAI, I update screen firmware with Private not DWIN.

**Comment by mriscoc** [comment]
> @mriscoc it does seem that my unit also has a DACAI screen but this firmware with the DWIN files (to the best of my understanding) works flawlessly too.

Is the Professional firmware showing the preview when you try to print this demo G-codes? :
[demo.zip](https://github.com/mriscoc/Ender3V2S1/files/9295457/demo.zip)

**Comment by mriscoc** [comment]
> 



> I owed Ender V2 Neo, the screen they used is DACAI, I update screen firmware with Private not DWIN.

Good to know. So, they updated the firmware for the DACAI screens, please test with the provided demo G-codes and Professional Firmware.

**Comment by ssrshark** [comment]
Professional firmware for 4.22 board, shown blank while preview on screen, we have to use their 4.2.2 firmware and the "Private" for screen which Creality privide to in order to make it work, I think if you check for it you would make it work.

https://www.creality.com/pages/download-ender-3-v2-neo?spm=..page_1934481.products_display_1.1&spm_prev=..page_1934087.header_1.1

**Comment by mriscoc** [comment]
Only binary files were published, we need to have the official sources or the API information for accessing the newly implemented functions on the DACAI new firmware.

The users of that printer can request to Creality to disclosure the Official source code for the Neo printer.

**Comment by adrianocr** [comment]
>The users of that printer can request to Creality to disclosure the Official source code for the Neo printer.

By email or is there a special request process or something? I wouldn't mind doing it.

**Comment by mriscoc** [comment]
> By email or is there a special request process or something? I wouldn't mind doing it.

Use all the channels as possible, mail to support, request in the [Creality repository](https://github.com/CrealityOfficial), etc.

**Comment by ssrshark** [comment]
I have contacted them via email couple day ago about the instruction how to generate thumbnail preview on screen, but they provided me with the useless instruction, but I have found that to generate preview thumbnail they use this slicer "
Creality_Print" "https://www.crealitycloud.com/software-firmware/software" there is an option in printer manager to generate thumbnail to Gcode.

**Comment by adrianocr** [comment]
@mriscoc so I'm having an issue where it seems I am incapable of getting the bed properly centered. Any tips?

I've set the bed size to 220x220 (even though if you actually measure it with something it is actually around 235x235) and I have manually tested all the end stops to come up with the X max and Y max, and manually centered the probe offsets by placing a dot in the direct center of the bed with a sharpie and then painstakingly centering the probe until it perfectly touches that center point (interestingly here the measurements I get with my caliper are off by 3mm on the x axis and a whole 11mm on the y axis). Auto home seems to work correctly and the device perfectly probes the direct center of the bed during homing.

However when I go print something the prints are always about 3-5cm left of center. I've tried prusa slicer and cura and manual gcodes. 

Any suggestions on what could be going on and how I could sort it out?

**Comment by mriscoc** [comment]
If auto home goes to the center, it is very possible that the problems are in the slicer settings. If you can send manual G-codes and your bed is 220x220, send `G0 X110 Y110` the nozzle will go to the center of the bed if the printer settings are correct; if not, first correct it by changing the XY MIN/MAX Position, then when it is right, start with the probe offset settings without change XY MAX/MIN Position.

Check the bed size in the slicer configuration, remove any offset.

**Comment by MarkforU** [comment]
You can make a center line on your bed, there's a file on Thingiverse to print a target. You adjust CURA to be center by going into Machine Settings and adjusting extruder in there for the amount more or less that you need to be on either the X and or Y Axis. That's where your adjustments take place for center printing. There's a YouTube video on this exact problem. I ran into it with Jyers and fixes it then, haven't paid attention to the new software and I'm using a printable area of 230x230mm which I set both in Cura and also the printer. I also limit my z-height also.

**Comment by DynaMight1124** [comment]
I came here because I have a S1 with a DACAI screen, I saw the V2 Neo had thumbnail support. I went to the Creality website and downloaded the V2 Neo firmware, I noticed it had the Private folder indicating a DACAI screen. I flashed the screen firmware and it flashed fine, the Professional firmware works fine. It had an actual firmware update called "firmware.zlib" which I hadnt seen before. I assume this is where the magic is. 

The thumbnails didnt work however but it does seem the screen firmware has been updated to allow it. It just needs people cleverer than me to work out how :)

**Comment by curather** [comment]
Tagging the link to Creality V2 Neo issue to get [Support the V2 Neo #1](https://github.com/CrealityOfficial/Ender-3V2/issues/1)

**Comment by mriscoc** [comment]
Please, can someone post here a file that the Neo uses to show the preview on the screen?

**Comment by adrianocr** [comment]
@mriscoc I'm not sure I understood correctly but here are the two files that come on the V2 Neo's SD card: 
[Archive.zip](https://github.com/mriscoc/Ender3V2S1/files/9472671/Archive.zip)

Both of those show a preview on the DACAI screen if you run the print via the Neo's screen.

If you open the files you'll see that at the top of the file there's the following block that seems to be what renders the image (base64 encoded, I believe):

```
; jpg begin 48*48 1254 1 47 500
; /9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
; HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
; MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAwADADASIA
; AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
; AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3
; ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm
; p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA
; AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx
; BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK
; U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
; uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5/oop
; QcEHrigD0L4aeGNF8Rw6h/aUTSSw424LYAI/2SO4NZz+ANQutTufsyR21j5reS0z5JTPHAyfzxXo
; 3gzUElhiFraQwPNbghEAVMEA9u4rfi0pFUB5wccYjBb9e1fPVcfVpVpu+9rLex3RoxlBHz7rXh3U
; NCm23UWYicJMnKN+PY+xrKr6S1iwhTQ73ZpxvH8ltsLnJdscAAAjrXhreBvE6QtK+jXKooySwA/r
; XoYPHxrRfO0mvPcxq0HB6HP0VasdNvtSlEVjZz3LnjEUZb+Vdro3wtvbyby9SvEsZVwXtyu6QA8j
; 2GR9a66uIpUl77sZRpylsjufBkdg/hXQZ4yn2sN5cq9zwcH8q6LUtQkgDJGvPHzAZ29cnHft+dcz
; pGiLpOpW0NqJWt7eTyyzjn657g1ra8zKRt6NnPH5V8xVjGda6d09fxPRi2oG1ZzlLeN7h9xBILxg
; c4JwQPyrm9UvrjRvB11bXeqPd3O2ZkuJ1CtjaSF4POP54FbCyJbaRC0h4SNSfc4rxzx74gOo3YtE
; fKqcvjoPQVeCwzrVbdL/AJCrVOSJ6F4I8XnUtAWCFo4LmLAdI0Az6/41qJaTSa6mobmk3IUkDDd2
; 4NeDaHrNzoWpR3ls5UqfmA7iu8vPiLC8Y/0y4lyPuICMfngV24jL5RqN0lpIxhXTjaXQ9PmlEYHn
; SpEAQfnYDoc9OtZl9rOlLuZ2afjG0fKv+NeRXXjeWQnybc/WR/6D/Gsa58Q6jcggyhFPZBj9etKl
; lMt5MJYldDtfF3jt5o/sdptTHAC9F+tebszO5ZiSxOST3oJLEkkknqTSV7FGhCjHlgjlnNzd2f/Z
; jpg end

; jpg begin 200*200 5914 3 197 500
; /9j/4AAQSkZJRgABAQEAeAB4AAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
; HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
; MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCADIAMgDASIA
; AhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQA
; AAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3
; ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWm
; p6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEA
; AwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSEx
; BhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElK
; U1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3
; uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD5/ooo
; oAKKKKACiiigAooooAKKKKACniKRl3CNyvqBXs+i+FrOz0+KSxslmYoCZym9iffuPpXWW66Utptm
; s5zPj+63X868mrmsYP3Y3OqOGb3Z800V7ze6BFqEchutOV4TnDSx4wP949/pXimsWsNlrF3bW5Jh
; jkIQnriuvDYuNe6S1RlUpOBRooorrMgooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACii
; igAooooA+ivBsyS6dbyROGUqMMpru0mkEWBI+PrXjPwwCyaOikupDsMo5U9favVEtX8sYvLkD03A
; /wBM18VmFJRrNXPXoSvBaGfr7fuHLN26k18163Ik2tXckbBkMhww6GvevFVsv2KRd8jFhjLyFv51
; z1h4Q0TT8GOySVx/HN85/XgfgK9LLq0MPTcnrcwxEHUlZHkllpOoaicWdnNMP7yr8o/HpXTWHw51
; GfDXlxDbL/dX52/Tj9a9PVQqhVAAHQClxXRUzGo/hVjOOHitzjB8N9K8gqbm78zH39y4z9MVxeu+
; FtQ0Jy0iebbZ+WdBx+Poa9oxTXjWRGR1DKwwVYZBFRSx1WDvJ3RUqEWtND59or0rxB8Porjdc6QV
; hl6m3Y/I3+6e306fSvO7q0uLK4a3uYXilXqjjBr16OIhWV4s5J05Q3IaKKK3ICiiigAooooAKKKK
; ACiiigAooooAKKKKAN/RvB+q61CtxCiRW7HAllbAP0A5NddYfDWxiw19dyzt/djGxf6n+VP8Gaw0
; OhW0UuXhXcuO6/MeldojJLGJImDoehFeLisVXjNxvZHZTpwauVfDtjbaXqElraRCKBdpVQSeo969
; Bi/1P4VxFlGyayZMfIyKM+4z/wDWrtYjiHJ9K8PGvmkmzso6KxynirmArnGSB+tVsVb19Fu3WNHH
; DAkg9gaq4ropv92kZy+JiYop2KMU7gNxRipY4pJW2xozt6KM1di0W9fBdFhHrI2P061MpxjuwSb2
; M7FZ2raHYa3b+VewhiB8sg4dPoa62PRIE5muWf2iXH6n/CrcdrZQ/wCrtUJ9ZDuP+FQsUoO8dyvZ
; 30Z86+JPCF54fH2gMJ7Jm2rKBgg9gwrnK91+Le6TwnnICpIpCgYA5x0/GvCq+lwGIlXo889zz68F
; CdkFFFFdpiFFFFABRRRQAUUUUAFFFFABRRRQBueG9RuINQitFYGGZsFW7HHUV6DZ301lLlDwfvIe
; hrzDRm261Zn/AKbKP1r0woHwO/bFedjIrm1W5vSbsdPa3UN7HviPzD7yHqKn5Ixk4rkI5JbaYOjF
; HHQivS9FW0u9MjuJbSN5SoJJJx+Wa8XExVFc26Oym+bQxVRnbailj6AZq7Fo19KATF5a+sh2/wD1
; 66BZTGu2ILGvpGoX+VQTTxxLvmlVB/edsfzrideT+FGvIupSj0OJeZ7rJ/uxLn9TVqOysYfuWwc+
; srbv06VXOqQscQRzXB/6Zpx+ZwP1pPN1CX7kUMA9ZGLn8hgfrUv2j+J/oNcvQ0fNZV2phF9EG0fp
; Vae7gg5nmRM/3mAzVY2Ukn/HxeTv/sodg/Tn9akhs7a3OYoEVj1bHJ/GpUYod2M/tJX/AOPe3nm9
; wm0fm2P0pu7UZf8Anhbj8ZD/AEH86t0U7pbILHgvxF1rULnxHd6ZLfSS2ls6hUIAG7aCTgDnkmuM
; r0fV/h9rGta9fagLi0jiuJmdNzsW2k8cAemO9Oh+EN5J9/UwP9y2Lf1FfVUcXhqNKMXJLQ8ydKpK
; TdjzaivVU+DjcbtQuD64tcf1qQ/B2MDm9vB/2xFV/aeF/m/MPq9TseTUV6BrXwyfT9MnvLTUPOMK
; GRo3j25UcnBz1xRXTSr06yvB3M5QlF2Z5/RRRWxAUUUUAFFFFABRRRQBZ09tupWrekyH9RXqDGXK
; iOJpM9ccYryqBtlxG3o4P619DeG9LW60xZioJLkV5mY1VSSkzow8XJtI55oDc2blkInhAZgR99Om
; fqD+n0rd8MajevG1jCsGI0yHkznGfQdav6zaJZLbXez5YG8uYD+KJuGH6/rWf4aga0168tmOTGjL
; n1wRzXjzqRq0W7f1/X5nWouM0jf+y3Mv+vvZMf3YQEH59f1p0Wn2kTblhUv/AH3+ZvzPNWqazbR6
; k8AV5/NLY3sgJCj+gpuXPQAfXmgEBsZy2Mmo53KW8rZxhCf0pJDHnzB3U+2MUoOeoINc5b67cC2S
; 3PlgqMCQrkn6mtHRdWGq20hdBHcQOY5kB4BHcexrWdCcU2yFNPQ06ZI4SJ3PRVJp1RyjdGU/v4X8
; zj+tZLco1LeLybeNANpVQDj6U8gnqaw/HN9fab4XuJNNJW7k/do4HKZBOR78Y/GvnCz8R61YagL6
; 31O7W53ZLmUtu/3gfvD2NdWDy6eLg6ikkZ1cQqTUbH1QRVa9O2zmOcHYQPrVbwzq58QeGbDVWQI9
; xFl1HQMCQ2PbINO1WXCrCOp+Zvp2/wA+1cSg41OR7pm1043Ry3iCVLbw/dE8KY9mPrx/LNFc98Rt
; SFvpDWyt8zDB+rcD9Mmivqcuot0uZ9TzcRP3rHjtFFFescoUUUUAFFFFABRRRQAdDmvp74eypcaL
; NEfvRy7vwYDH8jXzDXu/gDVhY3sCyNiK6hVCT/exlT/T8a8jOabqUNN0dWElaZ3ev2okt548cSRE
; D64//VXL6Id+sxT/APPaxBJ9SuEP/oNdjqFxFJDksAV5zXEeGnzeWo7rbSL+G8n+tfP4e/sZf1/W
; x3T+NHV1FuzI7HonH9T/AEqSq7MFtp2yONxNZJFsoaVcNcz3dw5wCRjPYc1j32tzXE7xJL5cbAhU
; GASPX1q5YEx6PfOOuCM/h/8AXrInthC8WBl5I1Y+vPIr0KcI87bMJN2Ro2ekre2LS27N5i9VJzz6
; U3w1GY9Uu2GRvQbh7g8fzNXPCk5h1draTKiVSCDxhhz/AI0zw9+9ur2f+8w/Uk1M5SSnF7afiEUt
; Gb9LGA1zApIGZVOT7HP9KbVW9P8AqR/tk/of8a4kr6GzOg1KGwvbR7a4uI9rdweQR0NeWar8LNKv
; tSMq30UKu2XaInn324Iz9DXWYoPAya3w8qmH/hyImoz+JGvpqaVomj2+n2cp8m2jCIMZJ/8Ark81
; kXl0FWW6m+uPU9hSquck4AAzk9hXM+IdTyuyMnA4Qf1p0KHPU7t7inO0TjviHG7abaXUm4tNKWJz
; wOoA/wDHT+GPWirXxZureG30TSYCN8UbyTAexESfpGT/AMCor6fAtugm/P8AM82t8bPMqKKK7DMK
; KKKACiiigAooooAK9P0py2k2bZ58lOn0Fea29tPdzrBbQyTSt0RFJJ/AV6Xp1tPZ6db21zH5c0aB
; XTIOD+FceMaska0jck1y9lt/KeTIK7S3cirvhSXfq8eD8ohcD+dYGARgjIrb8LH/AIncY9UYfpXk
; VoRjSlZHVBtyVzuKqOM2l2D33/yq3VWQAW90AezZ/wC+a8iJ1syLQAeHrskdd38hVLVADHYTr917
; ZRkeq5U/yq6vyeGJT6n/ANmArLFwsmnC2k6xMXib69R+ma7qafM5eZhLaxZbUlk1hb6PK5Ck8Yyd
; uCaveGkxZzP6yY/ID/GufzhT9DXT6Au3SkP95mP64/pRXio07LyQQd5GpVO6ObiMeisf1FW6py/N
; eMB2QfzNcUNzZjOnWlWPecntzz0HvUixYBdztUdWP8h61Qv75UQxoML/AHe59zWkU5OyJem5Bqmo
; JHEY0Py/q5/wrg9Xv/K3TuQdp3H8K2dQuS2Sxya4DxNfZXyVPLHn6V7WCw6uclaZjavqc+r6lLeT
; uzM3C57KOgoqjRXtJKKsjjbvqFFFFMAoop0cUk0gjiRnduiqMk/hQA2pbe1uLt9ltBLM/wDdjQsf
; 0ro9L8Aa7qRUvbi0jP8AFOcH/vnr/KvRtCt18PxLoc5XzIekmzZvJ55HrzXFXxsIK0PeZtCi3voj
; zK08EeILvBFgYlP8UzBMfh1/Sul0r4XSNKG1K63KP+WdsCSf+BEf0r1SxeDPlyRru7MRnNagAAwB
; gV49bNq2yVjqhhYbs5nSvDkGlQ+VYWMdup6t/E31J5NULyyi1CP7RAR5h5yOjfX3rta82tLx7SUl
; eUP3l9a58PKdRylfUuolGy6FZkaNyjghh1BrX8MHGuw+6t/KrFxaw6nbiaEgSY4b+hqv4fR4PEUE
; cilWG4Efga6ZzU6Uu9jNRtJHc1VcZjvB6k/+gCrNQEArcY6k8/XaK8mJ1sxp/l8MIOPmP/s2awhW
; 3fMP7DhhXl1ILAdhzWGK9Kjs/U55kUkbmUOZPkUcIB1PqTXaaSuzSrcf7Ofz5rj3+7+Ndtar5dnC
; n92NR+lZ4t+6kOktWTVBFF5t2x3YBOS391QOTT5XwuB1NErC0tDu4Zxub2XsPx6/lXEvI2ZT1S8y
; wC/KAMKP7o/xrmrufGeatXdzuZmJ5Nc/f3YUHmvSw9Hoc85Gdqt6I0Yk4Arzq8uTdXTynoTx9K19
; f1IyuYEb/erBr6ChT5InDOV2FFFFbkGjYaDqupqGs7CeVDwHC4X/AL6PFdNp3ww1q8Yee8UA7quZ
; G/IcfrXoukXsF5p8TW4VNigbFHC8cY9q7/SryG6swRsR4xiQcAD3+lfPYvNa9P4Y2O6lhoS3Z5hp
; PwbtIyr3nmznv5r7F/Jef1rutL8F6ZpaBYYY4x3ESBM/U9TWxJqtjE4Vpsk9NoPNUpvEUS8QQlvd
; jgV5FTFYuvu2dcadKGxpQWUFuP3MSr7gc/nXmfjyI23icv2mhR/5r/7LXUz63ezZAcRj0UVxvivf
; JLbTOzMSGUknPp/9etsBSnCteT3IryThZE+kaqJVW3nb5+iOf4vb611EF/sj2ygsR0I715lDJskX
; PTNeq2/2c2UUgVNxA5xzW+Npxg07bkUZNkP22V/9VCT7nmsuHw7EpyYR/wADbP6VuGZewNMMzdgB
; XJGco/DoauKe5Wi0qOIYyFHoi4qOa1hg1LT5EX5zKV3E842mrRdj1JqncH/T9O/67/8Asppxcm9X
; 3/ITsjVqBetz/vf+yipqiXGZsf3uf++RWSLZkYrPurHrJEPqv+FaWKUKW6AmuyMnHVGLVzmypaRE
; 7k4ruiQorHTRjcXqTDOVIOxBnJB71tC2CndNJz/dQ5P59BUYipGVrFQi0MhTfI0sg+ROo9T2H+fe
; sbWL/dKybs4OWPqav6rq0VtD5aFQ4HyoDnB9TXEXt994lsk9arDUXN8zJqSS0C9uwAea43XNXESF
; VOXPAFT6vq6wox3c9hXF3E73Epkc8n9K+hw2HtqzhqVL6IjZi7FmOSeSaSiiu4xCiiigDrvBuvzW
; d2tsWz/zzz3HdTXq0OowvbJOpfy5PkJUZMZPr/n0r59jkaKRZEYqynII7GvUvDfiAeWl3Cx2tgTx
; A8g+orysfhlL34o6aFS2jPTvKjnhjlJDvGPkIHt1rFtSwEkLkl4mI57jqP8APtV6DU5JIo2R0eE8
; jCAZH1xmoJ4CL4XMePKkXDc8+39a8KCcbpna9dULiq95ZxXtu0Mo4PQjqp9RVmiqUmndCtc4K9sp
; bG4MUo91bsw9a9E019+lQt/sis6/sIr+3MUnB6qw6qauaYPs2nJBKw3oMcd61xFX2tNd0TTjyyZc
; zRURnX+EE03zJHOFXGfxrkszW5Nmqd0cXun4/wCfgfyNXVsLt/vKyj/bO3+dTJpkS4MkoPsi5/U4
; oU4x6is2K0qL1YVFF5jySiKNnLtkADPYD+lWHaxtBlwgPrK2T+XT9Kp3HiK3Rdke5x2Cjav+fwqY
; pv4UNu25NHpRHMrIn1OT+Q/rVjyrS2Tc43Ad5DtX8h/jXOz+IJ3yE2xj2GT+tZc+oM53O5ZvUnNb
; LD1JfEyXOK2OqutdgiQpGd4/uoNq1z99rs8oIDiNfROP1rFnvuvNZVzfcHmuyjg4roYzqsuXd/gH
; muZ1TV1iRiWqDUtVESklua5a4uHuZN7n6D0r2aGHS1ZyzqXC5uZLqUu5+g9KhoortMQooooAKKKK
; ACtHR9Tk028DA/I3DCs6ik0mrME7HsWhawkO1WkDW0mDkH7hPf6f57V12CCCB1GfqK8Q8P6sbd/J
; lJMZ6jP617F4b8UWK2/2aWR1MfADJuBHYjGeorwMfhpU3zRVzuoVFLRmgAWOFUk+1TrY3Tf8sHA9
; WGB+ZqSTxJaqDseVh6KuB+uKoy+JgP8AV2/4s9eYo1XtE6bxXU0F0uX+OSNP+BZ/lmpV06BfvyOx
; 9FUD9f8A61c7L4ju2zsMcf8Aurn+dUJtVupfv3EhHpuwPyq1h6r3diXOKOzc2FqPnEa+8r8/0/lV
; eXxDZwAiOQn2hTb/AIVxDXHvULXHvWkcEn8TuS6vZHVT+J258mFR7uc/pWbca7dzZBnZR6J8v8qw
; mn96iac+tdMMLBbIh1GzSe7JJJbJNQNde9Z7TH1qJpTXQqSM3Ivtde9V5bo+tU3m2jJOB71l3es2
; cOQZ1ZvRPm/lW0KN9iHI0J7rg81g6jqixAjOW7AVn3muSTZWBdi/3m5NZLMzsWYkk9Sa7adHl3MZ
; TuPmmeeQu5yf5VHRRXQQFFFFABRRRQAUUUUAFFFFAD4Znt5kmjba6EMp9667SdaSS7Ro18tCMFP7
; h9B7Zzj24rjqkgmaCUOh5FROmprUak0ewx3G+MEGhpa5/RNTS7tlIbJ6EelaU93BbrmaeOMersBX
; jypOMrHWpXVy00tRNIaxbjxNpcGR9oMh9I1J/XpWXP4zj6W9oze8jY/QZrWOHm+hLml1OqaQ1GXN
; cNP4p1KXOxo4h/sJn+eazZ7+8uc+dcyuD2LHH5VvHCS6kOqjv7jUbS3z5tzEh9Cwz+VZk/ifT487
; DJKf9lcfzxXFUVtHDRW5DqM6OfxZIciC2Vfd2z+gxWdNr2ozZ/f7B6IoH/16zaK1VKC2RLk2SSzy
; zHMsrufVmJqOiitCQooooAKKKKACiiigAooooAKKKKACiiigAooooAVWZDlWIPsaCSxySSfU0UUA
; JRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB//2Q==
; jpg end
```

Edit: I can confirm that is base64 encoded. Screenshot: 
![Base64 to Image Decoder Converter 2022-09-01 at 3 21 13 PM](https://user-images.githubusercontent.com/7603338/187995532-d254feee-0392-4d5a-92ee-73cd92a5ddca.jpg)

**Comment by mriscoc** [comment]
Interesting, thank you!
We also use jpg encoded in base64.
So, we only need the correct API function to show the image in DACAI screens.

**Comment by orifer** [comment]
![IMG_20220902_165111](https://user-images.githubusercontent.com/7762786/188193756-be9ece74-2dee-4f8c-897b-853f4c72c0a1.jpg)
![IMG_20220902_165127](https://user-images.githubusercontent.com/7762786/188193757-7698ba51-6bdb-41e0-83ea-a92176bc7ba5.jpg)


So I installed the Neo firmware + screen and tried to load these files in my V2 with a DACAI screen and the thumbnails loaded. However, it's not loading when trying with a generated one with the python script. I saw some slight changes on the jpeg base64 encoding, but couldn't figure it out.

**Comment by mriscoc** [comment]
I can now also open the preview of the Neo files but only with DWIN displays:
  
<img align=left src="https://user-images.githubusercontent.com/2745567/188259217-5bf30e57-37c7-46f6-8111-eb2e70acfa04.jpg"></img>![chuan](https://user-images.githubusercontent.com/2745567/188259220-3d3ca71d-7f74-49c1-ac4f-8ac33bca00e1.jpg)
  
We need the DACAI API to enable preview on that screen.

**Comment by curather** [comment]
firmware.zlib does upgrade the firmware on the DACAI display.  I have a ender 3 v2.  I tested with the two different gcodes(one from manufactorer and other from cura), neither worked so it definitely has to do with the api calls to the display.
