### ISSUE TITLE
Firmware not installing 

### ISSUE THREAD

**Issue by AllenSlaghuis** [mriscoc/Ender3V2S1#284]
Hi. I have tried to load the firmware. On my ender 3 S1. And it seems not to update the firmware. Used two different sd cards. And still would not load. Please help

**Comment by mriscoc** [comment]
Check: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-install-the-firmware

**Comment by mriscoc** [comment]
No more user feedback.
