### ISSUE TITLE
Ender 3S1 Bed leveling with 9x9 mesh fails if HS mode is active

### ISSUE THREAD

**Issue by od1001** [mriscoc/Ender3V2S1#285]
Ender3S1-F1-20220716.bin hat einen Bug. Bed-Leveling mit 9x9 Mesh funktioniert nicht. Vor Probe Point 67 wird der Taststift eingefahren, sodass die Abtastung fehlschlägt. Das Bed-Leveling wird dann wiederholt. Sieht nach Speicherüberschreiber aus.

Ender3S1-F1-20220716.bin has a bug. Bed leveling with 9x9 mesh does not work. Before the Point 67 trial, the tape pencil is run in so that the scanning fails. The Bed leveling is then repeated. Looks like storage overwriters.

**Comment by mriscoc** [comment]
Check disable HS mode: https://github.com/mriscoc/Ender3V2S1/wiki/3D-BLTouch#notes-about-crtouch  

![probe-settings-1](https://user-images.githubusercontent.com/2745567/184405156-5e5bcc17-cfe0-440b-a043-04cf8cc72aaa.jpg)

**Comment by od1001** [comment]
I have an ender-3 s1 with no BLTouch.

**Comment by mriscoc** [comment]
Please search about CRTouch and BLTouch comparisons
