### ISSUE TITLE
S1 Pro filament sensor does not work

### ISSUE THREAD

**Issue by acevalsl** [mriscoc/Ender3V2S1#288]
**Describe the bug**
Cuando instalo el Firmware nuevo el sensor de filamento deja de funcionar.

Tenga o no tenga filamento la impresora sigue funcionando. Cuando cargo otra vez el Firmware original funciona perfectamente.

Tener en cuenta que la S1 pro lleva un sensor de filamento óptico.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
Ender3S1-F4-T13-20220717
Ender3S1-F4-20220716

**Additional context**

**Comment by acevalsl** [comment]
https://user-images.githubusercontent.com/22813078/184509500-881ae516-ab06-4999-b00b-6f78937ccd8f.mov

**Comment by mriscoc** [comment]
Did you check your runout distance?
Use the End-stop diagnostic to set up your runout sensor. The image is when there is filament inside of the sensor:
![endstops-diagnostic](https://user-images.githubusercontent.com/2745567/184510013-fe99c0a1-c34d-4473-9448-d87e7e986185.jpg)

**Comment by acevalsl** [comment]
Hola, en esa pantalla veo que tanto cuando tengo el filamento como cuando lo quito responde perfectamente.

Sin embargo luego cuando esté imprimiendo lo que te lo ponga siempre imprime.

Lo que me ha llamado la atención es que el z_min aparece Triggered y no sé por qué?
He intentado pasarte un vídeo pero dice que es demasiado grande.


Hello, on that screen I see that both when I have the filament and when I remove it it responds perfectly.

However, when you are printing what you put it on, always print.

What has caught my attention is that the z_min appears Triggered and I don't know why?


I've tried to send you a video but it says it's too big.

**Comment by acevalsl** [comment]
https://user-images.githubusercontent.com/22813078/184510413-fe79c48c-c941-4af9-8c30-99158f052565.mov

**Comment by mriscoc** [comment]
> IMG_4940-1.mov

The firmware recognizes your sensor correctly, please read about runout distance, or look for G-codes disabling the runout sensor.

**Comment by acevalsl** [comment]
Activated the code M 412 S1 to test it by typing it after the code M420 in the gcode.

If you have any idea, because I don't know how to activate it, I thought it was with that code.

**Comment by acevalsl** [comment]
I just tried M412 D10 and the sensor has worked. Thanks a lot

**Comment by acevalsl** [comment]
https://drive.google.com/drive/folders/1-cpvnjTAg99hUYbaq6m5Ycl3gjZOLGy4?usp=sharing <https://drive.google.com/drive/folders/1-cpvnjTAg99hUYbaq6m5Ycl3gjZOLGy4?usp=sharing>



Video
