### ISSUE TITLE
Bed leveling off

### ISSUE THREAD

**Issue by davkvi** [mriscoc/Ender3V2S1#29]
#### About the printer

**Version:** [Ender3v2-422-BLTouch-20220202.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20220202/Ender3v2-422-BLTouch-20220202.bin)
**Settings:** [Imgur album](https://imgur.com/a/VmAirX8)
**Mods:**
- Changed [mounting plate](https://i.imgur.com/dbFfV7F.png) for hotend to the ender 3 pro
- Changed [Fanduct](https://www.thingiverse.com/thing:3721746)

![Example drawing](https://i.imgur.com/2wqdvcP.png)

The red line illustrates where the probe and hotend starts.
The line is aprox 8.5mm off. It might be related to chainging the mounting plate. That does not explain why it levels all the way in the front of the bed.

**Comment by mriscoc** [comment]
EDIT: Please follow this guide: https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides

~Change your home offsets, verify your bed size~

**Comment by davkvi** [comment]
> Change your home offsets, verify your bed size

Home offsets are changed.
![https://i.imgur.com/YwuWBEb.jpeg](https://i.imgur.com/YwuWBEb.jpeg)

The bltouch probes the center off the bed.

**Comment by davkvi** [comment]
![Problem baby](https://i.imgur.com/TEkjBpC.png)

This image illustrates the issue now.

The x axis can be solved but the y axis is off no matter what the home is set too. I tried -50 and +50. Did not change the result apart from where the ABL probed initially to find the z height. 

Two issues i am seeing.

Probe does not use actual center for probe point. Might be the probe offset is not respected or compensated for.

**Comment by mriscoc** [comment]
What happens if you increase your probe margin?

**Comment by davkvi** [comment]
> What happens if you increase your probe margin?

![https://i.imgur.com/K4xSpMi.jpg](https://i.imgur.com/K4xSpMi.jpg)

Increasing the probe margin moves the probing further up and further inn.

**Comment by mriscoc** [comment]
Then there is a problem in the mesh points definition when Home Offsets are different to zero. I will investigate but I think that it could be a problem with the Marlin core.

**Comment by mriscoc** [comment]
Edit: **C12** was deprecated in favor of **G30**

There is a custom g-code that could help us to debug this issue, the C12 g-code allows to get the bed z-value of a given X, Y point with a probe. For example
```g-code
C12 X10 Y10
```

**Comment by mriscoc** [comment]
Would it be possible for you to test with the current bugfix version of Marlin? I will try to test but I have a different setup.

**Comment by davkvi** [comment]
> Would it be possible for you to test with the current bugfix version of Marlin? I will try to test but I have a different setup.

Will see if i can get around to compiling it for upstream Marlin :)

**Comment by mriscoc** [comment]
Please set home offset to 0 and move those values to X_MIN_POS and Y_MIN_POS

**Comment by davkvi** [comment]
> Please set home offset to 0 and move those values to X_MIN_POS and Y_MIN_POS

I cant find the x_min_pos and y_min_pos in the menu. I can compile the firmware if needed but would like to have access to the proui then.

**Comment by mriscoc** [comment]
The proui library is in the repository. https://github.com/mriscoc/Ender3V2S1/issues/25 
In the next version I'm adding the possibility of edit also the XY minimums in the physical settings menu.

**Comment by MichaelSordje** [comment]
maybe i have a similar problem... with this firmware bed tramming on right front and right back does nothing.
the printer dont want move and test. manually set x / y it is working.

i downgraded to version Ender3v2-422-BLTouch-20211121. here is all working

**Comment by MichaelSordje** [comment]
PS: on my ender 3 - s1 the firmware is working fine, only my s2 dont like it

**Comment by mriscoc** [comment]
Please test with this pre-release version, do not change Home Offsets, use Advance / Physical Settings / X/Y Min pos

[Experimental-Ender3v2-422-BLTouch-20220209.zip](https://github.com/mriscoc/Ender3V2S1/files/8042815/Experimental-Ender3v2-422-BLTouch-20220209.zip)
[Experimental-Ender3S1-20220209.zip](https://github.com/mriscoc/Ender3V2S1/files/8042817/Experimental-Ender3S1-20220209.zip)

Also check your **probe margin**.

**Comment by mriscoc** [comment]
Fixed in the last release

**Comment by classicrocker883** [comment]
@davkvi have you fixed the issue?

because if its like the last comment, decrease **mesh inset min**, and increase **mesh inset max**. that will maximize the area, if you need to make it smaller then about increase the **min** and decrease the **max**.

as for the probe. change the probe offsets. changing the X value moves it left or right.
changing the Y value changes it front to back.

the offset of the probe point should match the center point if you do a manual tramming.

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
