### ISSUE TITLE
Building a UBL Mesh on BTT SKR Mini E3 V3 board with disconnected thermistor results in printer hang

### ISSUE THREAD

**Issue by haqbany** [mriscoc/Ender3V2S1#290]
Auto Build Mesh on  BTT SKR Mini E3 V3 board No Response 

**Describe the bug**
after installing ( Ender3V2-SKRME3V3-BLTUBL-20220816 ) on  BTT SKR Mini E3 V3 board 
Auto Build Mesh After moving to home No Response and screen message ( Please wait....) than when press cancel 
this operation will not work or respond any more till you restart the printer with same result .

Traming working ok 
Z probe wizard ok 

**Version (please complete the following information):**
Ender3V2-SKRME3V3-BLTUBL-20220816

**Additional context**
Auto Build Mesh After moving to home No Response and  blue light

**Comment by haqbany** [comment]
as will nothing respond after the update , and the printer make little strange fan sound !?

**Comment by mriscoc** [comment]
Is the previous version https://github.com/mriscoc/Ender3V2S1/releases/download/20220527/Ender3V2-SKRMINI-BLTUBL-20220527.bin working for you?

**Comment by haqbany** [comment]
Yes was working fine but after the update this happened

**Comment by mriscoc** [comment]
Could you test again please to discard problems with hardware?

**Comment by haqbany** [comment]
Hi Miguel , 

when i use > Tilt Mesh , it working ok 
Auto Build Mesh no response 
Bed traming ok 

here is a video link 
https://youtu.be/01dDVfYa9BE
Best Regards,
Rashid

**Comment by haqbany** [comment]
also i would like to contribute with translation in to arabic i know little about programing but i'm sure i can do the translation if you're interested. as will graphic design .

**Comment by mriscoc** [comment]
From your video, something is not ok with your thermistors and/or heaters. The error is in the bed pre-heating.
In Advanced Settings / Mesh leveling / Set bed temperature to 0 and try again.

**Comment by haqbany** [comment]
thermistors is not connected, i have Set bed temperature to 0 and try again same thing 
.

**Comment by mriscoc** [comment]
> also i would like to contribute with translation in to arabic i know little about programing but i'm sure i can do the translation if you're interested. as will graphic design .

The DWIN/DACAI screens have a very limited charset mainly English and Chinese.

**Comment by mriscoc** [comment]
> thermistors is not connected, i have Set bed temperature to 0 and try again same thing .

It is difficult to predict what will be the behavior when the thermistor is disconnected, but I expected to have a runaway thermal alert.

**Comment by haqbany** [comment]
Thank you , for the update you are right i had replace thermistor and thing working great

**Comment by haqbany** [comment]
Can you make the firmware compatible  with touch screen from big treetouch ? many people has has purchased this screen but the firmware from them is horrible , if i need to use your firmware now witch in my opinion the best so far I will have to go back to the old screen. If you can do that I we all appreciate it   
the screen link
https://biqu.equipment/collections/lcd/products/btt-tft35-e3-v3-0-display-touch-screen-two-working-modes

**Comment by mriscoc** [comment]
Sorry, but touchscreens are totally different from the screens that I have.  I only code for hardware similar to the one I have.

**Comment by Nbrooks639** [comment]
> Can you make the firmware compatible with touch screen from big treetouch ? many people has has purchased this screen but the firmware from them is horrible , if i need to use your firmware now witch in my opinion the best so far I will have to go back to the old screen. If you can do that I we all appreciate it the screen link https://biqu.equipment/collections/lcd/products/btt-tft35-e3-v3-0-display-touch-screen-two-working-modes

you can hook up a ender v2/s1 screen to the skr board, it also just got even easier because BIQU made a cable. and the best part is that the PROUI works on it!!!

https://biqu.equipment/products/mini-e3-connecting-cable-for-ender-3-v2-display-screen?_pos=4&_sid=ff81c529c&_ss=r

![image](https://user-images.githubusercontent.com/100983669/185934577-3ba53752-908f-4ab5-a7b8-ec2bb087ec42.png)

**Comment by haqbany** [comment]
Hi ,yes it was working just fine
Regards
