### ISSUE TITLE
Activate leveling (use mesh) sticky (saved to config) and/or available in Tune menu during print.

### ISSUE THREAD

**Issue by t-ihmels** [mriscoc/Ender3V2S1#291]
I'm always frustrated when I start a print and realize that the auto leveling isn't active because it's old gcode or the slicer didn't have the gcode additions set (more than once slicer, slicer updates, etc).

What I'd like to see is the ability to store the state of auto leveling.  When I set it "on" in the menu I want it to be activated when I restart the machine .  I would also like to be able to control it from the Tune menu available during the print . (Depending on how it's architected it may not be practical to switch this during a print).

The only alternatives I see are to switch to another firmware that supports this (if any) or create a pull request and do it myself. :P

**Comment by mriscoc** [comment]
Sorry, currently the recommended way to enable leveling is using the G-code `M420 S1` (or G29 A for UBL). You could compile your own version with `RESTORE_LEVELING_AFTER_G28` enabled but you have to manually disable leveling before to do a tramming, z-offset and other calibrations.
