### ISSUE TITLE
Firmware update take too much time

### ISSUE THREAD

**Issue by hkpmatt** [mriscoc/Ender3V2S1#293]
I have updateto mm and bought a 3d touch and try to update to blt version.
my board is 4.2.2 and when the sd card is insert and the printer is turn on.
it pid keep stay blank and wont update the firmware.
any ideas why it happen?

**Comment by ghost** [comment]
> I have updateto mm and bought a 3d touch and try to update to blt version. my board is 4.2.2 and when the sd card is insert and the printer is turn on. it pid keep stay blank and wont update the firmware. any ideas why it happen?

test it by changing the file name because it doesn't have to be a different name from the ones you've used before

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/How-to-install-the-firmware

**Comment by mriscoc** [comment]
No more user feedback.

**Comment by hkpmatt** [comment]
I tried to format the SD and sometimes it still get blank
