### ISSUE TITLE
When octoprint is connected, it gives error code M112.

### ISSUE THREAD

**Issue by onur94** [mriscoc/Ender3V2S1#296]
**Describe the bug**
When printing starts while octoprint is connected, it gives error code M112.

**Screenshots**
https://ibb.co/2MLz5L6
https://ibb.co/HCRNhXM

I connected it to the octoprint to monitor temperature and percentage values. After the bed and nozzle reached the required temperature, I started printing. As soon as the nozzle touches the bed, it gives M112 printer killed error. It didn't do this in the previous version.

**Version (please complete the following information):**
20220816

**Comment by DokuKaefer** [comment]
See here under Error Handling:

https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint

**Comment by mriscoc** [comment]
Please read the Wiki: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#error-handling

**Comment by onur94** [comment]
> Please read the Wiki: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#error-handling

I fixed it from where you pointed, thanks.
