### ISSUE TITLE
HAS_PROBE does not exist

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#306]
**Describe the bug**

**To Reproduce**

### lcd\e3v2\proui\dwin.h
_line 230_

**originally**
#if !HAS_PROBE
  void HomeZandDisable();
#endif

### updated to

#if !HAS_BED_PROBE
  void HomeZandDisable();
#endif

//there is no such define HAS_PROBE
so it should be HAS_BED_PROBE

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
Firmware version and release date

**Additional context**

**Comment by mriscoc** [comment]
Thanks for the bug catch.

**Comment by classicrocker883** [comment]
@mriscoc 
im working on a few things, like adding the option for the BED_SCREW_INSET which changes the position where the nozzle or probe goes when leveling / tramming the corners.
also having the LCD_BACKLIGHT_TIMEOUT enabled with a menu option to change the value
is this a feature you look forward to having?

i am having trouble getting the lcd backlight timeout to work, i posted the issue under marlinfirmare.
so far it does work well just having the issue of resetting the timeout timer.

**Comment by mriscoc** [comment]
You don't need to set the bed tramming points over the screws positions, it is better at the mesh corners, that minimizes the mesh compensation values.

**Comment by classicrocker883** [comment]
@mriscoc 
the reason is because I saw [this video about it](https://www.youtube.com/watch?v=aMMYVVKzvO8)


![Screenshot from 2022-08-25 07-27-14](https://user-images.githubusercontent.com/18502096/186652751-e5474ccd-ad98-4823-bac0-e4cd4bad74e7.png)

**Comment by mriscoc** [comment]
> @mriscoc the reason is because I saw [this video about it](https://www.youtube.com/watch?v=aMMYVVKzvO8)

The only case when you need to put the tramming point exactly over the screws is when you know the exactly screw thread, then enabling ASSISTED_TRAMMING can give you how many degrees or minutes you must turn your knob, but in the reality turn 7° 15" don't says too much but just a small turn.

**Comment by classicrocker883** [comment]
thats good to know, i always wondered what that value was for if u have an M3 or M4 screw, thanks
