### ISSUE TITLE
Clarification. This will not work for the Pro variety with the touchscreen, correct? Thank you ahead of time. Are there any modifications I can make to the Pro to get this to work? End goal full support of octoprint.

### ISSUE THREAD

**Issue by wtstreetglow** [mriscoc/Ender3V2S1#313]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
Firmware version and release date

**Additional context**

**Comment by mriscoc** [comment]
Use discussion page.

**Comment by wtstreetglow** [comment]
I apologize for that. I will add it there shortly.
