### ISSUE TITLE
NOZZLE_PARK_POINT doesn't work in Configuration.h file

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#316]
### (Configuration.h line 2256)

```
#define NOZZLE_PARK_POINTS { { 0, 220, 40 } }
```

changed definition by adding an S and {}

### (proui.h line 44)

```
#define DEF_NOZZLE_PARK_POINT NOZZLE_PARK_POINTS
//{0, 220, 40}
```

removed the arbitrary value to the referenced one with added S

**Comment by mriscoc** [comment]
What file is config.h? Maybe it is Configuration.h? What bug does this change fix? please elaborate.

**Comment by classicrocker883** [comment]
yea configuration.h sorry about that it's less text to type

**Comment by classicrocker883** [comment]
so if you wanted to change the park point values in the configuration file, it doesn't actually change them because it's not actually being called by `DEF_NOZZLE_PARK_POINT`
if you see those values are arbitrarily put in proui.h

so what this does is call for those values if u want to change them in the configuration file, otherwise it is pointless and does nothing

**Comment by classicrocker883** [comment]
it may not need the S add and just be defined as `NOZZLE_PARK_POINT`
I havent tested that, Im don't fully know C++/C

**Comment by mriscoc** [comment]
You need to do these changes:
```cpp
// In configuration.h:
#define NOZZLE_PARK_POINT { 0, 220, 40 } 

// In proui.h:
constexpr xyz_int_t DEF_NOZZLE_PARK_POINT = NOZZLE_PARK_POINT;

// In dwin.cpp
PRO_data.Park_point = DEF_NOZZLE_PARK_POINT;
```
I'm going to implement them in the next version.

**Comment by classicrocker883** [comment]
@mriscoc hey BTW if i recall correctly, there is a typo in language_en.h

i think its MSG_NOOZLE....ect 
instead it should be NOZZLE

**Comment by mriscoc** [comment]
It is MSG_NOOZLE_CLEAN but I'm not using that.

**Comment by classicrocker883** [comment]
that fix worked great thanks for that.

**Comment by mriscoc** [comment]
Fixed in latest version.
