### ISSUE TITLE
platforms.h compile problem

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#322]
as you can see this does not work

platforms.h line 40 
```
#elif defined(ARDUINO_ARCH_STM32)
  #ifndef HAL_STM32
    #define HAL_STM32
  #endif
  #define HAL_PATH(PATH, NAME) XSTR(PATH/STM32/NAME)
```

### instead it should be written like this
```
#elif defined(ARDUINO_ARCH_STM32) || defined(HAL_STM32)
```

after it is like this no problems are detected

well i guess technically it is fine without the change, but to help mitigate compile errors

**Comment by mriscoc** [comment]
It could be better to elevate Marlin issues to the [Marlin repository](https://github.com/MarlinFirmware/Marlin), because those changes could affect multiple platforms.
Please here post only issues with the ProUI interface.
