### ISSUE TITLE
When editing mesh, probing Z reference goes down instead of up

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#324]
found another bug.

so when you select to edit the mesh in the mesh leveling settings, and then pick a point to find the Z reference, the nozzle/hotend moves down in the Z axis instead of going up.

this is the opposite of what you want so it doesn't accidentally scratch the bed.

**Comment by mriscoc** [comment]
Good catch! Fixed in the next version.
File bedlevel_tools.cpp:
```cpp
void BedLevelToolsClass::ProbeXY() {
  const uint16_t Clear = Z_CLEARANCE_DEPLOY_PROBE;
  sprintf_P(cmd, PSTR("G0Z%i\nG30X%sY%s"),
    Clear,
    dtostrf(bedlevel.get_mesh_x(BedLevelTools.mesh_x), 1, 2, str_1),
    dtostrf(bedlevel.get_mesh_y(BedLevelTools.mesh_y), 1, 2, str_2)
  );
  gcode.process_subcommands_now(cmd);
}
```

**Comment by classicrocker883** [comment]
how do you fix it so fast? do you know what the code should be or how do you solve it?

**Comment by mriscoc** [comment]
> how do you fix it so fast? do you know what the code should be or how do you solve it?

The correct code is posted in my previous comment.

**Comment by classicrocker883** [comment]
> > how do you fix it so fast? do you know what the code should be or how do you solve it?
> 
> The correct code is posted in my previous comment.

I know, I mean how do you know that is the correct fix? do you know computer programming languages very well?

**Comment by mriscoc** [comment]
I am the programmer of Professional Firmware and its ProUI interface.

**Comment by classicrocker883** [comment]
its good you know exactly what to do to fix this is a great firmware

**Comment by classicrocker883** [comment]
### this code doesnt fix the issue.
i mean sure it works when you select Probing Z Reference in the edit mesh menu, but when you select the box Moving to Probing Pos, it doesnt actually do this. it moves down first.
should the line read...?

` const uint16_t Clear = Z_CLEARANCE_DEPLOY_PROBE + Z_HOMING_HEIGHT;`

because if it goes to just the z_clearance_deploy_probe height, and if there is a -Z offset value, it moves down. from a height that is example 12. (z clearance deploy probe = 10, + Z-offset). 
the problem is that it moves down to Z_homing_height.

after in a ready position. it should read Z_homing_height? because then it would always move up to the Z clearance deploy probe height. that would make more logical sense, rather than being at the deploy probe height already. it should be "resting" or "waiting" at the Z homing height at all times. and only when it needs to probe then move to the clearance height. right?

with `Z_AFTER_HOMING` enabled the reading I get after tramming includes the Z offset. so instead of reading 0.00. it is giving me the value for the Z offset.

when Bed Tramming, if you select a position like Front Left, when it is at Z_clearance_deploy_probe height + z-offset value, it moves in the XY before in the Z.
this is an issue because what if somehow it were on the bed, then the nozzle would drag and scratch it.

also in probe.h -> line 164
should it read
` #if ALL(DWIN_LCD_PROUI, INDIVIDUAL_AXIS_HOMING_SUBMENU, HAS_MESH)`
and dwin.h -> line 130

`  #if BOTH(INDIVIDUAL_AXIS_HOMING_SUBMENU, HAS_MESH)`
should it read as this? with HAS_MESH instead of MESH_BED_LEVELING ??

**Comment by mriscoc** [comment]
Before editing the mesh or doing a bed tramming you should remove anything from the bed.
