### ISSUE TITLE
Display artifacts

### ISSUE THREAD

**Issue by Madmike-1337** [mriscoc/Ender3V2S1#328]
**Describe the bug**
There are odd text fragments appearing on the display during a print.

**To Reproduce**
1. Print any file
2. Observe Screen
3. See error

**Expected behavior**
The display to appear normally.

Photos Attached

**Version (please complete the following information):**
Ender3V2-422-BLTUBL-20220816.bin

**Additional context**
I am not 100% certain, but it looks like something may be coming from M73 and displaying off the screen. 

![20220828_074222](https://user-images.githubusercontent.com/85642175/187079995-8fb1916b-817c-4008-b168-1489d4e6888e.jpg)
![20220828_074217](https://user-images.githubusercontent.com/85642175/187080007-9f89f93b-947a-4ab1-a5e8-60a7dc000a4a.jpg)

**Comment by Madmike-1337** [comment]
This also appears to be intermittent. I am printing the same file again (acceleration test)  and now there is no artifact. I have been seeing this for several of the prints I have done since updating from the previous version.

**Comment by mriscoc** [comment]
Those artifacts are caused by interference in the display communication. It can be mitigated shortering the display cable, or with a ferrite ring, but that will not eliminate it totally.
It is a knowed issue. You can clear them by turn on/off the backlight display in the tune menu.
