### ISSUE TITLE
Boards with STM32F401RCT6 don't have enough program memory to enable Linear Advance

### ISSUE THREAD

**Issue by pAndrey200** [mriscoc/Ender3V2S1#330]
i am trying compile professional firmware with linear advance for stm32f4, but i get error
![image](https://user-images.githubusercontent.com/22397926/187144966-1592092d-2f54-42e9-bb15-a0536419c570.png)
i use last release 20220816
and i use this following additional configuration:
![image](https://user-images.githubusercontent.com/22397926/187145635-80ffe350-437a-4b48-a6f4-c8662d4ed67d.png)
without enabling linear advance all work fine.

**Comment by mriscoc** [comment]
Los F4 no tienen suficiente memoria de programa para habilitar Linear Advance junto con las demás características, deberá hacer espacio quitando algunas según su criterio.
