### ISSUE TITLE
skr e3 v3 dont work with e3v2 lcd

### ISSUE THREAD

**Issue by SuhzHome** [mriscoc/Ender3V2S1#332]
skr mini e3 v3 dont work with dwin lcd

can we fix this?

**Comment by DavidKrall88** [comment]
> 

You need change the original lcd cable to another one for skr mini e3 v3

This is the cable:
https://biqu.equipment/products/mini-e3-connecting-cable-for-ender-3-v2-display-screen?_pos=4&_psq=ender&_ss=e&_v=1.0

**Comment by BioCookieYT** [comment]
Hello,
You have to change the pinout of the display. Just rewire the cable like I did:
https://www.smith3d.com/skr-mini-e3-v2-v3-on-ender-3-v2-ender-3-s1-lcd-dwin-knob-screen
https://imgur.com/a/RiGhYAc
