### ISSUE TITLE
Have spanish language ? 

### ISSUE THREAD

**Issue by labotecno** [mriscoc/Ender3V2S1#342]
hello , how i can make spanish language ? 
thank you

**Comment by ghost** [comment]
edit configuration.h file and look for language, enter in front es

**Comment by mriscoc** [comment]
This page is for reporting bugs or request features, for get assistance use the discussion page.

**Comment by BO105** [comment]
Hi
Thank you for your response,
I downloaded the source code, changed the language to fr
but the compilation with visualstudio and Marline 2.1 bugfix. ends in errors.
It must also be said that this is the first time I try to compile.
