### ISSUE TITLE
Vertical fine artefacts on SKR Mini E3 V3

### ISSUE THREAD

**Issue by RoP09** [mriscoc/Ender3V2S1#343]
Maybe not a bug, but I recently exchanged the Creality 4.2.2 against the SKR Mini E3 V3 and the first calibration cubes showed VFAs mainly on the Y axis (like these [here](https://github.com/MarlinFirmware/Marlin/issues/13529)) 

As I did not do any other modification to the printer at that time I suppose this is either a matter of this board or its stepper drivers, or something related to the firmware configuration?

The Creality 4.2.2 did show these as well on smooth surfaces, but to a much lesser extent as with this board / FW combination (really hardly noticable on the Creality board).

Could it be an issue of the TMC2209 or the settings done for this FW (Current, interpolation etc...)?

**Comment by mriscoc** [comment]
Changing board involves other drivers and the electrical current through the steppers motors, all of them can have an effect in the mechanical response of the printer.
This is not a Firmware issue, please open a discussion, maybe other SKR users could help you.
