### ISSUE TITLE
Filament missing warning

### ISSUE THREAD

**Issue by pacocatech** [mriscoc/Ender3V2S1#348]
Hello I'm using the versions you released for ender 3 v2 board 4.2.2

releases: 20220816 / 20220716 / 20220419 BLT / MM

In all versions at some point the printing stops and it keeps saying that filament is missing, is there a known bug for this?
When I have the original creality FW this process does not happen.

![20220901_132024](https://user-images.githubusercontent.com/70729684/188152689-7f2f8b6d-5db9-46a5-a89c-1a6579f64144.jpg)

**Comment by mriscoc** [comment]
Check https://github.com/mriscoc/Ender3V2S1/issues/227

**Comment by pacocatech** [comment]
I've already tested with the LOW / HIGH setting and I still get the filament change warning.
Even if you disable the sensor or the warning continues

**Comment by mriscoc** [comment]
Do you have a filament runout sensor?

**Comment by pacocatech** [comment]
yes

**Comment by mriscoc** [comment]
Ok, in Advanced Settings there is a tool: End Stop Diagnostic, Runout must be in TRIGGERED status when there is filament inside.

**Comment by pacocatech** [comment]
I will check

**Comment by pacocatech** [comment]
@mriscoc 
With filament:
![image](https://user-images.githubusercontent.com/70729684/188274598-91e73f58-dd72-4166-aec1-5a21cb84fb30.png)


without filament:

![image](https://user-images.githubusercontent.com/70729684/188274618-877c3084-3c39-4673-97e1-11fe7fdeb31d.png)

**Comment by mriscoc** [comment]
That is correct for simple runout sensors, so if you got a pause inspect your G-code files for pause commands as M25, M125 or M600. Maybe your slicer has a filament change script.

If you have a BTT Smart Filament Sensor the active mode must be changed to MOTION.

**Comment by pacocatech** [comment]
This is my gcode 
[Teil1_2h51m_036mm_240C_PETG_ENDER3V2.zip](https://github.com/mriscoc/Ender3V2S1/files/9484916/Teil1_2h51m_036mm_240C_PETG_ENDER3V2.zip)

doesn't have any pause gcode.

**Comment by mriscoc** [comment]
Check your filament sensor connections. This is not a firmware issue.

**Comment by pacocatech** [comment]
then!
my sensor is new... with the original creality firmware i don't have this problem.
If there's any more tests I can do to confirm that there isn't a bug in the firmware version just let me know, I'd really like to understand what's going on to use your version.

**Comment by mriscoc** [comment]
Your pictures show the firmware can recognize your filament sensor correctly, I also have a V2 with 4.2.2 with filament sensor and don't have any problem. If you check your G-code and do not have any pause command, I can't figure out what is happening, but a connection problem. With Creality firmware you will not have this problem because that firmware doesn't support filament sensor support and ignores it.

**Comment by pacocatech** [comment]
I'm going to compile a new version of marlin, with the latest version available in the community and I'll test it, I'm sure the problem is not the sensor and it's not in the gcode either. Thanks for listening
