### ISSUE TITLE
Config files wrong

### ISSUE THREAD

**Issue by MikeOxawopper** [mriscoc/Ender3V2S1#349]
**Describe the bug**
Downloaded the newest version source code.
Extracted
Opened config folder
Copied the config files for Ender 3 v2 422 BLT to the marlin folder
Opened in visual studio
Did a test compile 
FAILED
It seems to think the chip set is STM32G0B1BR-btt

![Fail](https://user-images.githubusercontent.com/65547160/188157152-dc0ef564-d552-4cb6-a76f-289caf07baa5.JPG)
![mb Details](https://user-images.githubusercontent.com/65547160/188157157-8db4422b-e306-4048-a8b0-f05193a5cf18.JPG)

**Comment by mriscoc** [comment]
And platform.io to the root of the proyect: https://github.com/mriscoc/Special_Configurations

![image](https://user-images.githubusercontent.com/2745567/188170821-5b469bf2-4080-4a2b-9fd6-eeef29134cf6.png)
