### ISSUE TITLE
Adding Highlight Select Box around Button

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#350]
//function 
FILE **dwin_popup.cpp**
after line 45 add...</p>
```
void Draw_Select_Box(const uint16_t xpos, const uint16_t ypos) {
  const uint16_t c1 = HMI_data.Highlight_Color;
  DWIN_Draw_Rectangle(0, c1, xpos - 1, ypos - 1, xpos + 100, ypos + 38);
  DWIN_Draw_Rectangle(0, c1, xpos - 2, ypos - 2, xpos + 101, ypos + 39);
}
```

//
FILE   **dwin_popup.h**
after line 29 add

`void Draw_Select_Box(const uint16_t xpos, const uint16_t ypos);`

on line 47 add after
  if (button) DWINUI::Draw_Button(button, 86, 280)
`, Draw_Select_Box(86, 280);`

//look for Draw_Button(BTN_Continue...)
FILE  **dwin.cpp**

under the Draw_PrintDone() function
after line ~562 add

`    Draw_Select_Box(86, 300);`

after line ~571 add

`    Draw_Select_Box(86, 273);`

under Trammingwizard() function
after line ~2625 add

`    Draw_Select_Box(86, 305);`

//
FILE  **endstop_diag.cpp**
after line 64 add

`  Draw_Select_Box(86, 250);`

//
FILE  **meshviewer.cpp**
after line 121 add
```
else {
      DWINUI::Draw_Button(BTN_Continue, 86, 305);
      Draw_Select_Box(86, 305);
    }
```
### {} curly brackets should be added to "else"
 

<br>

//
FILE  **printstats.cpp**
after line 47 add

`  Draw_Select_Box(86, 250);`

**Comment by mriscoc** [comment]
Not a firmware issue
