### ISSUE TITLE
Allow max temperature to be increased

### ISSUE THREAD

**Issue by carrino** [mriscoc/Ender3V2S1#351]
I have the S1 Pro which can do up to 300C.  I'd like to be able to print hotter when I'm using the S1 Professional Firmware.

I don't know how hard this is, but possibly have another build Ender3S1Pro-F4-<buildnum> with 300C as the max temp

**Comment by mriscoc** [comment]
Use the custom G-code:
```gcode
C104 U1 T315
```

**Comment by mriscoc** [comment]
Not a firmware issue

**Comment by carrino** [comment]
This is a great solution for the hotend temp and works well for me.  Is there a similar one for the bed temp?  Mine can go to 110 instead of the default 100.  I found the custom g-code wiki page you made, but I didn't see it.

**Comment by hayden-t** [comment]
yes we need this too, currently no way but custom compile afaik
