### ISSUE TITLE
Toolbar Icon alternates

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#356]
Sometimes after compiling and flashing, the 2nd item Icon in the Toolbar doesn't stay what it is supposed to be.

It is labeled Tramming Wizard and supposed to be `ICON_SetHome`. The Icon becomes PLA (`ICON_PLAPreheat`). This is intermediate and happens sometimes with new firmware compile and flash.

i find in the code this error attributed to TBItemA[]
<br>
![Screenshot from 2022-09-09 02-39-32](https://user-images.githubusercontent.com/18502096/189288338-01beef04-faae-46e8-84ec-7fe084cfdd01.png)
</br>

i notice that the PLAPreheat icon is the next number in sequence in FILE _dwin_set.h_

```
#define ICON_Homing             29
#define ICON_SetHome            30
#define ICON_PLAPreheat         31
```

sometimes I can temporarily fix this by changing the Tramming Wizard Icon to `ICON_Homing`, and it becomes the correct icon when flashed

**Comment by mriscoc** [comment]
Is the bug present if you change:
```cpp
#define ICON_BedTramming       CI(1,ICON_SetHome)
```
to:
```cpp
#define ICON_BedTramming       ICON_SetHome
```
I can't replicate the bug with the current published sources.

![image](https://user-images.githubusercontent.com/2745567/189372894-e4ec8843-8ce1-4516-b9b2-a21aab3dc109.png)

**Comment by classicrocker883** [comment]
the error remains after the change, and after trying a brand new download of the files

**Comment by classicrocker883** [comment]
the only type of fix it suggests is to edit the IncludePath. it suggested i should have vcpkg installed, which i do. perhaps there is a library it is referring to that I do not have.

**Comment by classicrocker883** [comment]
![Screenshot from 2022-09-09 23-58-54](https://user-images.githubusercontent.com/18502096/189467798-754986cb-b993-4685-b626-6ddb1f3c64a5.png)

as you can see, it cuts off here.

<br>

![Screenshot from 2022-09-09 23-59-00](https://user-images.githubusercontent.com/18502096/189467799-2f0ea73b-f701-46e5-b0f0-3fccd001ab74.png)


and this is from the original source

**Comment by classicrocker883** [comment]
![Screenshot from 2022-09-10 00-03-38](https://user-images.githubusercontent.com/18502096/189467916-f3aa4ae2-c7d6-4761-85ad-86fd0c7bf9a5.png)

it is saying error-type as if the struct / class or typedef is incorrect

**Comment by classicrocker883** [comment]
![Screenshot from 2022-09-10 00-13-20](https://user-images.githubusercontent.com/18502096/189468217-28a813fc-1f2b-4a99-8189-822e5d7a5932.png)


after having Arduino.h in the include path, more errors pop up

**Comment by classicrocker883** [comment]
i think i fixed it.
i added `#include "../HAL/shared/progmem.h"`
to FILE multi_language.h

while that took away the error on VSCode, it did not solve the issue, the ICON is still the wrong one.

so far the temporary remedy is to do (ICON_SetHome - 1)

**Comment by mriscoc** [comment]
Maybe you have an error in your configuration files.

**Comment by mriscoc** [comment]
It is not possible to replicate.
