### ISSUE TITLE
Manual mesh Y axis is mirrored 

### ISSUE THREAD

**Issue by MaynardMann** [mriscoc/Ender3V2S1#361]
ender 3 s1 f4 chip 

as the title says Iv been trying to figure out why the manual mesh makes things so much worse for a week iv finally got it the y axis is mirrored same for x I think

**Comment by classicrocker883** [comment]
in the Configuration.h file

line 1640
```
// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false  // Ender Configs
#define INVERT_Y_DIR false  // Ender Configs
#define INVERT_Z_DIR true 
```

set the False to true.

### OR what you can do

is swap two of the 4 wires going into the stepper motor. be sure that the printer is OFF when you do this.

and look up search which two wires to swap in the connector

**Comment by MaynardMann** [comment]
Well I'm literally an as dumb as a rock I thought this was the issue but it isn't I also didnt understand the vernacular well enough I'm not manual meshing I'm using ABL to generate a mesh with my cr touch the conclusion that I'm now coming to is that my cr touch is defect or something because the the values ABL is shooting out for each probed point on my bed is seemingly random after doing it back to back 15 times each mesh generated is wildly different it just happened to shoot out random values twice in a row that made it appear that the mesh was inverted against the perceived warping of my bed making it seem like ABL was giving me a mirrored mesh.

**Comment by mriscoc** [comment]
The mesh is not inverted, there are some issues with S1 F4 boards and autoleveling, please check this: https://github.com/mriscoc/Ender3V2S1/issues/195

Currently, the only solution is creating a mesh and adjusting it using manual editing.
