### ISSUE TITLE
G34 Option in menu

### ISSUE THREAD

**Issue by tpups** [mriscoc/Ender3V2S1#366]
**Some UI like Marlin have an option to run G34 in the menu. In Marlin I believe it's under Motion > Z Auto Align**
It would be great if it could be added to Professional Firmware for those of us with dual z-axis + dual steppers.

**Additional context**
https://marlinfw.org/docs/gcode/G034-zsaa.html

**Comment by mriscoc** [comment]
That might be a candidate for a custom menu, but you'll need to compile your own firmware version.

**Comment by tpups** [comment]
Yeah that would be no problem. I was able to build Professional Firmware with G34 enabled, just would be nice to have the option of enabling it in the menus.

**Comment by tpups** [comment]
Ah just found the custom menu options in configuration.adv. Didn't realize that might be an option. Attempting to add to Configuration Menu.

**Comment by tpups** [comment]
Is it possible to add as a custom menu item using either CUSTOM_MENU_MAIN or CUSTOM_MENU_CONFIG in Configuration_adv? Where would those options appear in the UI?

_edit - nevermind, I see the custom menu options won't work with the v2 and its independent display firmware. It looks like the next best option might be to use the STARTUP_COMMANDS setting._

**Comment by mriscoc** [comment]
Or use a special configuration g-code file as: https://github.com/mriscoc/Ender3V2S1/wiki/Configuration-files
I know that I wrote to avoid any motion command, but you can try.

**Comment by dennisMe2** [comment]
Can someone point me to some docs to learn how to implement this? I'd really like it. 
For now I have a file on each SD card so I can run it before generating a mesh or tramming but its clunky!

**Comment by VovyCZ** [comment]
I would also like this option in the firmware menu for the SKR MINI E3 V3.

**Comment by sammcj** [comment]
Upgrading to the SKR Mini E3 V3 this weekend - this would be nice to have!

**Comment by gsuresh2u** [comment]
SKR mini e3 v3.0 has dual stepper connectors. But they both driven by single driver
G34 option is available only for individual Z steppers
Not possible for SKR mini e3 v3

**Comment by VovyCZ** [comment]
I know, but it dawned on me later. In the meantime I have upgraded to the Klipper and after some trials I am thinking of putting your firmware back into the Ender 3 V2 and selling it. As a replacement, I'm thinking about something with the Klipper, probably the RatRig V-Core 3.1. But this is offtopic...
