### ISSUE TITLE
[Feature Request] Transfer EEPROM values

### ISSUE THREAD

**Issue by davkvi** [mriscoc/Ender3V2S1#37]
Hi,

One feature that would be a "nice to have" is to export the parameters set to the sd card.
e-steps, home pos and so on.

So we could import it to the firmware when we upgrade :)

**Comment by mriscoc** [comment]
Hi, I received this request from day 1, also the official Marlin and other fork. I know that it could be easy for the user to simply export a configuration file and then import after a flash, but from a programming point of view there is a penalty in the space that this feature will consume in the now reduced (RCT6) flash space, is not only about of export the values, also when importing they must pass a filter and verification routines for ensure that all parameters are within the workable range, that could double what we already have in almost all g-code commands.

In professional use, it is better if you create a special configuration g-code file with all the machine specifications that you need, then, after flashing a new firmware, you need only to load that file to restore your preferences. The Professional firmware implements the standard Marlin g-codes and also special custom g-codes to allow you to create a complete configuration file. I invite you to try to use this approach. Your configuration g-code file could be:
 ```g-code
M502              ; load the firmware default values
; put here want you need
M500              ; save your preferences to the EEPROM 
M997              ; optional to reboot the printer
```
