### ISSUE TITLE
Unload filament seems not functioning correctly

### ISSUE THREAD

**Issue by ltsharma** [mriscoc/Ender3V2S1#385]
It is ender3 V2, When I use unload filament it is getting long string of plastic with filament, 
I guess the procedure to unload filament seems bit reversed.

**Current behaviour**

1.  Retracts
2. Waits for cooldown
3. Again it pushes filament Slowly back as much it retracted before
4. Starts unloading

Step 3 - Pushing back again to hotent is causing long string of plastic attached with filament.

**Expected behavior**
Filament unload without plastic string attached.
The steps  i was doing and it was perfect unload ( which can be done with extruder too)

1. Push filament a bit into hotend.
2. Retract a bit
3. Wait for cooldown
4. Start unloading

**Version:**
2.1.0.1 MRiscoC - 20220816

**Comment by mriscoc** [comment]
The Unload behavior is defined by the G-code [M702](https://marlinfw.org/docs/gcode/M702.html) in Marlin.
