### ISSUE TITLE
Micro SD Card to SD Card Adapter not clearing previous file

### ISSUE THREAD

**Issue by HTDPUK** [mriscoc/Ender3V2S1#405]
I have a farm of 10 Ender 3 v2's and use SD Card adaptors due to not wanting to overuse the micro sd card port on the printers themselves. An adaptor breaking is easy to replace while the micro sd card port isnt(for me at least).

After installing your latest release on 3 of the printers I have the problem that when I replace the SD card and then go to select "Print" the previous file is still showing even though that is not on the current installed SD card. To get the new file to show I need to remove the adaptor from the printers micro sd card port and put it back in.

The SD card Adaptors that I use are the following 
https://smile.amazon.co.uk/gp/product/B0855DBVXF/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

I like your firmware, I think its superior to Jyers but if I cant use these SD card adaptors then I will be unable to switch to your firmware.

Let me know if you need any more information.

**Comment by mriscoc** [comment]
For Card extenders support you need to enable the `Media update` option in Advanced settings menu.
