### ISSUE TITLE
Importing/exporting machine configuration 

### ISSUE THREAD

**Issue by Moobien** [mriscoc/Ender3V2S1#409]
Not sure if this is possible but i would love to be able to export/backup my printer settings prior to a firmware update and then simply import them back in afterwards. To my understanding the 'store settings' and 'load settings' data is wiped every firmware update.

Currently i have to note down or photograph my settings prior to doing firmware updates which can sometimes get tedius.

**Comment by mriscoc** [comment]
You can use [Configuration Files](https://github.com/mriscoc/Ender3V2S1/wiki/Configuration-files) to setup your printer after a firmware update.

**Comment by Moobien** [comment]
Oh cool! Thank you.
