### ISSUE TITLE
how to save my current machine settings Before flashing  ?

### ISSUE THREAD

**Issue by CaVO32** [mriscoc/Ender3V2S1#410]
each time i try to update my firmware it sets to default all my machine settings.... how do i save these settings before i flash or upgrade. 
i know your will say to use the [Configuration Files](https://github.com/mriscoc/Ender3V2S1/wiki/Configuration-files) for setting my tuned settings AFTER i have upgraded the firmware but i want to save these settings  B E F O R E   upgrading ?

**Comment by mriscoc** [comment]
Use [M503 ](https://marlinfw.org/docs/gcode/M503.html) to get your current settings.

**Comment by CaVO32** [comment]
so you are saying that i need to use other software like octoprint or similar to do this..??

**Comment by ghost** [comment]
> so you are saying that i need to use other software like octoprint or similar to do this..??

in Octoprint go to the terminal and type the command, it will display all the settings there you copy and generate the file to save your printer configuration

**Comment by mriscoc** [comment]
Also using a PC and installing Pronterface
