### ISSUE TITLE
Remaining Time not working and Stuck at "Nozzle Heating"

### ISSUE THREAD

**Issue by nicop777** [mriscoc/Ender3V2S1#42]
Hi. First off, what a great work. Thank you! Just wanted to share my experience, just a minor bug. While doing a test print after flashing the firmware and mesh leveled my bed, the Remaining (time) is not working and stuck at 00:00. Also, the status is stuck at "Nozzle Heating". 
![stuck remaining time](https://user-images.githubusercontent.com/40436285/153696087-0b9c7a2c-1486-4d19-a412-cf400f666ac5.jpg)

**Comment by Cal-LF** [comment]
I am running a print now and do not have that issue. Using V427 manual mesh.
I did notice that the time remaining stays at 0 until after it starts printing.

![Image01](https://user-images.githubusercontent.com/76499230/153697476-a36e49a3-3679-4894-8050-4729aca87259.jpg)

**Comment by nicop777** [comment]
Hi! I wonder why mine is bugging. May I ask if the firmware that you are using is the Feb 09 release (20220209)? Thanks!

**Comment by mriscoc** [comment]
If you are using Octoprint or another host to print you must configure the appropriate plugin.

**Comment by brunohenriquy** [comment]
About the "Nozzle Heating", it also happens with the Vanilla Marlin(bugfix-2.0.x), But there it's "E1 Heating".
It's the line 3670 from [temperature.cpp](https://github.com/mriscoc/Ender3V2S1/blob/Ender3V2S1-Released/Marlin/src/module/temperature.cpp) I Was looking the code for this Bug, then I saw that a long time ago @mriscoc made a commit there changing E to E1, then I got here and @nicop777 found the same bug as me hehehehe.

![IMG_3483](https://user-images.githubusercontent.com/8320519/153699866-d51f1b1b-18bd-4e09-bed6-e27de31097ac.jpg)

**Comment by mriscoc** [comment]
"Nozzle Heating" is not a bug, it is the last message sent to the status line from the Marlin core, for change that text, you can use any M117 plugin for your slicer. For example, I use a plugin for Cura that shows the current layer number.

**Comment by brunohenriquy** [comment]
> "Nozzle Heating" is not a bug, it is the last message sent to the status line from the Marlin core, for change that text, you can use any M117 plugin for your slicer. For example, I use a plugin for Cura that shows the current layer number.

Ohh Gotcha, so it sticks with the last message sent, now it makes sense. Thank you @mriscoc

**Comment by brunohenriquy** [comment]
> "Nozzle Heating" is not a bug, it is the last message sent to the status line from the Marlin core, for change that text, you can use any M117 plugin for your slicer. For example, I use a plugin for Cura that shows the current layer number.

Could you tell this plugin name? Link?

**Comment by mriscoc** [comment]
This
![image](https://user-images.githubusercontent.com/2745567/153700208-481599c8-5fd6-4da0-81af-4d6165b0bc5e.png)

**Comment by brunohenriquy** [comment]
> This ![image](https://user-images.githubusercontent.com/2745567/153700208-481599c8-5fd6-4da0-81af-4d6165b0bc5e.png)

Thank you so much!! xD

**Comment by mriscoc** [comment]
You are welcome
