### ISSUE TITLE
Error MAXTEMP in custom compile for S1 Pro (F4)

### ISSUE THREAD

**Issue by wassereimer86** [mriscoc/Ender3V2S1#428]
**Describe the bug**
I used the previous version from August for my S1 Pro (F4) with the special configuration https://github.com/mriscoc/Special_Configurations/releases/tag/T13 without any problems. After making the same changes to the newest version and after the firmware update is done the printer reboots and begins to beep fast with the message "Nozzle or Bed temperature is too high" in the display and very quick after this it's beeping continuously with the message "Printer killed! Err: MAXTEMP Turn off the printer". The precompiled version without the special configuration is working fine. Same with a self compiled version without any changes.

**To Reproduce**
1. Compile with special configuration

**Expected behavior**
Working fine

**Comment by mriscoc** [comment]
Could you test with the latest sources? try removing some features to make more program memory space.

**Comment by wassereimer86** [comment]
With the latest sources and the previous named special configuration, it's working this time! I got the error once after the update and loading the config file, but after that it didn't happen again. 🤷 I saw that I didn't replace the Version.h file last time. But I don't know if this could be the reason why I had no problems last time.

**Comment by mriscoc** [comment]
Good to know that it is fixed now.
