### ISSUE TITLE
Bed tramming Issue with Ender3v2-422-BLTouch-20220209

### ISSUE THREAD

**Issue by rm227** [mriscoc/Ender3V2S1#43]
About the printer

Version: [Ender3v2-422-BLTouch-20220209.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20220209/Ender3v2-422-BLTouch-20220209.bin)

an issue in the bed tramming menü. front right and back right are not functionable. i mean nothing happens when you chose it.

I increased the margin from 25 to 30, 35, 40,45,50 and it still doesn't work...

the auto mesh seems to work, but when he finishes doing the automatic mesh of the whole tray before launching an impression, the pin of the bltouch remains deployed and rubs on the tray when moving and risks bending or breaking if it comes into contact with an obstacle

but when testing the manual mesh, when it is on the right it tells me: position not reachable, check offsets 

however before the update everything was working perfectly, I had no problem

Could you explain in detail, what should be changed to correct this problem please?

And would it be possible to give me a link to download the old version "Ender3v2-422-BLTouch-20211121." because I can't find it on github anymore, and with this version I had no problem...

**Comment by mriscoc** [comment]
Hi, do you have negative home offsets? Please, post all your offsets and dimensional settings.

**Comment by rm227** [comment]
Hi, thank you for your answer, here are the dimensional settings of my printer, do I need more information?

![IMG_0580](https://user-images.githubusercontent.com/80790016/153749565-2bfe5a49-2572-4adb-8edd-156887ac70e5.JPG)
![IMG_0581](https://user-images.githubusercontent.com/80790016/153749569-892a1092-c5f6-448e-9888-a1060734ddc9.JPG)
![IMG_0582](https://user-images.githubusercontent.com/80790016/153749570-2f2a4b09-cfa8-4155-9402-5fe60817fe0e.JPG)
![IMG_0583](https://user-images.githubusercontent.com/80790016/153749572-fd34b4ea-6aab-4a13-9231-8045e04e4466.JPG)

**Comment by mriscoc** [comment]
I have tried your settings and all the tramming points were reachable.

About this:
>"the auto mesh seems to work, but when he finishes doing the automatic mesh of the whole tray before launching an impression, the pin of the bltouch remains deployed and rubs on the tray when moving and risks bending or breaking if it comes into contact with an obstacle"

When the auto mesh finishes the pin of the BLTouch must be stowed, if not, there is a problem of communication with your BLTouch. Please try disabling the HS mode.

**Comment by rm227** [comment]
I deactivated the HS mode, now during the automatic mesh when it arrives on the right the pin does not come out and it starts all the mesh again and repeats this without stopping.

tomorrow I will disassemble the bltouch and check all the wiring to see if there is not a bad contact somewhere

**Comment by mriscoc** [comment]
Don't forget to do a "Restore defaults" and "Store settings" to clear the EEPROM with the default values.

**Comment by MichaelSordje** [comment]
i have the same problem. with Ender3v2-422-BLTouch-2021112 it is working, with the latest firmware not.

**Comment by mriscoc** [comment]
> i have the same problem. with Ender3v2-422-BLTouch-2021112 it is working, with the latest firmware not.

[If you already do all the proposed tests then your BLTouch is not compatible with this version.](https://github.com/mriscoc/Ender3V2S1/wiki/Bed-tramming-menu#note1)

**Comment by rm227** [comment]
Hi, I checked the wiring and I don't see any problem there.

I also do the "Restore defaults" and "Store settings" but the problem persists

my BLtouch is a V3.1, I don't know if that's a compatibility problem

Would it be possible to send us the version of your marlin
"Ender3v2-422-BLTouch-2021112" please?

like that, while waiting for a more recent version that is compatible, we can continue to print with our printer, because with the old version it worked perfectly
Unfortunately I can't find it on github anymore.

**Comment by mriscoc** [comment]
I see posted here: https://www.facebook.com/groups/ender3v2firmware/posts/653009622407497/
Also try decreasing the probe z-feed rate

**Comment by rm227** [comment]
ok very good,
 thank you very much

**Comment by thedroidkid** [comment]
I am having this issue as well I am unable to Tram back right and back left. I have an Ender 3 S1 with the stock CR Touch

**Comment by mriscoc** [comment]
> I am having this issue as well I am unable to Tram back right and back left. I have an Ender 3 S1 with the stock CR Touch ![PXL_20220215_141927819](https://user-images.githubusercontent.com/42625519/154082498-203af394-ec74-4882-93ff-5f4cb0be5d94.jpg)

Did you change any value? Increase your probe margin.

**Comment by mriscoc** [comment]
> I left everything Stock. Just flashed this morning and wanted to level my bed using the probe tram method.

Sorry, not having a S1 to do metering and test make me to do some assumptions, please test this version and report back, thank you.

[Ender3S1-20220215.zip](https://github.com/mriscoc/Ender3V2S1/files/8074235/Ender3S1-20220215.zip)

**Comment by thedroidkid** [comment]
Will flash now thanks. If you need anything let me know Just picked up an s1 and sold my v2
