### ISSUE TITLE
Octoprint, Bed Visualizer, new mesh GCode G28 parameters issue  

### ISSUE THREAD

**Issue by ebada** [mriscoc/Ender3V2S1#439]
**Describe the bug**
Octoprint, Bed Visualizer, new mesh GCode G28 parameters:

Something caught my eye and just want to bring it to your attention.

Invalid parameter:
**G28 XYO   ; Do an optional XY home**

M155 S30  ; set temperature reporting delay, use a value longer than the time it takes for your leveling command to complete.
G28 XYO   ; Do an optional XY home
G28 Z     ; Do a Z home
@BEDLEVELVISUALIZER  ;
.....

**To Reproduce**
1. Go to https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#to-take-a-new-mesh-in-non-ubl-versions-use-this-code-in-the-configuration-page-of-the-plugin
3. New mesh for non ABL gcode section, line 2 
5. G28 XYO, I think this is invalid option.

**Expected behavior**
Replace line 2 and 3 with:  G28 XYZ

**Additional context**
line 2:  G28 XYO   ; Do an optional XY home
Optional XY home, where the option is present?     
 

Thank you

**Comment by mriscoc** [comment]
https://marlinfw.org/docs/gcode/G028.html
[O]  | Flag to skip homing if the position is already trusted
-- | --

**Comment by ebada** [comment]
Thank you! very helpful.
I had 0 as in zero, not O :) when the editor flagged the line.
