### ISSUE TITLE
Automatic bed leveling G29 before printing in UBL does not work.

### ISSUE THREAD

**Issue by akalomen76** [mriscoc/Ender3V2S1#443]
Before upgrading my Ender 3 V2 (4.2.2) to the latest released firmware [20221002](https://github.com/mriscoc/Ender3V2S1/releases/tag/20221002) [Ender3V2-422-BLTUBL-LA-20221002.bin](https://github.com/mriscoc/Special_Configurations/releases/download/LinearAdvance/Ender3V2-422-BLTUBL-LA-20221002.bin) with linear advance, automatic bed leveling with G29 in Cura start script worked perfectly. Now the G29 entry is not triggering and printer uses the stored mesh.

**Comment by mriscoc** [comment]
For UBL you need to use `G29 P1`, check UBL start script in the Wiki.

**Comment by akalomen76** [comment]
I confirm that this was the issue, my bad
