### ISSUE TITLE
problemas con la previsualizacion 

### ISSUE THREAD

**Issue by bombardeo38** [mriscoc/Ender3V2S1#444]
tengo problemas con cura y prusa slicer para configurar la previsualizacion de la imagen en la pantalla 
![Captura de pantalla (2)](https://user-images.githubusercontent.com/92440196/195906669-58941efd-336e-4a95-ad21-271c89e78d0c.png)
![Captura de pantalla (3)](https://user-images.githubusercontent.com/92440196/195906679-56a8fc09-e266-4cbb-96a1-981c76ffeff6.png)

**Comment by mriscoc** [comment]
Not a firmware issue, check troubleshoting at: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-generate-a-gcode-preview
