### ISSUE TITLE
Old configuration.h file

### ISSUE THREAD

**Issue by karlc28** [mriscoc/Ender3V2S1#464]
So reinstalled vs code and now that’s fixed my previous issue but now have this issue
I’m using the configuration.h file from the linear advance source code ender3v2-422-bltubl folder
![5AF86C99-BC55-45D5-8517-B9C8D2F55A0C](https://user-images.githubusercontent.com/92265354/197619185-2668481d-4857-4536-b319-c571715c6444.jpeg)

**Comment by mriscoc** [comment]
Update your configuration files with:
https://github.com/mriscoc/Special_Configurations/tree/main/Ender3V2-422-BLTUBL-LA

**Comment by classicrocker883** [comment]
you can change `#define CONFIGURATION_H_VERSION 02010200`
