### ISSUE TITLE
Typo in "Z After Homing" menu item (misspelled as "Homming")

### ISSUE THREAD

**Issue by gitname** [mriscoc/Ender3V2S1#468]
**Describe the bug**

In the "Homing" menu, the menu item "Z After Homming" contains a typo. In that menu item, the word "Homing" is misspelled as "Homming".

**To Reproduce**

1. Turn on an Ender 3 V2 printer running firmware `Ender3V2-422-MM-20221002.bin`
2. Navigate to the "Homing" menu (i.e. `Prepare > Homing`)
3. See the typo in the "Z After Homming" menu item

**Expected behavior**

I expected the menu item to be spelled "Z After Homing."

**Screenshots**

Here's a photo of the menu item (the spelling of the menu title at the top of the screen is correct):

![image](https://user-images.githubusercontent.com/7143133/198375190-66eda2bf-df0f-4f49-aa86-c106a9807165.png)

Here is its spelling on Wikipedia for reference:

![image](https://user-images.githubusercontent.com/7143133/198373364-126e06db-6cb6-4527-ac06-959a96da6f03.png)

- Source: https://en.wikipedia.org/wiki/Homing

**Version (please complete the following information):**

- Firmware file: `Ender3V2-422-MM-20221002.bin` (release: https://github.com/mriscoc/Ender3V2S1/releases/tag/20221002)

**Additional context**

I searched this Git repository for the string "Homming" and didn't find it anywhere in the code.

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/discussions/447
