### ISSUE TITLE
Power outage recovery feature is unreliable and sometimes is unable to continue

### ISSUE THREAD

**Issue by ivek81cro** [mriscoc/Ender3V2S1#469]
After power outage query appears if you want to continue, after confirmation goes to home twice and z axis starts going down hitting model or heat bed, which ever comes first

**Comment by nduzaone** [comment]
Seem to be experiencing the same issue. 
It gives an option to clean the nozzle before resuming - which is great - but fails to resume and drops the nozzle onto the bed - actually caused a scratch on the glass bed.

**Comment by mriscoc** [comment]
Marlin's power outage recovery is sometimes unreliable. It depends on G-code, SD card, buffers, etc. Sometimes the PLR file gets corrupted because the internal buffers of the SD card were not flushed, that can happen more on large SD cards and complex SD card prints.
