### ISSUE TITLE
Tune/"Firmware Retract"

### ISSUE THREAD

**Issue by GT-Geo** [mriscoc/Ender3V2S1#473]
Under the _Tune_ menu there is "Firmware Retract". Should that not read _Filament Retract_?

**Comment by classicrocker883** [comment]
no, its meant to go to the firmware retract menu. which is retraction settings based on the firmware.
youre right that it is filament retract, however this menu is based on the firmware.

**Comment by Nbrooks639** [comment]
you also have the option to select firmware retraction in your slicer.
![image](https://user-images.githubusercontent.com/100983669/198932337-d3b2be0f-a4a8-4a39-a12c-600605bbda2c.png)

**Comment by mriscoc** [comment]
It is always good to read the Wiki documentation: https://github.com/mriscoc/Ender3V2S1/wiki/Firmware-Retraction

**Comment by GT-Geo** [comment]
Sorry about that........apparently I have reading/learning to do.
