### ISSUE TITLE
Tramming not working - Ender 3 S1 Plus

### ISSUE THREAD

**Issue by TheCableGuy99** [mriscoc/Ender3V2S1#482]
**Describe the bug**
Tramming was working but suddenly stopped. Now I cannot get it to complete a full set of 4 probes. The main issue is it won't probe all 4 corners, sometimes it misses the front left and back right, other times it misses the front right and back right. When it misses the first probe it switches the bed heater off and the screen says (stopped) then continues to try do the other but as said misses certain point then registers all corners as level 0.00 even though they aren't. 

I have obviously turned the printer off and on, disconnected octoprint so the printer is not influenced by anything else and tried without the bed heater on.

It also sometimes throws a "home" in the middle of tramming which is weird.

**To Reproduce**
1. Heat bed to 60°C and wait for it to reach temp
2. Run the tramming wizard.

**Expected behavior**
Tramming wizard should complete and probe all 4 corners.

**Screenshots**
https://user-images.githubusercontent.com/39552752/199278489-2673cc7e-1d99-44a3-bf9f-a7560ee06cdb.mp4 (video)

**Version (please complete the following information):**
Version: 2.1.3 - 20221019 - 01.:40
I used the configurator selecting, Ender3S1, 301F4, BLT+UBL, T13.
Then compiled with the following features.

Changes made from the original config:
-----=====Configuration.h=====-----
Line 120 - Disable
//#define BAUD_RATE_GCODE     // Enable G-code M575 to set the baud rate  // MRiscoC Enables change the baudrate

Line 2226 - Set pre-heats as below
#define PREHEAT_1_LABEL       "PLA"
#define PREHEAT_1_TEMP_HOTEND 145
#define PREHEAT_1_TEMP_BED     60
#define PREHEAT_1_TEMP_CHAMBER 35
#define PREHEAT_1_FAN_SPEED     0 // Value from 0 to 255

#define PREHEAT_2_LABEL       "PETG"
#define PREHEAT_2_TEMP_HOTEND 145
#define PREHEAT_2_TEMP_BED     75
#define PREHEAT_2_TEMP_CHAMBER 35
#define PREHEAT_2_FAN_SPEED     0 // Value from 0 to 255

#define PREHEAT_3_LABEL       "TPU"
#define PREHEAT_3_TEMP_HOTEND 145
#define PREHEAT_3_TEMP_BED     45
#define PREHEAT_3_TEMP_CHAMBER 35
#define PREHEAT_3_FAN_SPEED     0 // Value from 0 to 255

#define PREHEAT_4_LABEL       "ASA"
#define PREHEAT_4_TEMP_HOTEND 145
#define PREHEAT_4_TEMP_BED     90
#define PREHEAT_4_TEMP_CHAMBER 35
#define PREHEAT_4_FAN_SPEED     0 // Value from 0 to 255

Line 2362 - Disable
//#define PRINTCOUNTER  // MRiscoC Enable Print Statistics

-----=====Configuration.adv.h=====-----
Line 1385 - Disable
//#define SOUND_MENU_ITEM   // Add a mute option to the LCD menu  // MRiscoC Enable Sound Menu Item

Line 1486 - Enable
#define SDCARD_READONLY  // Read-only SD card (to save over 2K of flash)

Line 1522 - Disable
//#define POWER_LOSS_RECOVERY  // Ender Configs

Line 1676 - Disable
//#define BINARY_FILE_TRANSFER  // MRiscoC Enabled for easy firmware upgrade

**Additional context**
I also set these settings after flashing:

; Professional Firmware Configuration File for Ender-3 S1 Plus 
;=====================================================
C10                    						; Mark as a configuration file
M117 Applying configuration
;-----------------------------------------------------
M302 S145	 								; set min extrude temp to 145 so we can set preheat settings below to 145
M145 S0 H145 B60 F0							; Set Pre-Heat PLA settings
M145 S1 H145 B75 F0							; Set Pre-Heat PETG settings
M302 S190	 								; set min extrude temp to 190 now above preheat settings have been set
M603 U100 L0								; Set unload and load lengths
M851 Z-2.56			   		  				; Set Z-Offset
C100 X-10 Y-4								; Set bed minimum limits
C101 X295 Y295 Z300							; Set XYZ Max position
C102 X300 Y300         						; Set a bed size of 300x300
C29 L10.00 R268.20 F10.00 B290.50 N9 T45 	; Set mesh levelling options
C125 X0 Y0 Z20	     		  				; Setup park position
M203 E45									; Set extruder max feedrate
M92 E430.50			   						; Set E-steps
M301 P22.64 I2.57 D49.81 					; Set hotend PID values
M304 P20.69 I2.25 D47.59					; Set bed PID values
C104 U1 T300          						; Set max hotend temp to 300
C412 M1              						; Filament sensor active mode: (M0:LOW, M1:HIGH, M2:MOTION)
M500										; Save all settings
;-----------------------------------------------------
G4 S1                  						; Wait a second
M300 P200              						; Beep
M117 Configuration Applied

**Comment by mriscoc** [comment]
Seems to be a problem with the CRTouch connection or a stuck pin.

**Comment by TheCableGuy99** [comment]
G28 works 5 out of 5 times.

Probe test with 10 fast down and ups works 5 out of 5 times as well.

I can only reproduce it using the tramming wizard.

**Comment by TheCableGuy99** [comment]
To add to this:
I just ran a UBL 9x9 probe and received this error:
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Probing Failed
Recv: Probing mesh point 52/81.
Recv: Error:!! STOP called because of BLTouch error - restart with M999

It does point to a probe error but I would like to point out that during the probing the pin is not retracted, just partially pushed in until it triggers.

What are your thoughts?

**Comment by mriscoc** [comment]
It can't be confirmed with the current precompiled binaries.
Disable HS mode. It could be an F4 bug.

**Comment by DanMan32** [comment]
I suspect the CR-Touch as well, shouldn't ever turn red, either blue or magenta.
Only time you might see it red is on first powerup as the board and firmware start up, where the board hasn't yet initialized communications with the Touch.

Perhaps run BL-Touch tests?

**Comment by TheCableGuy99** [comment]
Okay, I can confirm this is not a bug. The probe is faulty after more testing.

Sorry to waste your time.
