### ISSUE TITLE
Random Chinese character artifacts

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#496]
I'm getting these random Chinese characters at different times. usually when the printer is performing a command, these artifacts show up in random places. 

![random Chinese characters](https://user-images.githubusercontent.com/18502096/200982076-d4e9a31c-a180-48b1-a3e4-fe232e2cd0bc.jpg)

**Comment by mriscoc** [comment]
SKR board? +V disabled in USB cable?

**Comment by MartinBzm** [comment]
I have the same problem. I have an Ender 3v2 but not (yet) updated the firmware of the display.
Maybe that is *my* problem?
Also what do you mean by disabling +5 in USB cable: Should it be disabled/disconnected or not?

**Comment by classicrocker883** [comment]
this is a creality 4.2.7 board. nothing connected to usb

**Comment by classicrocker883** [comment]
@MartinBzm disabling 5v from the usb is an option so power doesn't back feed to the mainboard. if you ever had connected the printer via USB and shut it off, you may notice the mainboard stays powered on because of this.

I'm not so sure that the problem is because of the lcd firmware (DWIN_SET) the artifacts may be due to conflicting code, or something like the address and bytes need updating.

**Comment by classicrocker883** [comment]
I found it to be Input_shaping. I implemented the more recent Marlin code with this enabled, and it has caused issues. So for now input_shaping is disabled if ProUIex is to be enabled.

**Comment by mriscoc** [comment]
ProUI extensions works with the corresponding published sources.
