### ISSUE TITLE
the firmware don't recognize my sd gcode

### ISSUE THREAD

**Issue by scyther149** [mriscoc/Ender3V2S1#499]
**Describe the bug**

**To Reproduce**
1. i saved the .gcode with the script correctly
2. i turn on the ender 3 v2 and the machine don't recognize my .gcode

**Expected behavior**
see my gcode with a thumbnail in the print screen.

**Screenshots**
the script installed correctly

![222](https://user-images.githubusercontent.com/93342262/201198100-6141b04f-90fd-432b-a215-606f2ddc0b8b.jpg)

all the .gcode in the sd

![111](https://user-images.githubusercontent.com/93342262/201198058-3277e226-d9a1-4ceb-a4cc-970b363ab03d.jpg)

the print screen

![333](https://user-images.githubusercontent.com/93342262/201198231-380c3a38-2688-499e-b8b9-fae84221181c.jpg)

the firmware version (i tested "Ender3V2-422-MM-20220816" too)

![444](https://user-images.githubusercontent.com/93342262/201198289-49f1ec79-037d-4471-9588-384705804f0f.jpg)

the motherboard screen

![b154e008-adef-48a0-92e3-69c26142b01e](https://user-images.githubusercontent.com/93342262/201205308-06dddb54-b0f6-4aae-917b-e4b15c2dd503.jpg)

I have other 2 ender 3 v2 more and they can read the gcodes fine

![da731f4a-b548-4d32-8d1d-cb99bddf4d57](https://user-images.githubusercontent.com/93342262/201205517-4fc37081-2133-4504-9e55-c130855f5a6b.jpg)

I only have this error with my "green" ender (i was trying appears the thumbnail feature).
If i change this firmware for another one, it can read the gcodes well... i only have the problem with this

![d7306f3c-cf00-4be9-a227-2a01b608a39d](https://user-images.githubusercontent.com/93342262/201205766-3efa3bc3-9dd3-4300-ba21-6fa9217e52f6.jpg)

**Version (please complete the following information):**
"Ender3V2-422-MM-20221002.bin"
and i tested
"Ender3V2-422-MM-20220816,bin" too

**Additional context**
I have Cura 5.0.0.

**Comment by classicrocker883** [comment]
if the firmware works on other machines, then this is only particularly related to that machine. either the SD card isn't formatted correctly, or your SD card reader is malfunctioning, like a solder joint may need to be reflowed.

**Comment by scyther149** [comment]
> if the firmware works on other machines, then this is only particularly related to that machine. either the SD card isn't formatted correctly, or your SD card reader is malfunctioning, like a solder joint may need to be reflowed.

the sd is formatted fine because it work in other my other machines... and the sd card read it fine when i installed other firmware, only don't work with this in particulary, if i come back to fabric or i install other firmware it works again...
there's something like a bug with a specific series i think, the machine that don't work is my newest ender 3 v2, but is weird because is 4.2.2 too, like the others 2 olders

**Comment by MarkforU** [comment]
I got newest V2 and installed with a SanDisk 32gig card, fast card, newish card. Also have a Ender 3 modded has, 4.2.7 board in it. No problems. The thing is, that slot you drag your card in and out of, my first machine the board wasn't in there correctly and the card went right over the top. I'm guessing also, a bad solder joint or its not making correct contact, or a bad card...don't use Creality 8gig cards either, they fail at any given time.

**Comment by mriscoc** [comment]
Do your printers have any hardware differences?

**Comment by scyther149** [comment]
> Do your printers have any hardware differences?

the 3 screen motherboard looks pretty similar, and the 3 printers are 4.2.2, is it okay? or what do you mean with a hardware difference?

![SCR](https://user-images.githubusercontent.com/93342262/201373891-f8813fdb-0053-44ee-ab68-29845ca44a18.jpg)

PD: Thank you for respond me, Miguel! I'm from Argentina, we can continue in spanish if you want... I sent you a message in facebook a few days ago, i wanted personalize the visual appart of the printers, i did it with other firmware [https://github.com/jyers/marlin/releases?page=2](url) "E3V2-Default-v4.2.2-v2.0.1" + DWIN_SET(Original), when i upgraded this "thumbnail firmware" (Ender3V2-422-MM-20220816) almost all the icons work, but some of they don't, they crashed, that's because the name of the jpg inside the 9.ico don't are the same i think, can do you share with me the 9.ico of this firmware? the dwin_set folder i mean... i'm doing some skins of pokemon for the printers hahaha
These are the skins in the Jyers/Marlin firmware

![Ender 3 v2](https://user-images.githubusercontent.com/93342262/201374697-764bfe12-e709-40e9-9b70-54e71ed6775e.jpg)

and those are the icon fails with this (again... that's for the incompatibility names in the 9.ico i think)
![baa34654-c8a3-4c73-87a7-1c6cce610aef](https://user-images.githubusercontent.com/93342262/201376068-d6f6f0e9-cf75-425a-9aff-d1aaeb4ca329.jpg)
https://user-images.githubusercontent.com/93342262/201376072-37086168-5076-42b5-b6d2-ccfbd77417a0.mp4

**Comment by mriscoc** [comment]
>what do you mean with a hardware difference?

I am referring, for example, to memory card extenders. There is a item in Advanced settings menu: `Media Update` that force to re-read the file system of the memory card when listing files.

About screen icon assets see here: https://github.com/mriscoc/Ender3V2S1/tree/Ender3V2S1-Released/display%20assets

**Comment by mriscoc** [comment]
No more user feedback
