### ISSUE TITLE
Print is stuttering when printing mainly on bends

### ISSUE THREAD

**Issue by fwe01** [mriscoc/Ender3V2S1#508]
Im have a Ender 3 S1 with F1 soc. currently using the latest UBL firmware.

I notice that my print start to stutter when printing skirt. so i think maybe its beacuse the firmware corrupted or something so i reinstalled it. start a test print and all went well.

i then do the auto build mesh (memory slot 0), and start another test print with the same gcode. and it start stuttering again. i stop the print and tried to load a mesh from memory slot 1 which when i check is an empty mesh. and start another test print. this time it printed well without stuttering at all.

i dont know whether my setting is wrong or not. i use 9x9 mesh, with maximized area, and with HS mode turn off for the probe.

thankyou in advance

**Comment by fwe01** [comment]
This is the GCode i use

[CE3S1_04_02_400_ABS_xyzCalibration_cube.zip](https://github.com/mriscoc/Ender3V2S1/files/10045755/CE3S1_04_02_400_ABS_xyzCalibration_cube.zip)

**Comment by fwe01** [comment]
i am trying to see what happen if i build with smaller mesh

**Comment by mriscoc** [comment]
Format or change to a faster SD card.

**Comment by fwe01** [comment]
the issue did not happen on 8x8 mesh.

**Comment by fwe01** [comment]
> Format or change to a faster SD card.

I will try this fix and inform the result. thankyou for the answer
