### ISSUE TITLE
Creality Cloud-Octoprint Plugin in Ender3V2-422-BLT not working

### ISSUE THREAD

**Issue by wangrui1573** [mriscoc/Ender3V2S1#513]
When I use the firmware Ender3V2-422-BLT in Ender3 V2, the Octoprint Creality Cloud-Octoprint Plugin does not work, it repeatedly prompts that the model fails to obtain, even if I manually modify the model, can I customize the model or device name in the firmware

I think if I can change the name in the firmware to the official name, maybe the Creality Cloud-Octoprint Plugin will work

![image](https://user-images.githubusercontent.com/42831156/203011452-02780f92-5820-4231-981c-282eddb3a3eb.png)

**Comment by mriscoc** [comment]
I did not test the firmware with that plugin, maybe you can request to the plugin developer what the printer firmware needs to be recognized.

**Comment by wangrui1573** [comment]
Thanks , I modified the plugin's script to use manually specifying the devicename instead of reading the machine value and it's back to normal now

**Comment by wangrui1573** [comment]
fixed:
https://github.com/wangrui1573/OctoPrint-CrealityCloud-With-Video
