### ISSUE TITLE
Remove auto home from Z probe wizard

### ISSUE THREAD

**Issue by shmink** [mriscoc/Ender3V2S1#514]
In the Z probe wizard section I'd like to see the _Auto home_ option removed. I just made the mistake of setting my Z offset after selecting auto home instead of Z home. 

I assume there is some value that is added to the Z value, maybe 10mm, just a guess. 

As a result, I set my Z offset from this and starting a print crashed the nozzle into the print bed. My fault completley but I'm not sure the point of the auto home in the Z probe wizard as it complicates the matter.

**Comment by mriscoc** [comment]
The first option is a forced auto home that allow to the printer to get a well known XYZ position. "Move Z to home" does an optional XY home.
