### ISSUE TITLE
Z-Ofset not working (SKRMINI E3 V3)

### ISSUE THREAD

**Issue by gsuresh2u** [mriscoc/Ender3V2S1#517]
Sir, i changed my Ender3 V2 board to SKRMINIE3_V3
and i am using this firmware on that new board
i have used special configurations for this board
only i have enabled PSU control for Auto Shutdown after print
my Z-Offset is 3.23 mm (using Microswiss Direct drive Hotend)
after setting that 3.23 , stored settings, and restarted printer
that 3.23 offset is showing fine
But when start print, it is starting print in mid air, without takign that offset
i am attaching my Configs
Please check
[Configs.zip](https://github.com/mriscoc/Ender3V2S1/files/10073429/Configs.zip)

**Comment by mriscoc** [comment]
In a terminal try
```gcode
G0 Z0 F300
```
Z-offset with a probe like bltouch is a NEGATIVE number.

**Comment by gsuresh2u** [comment]
Yes, its negative -3.23
once its saved, printing starting in mid air not taking that Probe offset
once printer off and on again, after starting printing, same mid air printing
so, i am adjusting z offset when it is printing , so 2 nd time z offet is stored as -6.46 (3.23*2)
after restart printer and printing other, again same procesure, now offset is -9.69 (3.23*3)
every time its increasing, 
i tried with G0 Z0 F300, its stopping Z at height 3.23 (my offset)
so i think its a bug, Please check my configurations attached in 1 st post

**Comment by mriscoc** [comment]
So maybe the problem is not Z-offset is your Z-home. Did you try with https://github.com/mriscoc/Ender3V2S1/releases/download/20221002/Ender3V2-SKRME3V3-BLTUBL-20221002.bin ?

**Comment by gsuresh2u** [comment]
Sorry, my bad
i found the problem, its baudrate
Now enabling PSU control with z offset is working fine
Thank you so much
