### ISSUE TITLE
print head Start again at other Position 

### ISSUE THREAD

**Issue by ender3v2** [mriscoc/Ender3V2S1#522]
Hi.  Have I noticed that when I take a break to change the filament, the print head doesn't continue printing exactly where it left off?  It's shifted a bit.

**Comment by mriscoc** [comment]
Not a firmware issue, check your physical adjustments, belts, eccentric wheels, etc.

**Comment by ender3v2** [comment]
My printer runs perfect. Its only 1mm at Y postponed to front

**Comment by mriscoc** [comment]
Check the parking position, when the printer pauses the head goes to the parking position, maybe that position is unreachable.
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
