### ISSUE TITLE
Long filename support with scroll

### ISSUE THREAD

**Issue by ender3v2** [mriscoc/Ender3V2S1#523]
Hi.  Have the 4.2.7 board ender 3 v2.  The text stops with a long filename and does not scroll any further.  How to fix this ?

**Comment by mriscoc** [comment]
Can you provide the link to the firmware that you flash and an example of the gcode filename?
Only the status line message has scrolling capability.

**Comment by ender3v2** [comment]
I have the latest release installed,  Ender3 V2/S1 Professional Firmware 20221002. It occurs with every stl.  The text stops at all and does not scroll any further.

**Comment by mriscoc** [comment]
Post a video, there isn´t any problem with large filenames currently in the firmware.

**Comment by mriscoc** [comment]
No more user feedback
