### ISSUE TITLE
Incorrect offset of progress bar with some stock screen icon set

### ISSUE THREAD

**Issue by LunarstarFurry** [mriscoc/Ender3V2S1#532]
**Describe the bug**
Progress Bar doesn't seems right on Ender 3 V2 Neo?

**To Reproduce**
1. Just start Print

**Expected behavior**
I would hope the Progress bar being inside the square instead xD

**Screenshots**
![PXL_20221130_023220675](https://user-images.githubusercontent.com/36251959/204693909-7a56f545-fd78-4937-8268-19bb5fc3c291.jpg)

**Version (please complete the following information):**
2.1.3 20221002

**Additional context**
Or is that a settings I need to change myself pretty new in 3D Printing.
Oh and as far as what I see V2 Neo not showing Model Preview should be normal?

**Comment by mriscoc** [comment]
That can only be fixed If the screen is DWIN or DACAI with the icon set of: https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display

**Comment by LunarstarFurry** [comment]
That does indeed fix it Thank you! < 3

**Comment by LunarstarFurry** [comment]
BTW If I understand correctly there's currently no way for DACAI display to show Model Preview?

**Comment by mriscoc** [comment]
> 

We need that Creality release the source code of Ender3V2 Neo to be able to use the DACAI API

**Comment by LunarstarFurry** [comment]
hmmm Alright  Thx eitherway!
