### ISSUE TITLE
Is the hotend fan on ender 3 S1 with F1 chip always on?

### ISSUE THREAD

**Issue by fwe01** [mriscoc/Ender3V2S1#536]
I have ender 3 S1 with F4 chip. but the mainboard got some problem so it got swap a new board from the store. now it has F1 chip. what i notice is. with the old board the fan is only on when the hotend is hot. is F1 always on? and what can i do to achieve similar behavior like the F4 chip.

**Comment by mriscoc** [comment]
Hotend fan is always on in Creality boards, only part fan is controllable. It is not a firmware issue.
