### ISSUE TITLE
Stepper moves out of bounds when presenting print in end

### ISSUE THREAD

**Issue by davkvi** [mriscoc/Ender3V2S1#54]
Hi!

The y axis stepper moves out of bounds (makes clicking sounds when it hits the end of travel) when presenting the printed object at the end. Might have relation to home min x/y being a negative value?

**Comment by mriscoc** [comment]
Hi, I suppose that you are referring to Ender3S1, reduce the y max position and bed size.

**Comment by davkvi** [comment]
> Hi, I suppose that you are referring to Ender3S1, reduce the y max position and bed size.

Ender3v2. Will do and report back

**Comment by AntonyLeons** [comment]
This also happened to me on the 20220220 build

**Comment by mriscoc** [comment]
> This also happened to me on the 20220220 build

Have you a stock printer, or has the printer a print head mod? If the latter is true, you must adjust the physical limits to match your configuration.

**Comment by AntonyLeons** [comment]
Stock ender 3 v2

**Comment by mriscoc** [comment]
> Ender3v2. Will do and report back

The Ender3v2 must have min X/Y settled to 0 in the stock, if you need to change the mins because your mods, you must reduce also the max position to match the real movement capacity of your printer.

**Comment by AntonyLeons** [comment]
I concluded this happens when you start a print with the bltouch gcode. this happens to me on the X axis though At 0.

**Comment by AntonyLeons** [comment]
just happend on y 0. while auto homing

**Comment by AntonyLeons** [comment]
think I figured it out, the bed it too low so scarpes the back preventing the switch from being pressed
