### ISSUE TITLE
TJC displays needs a special custom compile

### ISSUE THREAD

**Issue by YanivKrit** [mriscoc/Ender3V2S1#542]
EDIT: Check the fix here: https://github.com/mriscoc/Ender3V2S1/issues/542#issuecomment-1345621590

**Describe the bug**
after using trimming wizard it doesn't show the numbers on the circules and after using the build mesh feature the display is unreadable and only when I turn off the LCD the display comes back

**To Reproduce**
1. Go to prepare
2. Click on build mesh/ trimming wizard
4. See attached pictures 

**Expected behavior**
see the numbers after using the trimming wizard and a working display with results and buttons after using the mesh build

**Screenshots**

![TJC_CircleMesh](https://github.com/mriscoc/Ender3V2S1/assets/2745567/5a738a66-d9ff-46fb-b824-0c561c2eff57) ![TJC_SquareMesh](https://github.com/mriscoc/Ender3V2S1/assets/2745567/46299627-2648-406f-93d8-27ff04dc0f8c) ![TJC_Plot](https://github.com/mriscoc/Ender3V2S1/assets/2745567/d6a42db9-2bcb-4648-9049-43cc7cbb8f12) 

![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/00a69166-8219-47e3-a93e-fa39ad47639d)
![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/9177ab9c-acb1-483c-9214-b0f180d6d36b)
![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/b9200430-9718-44ed-a8c4-b31042d93812)

**Version (please complete the following information):**
Ender3S1-F4-20221002.bin

**Additional context**
Thank you for a great frimware - it makes the leveling and operation much easier

**Comment by mriscoc** [comment]
EDIT: Some special TJC binaries have been released here: https://github.com/mriscoc/Special_Configurations/releases/tag/tjc

Some TJC displays need [updated firmware](https://github.com/mriscoc/Ender3V2S1/blob/Ender3V2S1-Released/display%20assets/tjc_update.zip?raw=true), to enable G-code preview and boot properly, extract the content of the zip file to the root of the SD card.  

Currently, this display needs a custom compile (special firmware version) to solve some DWIN API incompatibilities with the mesh viewer (missing value labels, line artifacts, etc.). Select TJC as display unit in the Configurator:

![The Configurator](https://raw.githubusercontent.com/mriscoc/Special_Configurations/main/images/Configurator.png)

**TJC** display 
![TJC](https://user-images.githubusercontent.com/2745567/206931166-24185525-e377-472e-9bed-37a39aab24fb.jpg)

For be able to display the G-code preview, the image needs to be square, set for example 180x180 in the post processing script for Cura or in Prusaslicer settings.

**Comment by seene** [comment]
Same Problem here. 
With a brand new Ender 3 S1 F4 :-)

**Comment by ugodnihc** [comment]
Does this screen issue affect the actual operation of the firmware beyond graphical display? I'm unable to see the numbers, but am able to still get the tramming wizard to confirm that it is flat - are the results dependable with an incompatible screen?

**Comment by seene** [comment]
So far, no problems while printig for me

**Comment by YanivKrit** [comment]
a quick update - just installed fw [Ender3S1-F4-20221222.bin](https://github.com/mriscoc/Ender3V2S1/releases/download/20221222/Ender3S1-F4-20221222.bin) and the display seems better - during calibration the display only missing the numbers and the buttons and the rest is fine but when going to "view mesh" the display remains the same

![5895241191476279708_121](https://user-images.githubusercontent.com/65375122/211153070-20cf8877-5ca2-4522-b962-f684f1afa876.jpg)

**Comment by MorphMixology** [comment]
I bought an Ender 3 Pro. I wanted to use this firmware and the Micro Swiss DD setup I had on my E3V2s before. I ordered this screen from Amazon thinking it was what I needed. Apparently I got the stupid screen that doesnt work right with this? Can anyone help?

https://www.amazon.com/dp/B098WFCQYW?psc=1&ref=ppx_yo2ov_dt_b_product_details

![IMG_6799](https://user-images.githubusercontent.com/104745488/224233281-5aea7909-621b-4c24-81fb-019919776eca.jpeg)

**Comment by jmealo** [comment]
I'm having issues with the mesh viewer, otherwise the screen seems to work fine. It seems the F4 variant comes with the incompatible screens :(. As far as I can tell, everything else works well. If you're going to pair this with OctoPrint (and follow the setup guide in the wiki of this repo)... I'm not deterred from using the firmware.

**Comment by mriscoc** [comment]
@migsun does you TJC screen this problem also? https://github.com/mriscoc/Ender3V2S1/issues/542#issue-1487494079

**Comment by mriscoc** [comment]
Hi TJC users, I want to identify some issues with TJC displays

Did you see this update:
![image](https://user-images.githubusercontent.com/2745567/226531138-423ab9aa-ecec-481c-9244-1d6094d4039c.png)

inside of this zip? https://file2-cdn.creality.com/file/753e7215008c87f6499da6bd4e414ea5/Ender-3S1_HWv24S1_301_SWV3.0.4_C_F401_FDM_LASER.zip

**Comment by asyxpaul** [comment]
Got the update and installed it.  Unfortunately it still didn't fix the issue with the numbers on tramming.
![20230321_122013](https://user-images.githubusercontent.com/121580791/226674869-f6170a76-551b-47dc-b7b1-802239d480dd.jpg)
![20230321_122248](https://user-images.githubusercontent.com/121580791/226674893-81ad8aaf-5ddf-48d0-8bca-6309209e055d.jpg)

**Comment by mriscoc** [comment]
@asyxpaul please test with this version:

[Experimental-Ender3V2-427-BLTUBL-MPC-TJC-20230321.zip](https://github.com/mriscoc/Ender3V2S1/files/11032060/Experimental-Ender3V2-427-BLTUBL-MPC-TJC-20230321.zip)

**Comment by asyxpaul** [comment]
It now has numbers but looks a little off
![20230321_140047](https://user-images.githubusercontent.com/121580791/226700660-a169b3e6-c075-4ede-b6a4-7cad21761383.jpg)

**Comment by mriscoc** [comment]
Sorry, I made a mistake, re-download and try again please.

**Comment by CalvinYohannes** [comment]
> @asyxpaul please test with this version:
> 
> [Experimental-Ender3V2-427-BLTUBL-MPC-TJC-20230321A.zip](https://github.com/mriscoc/Ender3V2S1/files/11032183/Experimental-Ender3V2-427-BLTUBL-MPC-TJC-20230321A.zip)

Does this work for S1 F4?

**Comment by CalvinYohannes** [comment]
> Hi TJC users, I want to identify some issues with TJC displays
> 
> Did you see this update: ![image](https://user-images.githubusercontent.com/2745567/226531138-423ab9aa-ecec-481c-9244-1d6094d4039c.png)
> 
> inside of this zip? https://file2-cdn.creality.com/file/753e7215008c87f6499da6bd4e414ea5/Ender-3S1_HWv24S1_301_SWV3.0.4_C_F401_FDM_LASER.zip

I tried clicking this link is not accessible
![Uploading Screenshot_20230322_042050.jpg…]()

**Comment by CalvinYohannes** [comment]
> Hi TJC users, I want to identify some issues with TJC displays
> 
> Did you see this update: ![image](https://user-images.githubusercontent.com/2745567/226531138-423ab9aa-ecec-481c-9244-1d6094d4039c.png)
> 
> inside of this zip? https://file2-cdn.creality.com/file/753e7215008c87f6499da6bd4e414ea5/Ender-3S1_HWv24S1_301_SWV3.0.4_C_F401_FDM_LASER.zip

I tried clicking this link is not accessible
![Screenshot_20230322_042050](https://user-images.githubusercontent.com/54514178/226749678-159f20b4-24d9-44cb-af2c-64ff6abcee29.jpg)

**Comment by mriscoc** [comment]
Look at the Creality Cloud website

![image](https://user-images.githubusercontent.com/2745567/226770896-58b934e1-9ee5-4c18-a1af-c33cfdff0c9c.png)

**Comment by CalvinYohannes** [comment]
> Look at the Creality Cloud website
> 
> ![image](https://user-images.githubusercontent.com/2745567/226770896-58b934e1-9ee5-4c18-a1af-c33cfdff0c9c.png)

This is TJC?

I mean, does this link work for S1? Because the link only says V2
https://github.com/mriscoc/Ender3V2S1/files/11032183/Experimental-Ender3V2-427-BLTUBL-MPC-TJC-20230321A.zip

**Comment by mriscoc** [comment]
> I mean, does this link work for S1?

No, please don't download or flash anything if you don't know what to do. There is a high risk of brick your printer.

**Comment by mriscoc** [comment]
Sorry. I deleted all the TJC updates to protect beginner users from incorrect firmware flashing. If you are an advanced user and want to test the TJC updates please join the Telegram test group.
The TJC fixes are available to all users by custom compiling an special TJC version, download the [main sources](https://github.com/mriscoc/Ender3V2S1), the Configurator from the [Special_Configurations](https://github.com/mriscoc/Special_Configurations) repository and select TJC as the display unit.

**Comment by mriscoc** [comment]
TJC Updates, Plot and Mesh Viewer are working
![TJC_pid_plot](https://user-images.githubusercontent.com/2745567/226774775-8290d55e-eb67-424d-8484-ae6f76c6492d.jpg)
![TJC_mesh_viewer](https://user-images.githubusercontent.com/2745567/226774784-88a5fcb9-e2fc-4f03-aa4e-2933ff4ab9a3.jpg)

**Comment by CalvinYohannes** [comment]
does it need a special folder?

**Comment by ugodnihc** [comment]
Awesome! Can’t wait for the next release, been waiting to use a custom firmware for some time now :)

**Comment by gilla013** [comment]
@mriscoc Is displaying thumbnails for TJC screens parts of this hotfix or related to something else?

**Comment by mriscoc** [comment]
> Is displaying thumbnails for TJC screens parts of this hotfix

No, currently TJC screens cannot display preview images.

**Comment by gilla013** [comment]
OK thanks for the info

**Comment by Ripwords** [comment]
Will this be included in the next firmware release or do I still need to custom compile a TJC firmware?

**Comment by mriscoc** [comment]
> Will this be included in the next firmware release or do I still need to custom compile a TJC firmware?

Currently only by custom compile. I don't know if I will release in the future some precompiled versions for TJC.

**Comment by gilla013** [comment]
I did a custom compilation and flashed it and I can confirm these changes also work on my S1 with F4 board.
Any change the thumnail preview images will be fixed? I don't know it if works on stock firmware. I directly flashed this one.

**Comment by YanivKrit** [comment]
I have microcontroller "STM32F401RCT6" and when compiling, choosing STM32F401RC_Creality 256K on marling auto build in VSCode, I get the errors:
```
c:/users/aaa/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/STM32F401RC_creality/firmware-20230408-180820.elf section `.rodata' will not fit in region `FLASH'
c:/users/aaa/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: region `FLASH' overflowed by 9124 bytes
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\STM32F401RC_creality\firmware-20230408-180820.elf] Error 1
```

did you get this error too? if so how you fixed it?

EDIT:
=============================================================
OK so after recreating the configuration file without the UBL there is no change, still no numbers and sometimes the screen returns to be like in the beggining, the steps I have done:
1. Download the [Source Files](https://github.com/mriscoc/Ender3V2S1/archive/refs/tags/20230312.zip)
2. Download [Special_Configurations](https://github.com/mriscoc/Special_Configurations)
3. Open Configurator.pyw and configure Ender3S1->301F4->TJC->BLT & uncheck UBL->T1->no features, then clicking Auto then Set Config Then Generate
![Configurator pyw](https://user-images.githubusercontent.com/65375122/230731837-6fa1a87a-65e1-4ebd-bde2-0ea59bec6642.png)
5. Copy from the generated folder platformio.ini to the source folder
6. Copy Configuration.h & Configuration_adv.h to Marlin folder in the source folder
7. Install [VSCode](https://code.visualstudio.com/) with [PlatformIO](https://platformio.org/install/ide?install=vscode) and [Auto Build Marlin](https://marlinfw.org/docs/basics/auto_build_marlin.html) extensions
8. in VSCode go to PlatformIO in "Activity Bar" and open the source folder
9. in VSCode go to Auto Build Marlin in "Activity Bar" -> clicking "Show ABM Panel" -> choosing build for "STM32F401RC_Creality (256K)" because I have STM32F401RCT6 microcontroller and by the datasheet it has 256kb flash size
10. copy the created bin file "firmware-date-time.bin" to the printers SD-Card folder "STM32F4_UPDATE"
11. power off Printer-> insert the SD-Card to the printer -> power on -> make sure fw was updated (date and time are correct for the version)
12. creating mesh 3x3 and tramming - no digits on the circles


**on step 3 if the "UBL" is checked then on compilation I get the errors above.

**Comment by mriscoc** [comment]
> 1. Download the [Source Files](https://github.com/mriscoc/Ender3V2S1/archive/refs/tags/20230312.zip)

You are downloading old sources.

**Comment by YanivKrit** [comment]
Thank you, I have downloaded the code from the main git and it works! (with some display glitches but still better)
do you have any suggestion about the UBL?
do you allow me to upload the compiled bin here so people won't have to make all the compilation by themselves?

![5877358163131481004_121](https://user-images.githubusercontent.com/65375122/230734936-d2300c0d-7b82-48c3-a109-81ac7a023738.jpg)

**Comment by mriscoc** [comment]
> region `FLASH' overflowed by

Lack of program memory space

**Comment by mriscoc** [comment]
> do you allow me to upload the compiled bin here so people won't have to make all the compilation by themselves?

Please don't post binaries here, maybe you can do a fork and publish in a release page.

**Comment by drnefarious360** [comment]
> Thank you, I have downloaded the code from the main git and it works! (with some display glitches but still better) do you have any suggestion about the UBL? do you allow me to upload the compiled bin here so people won't have to make all the compilation by themselves?
> 
> ![5877358163131481004_121](https://user-images.githubusercontent.com/65375122/230734936-d2300c0d-7b82-48c3-a109-81ac7a023738.jpg)

How did you compile those modifications so that the values ​​come out? and tried to compile your fix from your github and I don't get the values ​​in my tjc screen.

**Comment by CalvinYohannes** [comment]
> > Thank you, I have downloaded the code from the main git and it works! (with some display glitches but still better) do you have any suggestion about the UBL? do you allow me to upload the compiled bin here so people won't have to make all the compilation by themselves?
> > ![5877358163131481004_121](https://user-images.githubusercontent.com/65375122/230734936-d2300c0d-7b82-48c3-a109-81ac7a023738.jpg)
> 
> How did you compile those modifications so that the values ​​come out? and tried to compile your fix from your github and I don't get the values ​​in my tjc screen.

Hi bro, Do you have a TJC screen file? Please share it for me if it works

**Comment by drnefarious360** [comment]
> > > ¡Gracias, he descargado el código del git principal y funciona! (con algunas fallas en la pantalla pero aún mejor) ¿tiene alguna sugerencia sobre el UBL? ¿Me permite cargar el contenedor compilado aquí para que las personas no tengan que hacer toda la compilación por sí mismos?
> > > ![5877358163131481004_121](https://user-images.githubusercontent.com/65375122/230734936-d2300c0d-7b82-48c3-a109-81ac7a023738.jpg)
> > 
> > 
> > Como compilaste esas modificaciones para que te salgan los valores? e intenté compilar su solución desde su github y no obtengo los valores en mi pantalla tjc.
> 
> Hola hermano, ¿tienes un archivo de pantalla TJC? Por favor compártelo para mí si funciona.

what do you mean by screen file? to screen firmware? I only have the latest version of the mriscoc fw on an ender 3 v2 neo gd32 with a tjc screen. and I can not see the values ​​of the calibration of the bed.

**Comment by mriscoc** [comment]
We have the thumbnail preview working for the TJC display!!

![TJC_preview](https://user-images.githubusercontent.com/2745567/233119888-9b6af36b-66d1-4eb0-8d84-f4d749ab8f81.jpg)

It will be available to the all in the next source release.

**Comment by gilla013** [comment]
Nice work

**Comment by Dilysir55** [comment]
> We have the thumbnail preview working for the TJC display!!
> 
> ![TJC_preview](https://user-images.githubusercontent.com/2745567/233119888-9b6af36b-66d1-4eb0-8d84-f4d749ab8f81.jpg)
> 
> It will be available to the all in the next source release.

When will the next release be??

**Comment by CalvinYohannes** [comment]
> We have the thumbnail preview working for the TJC display!!
> 
> ![TJC_preview](https://user-images.githubusercontent.com/2745567/233119888-9b6af36b-66d1-4eb0-8d84-f4d749ab8f81.jpg)
> 
> It will be available to the all in the next source release.

when will all this be released?

**Comment by variableresults** [comment]
Sign me up for a pre-compiled .bin for the S1 F4 TJC. Mine was a recent purchase, and I suspect there will be more of them out in the wild, so I'm hoping a pre-compiled version will be made since the special compile instructions are a bit beyond me. 

EDIT: Figured out the compile. Just have to follow the steps, though you may have different software depending on Windows / MacOS / Linux as your compiling system (I compiled no problem on MacOS). 

I'm seeing the numbers on the mesh screen as it auto builds the mesh now!

**Comment by mriscoc** [comment]
For request a pre compiled bin file please check: https://github.com/mriscoc/Special_Configurations#these-special-configurations-and-releases-are-sponsored-by-donors

**Comment by kobusestas** [comment]
> I have microcontroller "STM32F401RCT6" and when compiling, choosing STM32F401RC_Creality 256K on marling auto build in VSCode, I get the errors:
> 
> ```
> c:/users/aaa/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: .pio/build/STM32F401RC_creality/firmware-20230408-180820.elf section `.rodata' will not fit in region `FLASH'
> c:/users/aaa/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld.exe: region `FLASH' overflowed by 9124 bytes
> collect2.exe: error: ld returned 1 exit status
> *** [.pio\build\STM32F401RC_creality\firmware-20230408-180820.elf] Error 1
> ```
> 
> did you get this error too? if so how you fixed it?
> 
> # EDIT:
> OK so after recreating the configuration file without the UBL there is no change, still no numbers and sometimes the screen returns to be like in the beggining, the steps I have done:
> 
> 1. Download the [Source Files](https://github.com/mriscoc/Ender3V2S1/archive/refs/tags/20230312.zip)
> 2. Download [Special_Configurations](https://github.com/mriscoc/Special_Configurations)
> 3. Open Configurator.pyw and configure Ender3S1->301F4->TJC->BLT & uncheck UBL->T1->no features, then clicking Auto then Set Config Then Generate
>    ![Configurator pyw](https://user-images.githubusercontent.com/65375122/230731837-6fa1a87a-65e1-4ebd-bde2-0ea59bec6642.png)
> 4. Copy from the generated folder platformio.ini to the source folder
> 5. Copy Configuration.h & Configuration_adv.h to Marlin folder in the source folder
> 6. Install [VSCode](https://code.visualstudio.com/) with [PlatformIO](https://platformio.org/install/ide?install=vscode) and [Auto Build Marlin](https://marlinfw.org/docs/basics/auto_build_marlin.html) extensions
> 7. in VSCode go to PlatformIO in "Activity Bar" and open the source folder
> 8. in VSCode go to Auto Build Marlin in "Activity Bar" -> clicking "Show ABM Panel" -> choosing build for "STM32F401RC_Creality (256K)" because I have STM32F401RCT6 microcontroller and by the datasheet it has 256kb flash size
> 9. copy the created bin file "firmware-date-time.bin" to the printers SD-Card folder "STM32F4_UPDATE"
> 10. power off Printer-> insert the SD-Card to the printer -> power on -> make sure fw was updated (date and time are correct for the version)
> 11. creating mesh 3x3 and tramming - no digits on the circles
> 
> **on step 3 if the "UBL" is checked then on compilation I get the errors above.

I tried this but get the region `FLASH' overflowed by 8948 bytes message with the same config, using the latest code from the repo. Thoughts?

**Comment by mriscoc** [comment]
> ![5877358163131481004_121](https://user-images.githubusercontent.com/65375122/230734936-d2300c0d-7b82-48c3-a109-81ac7a023738.jpg)

TJC can't draw lines very fast like DWIN, so a compromise must be reached between time and drawing. It can draw full circles but at slow speed or draw the lines interleave for a more faster circles. I choose for now the last option, it is not a glitch or bug.

**Comment by ArkhXI** [comment]
Recently bought an S1, have the same issue. Other than this everything works correctly, so i guess ill wait for a precompiled firmware.

**Comment by CalvinYohannes** [comment]
> Recently bought an S1, have the same issue. Other that this everything works correctly, so i guess ill wait for a precompiled firmware.

yes i also want ready made one

**Comment by mdemirtas1** [comment]
i hope the precompiled firmware relased soon for tcj screens

**Comment by mriscoc** [comment]
Special TJC binaries have been released here: https://github.com/mriscoc/Special_Configurations/releases/tag/tjc
Some TJC displays need [updated firmware to enable G-code preview](https://github.com/mriscoc/Ender3V2S1/blob/Ender3V2S1-Released/display%20assets/tjc_update.zip?raw=true)

**Comment by agr8lemon** [comment]
A bit a newbie question on the special config's posted. I see the following:

Ender3S1-F1-UBL-TJC-MPC-20230524.bin
and
Ender3V2-422-MM-TJC-MPC-20230524.bin

but nothing for the Ender3V2-422-UBL. 

Will the Ender3S1-F1-UBL work for my Ender 3v2?

Thanks and sorry for this basic question.

**Comment by mriscoc** [comment]
> Will the Ender3S1-F1-UBL work for my Ender 3v2?

No, you need a 422 firmware for a 4.2.2 board.

**Comment by agr8lemon** [comment]
Ahh ok, So no UBL yet for the TJC for 422 boards yet. Thank you for all your work!

**Comment by mriscoc** [comment]
It is not possible for me to compile all possible variants for free, so I prioritize the most used configurations. Any other configuration needs to be [compiled by the users](https://github.com/mriscoc/Special_Configurations#creating-your-own-custom-configuration) or request a custom binary: https://github.com/mriscoc/Special_Configurations#how-to-request-a-custom-build

**Comment by jmealo** [comment]
Is this just a matter of getting more CI minutes on GitHub?

**Comment by yurecz** [comment]
Hello Mriscoc,

Many thanks for all of your work done with the Professional firmware for the Ender!

I have Ender 3 S1 F4 with the TJC display and using the binary Ender3S1-F4-LA-20230524.bin without problems, except that the model preview does not work, and the numbers do not appear in the automatic bed mesh leveling menu as described in this thread.

My question: Would it work to compile the binary by myself for the TJC together with the Linear Advance and BTL without UBL and other features? My concern is that the F4 will not be able to handle the size of the compiled binary. I ask the question because see that the features for F4 always cut in comparison to the F1.

Best regards

**Comment by mriscoc** [comment]
> Would it work to compile the binary by myself for the TJC together with the Linear Advance and BTL without UBL and other features?

The different chips used on the various Creality boards have different amounts of flash ROM for firmware storage, this means that different boards will be limited by ROM size to which firmware features can be enabled while still allowing the firmware to fit. The F4 RCT6 chip has the smallest amount of usable ROM. The maximum firmware size for the F4 is 192k, any compiled firmwares over 192k will not work due to the mentioned size limitations, the precompiled firmwares for the F4 boards have some minor features removed to allow for stuff like LA and UBL and other new marlin features. https://github.com/mriscoc/Ender3V2S1/issues/648
