### ISSUE TITLE
Creality 4.2.7 board with Voxelab Aquila screen knob motion reversed

### ISSUE THREAD

**Issue by Skippy-the-meh** [mriscoc/Ender3V2S1#543]
I have what started life as a Voxelab Aquila X2. The board has since been replaced with the Creality 4.2.7 board on which i've installed the Professional Firmware. Previously i was running Jyers. With the professional firmware installed the cursor movement on the screen is reversed from the movement of the knob. For example when i rotate the knob clockwise i expect the cursor to move to the right or down. Counter clockwise i expect it to move left or up. What happens is the opposite of that. When i rotate clockwise the cursor moves left or up and counter it moves right or down.

**Comment by mriscoc** [comment]
The Aquila screen has a reversed encoder, so a special version needs to be compiled for that printer with the `REVERSE_ENCODER_DIRECTION` config define enabled. The Configurator will take care about of enable it for you.
![image](https://user-images.githubusercontent.com/2745567/206879719-23e87084-b0dd-4cfa-a316-515604e22a56.png)
