### ISSUE TITLE
Cannot install Pro FW to Ender S1

### ISSUE THREAD

**Issue by ikarus-71** [mriscoc/Ender3V2S1#549]
Hello,

I have a Ender S1 with a board STM32F401, firmware v3.0.3.

I correctly formatted the SD card (FAT32, 4096, MBR) to install firmware and copied the related file.

I insert the card and turn on the printer, but it does not read the card and boots up to the stock firmware. Any thoughts?

Thanks

Murat

**Comment by mriscoc** [comment]
Please check carefully https://github.com/mriscoc/Ender3V2S1/wiki/How-to-install-the-firmware

**Comment by ikarus-71** [comment]
Hello, I do not think instructions on the web site is correct, I have to create a folder in SD card as STM32F4_UPDATE and put the firmware there also, and that was the only way it worked for me. This might be an exception for Ender S1 perhaps, but will be good if you can update instructions for everyone.
Thanks 

Murat

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/How-to-install-the-firmware#manual-installation-for-ender3-s1-with-the-stm32f4-soc

![image](https://user-images.githubusercontent.com/2745567/207747141-a99ecdf8-a4c4-465d-a07f-10e7f45221d7.png)

**Comment by ikarus-71** [comment]
Thank you Miguel, had not recognized this.

It is a great firmware, thanks for developing it!

Murat
