### ISSUE TITLE
XY&Z Axis manual setpoint moves

### ISSUE THREAD

**Issue by I-wish-2** [mriscoc/Ender3V2S1#552]
Has there been any thought to allowing the X Y & Z axis to be manual moved by first dialing in the value you want for the move and then click enter to make the move.  The same as the Extruder does now.  This enhancement would be very helpful when working on the printer and not wanting the axis to just take off when a value is dialed in.  Its hard to stop the mistaken axis move short of powering off the printer.
Regards
Doc'

**Comment by mriscoc** [comment]
This was implemented in the latest experimental version and will be in the next public release.

**Comment by I-wish-2** [comment]
Greetings Miguel,
Thank you for your reply and making the enhancement changes.  I'm using the Linear advance version and it is working great so far although it requires some very fine tuned input values to get the cornering dialed.  Again Thank you.
Doc'
