### ISSUE TITLE
Home off center

### ISSUE THREAD

**Issue by Rsmyth166** [mriscoc/Ender3V2S1#563]
**Describe the bug**
Sprite pro homes off center and probes off the front of the bed

3v2-422-BLTUBL-T13

**Comment by JEBurroughs** [comment]
I don't know crap, but here is the process I use to setup mine and the items I check.
Make sure X and Y stops are set so they both apex the front left corner. This is where I set my Park Head to as well and I changed them to 0,0,20. Manually set those first. Then go to  "Advanced/ Physical Settings" and set the Printer Bed size.. Now Back out to the Main "Advanced/ Mesh Leveling / Mesh Inset" and Set your  Max and Minimum, or it gives you a couple of choices at sets it for you. You can find those numbers by using the "Prepare/ Move Axis" to find how far you can go. Make sure your Probe Offsets are correct. I am using my Fang Mod with a center mounted BLTouch so my numbers are a bit odd from a normally mounted BLTouch. Now you can probe the Z offset and then Go to the Tramming Wizard

https://www.youtube.com/watch?v=p88xGOVdaYQ

**Comment by mriscoc** [comment]
Follow this:
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides
