### ISSUE TITLE
Thermal runaway protection system fails

### ISSUE THREAD

**Issue by TheRealOne78** [mriscoc/Ender3V2S1#586]
So, the thermal runaway is supposeed to stop the printer whenever the thermistor reading is weird, to stop your 3D printer from burning your house.

It does work... but not very well. I'll explain:
So if you want to test the thermal runaway protection, one of the simplest way is to remove the sock and cool your nozzle block while warming up/hot. If the thermistor starts to send suspicious readings such like the nozzle sending a constant temperature while the nozzle still warms up, or the temperature instantly dropping.

So what doesn't work?
Here is a list of what works and what doesn't(if checked, it means it works)
* [ ] Starting to force cool the nozzle when starting to warm up
* [x] Starting to force cool the nozzle when 50% warmed
* [x] Starting to force cool the nozzle when fully warmed

Here are some videos showing my Ender 3 V2 when:
* [Cooling when starting to warm up](https://www.youtube.com/watch?v=qoPrx5_YsAI)
* [Cooling when mid warm](https://youtube.com/shorts/Im4pp7pB97Y)
* [Cooling when fully warmed up](https://youtube.com/shorts/URpz9-MutSE)

To give a reason why this is a bad thing, imagine this:
  1. Your 3D Printer has a defectuous thermistor(whether it's not fully screwed, touching or just doesn't work properly doesn't matter) and you don't know about it.
  2. You start your printer and print something.
  3. You leave.
  4. Meanwhile, the printer heats the heater cartridge more and more while the thermistor reads a value, but only increases  when the air around it gets hotter(but not the same as the nozzle).
  5. Heating cartridge, nozzle block and everything around it gets so hot starts to melt and even burn your 3D printer, maybe even your house!
  6. You're screwed.

_PS: sorry I have to upload these videos on youtube, but I don't have any other alternative_

**Comment by mriscoc** [comment]
I think that it is the normal behavior of Marlin firmware with the stock parameters of Creality configuration files.  As long as there is a positive change in the temperature when the nozzle is heated, no thermal runaway will be triggered.

**Comment by Ariimeow78** [comment]
I can agree with you, but what if the temperature gradually rises but very slow? Wouldn't that be a sign of thermal runaway?

**Comment by mriscoc** [comment]
Could also be an All-metal hot-end with a low power heater, a hot-end and part fan turned on and not good isolated nozzle, a filament with high specific heat. In any case an issue in the main Marlin repository could be better after trying the same configuration with the latest Marlin bugfix.

**Comment by Ariimeow78** [comment]
Alright then, I guess I'll see more on the way.
Thank you for the info.
