### ISSUE TITLE
Ender S1 not displaying print info using Octoprint

### ISSUE THREAD

**Issue by mattfox27** [mriscoc/Ender3V2S1#59]
I just setup octoprint for my S1 and its weird its not showing any of the current print info on the printer screen, its just showing the menu as if nothing was happening.  Its printing though.

**Comment by mriscoc** [comment]
You must follow the instructions from the Wiki: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint

**Comment by mattfox27** [comment]
Thank you
