### ISSUE TITLE
Manual mesh after power on. not working until repeat manual mesh again.

### ISSUE THREAD

**Issue by Blakinas** [mriscoc/Ender3V2S1#600]
**Im not catched exactly, but some how printer starts not using manual mesh values,  after few prints. looks like after power on, or after some time, or after some manual stop. im not shure. but for shure that start to ignore manual mesh. **

What for shure works, that if i do manual mesh, press store setting, then next print manual mesh works.
I have two identical printers. so for this bug, i redone manual mesh, started both printers, and recorded video.
You will see, that first printer is working with manual mesh, while second not.
Both are with the same firmware. both launch the same G-code. 
And both behavior is the same: at least for some prints manual mesh works, but then, at some point id doesnot work.
Please help.

**Not found yet how to reproduce. just after normal usage i see that not working.**

**should compensate mesh values to the bed, until new manual mesh made**

Video:
**https://youtu.be/8hEb5CleXYA**

**Ender3V2-422-MM-20221002**
Firmware version and release date
I enabled Linear advance
K factor 0.2

**Comment by mriscoc** [comment]
The second printer doesn't have the background of the z-offset icon blinking, so leveling is not active, perhaps because the M420 S1 after the G28 is missing from the start g-code script.

**Comment by Blakinas** [comment]
Yes. thank you. 
i added M420 S1, and now manual mesh works.
Case closed.
