### ISSUE TITLE
Printer doesn't save Flow 

### ISSUE THREAD

**Issue by TheBest6337** [mriscoc/Ender3V2S1#620]
When I save the Flow it works as usual, but when I turn off the printer and turn on again it's back again at 100%.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Flow
2. Set it to something different than 100
3. Save it
4. Turn printer off
5. back on again

**Expected behavior**
The Flow should be back at 100% and not the saved percentage.

**Version (please complete the following information):**
Version 2.1.3

**Comment by mriscoc** [comment]
Duplicate https://github.com/mriscoc/Ender3V2S1/issues/260
