### ISSUE TITLE
Linear Advance can't be disabled with K = 0 (Ender 3 V2 4.2.2)

### ISSUE THREAD

**Issue by czy5197** [mriscoc/Ender3V2S1#625]
Just gave the LA experimental version a try, LA is definitely working, but when setting the K value to 0, either in the firmware UI or by using M900 K0, LA is not disabled. M900 command confirms that K value is 0 but there's very heavy compensation on motor movements.

Firmware version is the latest experimental LA firmware for Ender 3 V2 4.2.2. the precompiled one released two weeks ago.

**Comment by mriscoc** [comment]
It could not be LA but the Juntion Deviation.

**Comment by mriscoc** [comment]
No more feedback
