### ISSUE TITLE
Ender 3V2 Bed Visualizer Plugin Gcode from Wiki does not work, only homes

### ISSUE THREAD

**Issue by knuxyl** [mriscoc/Ender3V2S1#640]
The gcode for the bed visualizer plugin do not create nor view the current mesh. All it does is home x,y, and z. and after a while, sends a completely flat bed mesh to octoprint.
I waited to see if it was waiting for bed termperature or something but it didn't set anything and nothing was increasing.
I followed the entire wiki and setup everything as I was told. I have a Ender 3V2 with BLTouch and v4.2.2 w/Dacai screen.

This was tried multiple times after bed tramming and z probe offset setting

This gcode does not initiate bed level mesh creation

> M155 S30  ; set temperature reporting delay, use a value longer than the time it takes for your leveling command to complete.
> G28 XYO   ; Do an optional XY home
> G28 Z     ; Do a Z home
> @BEDLEVELVISUALIZER  ; instruct plugin to start recording responses from printer.
> G29       ; Take a ABL bed leveling mesh.
> M155 S3   ; set the temperature reporting delay back to a shorter time span.

**Comment by mriscoc** [comment]
Check the Wiki and use the g-code sniped according to your leveling version: non UBL or UBL.
