### ISSUE TITLE
Allow absolute parking z position

### ISSUE THREAD

**Issue by Santos-Rui** [mriscoc/Ender3V2S1#663]
**Is your feature request related to a problem? Please describe.**

My Z gantry falls with gravity alone when steppers are deactivated, so i built a small magnetic mechanism and wanted to be able to park my nozzle after prints in a specific Z range.

My max Z is 225, but the mechanism will engage at 195. So i would want to be able to use the G27 P0 described [here  ](https://marlinfw.org/docs/gcode/G027.html )

- If the z  value is under 195 go to 195, 

- If the z  value is over 195, no need to raise 

(at least thats how i understand it), anyhow, thats the behaviour i wanted.

**Describe the solution you'd like**

The NOZZLE_PARK_POINT went from `// Specify a park position as { X, Y, Z }` to `// Specify a park position as { X, Y, Z_raise }` (on version 2 of marlin i think), becoming a relative value, and with that came a limit of 50 for the z value, and i can't seem to find how to disable this hardcoded max value. 

**Describe alternatives you've considered**

changing the default case on nozzle.cpp to move only if under the park.z
```
do_blocking_move_to_z(park_mode_0_height(park.z), fr_z);
//do_blocking_move_to_z(_MAX(park.z, current_position[Z_AXIS]), fr_z);
```

changing the menu to allow values over 50 on dwin.cpp
```
 //void SetParkZRaise() { SetPIntOnClick(Z_MIN_POS, 50); }
 void SetParkZRaise() { SetPIntOnClick(Z_MIN_POS, Z_MAX_POS); }
```

and while this allows to select/show values over 50, when the printer is reseted, values over 50 will be defaulted to 50. Same behavior when changing NOZZLE_PARK_POINT, values under 50 are stored, values over are defaulted to 50, which leads me to believe, that the function that actually writes the value doesn't allow values over 50, but i can't find it at any cost

**Additional context**
If the request is accepted, it might be better to add another flag (Like P4), and dont change current behaviors, but if not, and you could at least help me understand where the value setting is hardcoded at 50 max (if its even possible to change) i would greatly apreciate it!

Thanks in advance

**Comment by mriscoc** [comment]
The Professional firmware is a fork of Marlin firmware so it follows the functionalities of standard G-codes. If you want to change the behavior of standard G-codes I suggest you to request that in the official [Marlin repository](https://github.com/MarlinFirmware/Marlin) if those changes are accepted and become standard, they will be part of Professional firmware in the next bugfix branch merge.
