### ISSUE TITLE
C125 doesn't seem to take negative positions via file

### ISSUE THREAD

**Issue by dfinberg** [mriscoc/Ender3V2S1#667]
**Describe the bug**
I'm attempting to use the C125 custom gcode command, but it won't allow me to set the X position to -20 via a gcode.

**To Reproduce**
Use a custom gcode command to set a negative X offset (within the system dimensions) and it is returning 0.
M503
...
Recv: echo:; Physical minimums:
Recv: echo:  C100 X-20 Y0
Recv: echo:; Physical maximums:
Recv: echo:  C101 X310 Y310 Z320
Recv: echo:; Bed size:
Recv: echo:  C102 X300 Y300
...

Send: C125 X-20 Y0 Z20
Recv: echo:; Park Head:
Recv: echo:  C125 X0 Y0 Z20
Recv: ok P15 B15
[...]

sent via octoprint, but same results via custom config file.

It does allow me to set it via the advanced/physical/park menu.

**Expected behavior**
Should allow the offset.

**Version (please complete the following information):**
422 latest release, as well as DACAI display test binary.
Send: C115
Recv: Marlin ProUI 2.1.3 MRiscoC
Recv: Build: 20230122 - 02:49
Recv: Author: Miguel A. Risco-Castillo (MRiscoC)

**Comment by mriscoc** [comment]
Fixed in latest version
