### ISSUE TITLE
9x9 Mesh : zero in corners instead of the center

### ISSUE THREAD

**Issue by Caouette1988** [mriscoc/Ender3V2S1#67]
**Describe the bug**
Hi, wonderfull firmware, I like it, you did a great job! I'm running actually on 4x4 mesh, but would like to use the 9x9 mesh (or to know wich larger mesh is stable). In 9x9 mesh, the zero height switch in the corner instead of the center position.

**To Reproduce**
I level the bed with tramming wizard, with probe margin at 10mm. (1rst screenshot)
I then try 9x9 mesh and it cannot finish the mesh (the mesh restart itself at the 51/81 point)
So, like other issues, I disabled HS mode and increase Z speed at 960mm/s(max).
The mesh then work, see 2nd screen shot.
But then, I try to make an other 9x9 mesh, but at regular speed with HS mode still disabled (I dont know if reducing the speed cause this), It work too!, but the mesh viewer then show me zero height in the corner instead of the center of bed. See 3rd screenshot. (I think it is not suppose to do this)
Then I check corner of bed in tramming wizard (4rth screenshot) (I did not modify bed screw) and 4 corners and also the center of bed were evaluated at zero by the probe.

After that, I flash the firmware to original, then back to 20220220 and I'm stable using 4x4 mesh with HSmode activated at 480 Zspeed with 10mm margin.

**Screenshots**
![IMG_7543](https://user-images.githubusercontent.com/100353740/156002528-f76521ab-1ef3-449c-ae6c-2bab6d7d7476.JPEG)
![IMG_7544](https://user-images.githubusercontent.com/100353740/156002547-e11bf2fa-8920-44e8-9d0e-819deec3c2f9.JPEG)
![IMG_7546](https://user-images.githubusercontent.com/100353740/156002581-7d06d7fb-f046-43e2-aba1-f68ed871a04e.JPEG)
![IMG_7547](https://user-images.githubusercontent.com/100353740/156002605-f27e4df6-59e2-4489-9a2e-6731d4df11dd.JPEG)

**Version (please complete the following information):**
Config : Ender 3 S1 stock
Firmware version and release date : 20220220

**Comment by mriscoc** [comment]
Hi, the numbers in the bed tramming feature are not directly related to the mesh, also each time that the z axis is homed you could get values in reference to the last z = 0. If your bed is heating or cooling you also can get different values and the center could not be 0 because its level is different than when the Z axis was homed. Please try with the latest version and always do the test at the same temperatures (nozzle and bed), wait to reach the thermal stability.
