### ISSUE TITLE
S1 Hotend fan control

### ISSUE THREAD

**Issue by Kaan88** [mriscoc/Ender3V2S1#671]
For some reason "EXTRUDER_AUTO_FAN_SPEED" doesn't let me reduce the speed of the extruder fan. I've tried everything I've found online and nothing helped. Fan is always 100% on. I know that it can be controllable because with Klipper I can reduce the fan's speed to 60%. (PIN PC0)

Is this somehow not possible with marlin? (even though source code suggests otherwise)

I put a 5015 fan and it's way more powerfull than the stock one. I'd like to make it quiter.

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/discussions/477
