### ISSUE TITLE
New Thermistor Support?

### ISSUE THREAD

**Issue by eblieb** [mriscoc/Ender3V2S1#68]
Is it possible to compile or any tips on how I can compile the firmware myself? I have been using this thermistor https://www.amazon.com/gp/product/B08YNX79H8/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 and just realized I am suppose to use sensor 13 100k Hisens 3950 1%... Not sure if using the stock sensor 1 would cause any real issue.

**Comment by mriscoc** [comment]
For new configuration files please review here: https://github.com/mriscoc/Marlin_Configurations
