### ISSUE TITLE
All-metal Sprite Pro...will this have or provide any issues with your professional firmware, on the S1?

### ISSUE THREAD

**Issue by Woopah** [mriscoc/Ender3V2S1#69]

**Comment by mriscoc** [comment]
The S1 Pro will have a touch screen, this firmware is not compatible with touch screen.

**Comment by Woopah** [comment]
I didn't ask about the S1pro, nor did I inquire about the touch screen.

Is there any reason why the SPRITE PRO EXTRUDER would have issues with your professional fw?
