### ISSUE TITLE
Unexpected error while reading serial port,

### ISSUE THREAD

**Issue by hendrixradek** [mriscoc/Ender3V2S1#692]
After upgrade i randomly getting serial connection close.

`Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:3997
Please see https://faq.octoprint.org/serialerror for possible reasons of this.
Changing monitoring state from "Operational" to "Offline after error"
Connection closed, closing down monitor`

I already have new power supply, usb cable and cpu cooling fan (connected to separate power source).

**Comment by mriscoc** [comment]
Could be related to EMI, check that you have the +VUSB disabled.

Not a firmware issue.
