### ISSUE TITLE
Sprite EXTRUDER pro FW compatibility 

### ISSUE THREAD

**Issue by Xrayzor1337** [mriscoc/Ender3V2S1#70]
I didn't ask about the S1pro, nor did I inquire about the touch screen.

Is there any reason why the SPRITE PRO EXTRUDER would have issues with your professional fw?

_Originally posted by @Woopah in https://github.com/mriscoc/Ender3V2S1/issues/69#issuecomment-1054960207_

**Comment by mriscoc** [comment]
It depends on whether it has the same thermal sensor as the normal S1 extruder. if it is different, then special configuration files should be prepared for it.
