### ISSUE TITLE
Adding Mesh Edit Menu

### ISSUE THREAD

**Issue by nicop777** [mriscoc/Ender3V2S1#71]
Hi. I tried compiling firmware based on your files because I wanted to add a feature which is Mesh Edit. I tried uncommenting  #define LCD_BED_LEVELING and #define MESH_EDIT_MENU  in configuration.h file but after flashing, the feature was not added or at least visually added in the lcd. I wish you can help me add this feature. Thanks!

**Comment by Cal-LF** [comment]
It takes much more to add a menu item to the screen.

**Comment by nicop777** [comment]
I see. Although I created a custom firmware for ender 5 pro and enabled this feature by uncommenting that and it did the trick. But that has basic lcd. maybe that's why it's simpler?

**Comment by mriscoc** [comment]
> 

That "#define features" are only for enable the menus in Marlin UI, not works in other UI. For edit the mesh you can use the g-code [M421](https://marlinfw.org/docs/gcode/M421.html)
