### ISSUE TITLE
GD32 chip support on Ender 3 v2 Neo

### ISSUE THREAD

**Issue by talentoscope** [mriscoc/Ender3V2S1#721]
**Describe the bug**
This firmware does not support the newer GD32 chips in the newer Ender 3 v2 Neo machines (of which I have one)

**Version (please complete the following information):**
Latest

**Additional context**
The board is the 4.2.2 one, the chip is RET6

**Comment by mriscoc** [comment]
Not a bug, here are the firmware requirements: https://github.com/mriscoc/Ender3V2S1/wiki#requirements
GD support is very inconsistent due to several Creality board implementations.

**Comment by sammcj** [comment]
What happens when you try to run it @talentoscope?

I also have a 4.2.2 GD32F303 and it works fine.

![image](https://user-images.githubusercontent.com/862951/218287843-02c8184b-3b94-44f6-b220-c978b0c4dbbe.png)

**Comment by talentoscope** [comment]
Oh wow, really?

It just hangs at the Creality logo. I'm using the Ender3V2-422-BLTUBL-MPC-20221222.bin ?

Really want to get this working, but it's annoying

**Comment by sammcj** [comment]
Yep! No issues at all (other than the known Marlin smart resume/M600 bug #695) and I'm running the same - `Ender3V2-422-BLTUBL-MPC-20221222.bin`

![IMG_8051](https://user-images.githubusercontent.com/862951/218294042-f68c37ba-43d2-4528-8d69-f71af0b5166d.jpeg)

**Comment by sammcj** [comment]
I just installed a Spider hot end today and I'm going to do a custom FW build with some updated settings - I guess I'll find out if it works a second time!

**Comment by talentoscope** [comment]
Ahh, it's a GD32F303 here. That might be it. will have to hunt around.

Thank you :)

**Comment by sammcj** [comment]
Could be unrelated but I had that with the SD Card that came with the printer - I swapped it out for a 16GB one I had lying around that I formatted to FAT (mbr with 4k blocks).

**Comment by talentoscope** [comment]
Doubtful as I can flash the Creality one back afterwards but anything is
with a try

**Comment by sammcj** [comment]
The creality one worked on the stock SD card for me.

Make sure you format with a 4096 block size, e.g if you're on macOS:

sudo newfs_msdos -F 32 -b 4096 disk4s1

**Comment by talentoscope** [comment]
Got it, thanks Sam, appreciated!

**Comment by talentoscope** [comment]
Just thought I'd update here for anyone interested.
Bought a Kingston 32GB Class 10 SD card and I now have this on my Ender 3 v2 Neo with the F303 chip.

Thanks!
