### ISSUE TITLE
Pause, filament keep purging nonstop!

### ISSUE THREAD

**Issue by ssrshark** [mriscoc/Ender3V2S1#726]
After pressing pause while printing, the filament keeps purging nonstop, the purge button keeps flashing and clicking itself repeatedly, so the filament keeps purging nonstop until I quickly move the select cursor to resume button then it starts clicking itself on resume button to continue printing. Does anybody have the same problem as I do with this latest professional firmware.

**Comment by mriscoc** [comment]
The issue cannot be reproduced.
