### ISSUE TITLE
TJC screens: missing optical elements - temp curve and height values at bed leveling

### ISSUE THREAD

**Issue by migsun** [mriscoc/Ender3V2S1#728]
Graphic displays/values are missing.
Temperature curve at PID and height values at leveling

Ender 3S1 F4
Firmware 20221222

![TJC_CircleMesh](https://github.com/mriscoc/Ender3V2S1/assets/2745567/9b0f1f92-c53c-41df-bd5f-889b0d095b52) ![TJC_SquareMesh](https://github.com/mriscoc/Ender3V2S1/assets/2745567/ab7163ca-a11c-4c02-9ec9-2884b3e2c70a)
![TJC_Plot](https://github.com/mriscoc/Ender3V2S1/assets/2745567/eb941cc6-582b-4733-b135-ddbc764224c2)

**Comment by mriscoc** [comment]
Duplicate of https://github.com/mriscoc/Ender3V2S1/issues/542

**Comment by IS78CO** [comment]
Das habe ich auch wird daran gearbeitet oder muss man eine andere Vision nehmen. Gruß Ingo

**Comment by mriscoc** [comment]
Closed as duplicate
