### ISSUE TITLE
Horizontal line artefacts with IS / LA?

### ISSUE THREAD

**Issue by RoP09** [mriscoc/Ender3V2S1#734]
Hello,

with the latest update i noticed some irregular horizontal line artefacts in my prints which were not there before.
E.g. especially visible when I print a X Y Z calibration cube (on both X and Y sides) but not at all when I print a cylinder in vase/spiral mode - that one prints perfectly clean.

Could that be due to the new features introduced lately (especially Input Shaping even if it is disabled by GCode m593....)?

I am using a BTT SKR E3 V3 board on Ender 3 V2 with both LA and IS enabled in FW (LA was already used in previous FW without issues).

BR

**Comment by classicrocker883** [comment]
I think input shaping is enabled no matter what if it was so when firmware was compiled. I have noticed this too. even if you set the input shaping values to Zero or try to disable, you get artifacts. have you done the calibrations required to use input shaping?

**Comment by mriscoc** [comment]
IS or LA are enabled only in [special firmwares with IS or LA](https://github.com/mriscoc/Special_Configurations). Regular releases in this repository don't have IS or LA.

**Comment by RoP09** [comment]
@mriscoc : Yes, but it seems the problem is IS cannot be disabled even by M593 F0.

> I think input shaping is enabled no matter what if it was so when firmware was compiled. I have noticed this too. even if you set the input shaping values to Zero or try to disable, you get artifacts. have you done the calibrations required to use input shaping?

That's how it looks like, and no I did not do any calibration yet.

**Comment by mriscoc** [comment]
Did you check if the latest Marlin bugfix has the same behavior?
