### ISSUE TITLE
Dacai screen and skr mini e3 v3

### ISSUE THREAD

**Issue by Rsmyth166** [mriscoc/Ender3V2S1#737]
**Describe the bug**
flashed screen now it stays blank
**To Reproduce**

**Expected behavior**
flash screen and work
**Screenshots**

**Version (please complete the following information):**
Firmware version and release date
ender 3 v2 skr firmware
private folder for dacai screen

**Comment by mriscoc** [comment]
There are currently no issues with supported screens and SKR Mini E3 V3 board.

**Comment by mriscoc** [comment]
Not a firmware issue
