### ISSUE TITLE
Freezes on boot

### ISSUE THREAD

**Issue by PolyPlugins** [mriscoc/Ender3V2S1#738]
**Describe the bug**
After installing the latest version, if we don't interact with the printer when it first boots, it freezes and the credit popup will keep popping up over and over again. Using the October release works fine.

**Version (please complete the following information):**
20221222

**Comment by mriscoc** [comment]
When checking the Ender3V2-422-BLTUBL-MPC-20221222.bin version, the reported problem does not appear.

**Comment by PolyPlugins** [comment]
> When checking the Ender3V2-422-BLTUBL-MPC-20221222.bin version, the reported problem does not appear.

Apologies, we're using Ender3V2-422-MM-MPC-20221222.bin

Edit: Manually compiling the firmware with the MM configuration fixes the issue.

**Comment by joost01** [comment]
I also have this problem with the Ender3V2-422-BLTUBL-MPC-20221222.bin file. Booting without the SD card seems to solve the problem, at least Octoprint can connect to the printer again. With the SD card inserted Octoprint won't connect and every 3-5 seconds the credits pop-up is displayed. Also, you cannot manually change settings on the display.

**Comment by J-oe-rg** [comment]
Sounds to me like the issue described in #679 and #480.

**Comment by mriscoc** [comment]
The issue can't be replicated in the test group.
