### ISSUE TITLE
Manual Tramming on/off issue - Possibly collision

### ISSUE THREAD

**Issue by TRX0011** [mriscoc/Ender3V2S1#742]
**Describe the bug**
Printer Ender 3v2 with CR Touch, dual Z kit, Sprite Pro (=S1 Pro with glass bed). 

Manual bed tramming is not working correct when we disable it (from enabled condition) and try to move to another point. In result, it moves the head at the lower position (Z=0) with highly possibility to crash or scratch the bed.

**To Reproduce**
When using bed tramming, if manual tramming is off (unchecked) and want to check FL,C,FR etc, the head moves up (+z) before each movement to avoid any collision with the bed. This is correct.

If manual tramming is ON (checked), the head moves to the point we select (say Front Left) and lowers to the zero Z. If we select another point (say Center), the head moves up (+Z) and moves to the point (Center) ad lowers again at Z=0. This is also correct.

The error:

1. In Bed Tramming, uncheck the Manual Tramming (CR Touch based tramming).
2.  Move to different points like corners and center
3. Go  and check Manual tramming (on)
4. Try to move to different points. Will behave correctly.  The head remains at zero Z and moves up only if it has to move to a different point.
5. Now, uncheck the manual tramming (off)
6. Try to move to a new point or even on the same point you used in the last step
7.  -->> the head stays at zero Z and moves to the point. This is wrong and possibly to scratch the bed/nozzle if the bed is not leveled.

**Expected behavior**
The head has to lift up (+Z) like it did in the previous steps.

**Screenshots**
No screenshot

**Version (please complete the following information):**
https://github.com/mriscoc/Special_Configurations/releases/download/T13/Ender3V2-422-BLTUBL-T13-MPC-20221222.bin

**Additional context**
Ender 3v2 (board 4.2.2 w/ 512K) + official CR Touch + official Dual Z kit + Official Sprite Pro

Sorry for my English and any mistake I did or not provide correctly, this is my first post!

**Comment by mriscoc** [comment]
It will be fixed in the next release.
