### ISSUE TITLE
[Improvement] Disable heating while pause

### ISSUE THREAD

**Issue by tomaszczura** [mriscoc/Ender3V2S1#754]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Not a bug, but an improvement, or restoring behavior I saw on original firmware. 
If I pause the printer, I'd like to have possibility to lower temperature - e.g. to pause it overnight, set bed and nozzle temp to 0 and restore in the morning. Currently it is not possible - on pause, I get a screen with purge/continue buttons. It was possible on original firmware.

### Bug Timeline

old issue

### Version of Professional Firmware

Marlin 2.1.3 MRiscoC Ender3V2-422-BLTUBL-MPC, based on bugfix-2.1.x (Dec 22 2022 02:12:07)

### Printer model

Ender 3V2

### Electronics

Board 4.2.2

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

None

### Host Software

None

**Comment by ghost** [comment]
From my perspective it should not be stopped but set to material_standby_temperature (idk yet how it is called in this, still in my setup I use warmups temps modified to standby, not extrusion temperatures, which I get first from Cura SW, material info and/or experiments). Do you think such additional standby temperature could be good direction to develop @mriscoc ?

**Comment by mriscoc** [comment]
When paused, the heaters are automatically disabled after some time and turned on at resume.

**Comment by tomaszczura** [comment]
Does that apply both to bed and nozzle?

**Comment by mriscoc** [comment]
> Does that apply both to bed and nozzle?

The nozzle temperature in monitored, but the time out disable all heaters. In a special case where the nozzle temperature was lower than the extruder minimum temperature no timeout will occur.

**Comment by auswin17** [comment]
I agree with @tomaszczura about this feature. When I want to pause overnight I can press pause and make it cooldown before I turn it off. I tried waiting in pause for a long time and it does not seem to cooldown. Do you know how long until the heating system disable automatically?

Still, it would be nice if you can add a cooldown feature while pause, so I can shut it down safely and continue printing in the morning.

Thank you in advance.

**Comment by mriscoc** [comment]
Latest experimental implements the G-code [M86](https://marlinfw.org/docs/gcode/M086.html) and [M87](https://marlinfw.org/docs/gcode/M087.html) to control the hotend idle timeout
