### ISSUE TITLE
Input Shaping X freq in Y

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#756]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

https://github.com/mriscoc/Ender3V2S1/commit/4b086790e9597c7d03e6ffc7c215271aa003f793

### Version of Professional Firmware

Newest

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by classicrocker883** [comment]
in dwin.cpp file line 3188, fix should be like this https://github.com/mriscoc/Ender3V2S1/commit/4b086790e9597c7d03e6ffc7c215271aa003f793

**Comment by mriscoc** [comment]
Fixed in current experimental sources, thanks.
Related to: https://www.facebook.com/groups/ender3s1printer/posts/6526024700759438

**Comment by mriscoc** [comment]
Fixed in latest version.
