### ISSUE TITLE
[BUG] Mesh and tramming don't go all the way to the right on a 30x30 bed (ender s1 plus)

### ISSUE THREAD

**Issue by glebtv** [mriscoc/Ender3V2S1#790]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I've set physical dimensions & axis limits properly. Printing & manual axis move work fine.
But tramming and mesh don't go all the way to the right, the last (4th) point for the mesh is here:
![2023-03-13_19-28](https://user-images.githubusercontent.com/1041407/224765521-97596063-cffa-44c6-aa5e-2b79960ccdcb.png)
It seems to match the regular ender s1 bed. Can I do anything to change mesh&manual tramming size?

### Version of Professional Firmware

20221222

### Printer model

Ender S1 Plus

**Comment by mriscoc** [comment]
Check mesh insets: https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides

**Comment by glebtv** [comment]
Yes, thank you!
Somehow been skipping over mesh inset settings for 2 days.
