### ISSUE TITLE
[REQUEST] Include MM binaries for SKRME3V3 as it used to be

### ISSUE THREAD

**Issue by evgarthub** [mriscoc/Ender3V2S1#794]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Release artefacts are used to include manual mesh (MM) precompiled firmware. Latest one does not.
Would be really useful to have those.

Huge thanks!

### Bug Timeline

20230312

### Expected behavior

Ender3V2-SKRME3V3-MM-MPC-20230312.bin is published

### Actual behavior

only Ender3V2-SKRME3V3-BLTUBL-MPC-20230312.bin is available

### Version of Professional Firmware

20230312

### Electronics

SKR Mini

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
The issue page is only to report bugs in the current version of the firmware. You can request a custom version sponsoring it. Look here: https://github.com/mriscoc/Special_Configurations
