### ISSUE TITLE
[BUG] At the end of a print the motors are not automatically deactivated

### ISSUE THREAD

**Issue by fabiomaticus** [mriscoc/Ender3V2S1#799]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

After updating the firmware to the latest 20230312 version, at the end of a print the motors remain blocked.
I have in gcode M84

### Version of Professional Firmware

2.1.3 20230312

### Printer model

Ender 3S1

### Bed Leveling

None

### Your Slicer

Prusa Slicer

### Host Software

None

**Comment by ghost** [comment]
@fabiomaticus what if you try to send `M18`?

**Comment by fabiomaticus** [comment]
I have 3 ender 3 S1 printers. The problem was present on all. After restarting them, the problem is solved
