### ISSUE TITLE
The Extruder does not move if hotend temperature is lower than EXTRUDE_MINTEMP

### ISSUE THREAD

**Issue by jaykeny** [mriscoc/Ender3V2S1#809]
### Did you test with a precompiled firmware?

No, but I will test it now!

### Bug Description

I noticed on one of my prints that the extruder wasn't working, after it happened again I looked in OctoPrint's terminal to see "cold extrusion prevented". I happened to remember the only thing I changed was filament profiles and after comparing, noticed it was 5 degrees lower than my previous profile. I saw a comment in Configuration.h from mriscoc that there's an option in the menu to change the EXTRUDE_MINTEMP, but I couldn't find it. I'm assuming it's controlled by the filament unload temperature as it was the only setting that was above 200 degrees. After I changed it to 190, the extruder started working again. There should be it's own setting in the menu or if there is a setting that I may have missed, then unload temperature should not take priority over it.

### Version of Professional Firmware

20230312

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Not a firmware issue, The extruder does not move if hotend temperature is lower than EXTRUDE_MINTEMP, The user need to preheat the hotend to a temperature higher than EXTRUDE_MINTEMP if want to Load/Unload filament, if not, the printer will heat the filament automatically to EXTRUDE_MINTEMP as a security measure.

![filament-settings1](https://user-images.githubusercontent.com/2745567/226500754-e66f2a75-50c3-4034-bc6a-44d6f9ed7548.jpg)
