### ISSUE TITLE
Steppers jittering when UBL is on [BUG] (bug summary)

### ISSUE THREAD

**Issue by Skateboss** [mriscoc/Ender3V2S1#812]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

When printing a large print with UBL with the following in my start gcode:
G29 A ; Activate UBL bed leveling
G29 L0 ; Load mesh from slot 0
G29 J ; Probe 3 points on the bed and tilt mesh accordingly

My whole printer keeps freezing for approx 1 second then continues to print for 1 second in a loop for around 30 seconds then the printer starts running smoothly again, it does the same again when the head reaches the same point on the next go around.

I'm slicing using Cura 5.3

This problem stops if I take that gcode out of the start gcode.

### Bug Timeline

new bug using latest UBL firmware

### Expected behavior

N/A

### Actual behavior

N/A

### Steps to Reproduce

N/A

### Version of Professional Firmware

Ender3 V2/S1 Professional Firmware 20230312

### Printer model

Ender 3 pro v2 

### Electronics

4.2.7

### Add-ons

N/A

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by classicrocker883** [comment]
I think you should post this on the main Marlin Firmware issues. if you can try using a different firmware, or a known good firmware file, maybe video record the issue, give as much details as possible.

I had an issue when I was swapping my stepper motor with an aftermarket one. it started like grinding and stuttering, just all around not good. I ended up swapping the two middle wires of the connector and that fixed that issue, which is almost sounding like whats going on with yours.

i would suggest try entering the gcode commands manually like via Pronterface. cura can do this also if the computer is plug into the printer.
