### ISSUE TITLE
STM32F4RE environment can be successfully compiled and cannot be installed on Ender 3S1 with STM32F401RCT6

### ISSUE THREAD

**Issue by leezoneline** [mriscoc/Ender3V2S1#818]
I'm using an STM32F4 based Ender 3 s1 now. It's necessary for me to use LA to print pricisely. But I'd like to print some fliament that needs high temperature recently, so I also need the T13 configuration. There's no mutiple configurations for F4 like ender 3 s1 F1 version. I tried to compile one, but only the STM32F4RE environment can compile successfully, and it cannot flash into my printer. I wonder that if it's an problem couldn't solve or there's some solutions I didn't find. 
Hope for your reply soon! 
![image](https://user-images.githubusercontent.com/122147135/227246474-69e16e68-b1c9-408b-8d75-b39b9640ed51.png)

**Comment by mriscoc** [comment]
STM32F4RE environment could brick boards with the STM32F401RCT6 SoC, I suggest you first learn about Marlin and PlatformIO use before attempting to do some dangerous test.

STM32F401RCT6 doesn't have enough program flash memory.

It is not a firmware issue.
