### ISSUE TITLE
[BUG] Micro SD card extender problems with skr mini v3 board 

### ISSUE THREAD

**Issue by 3d-not-2d** [mriscoc/Ender3V2S1#833]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I compiled some firmware using the Ender 3V2-SKRME3V3-BLUBL-LA-MPC configuration files. I enabled #define NO_SD_DETECT in the adv.h and
#define HAS_SD_EXTENDER 1 in the .h config files. After flashing the new firmware to my board it works normally with just the sd in the board or nothing in it, but when I have the SD extender plugged in and I turn it on my screen just lights up blank and stays blank. Kinda at a loss for what to do next.

### Bug Timeline

as soon as i plugged in the sd extender 

### Expected behavior

ss extender works properly 

### Actual behavior

screen lights up blank when turned on if extender plugged in

### Steps to Reproduce

1. plug in extender 
2. turn on
3. look at blank screen
4. unplug extender 
5. turn back on
6. ender works but without extender plugged in

### Version of Professional Firmware

most recent 

### Printer model

3v2

### Electronics

skr mini 

### Add-ons

SD card extender 

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

**Comment by mriscoc** [comment]
Try the latest version of Marlin Bugfix.
