### ISSUE TITLE
Unable to flash stock firmware

### ISSUE THREAD

**Issue by CorruptName** [mriscoc/Ender3V2S1#834]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

The firmware ignores STM32F4_UPDATE folder placed on SD Card. I see plenty of documentation on how to install firmware, but cannot find info on reverting to stock.

### Version of Professional Firmware

latest

### Printer model

Ender3 S1

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by Crazy-Charles** [comment]
Does your controller board have the STM32F401 mcu or the STM32F103 ?

**Comment by CorruptName** [comment]
F401

**Comment by mriscoc** [comment]
It is not a Professional firmware issue, please post in the Creality github.

**Comment by Crazy-Charles** [comment]
The folder name STM32F4_UPDATE is hardcoded into the bootloader on the chip, so not a firmware issue, more then likely a sdcard issue.

**Comment by CorruptName** [comment]
> The folder name STM32F4_UPDATE is hardcoded into the bootloader on the chip, so not a firmware issue, more then likely a sdcard issue.

Thanks but I don't think it's the SD card. Used the same SD card to update the screen. Maybe a naming issue tho, I have tried changing it to "firmware.bin" and placing it directly on root. nothing seems to help.
Trying to use the Creality Sonic Pad but cannot install klipper (or stock then klipper)

**Comment by mriscoc** [comment]
Format your SDCard and create the STM32F4_UPDATE  folder, put the stock firmware there. The Creality bootloader is a little buggy, maybe it uses a 8.3 DOS format for the folder and filenames, so it is possible STM32F4_UPDATE folder is not exactly in the 8.3 name expected by the bootloader.

**Comment by CorruptName** [comment]
> Format your SDCard and create the STM32F4_UPDATE folder, put the stock firmware there. The Creality bootloader is a little buggy, maybe it uses a 8.3 DOS format for the folder and filenames, so it is possible STM32F4_UPDATE folder is not exactly in the 8.3 name expect by the bootloader .

I just got it working by flipping the printer off and on twice quickly. Guess I just have a goofy printer. Thanks and sorry this turned out to be completely unrelated to firmware as you suggested before.
