### ISSUE TITLE
Hotend Cooling Fan

### ISSUE THREAD

**Issue by MTUpower** [mriscoc/Ender3V2S1#836]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Dear Sir
I am really great full for your Version of the Ender Firmware brilliant and very easy to use.  I have however discovered a small issue, to which I would be great full for your help.  I am using Cura, and have activated Printer fir wear retraction so that I can tune the printer on the "fly" as it were.  But there appears to be an small issue intuit the hotted cooling and indeed the part cooling does not appear to work automatically unless I activate it manually on the printer screen?

Now I think of it there is also one other question.  Flow.  I have set the required flow in Cura but this does not appear to have a affect on the screen as always shows 100%.  even if I change and save it always defaults back to 100?  

If you are able to help it would be most appreciated.

Kind Regards

MTUPower

### Version of Professional Firmware

Mrscoc latest version

### Printer model

Ender 3 V3

### Electronics

4.2.7

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Printer flow is controlled by G-code [M221](https://marlinfw.org/docs/gcode/M221.html), check your slicer or G-code file and look for that command. In some slicer profiles the part cooling fan is turned off in the first layers. Fan speed is controlled by G-code [M106](https://marlinfw.org/docs/gcode/M106.html)
