### ISSUE TITLE
Heater Capacity

### ISSUE THREAD

**Issue by MTUpower** [mriscoc/Ender3V2S1#837]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

This is not really an issue more of a question.  In the MPC autotune settings you have a Heater Power (Watts) but what is meant by Heat Capacity?

kind Regards

MTUpower

### Version of Professional Firmware

Mrscoc

### Printer model

Ender V2

### Electronics

4.2.7

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Please use the Discussion page for questions. About block heat capacity, it is a physical property of the amount of heat required to change its temperature by 1 K.
