### ISSUE TITLE
[BUG] don't read the sd card

### ISSUE THREAD

**Issue by scyther149** [mriscoc/Ender3V2S1#839]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Hi, i have 3 ender 3 v2 4.2.2
the update works in 2 of my 3 machines, but in one doesn't... i just have this bug with this firmware (in differents versions the bug works), i tested 
Ender3V2-422-MM-20220816.bin
Ender3V2-422-MM-20220816.bin
Ender3V2-422-MM-MPC-20230312

### Bug Timeline

a old issue, still persist in all the versions

### Version of Professional Firmware

20230312

### Printer model

Ender 3V2

### Electronics

4.2.2

### Bed Leveling

None

### Your Slicer

Cura

### Host Software

None

### Additional information & file uploads

But the problem isn't the printer, because when i install another firmware, the default or "E3V2-Default-v4.2.2-v2.0.1" the sd reader works fine... i only have the read problem with this :c can do you help me?
i uploaded this video... i didn't installed other firmware in the video because is a lot of time, but the sd reader works fine with another firmwares...

[https://youtu.be/jMlXZm7s3LA](url)

**Comment by mriscoc** [comment]
It is not a firmware bug.
You have a faulty µSD card slot. A good slot informs to the printer when a memory card is inserted/removed, yours not.
You can activate in the Advanced Settings the "Media Update" option. But be aware that it is only a workaround.
Other firmwares have "Media Update" function enabled by default and can't be disabled. That mask a faulty card slot.
