### ISSUE TITLE
Need help with SKR Mini E3 V3.0.1

### ISSUE THREAD

**Issue by Lentica** [mriscoc/Ender3V2S1#842]
Hi,

So I have SKR Mini E3 v3.0.1, is it possible at all to use this firmware? I have tried flashing it with edited config file to reflect my board (and changing the LCD_SERIAL_PORT condition to include BTT_SKR_MINI_E3_V3_0_1), but the screen just freezes after the boot screen. Any ideas?

_Originally posted by @Lentica in https://github.com/mriscoc/Ender3V2S1/discussions/785#discussioncomment-5522801_

**Comment by mriscoc** [comment]
Use the Discussions page to post questions.
