### ISSUE TITLE
[BUG] C104 wont set max extruder temperature.

### ISSUE THREAD

**Issue by hendrixradek** [mriscoc/Ender3V2S1#864]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

After sending C104 U1 315T max temperature of extruder is still 260C.

### Version of Professional Firmware

FIRMWARE_NAME:Marlin 2.1.3 MRiscoC Ender3V2-427-BLTUBL-MPC, based on bugfix-2.1.x (Mar 12 2023 17:19:55) SOURCE_CODE_URL:github.com/mriscoc/Ender3V2S1 PROTOCOL_VERSION:1.0 MACHINE_TYPE:Ender3V2-427-BLTUBL-MPC EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
> After sending C104 U1 315T

Your command is not correct, use: `C104 U1 T315`
Note: Do not use Pronterface.
