### ISSUE TITLE
High noise in extruder when it retracts with default speed and acceleration

### ISSUE THREAD

**Issue by RigoHoward** [mriscoc/Ender3V2S1#867]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

Ender3V2-422-BLTUBL-MPC-20230312

### Bug Description

Im just overwhelmed on how many useful options and how its almost everything perfect on this firmware, but i encountered and annoying issue which i will describe in the following lines...

When im printing, the extruder stepper motor does a loud noise when it's constantly retracting the filament.
I tried several retraction (reduced) values in the slicer (also in the firmware retraction menu too) and i couldnt get rid of the loud noise at all. But what its even worst, i founded as a consecuence with the excesive retraction movements, the filament starts to whorn out and the gears finally doesnt grab them anymore, resulting in no filament extruded from the nozzle after a few layers.

I try using jyers firmware and also the official creality 1.0.7 firmware and i dont get the noise from the extruder stepper motor or the filament whorn out issue at all, so its very odd.

Here its a video when you can clearly hear what im describing:
[https://youtube.com/shorts/KoPff-nAp9s?](url)

### Bug Timeline

I noticed the issue since the first use of the mriscoc firmware

### Expected behavior

When the extruder motor its doing retraction moves you hear a slight sound from the gears besides that, everything works as it should (you can get a succesful print)

### Actual behavior

The extruder stepper motor do a loud noise everytime it retracts the filament

### Steps to Reproduce

1. Slice a stl file with latest version of Cura (let the retraction settings with the default values)
2. Put the gcode on your microsd
3. Start your print on your ender 3v2 with the latest release of mriscoc firmware
4.  Hear the noise of the extruder stepper motor when it does retraction movements
5. The print fails because after a few layers no more filament its extruded by the nozzle (the cause its the whorn by the friction of the gears)

### Version of Professional Firmware

Release 
Ender3V2-422-BLTUBL-MPC-20230312

### Printer model

Ender 3V2

### Electronics

4.2.2

### Bed Leveling

BL Touch clone

### Your Slicer

Cura (lastest stable version)

### Host Software

None

### Additional information & file uploads

I really like a lot this firmware, but i cant get any successful print using it

**Comment by mriscoc** [comment]
For lower the noise for that particular extruder try decreasing the speed and acceleration of the extruder in the Control/Motion menu.

**Comment by RigoHoward** [comment]
Oh you were right! thank you.

I take the deafult values for speed and acceleration from jyers firmware, and now im printing well without the noise on the extruder retractions.

Here are the values if anyone is interested...

extruder max acceleration 1000
extruder max speed 25
