### ISSUE TITLE
[BUG] preview glitch

### ISSUE THREAD

**Issue by Make-It-Racing** [mriscoc/Ender3V2S1#871]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I am using Prusa slicer 2.52 with the CreateHeaderAndThumbnail.py script to generate the preview file.
Everything works but the preview image is not displayed correctly :
![IMG_0962](https://user-images.githubusercontent.com/60300961/232977210-dd4a068e-0d4c-44d2-b077-6ab7684f47d9.jpeg)

I don't have any other issues with the lcd (Ender s1 F4 printer) the qr code and everything else is shown correctly...
Am I doing something wrong?

### Version of Professional Firmware

Ender3S1-F4-20230312

### Printer model

S1 F4

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by Make-It-Racing** [comment]
I did open the gcode file and found the thumbnail base 64 code.
I decoded it using an online tool and the image itself looks good
![image](https://user-images.githubusercontent.com/60300961/233044582-2e7484b4-0232-4bcd-9035-b2168803b69c.jpg)

**Comment by mriscoc** [comment]
You could have a TJC display unit, that screen has currently some limitations. Next version of the firmware will have a workaround.

**Comment by Make-It-Racing** [comment]
Yes I believe I have the TJC display.
I also noticed I don't see the numbers on the circled during leveling
Ok will be patiently waiting for the next version :-)

**Comment by mriscoc** [comment]
EDIT: TJC displays need an square preview thumbnail and it is now supported in the latest firmware version.

~~Not a firmware issue, TJC is currently incompatible (check the wiki) with the latest released version.~~

**Comment by mriscoc** [comment]
TJC displays need an square preview thumbnail and it is now supported in the latest firmware version.
