### ISSUE TITLE
[BUG] PID tune temp != default value

### ISSUE THREAD

**Issue by classicrocker883** [mriscoc/Ender3V2S1#872]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

**src/lcd/e3v2/proui/dwin_defines.h** line ~_65_
```
#define DEF_HOTENDPIDT TERN(PREHEAT_1_TEMP_BED, PREHEAT_1_TEMP_HOTEND, 195)
#define DEF_BEDPIDT TERN(PREHEAT_1_TEMP_BED, PREHEAT_1_TEMP_HOTEND, 60)
```

should this be
```
#define DEF_HOTENDPIDT TERN(PREHEAT_1_TEMP_HOTEND, PREHEAT_1_TEMP_HOTEND, 195)
#define DEF_BEDPIDT TERN(PREHEAT_1_TEMP_BED, PREHEAT_1_TEMP_BED, 60)
```

but for some reason when `PREHEAT_1_TEMP_BED` or `PREHEAT_1_TEMP_HOTEND` are defined and enabled, the value goes to the default _195 / 60_, and not the defined preheat 1 temp values

### Version of Professional Firmware

current

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Thanks!

Use this:

```cpp
#ifdef Z_AFTER_HOMING
  #define DEF_Z_AFTER_HOMING Z_AFTER_HOMING
#else
  #define DEF_Z_AFTER_HOMING 0
#endif
#define DEF_HOTENDPIDT PREHEAT_1_TEMP_HOTEND
#define DEF_BEDPIDT PREHEAT_1_TEMP_BED
```
