### ISSUE TITLE
Pause/Resume broken - Filament doesn't feed after resuming from smart pause

### ISSUE THREAD

**Issue by mfraser** [mriscoc/Ender3V2S1#873]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Using an Ender 3 V2 Neo, I was trying to use M125 to do a smart pause so that I could insert a magnet mid print, but the layer after I did the pause wasn't printing properly. 
![20230418_190026](https://user-images.githubusercontent.com/195323/233382076-7a53ec4e-2435-467d-991c-c3ed8d75201b.jpg)

I thought this might be caused by using M125 so I used M600 instead with the same result.

The GCode produced by PrusaSlicer 2.6 alpha 6 shows this:

; stop printing object Dice 20mm id:0 copy 0
;LAYER_CHANGE
M117 INDICATOR-Layer10
;Z:2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0
;2

G10 ; retract
G1 Z2 F9000
;AFTER_LAYER_CHANGE
;2
;COLOR_CHANGE,T0,#25AF21
M600
; printing object Dice 20mm id:0 copy 0
G10 ; retract
G1 X103.638 Y119.006
G11 ; unretract

### Bug Timeline

Could be related to bug #695

### Expected behavior

I expected the layer to look exactly like previous layers.

### Actual behavior

It is either printing too high or the it hasn't unretracted enough.
![20230419_181642](https://user-images.githubusercontent.com/195323/233382879-f96ae4a2-c16b-494c-88b8-a06f6936b81b.jpg)

### Steps to Reproduce

1. Print file with M600
2. Printer pauses for filament change
3. Printer resumes, but layer isn't properly formed
4. Part separates at later

### Version of Professional Firmware

Marlin 2.1.3 MRiscoC Ender3V2-422-BLTUBL-MPC, based on bugfix-2.1.x (Mar 12 2023 17:15:44)

### Printer model

Ender 3 V2 Neo

### Electronics

4.2.2

### Add-ons

None

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
> **G10** ; retract
> **G1 Z2 F9000**
> ;AFTER_LAYER_CHANGE
> ;2
> ;COLOR_CHANGE,T0,#25AF21
> M600
> ; printing object Dice 20mm id:0 copy 0
> **G10** ; retract

Is your Z axis going to +2?    
Is it a problem with the Z position when return? Check Park Z Raise in Park Head menu   
Is it a problem with extruder? Your G-code has a double retract also check your minimum extruder temperature in Filament settings menu

**Comment by mfraser** [comment]
> > **G10** ; retract
> > **G1 Z2 F9000**
> > ;AFTER_LAYER_CHANGE
> > ;2
> > ;COLOR_CHANGE,T0,#25AF21
> > M600
> > ; printing object Dice 20mm id:0 copy 0
> > **G10** ; retract
> 
> Is your Z axis going to +2? Is it a problem with the Z position when return?
That seems to be where it is parking.
> Check Park Z Raise in Park Head menu Is it a problem with extruder?

Should I set that to zero? The extruder is working fine at other times, just seems to be when restarting after a layer change.

> Your G-code has a double retract also check your minimum extruder temperature in Filament settings menu

Noticed that, think it is retracting to stop ooze after filament change.
[Magnet Test.gcode.txt](https://github.com/mriscoc/Ender3V2S1/files/11288048/Magnet.Test.gcode.txt)
