### ISSUE TITLE
M600 causes multiple filament change every few layers

### ISSUE THREAD

**Issue by Make-It-Racing** [mriscoc/Ender3V2S1#874]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I added one filament change in Prusa Slicer (I order to change color). 
The printer however initiated the first filament change in a middle of a layer (one layer too early) then I inserted the same fillament color becuase the layer was not completed. 
The printer then completed the layer and initiated a layer change again after the end of the layer.
And then the printer initiated another layer change every few layers (not sure if randomly or not).
I verified that there is only one M600 in the gcode...

### Version of Professional Firmware

Ender3S1-F4-20230312

### Printer model

S1 F4

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Can't be replicated, check your filament runout sensor

**Comment by Make-It-Racing** [comment]
Indeed this was cased by the runout sensor. It was causing all the print posing not the m600 at all.
Thank you
