### ISSUE TITLE
Hotbed not cooled down after Auto Mesh Wizard

### ISSUE THREAD

**Issue by ftnt-apopisteru** [mriscoc/Ender3V2S1#885]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

After configuring the hotbed temperature for auto mesh wizard in Advanced > Mesh Leveling > Temp and running the Auto Mesh Wizard, hotbed temperature is not decreased, but is maintained at the configured value for indefinite duration or until G-code file containing hotbed teperature configuration commands is loaded.

FW ver. : Ender3V2-422-BLTUBL-MPC-20230312.bin
Printer: Creality Ender-3 V2 4.2.2 board w. CR-Touch
Env: the symptom occurs with both
Z feed rate=960 mm/min, High Speed active
Z feed rate = 480 mm/min (default); HS inactive

### Expected behavior

Hotbed temperature ought decrease to ambient after performing Auto Mesh Wizard.

### Actual behavior

Hotbed temperature is not decreased.

### Steps to Reproduce

1. configure hotbed temperature in Advanced > Mesh Levelling > Temp
2. run auto mesh leveling in Prepare Auto Mesh Wizard - save or continue options do not affect the symptom

### Version of Professional Firmware

Ender3V2-422-BLTUBL-MPC-20230312.bin

### Printer model

Ender-3 V2

### Electronics

4.2.2

### Add-ons

CR-Touch; dual Z-axis w. breakout cable

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

Same as my slicer

**Comment by mriscoc** [comment]
Because a leveling is primarily a step prior to a print job, the bed is not cooled to help with thermal stabilization. That is the intended behavior.
