### ISSUE TITLE
[BUG] DWIN_Popup_ConfirmCancel hard coded to show ICON_BLTouch

### ISSUE THREAD

**Issue by Crazy-Charles** [mriscoc/Ender3V2S1#887]
### Did you test with a precompiled firmware?

No, but I will test it now!

### Bug Description

Functions that call DWIN_Popup_ConfirmCancel will always get the BLTouch icon instead of what is being asked for.

 void DWIN_Popup_ConfirmCancel(const uint8_t icon, FSTR_P const fmsg2) {
  DWIN_Draw_Popup(ICON_BLTouch, F("Please confirm"), fmsg2);
  DWINUI::Draw_Button(BTN_Confirm, 26, 280);
  DWINUI::Draw_Button(BTN_Cancel, 146, 280);
  Draw_Select_Highlight(HMI_flag.select_flag);
  DWIN_UpdateLCD();
}

DWIN_DRAW_Popup needs changing to "DWIN_Draw_Popup(icon, F("Please confirm"), fmsg2);"

### Bug Timeline

Only noticed whilst adding new menu actions

### Expected behavior

I expected the requested Icon to be displayed

### Actual behavior

Wrong icon displayed

### Version of Professional Firmware

2.1.3

### Printer model

DIY with F103RE

### Electronics

My own

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Thanks, I'm fixing the sources and the fix will be integrated in the next release.

**Comment by classicrocker883** [comment]
I had done this fix/feature in my repo of this, 

in **proui/dwin_popup.h**
```
template<typename T, typename U>
void DWIN_Draw_Popup(const uint8_t icon, T amsg1=nullptr, U amsg2=nullptr, uint8_t button=0) {
  DWINUI::ClearMainArea();
  Draw_Popup_Bkgd();
  if (icon < 22) DWINUI::Draw_Icon(icon, 97, 95);
  if (icon < 82 && icon > 22) DWINUI::Draw_Icon(icon, 101, 105);
  if (icon > 89) DWINUI::Draw_Icon(icon, 82, 90);
------>
```

in **proui/dwin_popup.cpp**
```
void DWIN_Popup_ConfirmCancel(const uint8_t icon, FSTR_P const fmsg2) {
  DWIN_Draw_Popup(icon, F("Please confirm"), fmsg2);
------>
```
add _icon_ instead of _ICON_BLTouch_. and I split the `if(icon < ....)` to account for the different icon types/size, as [you can see here](https://github.com/alexqzd/Marlin/commit/9973db388df86f6d2a2a67865572b4ae0f3d67fb)
