### ISSUE TITLE
[Thermal Runaway] Nozzle not Heating up sometimes or dropping in Temperature

### ISSUE THREAD

**Issue by Niklas344** [mriscoc/Ender3V2S1#889]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I am using the precompiled version [Ender3V2-SKRME3V3-BLTUBL-MPC-20230312.bin] that is the latest updated version.
I came across the Issue that my Nozzle is not heating up sometimes. The Issue appeared after 2 small Test prints < 1 hour. 
(Right after i installed the Firmware)
And since then it kills my printer at random times. 1 Time after 7 hours of printing, i guess my Nozzle temperature fall and didnt rise again. 
Now i wanted to test it again, i printed a part 28min and had no problem. After this i wanted print something other again and my Nozzle Temperature stays at 28 °C and doesnt rise. ---> leads to Thermal Runaway Issue and Killing Printer, or to Nozzle not Heating up and killing Printer

### Bug Timeline

Right after i installed the Firmware after 2 Testprints

### Expected behavior

I expect that my nozzle is heating up normally like it should and staying at the given Temperature. 

### Actual behavior

Temperature sometimes falls mid print and then killing my printer, or not even heating up sometimes and therefore killing my printer.

### Steps to Reproduce

1. Use Ender 3-V2 with SKR mini E3 V3
2. Install Spider Hotend with custom Hotend Case and direct Extruder
3. Noctua Fan on Hotend Cooling and 4010 Radial Fans for Part Cooling
4. Print 

spider Hotend: https://store.creality.com/de/products/spider-hochtemperatur-und-hochgeschwindigkeits-hotend?awc=32419_1682430642_ec3a1c158f9f8d58f2d7d0a9da18e5ed

Custom Case: https://thangs.com/designer/TheBuildBay/3d-model/Dual%20Blower%20Fan%20Duct%20for%20Ender%203%20V2%20with%20Spider%20Hotend%20V1%20-776965

### Version of Professional Firmware

Ender3V2-SKRME3V3-BLTUBL-MPC-20230312.bin

### Printer model

Ender 3V2

### Electronics

SKR Mini E3 V3

### Add-ons

Noctua Fan, 4010 Radial Fans, Spider Hotend

### Bed Leveling

3D-Touch (UBL)

### Your Slicer

Cura 

### Host Software

None

**Comment by ajaybnl** [comment]
MPC Autotune done, the problem gone. Try on your printer.

**Comment by mriscoc** [comment]
If you can't fix that by PIC/MPC autotune, your custom Hotend or some non-stock fans might require custom build or disable thermal runaway protection.

**Comment by ernestp** [comment]
Also having this issue after updating stock Ender 3 v2, no mods on hotend or fans

Never seen such drops before

<img width="627" alt="Screenshot 2023-07-14 at 17 22 34" src="https://github.com/mriscoc/Ender3V2S1/assets/7553589/e36d0d37-6fdf-4b4b-a0a8-b8e5fe26eb36">

<img width="621" alt="Screenshot 2023-07-14 at 18 02 18" src="https://github.com/mriscoc/Ender3V2S1/assets/7553589/d4d54ac5-62ab-46c9-b9ce-450414a838fd">

**Comment by ernestp** [comment]
For the graphs above, after more testing, it seems the issue was related to printing on higher speed, and spikes happens when nozzle hit deformed material on the way. So it creates tension on stepper motors, causing voltage drops which affect reading of temperature sensors.
