### ISSUE TITLE
Fillement endstop stays triggered without a filememt sensor 

### ISSUE THREAD

**Issue by crelis79** [mriscoc/Ender3V2S1#89]
Hi i updated the lasted manual mesh leveling firmware for the 4.22 and now my extruder motor wont turn anymore. I don't have a runout sensor. I re install the original firmware but its stil not working. So what to do now?
![16472699797554175921378447796789](https://user-images.githubusercontent.com/84041848/158199538-13fb5015-22ee-409f-a899-49621450cb79.jpg)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
Firmware version and release date

**Additional context**

**Comment by mriscoc** [comment]
Hi. Filament TRIGGERED is the default value without filament sensor and when the configuration Runout active is LOW. But if you don't have a filament sensor, could be better to disable the support in Advanced / Filament settings / Enable Runout
![filament-settings1](https://user-images.githubusercontent.com/2745567/158213755-d546ca5e-f02d-4c01-bc57-78406b71d0d5.jpg)
About your extruder motor, check you wires.

**Comment by crelis79** [comment]
At the end it was a broken extruder cable 😁
