### ISSUE TITLE
Add a standard menu option for the printing speed parameter

### ISSUE THREAD

**Issue by dfinberg** [mriscoc/Ender3V2S1#890]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

During a print, a tune menu is available. Those settings are persistent across prints, so it would be nice to be able to reset them when a print has finished. As best I can tell the "speed" parameter doesn't seem to be on any other menu, so to reset it you need to start a print.  Or perhaps I'm just blind, but it would be nice to have these available in an obvious place to reset.

### Bug Timeline

N/A

### Expected behavior

speed should be able to be reset without printing.

### Version of Professional Firmware

20230312

### Printer model

Max Neo

### Electronics

4.2.2

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
You must use the [M220](https://marlinfw.org/docs/gcode/M220.html) G-code in your slicer start script for set/reset the speed.
Currently the speed (feedrate_percentage) can be changed in the tune menu only.
https://github.com/mriscoc/Ender3V2S1/wiki/Slicer-G-code-Scripts
