### ISSUE TITLE
[BUG] Crash after removing SD card

### ISSUE THREAD

**Issue by officiallyemma** [mriscoc/Ender3V2S1#894]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Version: Latest latest [Release #20230312](https://github.com/mriscoc/Ender3V2S1/releases/tag/20230312). Also confirmed on: #20221222

Firmware crashes (freezes and shows version popup) when selecting the "media" tab after printing and removing the SD card.

### Expected behavior

Expected Behavior
When media is removed, the selected file should be reset to the top position ("Back").

### Actual behavior

The selection indicator remains in the same position as the last selected file, even though there are no files present. Moving the scroll wheel selects the "Back" entry, and promptly freezes. After a few seconds, the firmware will restart, showing the version info.

<img src="https://user-images.githubusercontent.com/20545489/235409142-62711dd5-95b8-452e-ae89-47d8d21e2a28.png" width="300">

### Steps to Reproduce

[Video showing the bug in action](https://streamable.com/aafdwb)

Reproduction:
1. Select an item in the Media menu. Either successfully print or cancel. You should be brought back to the main menu and your selection will be saved when you return to the media menu.
2. Remove the SD card. Observe "Media Removed" M117 message
3. Enter the Media menu. Observe that the selection from before is still 'selected' even though the menu is blank. See image above.
4. Move the selector wheel, the selection should jump to the top ("Back") and the firmware will hang, before showing the version info popup and restarting.

### Version of Professional Firmware

Professional Firmware v2.1.3 - Build Time 20230312 (Lastest GitHub release as of posting)
Ender3V2-422-BLTUBL-MPC-20230312.bin

### Printer model

Ender 3v2

### Add-ons

BL Touch

### Bed Leveling

UBL

### Your Slicer

None

### Host Software

None

**Comment by Majboor** [comment]
xpected behavior should be that when the media is removed, the selection should be set to the top item "Back" in the media menu, and the application should not crash?

**Comment by officiallyemma** [comment]
Just tested on the latest [Release #20230312](https://github.com/mriscoc/Ender3V2S1/releases/tag/20230312) and can confirm that I am still experiencing this bug. I'll update the issue to reflect that.

@Majboor Yes. Opening the media menu after printing and removing the SD card causes a crash. 

I've recorded a quick (and quite shaky, my apologies) demonstration video of the bug in effect on my Ender 3 v2. You can view that here: https://streamable.com/aafdwb

Here's what the bug looks like. Moving the scroll wheel at this point causes the printer to restart.
![image](https://user-images.githubusercontent.com/20545489/235409142-62711dd5-95b8-452e-ae89-47d8d21e2a28.png)

I've added this information, and clarified a few things, in the original post.

**Comment by classicrocker883** [comment]
do you have SD extender installed? try enable that setting in the configuration.h file.

**Comment by mriscoc** [comment]
This bug was fixed in the latest release.

**Comment by officiallyemma** [comment]
Cheers! Thanks for continuing to support this firmware

**Comment by shayenss** [comment]
> Тази грешка беше коригирана в последната версия.

I have two Ender 3 S1 models and I uploaded version Ender3S1-F1-UBL-MPC-20230522B to both. I have the same problem with the SD card. It doesn't read my files and reboots, telling me the firmware version. Ask for assistance.
...The weird thing is that the first time, it read my SD card and after I took it out and put it back in, I got this error

**Comment by mriscoc** [comment]
> I have the same problem with the SD card

Sorry, but it is not the same error, the bug listed here needs a specific procedure to trigger it. You can read from the OP post that he saw the items and printed them.

Your problem probably is your SD card.
