### ISSUE TITLE
Is this firmware dead now for public use ?

### ISSUE THREAD

**Issue by enly1** [mriscoc/Ender3V2S1#9]
I've seen lots of messages around about this firmware and not continuing publically, but wanted to check the formal status.
Is this firmware dead now for public use ?

**Comment by mriscoc** [comment]
It's not dead, check the commits. but a lot of development is in private.

**Comment by josederas** [comment]
@mriscoc I believe you are bringing all your changes into the main Marlin train, yes?  I believe I saw the PROUI added to the 2.0bug-fix?  Is it assumed then that this is a specific compiled version of the main  tree?

**Comment by tom-wetfrog** [comment]
Hello, can we gete a compiled .bin file, please? Need it for V4.2.7 for the E3 V2
I have no Idea how to do this

**Comment by Cal-LF** [comment]
@tom-wetfrog Try this. It is my compile of the current release. V427 board.
[MRC 20220126.zip](https://github.com/mriscoc/Ender3v2/files/7974574/MRC.20220126.zip)

**Comment by gokhanselen** [comment]
Yeni sürümleri nasıl indiricez yardımcı olurmusunuz

**Comment by Cal-LF** [comment]
@gokhanselen There are no precompiled files to download at this time. See #6.

**Comment by jeroenvermeulen** [comment]
Build instructions: #12
