### ISSUE TITLE
Wierd Power Outage implementation

### ISSUE THREAD

**Issue by acritum** [mriscoc/Ender3V2S1#90]
**Describe the bug**
1) When "Power Outage" feature is enabled, before resuming the printing, the extruder goes mad and tries to extrude pretty much more of the filament that the nozzle can physically pass through. There can be heard crazy sounds in the extruder as it wants to pass even more and more filament, but it can't. You can see a spring of the filament filled from the left bottom of the table to the center of the table.
2) Finally when it continues the print, it doesn't seem to continue from where it stopped, but it reprints the whole layer from the beginning, thus some part of the layer becomes printed twice, and the rest of the layer is printed once, which leads to further shifting in all the following layers

**To Reproduce**
1. Start to print a cube or whatever.
2. Turn off the power in the middle of the printing process.
3. Wait 5-10 secs and turn the power on.
4. Press "continue" to resume printing.
5. See the shit that happens there...

**Expected behavior**
It should resume printing from where it was stopped last.

**Version :**
2.0.9.4 / 20 feb 2022. (Ender 3 V2)

**Screenshots**
![1_tn](https://user-images.githubusercontent.com/6622765/158227960-99f139cd-2aaa-47f6-bf8c-33ff20e47bc1.jpg)
![2_tn](https://user-images.githubusercontent.com/6622765/158227966-850ef6e1-3a8c-4bd0-bd10-b236fa92ff7b.jpg)

**Comment by mriscoc** [comment]
That could be a problem with the PLR file written to the memory card because a slow write access. Try using another card and also the latest version of the firmware.

**Comment by acritum** [comment]
> That could be a problem with the PLR file written to the memory card because a slow write access. Try using another card and also the latest version of the firmware.

I use the tf card that was bundled with Ender 3V2. I printed a lot of stuff and there has never been any problems with the card speed. The described problem only occurs in the power outage mode after restoring the print task. I use standard .gcode files generated with Cura. It was also possible that the increase of printing speed in the Tune menu could somehow affect  this because I usually increase speed to the maximum when I print unimportant test models. I'm not sure that 999% is really 10 times faster (could be 50 cm/sec but evidently it's not) and the max speed is probably limited somewhere else, but I set it to 999% after the first layer is complete and the quality of prints is still acceptable at a fast speed. Maybe there is some misinterpretation of the speed after the power is restored that makes the extruder not synchronized with the task until it reaches the place where it should continue the print process. Try it and maybe you will get it. Personally I don't want to try it again until it is fixed because when this happened I thought that it will break the extruder or the hotend  because the extruder tried to extrude more plastic than the hotend could pass through and made crazy cracking sounds. I haven't seen this behaviour with the stock firmware so I think it was reasonable to note it here, and now you decide if it's worth investigating the case or not. 

One more problem that I see with this firmware is that when I print a file first time, it sets the hotend temperature correctly, but if I print it one more time or if I cancel the print and start the it again, the hotend temperature is reset to 0 and I have to set it manually in the Tune menu, otherwise the temperature really drops to 0 instead of increasing. This is really annoying, but I can't find any mentioning of this problem in forums so maybe there's something wrong with my device, I don't know.

**Comment by mriscoc** [comment]
Could be a problem with the Marlin core power outage feature and your speed settings. In our tests at normal speed that works ok.

https://user-images.githubusercontent.com/2745567/159381453-9febe84a-893e-47af-88c4-28c2ac9ad222.mp4

About the second issue, please test with the latest version to see if that behavior still exists.

**Comment by acritum** [comment]
So, I can imagine that the speed setting could affect the incorrect extruder behavior, but did you test if it continues to print from exactly where it stopped or reprints the whole layer from the beginning, thus causing some parts of the layer printed twice?

Yet another thing I can suggest is that when the header moves to allow nozzle cleaning, the second step that I would  suggest is to print a line in some unused space of the table to ensure that the filament is completely ready to continue the printing process. I don't know, maybe it happens with my printer/nozzle/filament only, but when I start printing, CURA prints two "useless"  lines on the left side of the table to ensure that the filament is ready, and most often the first line starts not in the corner of the table but somewhere in the middle of the table which means that when the printing starts without trying to print these lines, the real print may lack first 5-10 cm of line, or the initial line will be thinner than it is supposed to be. Evidently, the extruder should work a little "for no actual reason" after it was not used for some time to ensure further stable filament extrusion.

**Comment by mriscoc** [comment]
That is not possible because the printer does not know what place is clear in the bed and also, Z can't be lowered, the head bar (x axis) could crash with the piece already printed. The perfect place is the parking position because it is normally outside of the bed.

**Comment by acritum** [comment]
I just thought it is not necessary to print a line somewhere on the table. We only need to extrude some filament to ensure that the nozzle is filled up completely and ready. As the system shows a screen that offers to clean the nozzle and this needs manual action, I think it would be reasonable to add a button there like "extrude some filament". The "some" amount for my filaments is somewhere between 5-15 cm until the stable extrusion, so I think this value should be configured somewhere in the settings so that anyone could customize it for his needs. So, the user presses this button (if he thinks he needs it) and there begins the extrusion into the air (as the hotend is at the right side outside the table now, it won't spoil the pre-printed parts). The users evaluates the amount of the filament that goes out and decides if he wants to repeat the extrusion once again or continue the print. If the user doesn't need extrusion or if he thinks that he extruded enough, he just cleans the nozzle and presses "continue" button.

**Comment by pto199** [comment]
When I turn the printer back on, I get no screen asking me to resume.  This feature is not working at all for me :(.  Yes, I have the power outage option checked in the menu (assuming power outage means Power recovery)

**Comment by mriscoc** [comment]
Tested and it is working. Because your issue is different from the OP's, you need to open a new issue and fill in all the details.
![image](https://user-images.githubusercontent.com/2745567/162102050-d11328c5-6d73-4298-a29c-f73b2942bab4.png)

**Comment by acritum** [comment]
> When I turn the printer back on, I get no screen asking me to resume. This feature is not working at all for me :(. Yes, I have the power outage option checked in the menu (assuming power outage means Power recovery)

It's worth mentioning that this firmware requires to save the options after every change, so if you check power outage, you should save the  settings  at once, otherwise when you turn the power off, the power outage will be disabled again  :) It's not obvious so the first time I tried it I also thought that this feature doesn't work. The other thing to keep in mind (I'm not sure but only guess, the developer should know better) is that this power outage feature seems to remember only the last successfully printed layer number  but not the position of the last gcode line that was printed, and when the power resumes, it continues from the beginning of the next layer that follows the last successfully printed layer, no matter if the half of that layer was already printed. So, it's only my guess, that if you test the feature and turn off the printer at the first layer, it may really do nothing when the power resumes, as 0 successful layers were printed by the moment of the power outage. But this is only my guess, I'm still not quite sure how exactly it works. Try turning off the power after several layers were printed, maybe the resume feature will work for you.

**Comment by mriscoc** [comment]
Hi, the power outage recovery behavior is the one set by the Marlin core, it is not possible to write to the memory card too often otherwise the card could wear off too fast, then it is a compromise between functionality and preserving of the memory card.

**Comment by acritum** [comment]
> Hi, the power outage recovery behavior is the one set by the Marlin core, it is not possible to write to the memory card too often otherwise the card could wear off too fast, then it is a compromise between functionality and preserving of the memory card.

I thought modern memory cards are durable. At least I use one frequently during several years and I think I have overwritten several terabytes already. It's hard to imagine that writing a number of the last  executed G-code line once in 30 seconds for instance will wear out the card quickly.  The problem of reprinting an already printed layer as I see it is that if you print something thin like a bolt or a stud, the nozzle can bump into the pre-printed part and unglue it from the bed, so the whole work will be spoiled. I had such a case once with overextruded PETG even without power outage.

**Comment by mriscoc** [comment]
For change the frequency of saved data, you can modify the configuration_adv.h file:
https://github.com/mriscoc/Ender3V2S1/blob/9a2488515cf11c28e9741f17a02f074a5a295d73/Marlin/Configuration_adv.h#L1488-L1490
If you want to change the behavior of the power outage function you must open an issue in the official Marlin repository:
https://github.com/MarlinFirmware/Marlin/issues
