### ISSUE TITLE
[BUG] head getting stuck on buildplate clip, after pausing for filament reload

### ISSUE THREAD

**Issue by m0nk1111** [mriscoc/Ender3V2S1#911]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

if i pause the print to change filament, the head moves to an outer corner, where a clip is to hold the buildplate in its place.
it gets stuck on the clip, but it thinks it still moving, which results in the coordinates being off. so when i resume it resumes at wrong coordinates. 

can the hotend plz not move to the corner, but in the middle, where no buildplate clip is to be expected?

### Bug Timeline

i just noticed it

### Expected behavior

when pausing print, move the head to a location, where no buildplate hold in place clips would be expected

### Actual behavior

it moves to my clip in the right back corner, when i hit pause print

### Steps to Reproduce

oke

### Version of Professional Firmware

the last one

### Printer model

CE3V2

### Electronics

4.2.2

### Add-ons

non

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Check your park head position
https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides

**Comment by m0nk1111** [comment]
oke then let me put it differently
why is the park head default position in the right corner for an ender 3 Vx when theres clips in the corners most of the time?

btw, thx for this awsome firmware, has served me right

**Comment by mriscoc** [comment]
The default park position is calibrated for an all-stock Ender 3 V2 and allows for post-purge nozzle cleaning when a pause or filament change is required.

**Comment by m0nk1111** [comment]
oke
but do you reconize my problem here?
its not a big problem:p

i expect this to work OOTB, since this is pretty specific firmware/printer related

**Comment by mriscoc** [comment]
Do you have a totally stock Ender 3V2?
The defaults settings should work.

**Comment by m0nk1111** [comment]
i have a second z axis and some led lighting,
![](https://cdn.discordapp.com/attachments/676397975857004547/1106686411215753266/IMG_20230512_225456.jpg)

and some custom clips
oh end the bl touch is broken,
but i run the manual firmware anyway

and an all metal extruder
and i have a z axis cammount for a note4
and a stainless steal nozzle
its connected with a RPI4b running octoprint 1.8
but im sure that cant be related :P

**Comment by m0nk1111** [comment]
oh, running prints from octoprint could be related
i start al my prints from octoprint
but i paused it with the UI on the printer
