### ISSUE TITLE
[Solved] with ender 3 v2 and sprite extruder pro and cr touch (MY Mistake!!! & Bad timing!, I had a bad ribbon cable)

### ISSUE THREAD

**Issue by Bradford1040** [mriscoc/Ender3V2S1#913]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I have been using your fabulous firmware, Thank you very much!

I was using  Ender3V2-422-MM-MPC-20230312.bin on my ender 3 v2 with a sprite extruder pro, and it was working 100%, no restarting the firmware after a print like with the previous version  I even figured out the manual mesh finally, well today after a perfect 12 hr print I installed a cr touch then installed Ender3V2-422-BLTUBL-MPC-20230312.bin, every thing was working as it should I had to disable HS mode but no biggie, but I cant get a print going do to after I click print the nozzle wont heat up, but if I preheat or do a mpc autotune it heats up fine, but soon as I click on a print the temperature starts dropping and i get a M112 kill the printer, I rolled back to the MM-MPC  and it prints but I dont have the features of the BLTUBL-MPC, 

I use prusa slicer, but  I tried several gcodes that I have sliced even ones sliced in cura from many months ago, soon as I click the print button I can not get the hotend to heat up   

### Bug Timeline

new

### Expected behavior

expected it to heat up the hotend

### Actual behavior

it doesn't heat up the hot end 

### Version of Professional Firmware

Ender3V2-422-BLTUBL-MPC-20230312.bin

### Printer model

ender 3 v2

### Electronics

4.2.2

### Add-ons

sprite extruder, dual z axis, cr touch

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
Read the documentation in the Wiki: https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#error-handling
