### ISSUE TITLE
Beagleprint Camera display bug

### ISSUE THREAD

**Issue by blasirio** [mriscoc/Ender3V2S1#920]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Beagleprint Camera Filenames & Status progress not displayed in LCD

### Bug Timeline

New

### Expected behavior

Display Filename and Status progress bar %

### Actual behavior

Filename is not displayed anywhere and progress bar stays at 0%, but when it finish it jumps to 100% complete.

### Version of Professional Firmware

2.1.3

### Printer model

Ender3v2

### Electronics

4.2.2

### Add-ons

Beaglecamera

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

Other (explain below)

### Additional information & file uploads

Using BeaglePrint Camera/App

Firmware: 1.2.0

![image](https://github.com/mriscoc/Ender3V2S1/assets/126421140/0f27d301-64e3-424a-b08c-ce40cc8f1638)

![image](https://github.com/mriscoc/Ender3V2S1/assets/126421140/988acbc4-a114-4216-bf4c-ae276ccc628d)

**Comment by mriscoc** [comment]
Ask in Beagleprint forums. Not a firmware issue.
https://github.com/mriscoc/Ender3V2S1/wiki/Octoprint#display-print-progress
