### ISSUE TITLE
Installing hint: Add troubleshoot sentence into wiki

### ISSUE THREAD

**Issue by holgerlembke** [mriscoc/Ender3V2S1#926]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

In https://github.com/mriscoc/Ender3V2S1/wiki/How-to-install-the-firmware please add a sentence into the troubleshooting section:

-----------------

Flashing with some SD-cards may not work. Try changing the SD card to a more modern one/different manufacturer.

-----------------

I usually have a 2 GB sd card for my print files. works well. but not for flashing. formatting, empty, whatever, printer ignores the flash file. Chaning the sd card to a 8gb one, same prep steps, instantly working.

### Version of Professional Firmware

a

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Currently there is this:
![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/c1e6e6d7-23db-40a2-a0ba-915610eb15fe)

I will add some additional information.

**Comment by mriscoc** [comment]
Not a firmware issue
