### ISSUE TITLE
[QUESTION] Is the customizable color menu missed in the latest update? I'm on F4 UBL

### ISSUE THREAD

**Issue by UsSuggester** [mriscoc/Ender3V2S1#928]
Asking because I don't see it as a missing option due to lack of memory on F4. I was really a fan specially of dark background but, if the printer works better without it, welcome.

**Comment by mriscoc** [comment]
Yes, I removed it by disabling `HAS_CUSTOM_COLORS` in the configuration file to make more program memory space for UBL.

**Comment by UsSuggester** [comment]
Thank you. Solved.
