### ISSUE TITLE
[BUG] Display problems at G29

### ISSUE THREAD

**Issue by rstalde** [mriscoc/Ender3V2S1#935]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I have a small problem with the May 2023 version.
Since I often change the printing plate, I have the G29 command as default in the G-code on the SD card.
When the command is executed, the results are overlaid on the existing display and a key press is expected at the end of the command execution.
Using the G29 V0 (Verbose off) option also did not change anything.
The other functions, incl. thumbnail display, are as expected :)

Printer: Ender 3 V2 original
MB: Creality 4.2.2

Translated with www.DeepL.com/Translator (free version)

### Expected behavior

G29 command in G-Code

### Version of Professional Firmware

Ender-3 V2 Professional Firmware 20230522

### Printer model

Ender 3 V2

### Electronics

4.2.2

### Add-ons

None

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

05-30-2023
In the meantime I could solve the problem myself perfectly :)
Don't need future support from here.

**Comment by mriscoc** [comment]
Not a firmware issue, this was already answered but I don't have the link at hand.

```g-code
C108
```
