### ISSUE TITLE
I feel like since updating to march 14 release i'm seeing issues with overextrusion?

### ISSUE THREAD

**Issue by mattfox27** [mriscoc/Ender3V2S1#95]
After updating to march 14 release for Ender S1 I feel like prints are possibly overextruding?  I have a part that I print and it has threads and a bolt, prior to march 14 release it fit fine now after march 14 release the parts no longer fit?  Same file.

**Additional context**

**Comment by mriscoc** [comment]
Over extruding can be controlled only by the extruder steps/mm and flow. Calibrate the extruder steps/mm according to your filament and setup
![image](https://user-images.githubusercontent.com/2745567/158720387-533df832-c504-4c4b-b3f8-de7569b3a1d2.png)

**Comment by nicop777** [comment]
Mine is overextruding as well. then i returned to previous version, still overextruding. Then i tried going back to jyers, it fixed the problem. then i switch back to mriscoc latest firmware, overextruding again. i wish this is fixed because overall, i liked this firmware than jyers. im using ender 3 v2 manual mesh 4.2.2 btw

edit: im recalibrating e-steps every after flashing firmware

**Comment by mriscoc** [comment]
The extruder motor is under control of the Marlin core, if you calibrate the e-steps then the core simply follows the commands from the G-code file. We don't have reports about over extruding. I will notify this concern to our test group.

**Comment by mriscoc** [comment]
> Mine is overextruding as well. then i returned to previous version, still . Then i tried going back to jyers, it fixed the problem. then i switch back to mriscoc latest firmware, overextruding again. i wish this is fixed because overall, i liked this firmware than jyers. im using ender 3 v2 manual mesh 4.2.2 btw
> 
> edit: im recalibrating e-steps every after flashing firmware

For Ender 3v2 definitely there aren't reports of over extruding for that printer. The OP refers to the Ender3S1

**Comment by mattfox27** [comment]
Yes I went back to stock firmware and the problem went away, yes I also calibrated E-steps

**Comment by enzu4l** [comment]
Can’t confirm that. Maybe tighten your screws. Especially the hidden screw for adjustments on the z axis gets lose after a while. Recently I had that problem and it gave me nuts.

**Comment by mriscoc** [comment]
No more feedback, it can't be replicated by the test group.
