### ISSUE TITLE
[BUG] Auto Build Mesh leaves the bed heated to 50C after the mesh is save or mesh build is completed.

### ISSUE THREAD

**Issue by awoodcroft95** [mriscoc/Ender3V2S1#956]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

When running the Auto Build Mesh feature from the prepare menu the bed is heated to 50 degrees celsius. Once the mesh has been built and either option is selected (save or cancel/done) the bed is left heated to 50 deggrees.

This should probably reset back to default/unheated to allow for the bed to cool back down and stop drawing power.

Bin used: Ender3V2-422-BLTUBL-MPC-20230522B.bin

### Expected behavior

Bed should return to default temperature/off state once Auto Build Mesh menu is exited or once Auto Build Mesh is complete.

### Actual behavior

Bed was left heated to 50 degrees celsius after exiting the menu.

### Steps to Reproduce

Select Auto Build Mesh in the Prepare with a bed temperature of 50 set in the Mesh Leveling advanced settings.
Wait for Auto Build Mesh to complete. Once complete select Save or Done/Exit/Cancel.
See that bed temperature remains set to 50.

### Version of Professional Firmware

2.1.3 MRiscoC

### Printer model

Creality Ender 3V2

### Electronics

Board 4.2.2

### Add-ons

Creality CR Touch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
Duplicated of https://github.com/mriscoc/Ender3V2S1/issues/885
