### ISSUE TITLE
[BUG] Attempted TJC update throw error that there are multiple tft files 

### ISSUE THREAD

**Issue by dreed47** [mriscoc/Ender3V2S1#967]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Attempted TJC update on 3S1 and it throws an error that there are multiple tft files.  

`
Baud: 115200
SD Card Update...
The system detects multiple tft files, can not be upgraded, please remove the extra tft file
` 

There is only one tft file on the card.  I even tried to reformat the card first and I still get the same error.

### Expected behavior

I expected the TJC LCD to get its firmware updated.

### Actual behavior

I get 'The system detects multiple tft files, can not be upgraded, please remove the extra tft file' erro and nothing is updated.

### Steps to Reproduce

formatted new sd card
downloaded tjc.tft file and moved it to the sd card
inserted the sd card into the back of the lcd and powered on the printer

### Version of Professional Firmware

2.1.3

### Printer model

S1

### Bed Leveling

ABL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
https://github.com/mriscoc/Ender3V2S1/wiki/How-to-update-the-display

![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/bc538fc8-0543-4b84-a2da-82b4d435ac07)
