### ISSUE TITLE
Bed temp drops to 0

### ISSUE THREAD

**Issue by KBalage** [mriscoc/Ender3V2S1#969]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

I've tried to print ASA with bed temp 100°C, Hotend 260, had an E3S1+ with firmware Ender3S1-F4-UBL-20230522B.bin, PrusaSlicer 2.6.
My starting G code sets the heat for bed to target and hotend first to 160 only, then after levelling steps (only load mesh) it sets the hotend temp to 1st layer temp. 

The problem is that the bed temp never reach 100, and a new target - 0 - is set by some reason. By the time the hotend reach the set temp and printing starts, the bed has a 0 target, slowly cools down and the print is messed up.

### Version of Professional Firmware

Ender3S1-F4-UBL-20230522B.bin

### Printer model

E3S1+ F4

### Electronics

F4

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Prusa Slicer

### Host Software

OctoPrint

### Additional information & file uploads

![image](https://github.com/mriscoc/Ender3V2S1/assets/106810901/19c8674d-50d3-4a32-9e45-a5fa64ccf0fe)
![image](https://github.com/mriscoc/Ender3V2S1/assets/106810901/20cde2a9-d189-41ac-8aa0-520824ec17b2)

**Comment by KBalage** [comment]
if it's a hardcoded/built-in timeout for heated bed
- it would be nice to have a menu item to adjust
- and printing job should not started if temp drops like this

**Comment by mriscoc** [comment]
Compare your start script with: https://github.com/mriscoc/Ender3V2S1/wiki/Slicer-G-code-Scripts

**Comment by KBalage** [comment]
> Compare your start script with: https://github.com/mriscoc/Ender3V2S1/wiki/Slicer-G-code-Scripts
I did, and I even checked the generated G code for M140 commands - there weren't any - apart from the first one which set the bed temp to 100 (M140 S[first_layer_bed_temperature] ; set bed temp).
Interesting - if I start the printer, pre-heat the bed (close to 100) it works fine. If I start with cold bed, it fails just like I described. 
There's a timeout somewhere...

**Comment by mriscoc** [comment]
Yes, there is a 10 minutes timeout if the nozzle is heated and the extruder doesn't move, because that could cause filament residues to crystalize and clog the nozzle.

https://github.com/mriscoc/Ender3V2S1/blob/73c11535a7c0de0044cfed0f564154a079be5782/Marlin/Configuration_adv.h#L553-L559

After the timeout, both the extruder and bed heaters are turned off.

**Comment by KBalage** [comment]
Thank you, it explains now what's going on here.

PrusaSlicer by default heat the extruder to 170°C and then wait till bed leveling temp. After the leveling done it continues with heat up the extruder to first layer temp. I've adapted a same method to my E3S1+.
In case we have a slow performance in bed heating (like E3S1+ with 100°C target) it leads to the timeout on both extruder and bed temp, but extruder temp later set to first layer temp while the bed is turned off. Print fails with too low bed temp, lost adhesion.

I just have to reorder the start G code a bit, wait till bed temp, wait till extruder leveling temp and then continue. 



M862.3 P "[printer_model]" ; printer model check
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S[first_layer_bed_temperature] ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S[first_layer_bed_temperature] ; wait for bed temp
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M204 T[machine_max_acceleration_travel] ; restore travel acceleration
M104 S[first_layer_temperature] ; set extruder temp
G92 E0
G1 Y-2 X179 F2400
G1 Z3 F720
M109 S[first_layer_temperature] ; wait for extruder temp

; intro line
G1 X170 F1000
G1 Z0.2 F720
G1 X110 E8 F900
G1 X40 E10 F700
G92 E0

M221 S95 ; set flow
