### ISSUE TITLE
[BUG/TYPO] Bed tramming wizard is misspelled as Bed tramming wizzard

### ISSUE THREAD

**Issue by lucasrdrgs** [mriscoc/Ender3V2S1#971]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

When running automatic bed tramming wizard, the tooltip (in yellow text) is misspelled as Bed tramming wizzard (notice the double z)

### Version of Professional Firmware

2.1.3

### Printer model

Ender 3 V2 Neo

### Electronics

Board 4.2.2

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Thank you
