### ISSUE TITLE
[BUG] X-axis not moving during printing stage. 

### ISSUE THREAD

**Issue by LuWang9018** [mriscoc/Ender3V2S1#974]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Just updated my farmwear to Ender-3 V2/S1 Professional Firmware 20230522

The x-axis is moving and working fine during Homing and Leveling. However, at the beginning of the print stage. The head will move to the left-most (hit the switch) and then stop there(not even moving backward). Y-axis and Z-axis are moving fine.

### Version of Professional Firmware

Ender-3 V2/S1 Professional Firmware 20230522

### Printer model

Creality Ender 3V2

### Electronics

4.2.2

### Add-ons

Creality Sprite Extruder Pro Kit

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by classicrocker883** [comment]
this can be something with your Start Gcode. do other gcode files print fine?

**Comment by pascallanger** [comment]
I had the same behavior. I need to check if I can reproduce it but that was after redoing the mesh and verifying the nozzle probe offset. When you reboot the printer everything works again.

**Comment by rlv003** [comment]
I had the same problem too after adjusting the e steps, doing a mesh, and adjusting a lot of settings. I turned the printer off and back on it started to work normal again.

**Comment by awabom** [comment]
Not really a 'false alarm'

Had this happen to me right now with the September version (on an Ender 3 V2 422 with cr-touch). This was on a clean install after doing all the configuration settings, mesh build, etc. Without powering off or rebooting I started a print that just moved in Y direction while printing the skirt around the print etc.

Power off and on, and the problem is gone - same gcode runs fine.

**Comment by mriscoc** [comment]
An issue is labeled as "false alarm" when it is not a firmware issue but a mechanical, user or custom configuration problem. The [calibration guides](https://github.com/mriscoc/Ender3V2S1/wiki/Calibration-Guides) clearly specify that the printer MUST be rebooted after changing the physical settings.
