### ISSUE TITLE
[BUG] the lcd knob is going insane

### ISSUE THREAD

**Issue by liamwerk7676** [mriscoc/Ender3V2S1#977]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

frimware makes lcd knob jump numbers foward and backwards before update worked fine now its all over the place

### Bug Timeline

since updating

### Expected behavior

lcd knob ups the number by 1

### Actual behavior

randomly chooses a number

### Version of Professional Firmware

20230522

### Printer model

ender 3v2

### Electronics

Board 4.2.2

### Add-ons

bltouch

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
It is not a firmware issue but a knob encoder issue, I have the same problem so I implemented a knob filtering in previous versions, but that filtering affects the speed for people with a good knob encoder. In the latest version I made the smooth optional by enabling or disabling it in the configuration file by using:
https://github.com/mriscoc/Ender3V2S1/blob/73c11535a7c0de0044cfed0f564154a079be5782/Marlin/Configuration.h#L3365
If you want a smooth encoder operation you need to enable that line and custom compile your firmware version.
