### ISSUE TITLE
[BUG] (Cannot compile FW)

### ISSUE THREAD

**Issue by drradkov** [mriscoc/Ender3V2S1#982]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

When try to compile firmware, error appears:
   77 |   #error "HAS_GCODE_PREVIEW requires PROUI_EX."
   80 |   #error "HAS_TOOLBAR requires PROUI_EX."
      |    ^~~~~
Error: Failed to parse Marlin features. See previous error messages.

### Bug Timeline

New

### Expected behavior

.

### Actual behavior

.

### Steps to Reproduce

.

### Version of Professional Firmware

Latest

### Printer model

Creality Ender 3V2

### Electronics

Board 4.2.7

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

OctoPrint

**Comment by mriscoc** [comment]
You need to follow those requirements
```cpp
77 | #error "HAS_GCODE_PREVIEW requires PROUI_EX."
80 | #error "HAS_TOOLBAR requires PROUI_EX."
```

**Comment by drradkov** [comment]
Could you please sugdest, how to fix it?

**Comment by mriscoc** [comment]
It is not an bug, it is a requirement. If you want to use the toolbar, for example, you need to enable PROUI_EX.

**Comment by drradkov** [comment]
Buh how? i tied to search the repo. Nothing found. 
Thanks.

**Comment by mriscoc** [comment]
It is enabled by default in the provided configuration files. https://github.com/mriscoc/Ender3V2S1/wiki#compiling-your-firmware-flavor

**Comment by drradkov** [comment]
Thank you. Somehow i downloaded an old version of configurator. After dowloading the lates py script, everything is compiling without issues.

**Comment by Vodlex1** [comment]
Is there a way that I could disable the toolbar and gcode previewer? And would doing that cause other problems?

**Comment by mriscoc** [comment]
> Is there a way that I could disable the toolbar and gcode previewer? And would doing that cause other problems?

Yes, look for:

```cpp
  #define HAS_GCODE_PREVIEW 1
  #define HAS_TOOLBAR 1
```

In the Configuration.h file and disable them.
