### ISSUE TITLE
CURA 5.4 no Jpeg Preview

### ISSUE THREAD

**Issue by jxer** [mriscoc/Ender3V2S1#990]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

Upgraded to 5.4.0, script and post processing tasks all look correct but the ender is showing the qr code

### Version of Professional Firmware

2 revisions back from latest

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

**Comment by mriscoc** [comment]
Update your firmware, Seems that Cura 5.4 is working ok with the latest firmware and post processing script:   

![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/9283dbd8-9a5e-4242-8923-e81e5c2f77e0)

Note: the latest firmware version allows setting custom size thumbnails.

**Comment by classicrocker883** [comment]
I'm also actually not getting a preview image either using Prusa Slicer. it just shows blank. it also takes a second longer to load, the other files and gcode sliced in Cura have no issue.

Could it be something with the .py file? or the parameters entered in the slicer itself?

**Comment by Antufatiko** [comment]
Did you fix the problem? @jxer i have the same and don't know what to do

**Comment by jxer** [comment]
> Did you fix the problem? @jxer i have the same and don't know what to do

No, 5.4 has a bug that made me go back to 5.1.1 till its fixed

**Comment by classicrocker883** [comment]
is it possible that it wont work because the size value you are using is unsupported? so maybe it needs to be changed to another value.

**Comment by Antufatiko** [comment]
> is it possible that it wont work because the size value you are using is unsupported? so maybe it needs to be changed to another value.

I did everything the post said but in Cura 5.4 doesn't appear the "Create JPEG thumbnail".
I did it in Cura 5.2.1 and it works.

**Comment by mriscoc** [comment]
> I did everything the post said but in Cura 5.4 doesn't appear the "Create JPEG thumbnail".

![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/fabff80b-ca14-46d0-82a1-3cfae3e3b9f8)
![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/4b09f642-94b6-419a-9aba-6272e160402f)
![image](https://github.com/mriscoc/Ender3V2S1/assets/2745567/9283dbd8-9a5e-4242-8923-e81e5c2f77e0)

**Comment by classicrocker883** [comment]
when you installed the new Cura, did you make sure to paste the slicer script *for Cura* in the correct folder?

that's how to get the create jpeg thumbnail to appear
