### ISSUE TITLE
[BUG] Homing breaks Y min Position

### ISSUE THREAD

**Issue by tofo2** [mriscoc/Ender3V2S1#995]
### Did you test with a precompiled firmware?

Yes, and the problem still exists.

### Bug Description

If i home my printer than the Y min position is shown but it does not keep a distance from the edge

### Expected behavior

I expected the min Y distance to be respected

### Actual behavior

The min Y distance was not respected 

### Steps to Reproduce

1. min Y Distance to 5
2. store Settings
3. homing

### Version of Professional Firmware

:Marlin 2.1.3 MRiscoC Ender3V2-422-MM-TJC-MPC

### Printer model

Ender3V2

### Electronics

4.2.2

### Bed Leveling

MBL Manual Bed Leveling

### Your Slicer

Cura

### Host Software

SD Card (headless)

**Comment by mriscoc** [comment]
After homing axes, the printer head remains at XY home position (xy min pos), it doesn't move to 0,0 that is normal behavior.
